Repository infinispan/infinispan, pull requests merged in 2018-06, with the labels that each got.

#5979 Unquarantine some tests
  core/src/test/java/org/infinispan/api/mvcc/LockPerEntryTest.java
  core/src/test/java/org/infinispan/distribution/UnknownCacheStartTest.java
  core/src/test/java/org/infinispan/partitionhandling/ScatteredSplitAndMergeTest.java
  core/src/test/java/org/infinispan/persistence/BaseStoreFunctionalTest.java
  persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/PooledConnectionFactoryTest.java
  server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRod10ReplicationTest.java
Labels: Test FIX, Trivial :-)

#6046 ISPN-7420 Documentation fix
  documentation/src/main/asciidoc/user_guide/server_protocols_hotrod_wire.adoc
Labels: Trivial :-)

#6068 ISPN-8988 Cache item can be expired after loading immediately
  core/src/main/java/org/infinispan/persistence/PersistenceUtil.java
Labels: Trivial :-)

#6071 ISPN-8988 Cache item can be expired after loading immediately
  core/src/main/java/org/infinispan/persistence/PersistenceUtil.java
Labels: Backport

#6074 ISPN-9289 Ignore TransactionSynchronizationRegistry
  server/integration/testsuite/src/test/java/org/infinispan/server/test/client/hotrod/HotRodTransactionalCacheIT.java
  server/integration/testsuite/src/test/resources/config/infinispan/default-dist.xml
  server/integration/testsuite/src/test/resources/config/infinispan/default-repl.xml
Labels: Test FIX

#6067 ISPN-9020 Unify RemoteQueryDisableIndexingTest and RemoteQueryDisable…
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/RemoteQueryDisableIndexingTest.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/RemoteQueryDisableLegacyIndexingTest.java
Labels: Trivial :-)

#6024 ISPN-9224 Reduce ExceptionEvictionTest combinations
  core/src/test/java/org/infinispan/eviction/impl/ExceptionEvictionTest.java
Labels: Trivial :-)

#6077 9.3 Codename: Estrella Galicia
  pom.xml
Labels: Trivial :-)

#6064 ISPN-9292 PessimisticTxAtomicLockingTest and OptimisticTxAtomicLockingTest not running
  core/src/test/java/org/infinispan/atomic/BaseAtomicMapLockingTest.java
  core/src/test/java/org/infinispan/atomic/OptimisticTxAtomicLockingTest.java
  core/src/test/java/org/infinispan/atomic/PessimisticTxAtomicLockingTest.java
  core/src/test/java/org/infinispan/distribution/DistSyncL1FuncTest.java
  core/src/test/java/org/infinispan/distribution/DistSyncTxL1FuncTest.java
  core/src/test/java/org/infinispan/tx/exception/ReplicationTxExceptionTest.java
  core/src/test/java/org/infinispan/util/ControlledRpcManager.java
Labels: Test FIX

#6094 ISPN-8431 Fix test name in @Test annotation
  core/src/test/java/org/infinispan/atomic/OptimisticTxAtomicLockingTest.java
  core/src/test/java/org/infinispan/atomic/PessimisticTxAtomicLockingTest.java
Labels: Trivial :-), Urgent!
