Repository infinispan/infinispan, pull requests merged in 2018-04, with the labels that each got.

#5890 ISPN-9034 InfinispanExtensionIT should depend on "org.infinispan"
  integrationtests/wildfly-modules/src/test/java/org/infinispan/test/integration/as/InfinispanExtensionIT.java
Labels: Test FIX, Trivial :-)

#5893 ISPN-9035 Add management-http(s) socket bindings to domain template
  server/integration/feature-pack/src/main/resources/configuration/domain/template.xml
Labels: Trivial :-)

#5891 ISPN-9034 Replace CacheContainer with EmbeddedCacheContainer
  integrationtests/wildfly-modules/src/test/java/org/infinispan/test/integration/as/InfinispanExtensionIT.java
Labels: Test FIX, Trivial :-)

#5886 ISPN-8728 ExceptionEvictionTest.testSizeCorrectWithStateTransfer random
  core/src/test/java/org/infinispan/eviction/impl/ExceptionEvictionTest.java
Labels: Test FIX, Trivial :-)

#5896 ISPN-8719 KeySet.(iterator|spliterator|stream) not compatible with
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/ProtocolVersion.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheImpl.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/IterationNextOperation.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/IterationStartOperation.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/protocol/Codec.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/protocol/Codec12.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/protocol/Codec20.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/protocol/Codec23.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/protocol/Codec24.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/protocol/Codec25.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/protocol/Codec26.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/BulkOperationsTest.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/Encoder2x.java
Labels: Urgent!

#5903 ISPN-8719 KeySet.(iterator|spliterator|stream) not compatible with
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/ProtocolVersion.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheImpl.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/IterationNextOperation.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/IterationStartOperation.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/OperationsFactory.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/protocol/Codec.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/protocol/Codec12.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/protocol/Codec20.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/protocol/Codec23.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/protocol/Codec24.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/protocol/Codec25.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/protocol/Codec26.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/BulkOperationsTest.java
Labels: Backport, Urgent!

#5910 ISPN-9057 JGroupsTransport.invokeCommand should return CompletionStage
  core/src/main/java/org/infinispan/manager/impl/AllClusterExecutor.java
  core/src/main/java/org/infinispan/manager/impl/SingleClusterExecutor.java
  core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
  core/src/test/java/org/infinispan/statetransfer/StateTransferRestart2Test.java
Labels: Trivial :-)

#5915 Fix broken link to JavaDocs
  documentation/src/main/asciidoc/user_guide/cache_manager.adoc
Labels: Trivial :-)

#5923 ISPN-9081 Expose Query.getQueryString() as official API
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/event/ContinuousQueryImpl.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/filter/Filters.java
  object-filter/src/main/java/org/infinispan/objectfilter/impl/BaseMatcher.java
  query-dsl/src/main/java/org/infinispan/query/dsl/Query.java
  query-dsl/src/main/java/org/infinispan/query/dsl/impl/BaseQuery.java
  query-dsl/src/test/java/org/infinispan/query/dsl/impl/DummyQuery.java
  query/src/main/java/org/infinispan/query/Search.java
  query/src/main/java/org/infinispan/query/continuous/impl/ContinuousQueryImpl.java
Labels: Trivial :-)

#5928 ISPN-8719 KeySet.(iterator|spliterator|stream) not compatible with
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/protocol/Codec26.java
Labels: Backport, Trivial :-)

#5927 ISPN-8719 KeySet.(iterator|spliterator|stream) not compatible with
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/protocol/Codec26.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/protocol/Codec27.java
Labels: Backport, Trivial :-)

#5926 ISPN-8719 KeySet.(iterator|spliterator|stream) not compatible with
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/protocol/Codec26.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/protocol/Codec27.java
Labels: Trivial :-)

#5931 [9.2.x] ISPN-9092 Upgrade Protostream to 4.2.0.Final
  bom/pom.xml
  pom.xml
  server/integration/licenses/src/main/docs/licenses/licenses.xml
Labels: Backport

#5925 ISPN-9085 Add forEach taking IntConsumer to IntSet
  commons/src/main/java/org/infinispan/commons/util/ImmutableIntSet.java
  commons/src/main/java/org/infinispan/commons/util/IntSet.java
  commons/src/main/java/org/infinispan/commons/util/RangeSet.java
  commons/src/main/java/org/infinispan/commons/util/SmallIntSet.java
  commons/src/test/java/org/infinispan/commons/util/RangeSetTest.java
  commons/src/test/java/org/infinispan/commons/util/SmallIntSetTest.java
Labels: Changes Required

#5933 ISPN-8524 Disable (unstable) ScatteredDelayedAvailabilityUpdateTest
  core/src/test/java/org/infinispan/partitionhandling/ScatteredDelayedAvailabilityUpdateTest.java
Labels: Test FIX, Trivial :-)

#5936 ISPN-9099 StaggeredRequest throws IllegalStateException
  core/src/main/java/org/infinispan/remoting/transport/jgroups/StaggeredRequest.java
  core/src/test/java/org/infinispan/remoting/transport/jgroups/JGroupsTransportTest.java
Labels: Test FIX
