Repository infinispan/infinispan, pull requests merged in 2018-09, with the labels that each got.

#6233 ISPN-9481 implements toString in EncoderCache.EntryWrapper
  core/src/main/java/org/infinispan/cache/impl/EncoderCache.java
Labels: Trivial :-)

#6231 [9.3.x] ISPN-9128 RehashWithSharedStoreTest.testRehashes random failures
  core/src/main/java/org/infinispan/partitionhandling/impl/AvailabilityStrategy.java
  core/src/main/java/org/infinispan/partitionhandling/impl/PreferAvailabilityStrategy.java
  core/src/main/java/org/infinispan/partitionhandling/impl/PreferConsistencyStrategy.java
  core/src/main/java/org/infinispan/scattered/impl/ScatteredStateConsumerImpl.java
  core/src/test/java/org/infinispan/remoting/transport/ControlledTransport.java
  core/src/test/java/org/infinispan/scattered/statetransfer/CoordinatorStopTest.java
  core/src/test/java/org/infinispan/test/TestingUtil.java
  core/src/test/java/org/infinispan/test/TopologyChangeListener.java
  core/src/test/java/org/infinispan/test/ViewChangeListener.java
  core/src/test/java/org/infinispan/test/transport/DelayedViewJGroupsTransport.java
  core/src/test/java/org/infinispan/topology/TestClusterCacheStatus.java
  core/src/test/java/org/infinispan/tx/InfinispanNodeFailureTest.java
  core/src/test/java/org/infinispan/util/BlockingLocalTopologyManager.java
  core/src/test/java/org/infinispan/xsite/statetransfer/BaseStateTransferTest.java
Labels: Backport

#6239 ISPN-9488 Include the cleanup script output in the build log
  Jenkinsfile
Labels: Trivial :-)

#6238 ISPN-9470 refactoring test and adds new tests for async
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheSupport.java
  commons/src/main/java/org/infinispan/commons/api/AsyncCache.java
  core/src/main/java/org/infinispan/cache/impl/AbstractDelegatingCache.java
  core/src/test/java/org/infinispan/api/AsyncAPITest.java
  jcache/remote/src/main/java/org/infinispan/jcache/remote/RemoteCacheWrapper.java
Labels: Trivial :-)

#6120 [9.3.x] ISPN-9303 IndexingMetadata.getFieldMapping results in NPE if the type…
  remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/IndexingMetadata.java
Labels: Changes Required, Question

#6164 ISPN-9378 Add test to demonstrate no stack overflow occurs during par…
  query/src/test/java/org/infinispan/query/dsl/embedded/QueryDslConditionsTest.java
Labels: Trivial :-)

#6252 ISPN-9512 *TxPartitionAndMerge*Test tests hang during teardown
  core/src/test/java/org/infinispan/test/fwk/TestCacheManagerFactory.java
Labels: Test FIX

#6246 ISPN-9499 Json to text conversion ignore charset
  server/core/src/main/java/org/infinispan/server/core/dataconversion/JsonTranscoder.java
  server/core/src/test/java/org/infinispan/server/core/dataconversion/JsonTranscoderTest.java
Labels: Trivial :-)

#6250 Update migration guide for 9.4
  documentation/src/main/asciidoc/upgrading/upgrading.asciidoc
Labels: Trivial :-)

#6251 ISPN-9509 OffHeapConcurentMap can throw exception during shutdown
  core/src/main/java/org/infinispan/container/impl/DefaultSegmentedDataContainer.java
  core/src/main/java/org/infinispan/container/offheap/OffHeapDataContainer.java
Labels: Trivial :-)

#6272 Fix security chapter disappearance
  documentation/src/main/asciidoc/user_guide/compatibility_mode.adoc
  documentation/src/main/asciidoc/user_guide/endpoint_interop.adoc
Labels: Trivial :-)

#6288 ISPN-9523 Docs for HR Transactions
  documentation/src/main/asciidoc/user_guide/server_protocols_hotrod_transaction.adoc
Labels: Needs Rebase
