Repository infinispan/infinispan, pull requests merged in 2018-05, with the labels that each got.

#5943 ISPN-9106 Server cli linking error
  server/integration/feature-pack/src/main/resources/modules/system/layers/base/org/jboss/as/cli/main/module.xml
Labels: Trivial :-)

#5957 ISPN-9002 LocalModeNoPassivationTest.testValuesWithEvictedEntries random
  core/src/main/java/org/infinispan/persistence/util/PersistenceManagerCloseableSupplier.java
Labels: Test FIX, Trivial :-)

#5959 Use if (trace) before log.tracef(...)
  core/src/main/java/org/infinispan/factories/ComponentRegistry.java
  hibernate/cache-commons/src/main/java/org/infinispan/hibernate/cache/commons/access/LockingInterceptor.java
Labels: Trivial :-)

#5971 Add javadocs for InvocationStage methods
  core/src/main/java/org/infinispan/interceptors/InvocationCallback.java
  core/src/main/java/org/infinispan/interceptors/InvocationExceptionFunction.java
  core/src/main/java/org/infinispan/interceptors/InvocationFinallyAction.java
  core/src/main/java/org/infinispan/interceptors/InvocationStage.java
  core/src/main/java/org/infinispan/interceptors/InvocationSuccessAction.java
  core/src/main/java/org/infinispan/interceptors/InvocationSuccessFunction.java
Labels: Trivial :-)

#5984 ISPN-9164 ClassNotFoundException thrown by the REST server when using JSON
  server/integration/testsuite/src/test/java/org/infinispan/server/test/query/RemoteQueryIT.java
Labels: Test FIX, Trivial :-)

#5980 ISPN-9150 RemoteCache additional tests
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/BulkOperationsTest.java
Labels: Trivial :-)

#5998 ISPN-9189 ExceptionEvictionTest test failure causes testng to panic
  commons-test/src/main/java/org/infinispan/commons/test/TestNGTestListener.java
Labels: Test FIX, Trivial :-), Urgent!

#6000 ISPN-9193 CollectionMapper forEach should delegate to actualCollection
  core/src/main/java/org/infinispan/util/CollectionMapper.java
  core/src/test/java/org/infinispan/api/CacheAPITest.java
Labels: Trivial :-)

#5994 ISPN-9183 Replace <eviction> with <memory> in 2LC configs
  hibernate/cache-commons/src/main/resources/org/infinispan/hibernate/cache/commons/builder/infinispan-configs-local.xml
  hibernate/cache-commons/src/main/resources/org/infinispan/hibernate/cache/commons/builder/infinispan-configs.xml
  hibernate/cache-commons/src/test/resources/alternative-infinispan-configs.xml
Labels: Trivial :-)

#6003 ISPN-9201 Do not forget to apply Hot Rod flags to the cache before pe…
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/admin/RemoteCacheAdminTest.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodServer.java
Labels: Test FIX

#6009 [9.2.x] ISPN-9183 Replace <eviction> with <memory> in 2LC configs
  hibernate/cache-commons/src/main/resources/org/infinispan/hibernate/cache/commons/builder/infinispan-configs-local.xml
  hibernate/cache-commons/src/main/resources/org/infinispan/hibernate/cache/commons/builder/infinispan-configs.xml
  hibernate/cache-commons/src/test/resources/alternative-infinispan-configs.xml
Labels: Backport, Trivial :-)

#6005 ISPN-9204 Single node JgroupsTransport invoke* methods that take a
  core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
  core/src/test/java/org/infinispan/remoting/rpc/RpcManagerTest.java
Labels: Trivial :-)

#6019 ISPN-9216 Importing @Immutable from nashorn instead of net.jcip break…
  counter/src/main/java/org/infinispan/counter/impl/entries/CounterValue.java
Labels: Trivial :-)

#5804 ISPN-8894 Remove usages of junit.framework.*
  hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/ReadWriteTest.java
  integrationtests/wildfly-modules/src/test/java/org/infinispan/test/integration/as/InfinispanExtensionCliIT.java
Labels: Trivial :-)

#6029 ISPN-9243 Upgrade integration tests to WildFly 13.0.0.Final
  integrationtests/as-lucene-directory/pom.xml
  integrationtests/as-lucene-directory/server-provisioning.xml
  integrationtests/as-lucene-directory/src/wildflyConfig/patching/module.xml
Labels: Trivial :-)
