Repository infinispan/infinispan, pull requests merged in 2018-07, with the labels that each got.

#6125 Expose a method for deriving the index name from cache name rather th…
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/RemoteQueryDisableIndexingTest.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/RemoteQueryDslConditionsTest.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/RemoteQueryDslConditionsTunedTest.java
  remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/ProgrammaticSearchMappingProviderImpl.java
  remote-query/remote-query-server/src/test/java/org/infinispan/query/remote/impl/indexing/ProtobufWrapperIndexingTest.java
Labels: Trivial :-)

#6127 ISPN-9349 Fix jquery script for xsd doc viewer
  tools/src/main/resources/xsd/xsdoc.xslt
Labels: Trivial :-)

#6138 ISPN-9359 RocksDB clear always reinitializes the database
  persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/RocksDBStore.java
Labels: Trivial :-)

#6123 [9.3.x] HHH-12531 Handle legacy names in configuration
  hibernate/cache-v53/pom.xml
  hibernate/cache-v53/src/main/java/org/infinispan/hibernate/cache/v53/InfinispanRegionFactory.java
  hibernate/cache-v53/src/test/java/org/infinispan/test/hibernate/cache/v53/util/TestInfinispanRegionFactory.java
  pom.xml
Labels: Backport

#5989 ISPN-9128 RehashWithSharedStoreTest.testRehashes random failures
  core/src/main/java/org/infinispan/partitionhandling/impl/AvailabilityStrategy.java
  core/src/main/java/org/infinispan/partitionhandling/impl/PreferAvailabilityStrategy.java
  core/src/main/java/org/infinispan/partitionhandling/impl/PreferConsistencyStrategy.java
  core/src/main/java/org/infinispan/scattered/impl/ScatteredStateConsumerImpl.java
  core/src/test/java/org/infinispan/remoting/transport/ControlledTransport.java
  core/src/test/java/org/infinispan/scattered/statetransfer/CoordinatorStopTest.java
  core/src/test/java/org/infinispan/test/TestingUtil.java
  core/src/test/java/org/infinispan/test/TopologyChangeListener.java
  core/src/test/java/org/infinispan/test/ViewChangeListener.java
  core/src/test/java/org/infinispan/test/transport/DelayedViewJGroupsTransport.java
  core/src/test/java/org/infinispan/topology/TestClusterCacheStatus.java
  core/src/test/java/org/infinispan/tx/InfinispanNodeFailureTest.java
  core/src/test/java/org/infinispan/util/BlockingLocalTopologyManager.java
  core/src/test/java/org/infinispan/xsite/statetransfer/BaseStateTransferTest.java
Labels: Changes Required

#6166 ISPN-9128 RehashWithSharedStoreTest.testRehashes random failures
  core/src/main/java/org/infinispan/partitionhandling/impl/AvailabilityStrategy.java
  core/src/main/java/org/infinispan/partitionhandling/impl/PreferAvailabilityStrategy.java
  core/src/main/java/org/infinispan/partitionhandling/impl/PreferConsistencyStrategy.java
  core/src/main/java/org/infinispan/scattered/impl/ScatteredStateConsumerImpl.java
  core/src/test/java/org/infinispan/remoting/transport/ControlledTransport.java
  core/src/test/java/org/infinispan/scattered/statetransfer/CoordinatorStopTest.java
  core/src/test/java/org/infinispan/test/TestingUtil.java
  core/src/test/java/org/infinispan/test/TopologyChangeListener.java
  core/src/test/java/org/infinispan/test/ViewChangeListener.java
  core/src/test/java/org/infinispan/test/transport/DelayedViewJGroupsTransport.java
  core/src/test/java/org/infinispan/topology/TestClusterCacheStatus.java
  core/src/test/java/org/infinispan/tx/InfinispanNodeFailureTest.java
  core/src/test/java/org/infinispan/util/BlockingLocalTopologyManager.java
  core/src/test/java/org/infinispan/xsite/statetransfer/BaseStateTransferTest.java
Labels: Trivial :-)

#6161 Add surefire report to archived artifacts
  Jenkinsfile
Labels: DO NOT INTEGRATE

#6174 ISPN-9403 Increase build timeout to work around slow CI
  Jenkinsfile
Labels: Trivial :-)
