Repository infinispan/infinispan, pull requests merged in 2018-08, with the labels that each got.

#6157 ISPN-9387 Server-side TCP KeepAlive
  server/core/src/main/java/org/infinispan/server/core/configuration/AbstractProtocolServerConfigurationChildBuilder.java
  server/core/src/main/java/org/infinispan/server/core/configuration/ProtocolServerConfiguration.java
  server/core/src/main/java/org/infinispan/server/core/configuration/ProtocolServerConfigurationBuilder.java
  server/core/src/main/java/org/infinispan/server/core/configuration/ProtocolServerConfigurationChildBuilder.java
  server/core/src/main/java/org/infinispan/server/core/transport/NettyTransport.java
  server/core/src/test/java/org/infinispan/server/core/configuration/MockServerConfiguration.java
  server/core/src/test/java/org/infinispan/server/core/configuration/MockServerConfigurationBuilder.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/configuration/HotRodServerConfiguration.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/configuration/HotRodServerConfigurationBuilder.java
  server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/Attribute.java
  server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/EndpointSubsystemReader.java
  server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/HotRodSubsystemAdd.java
  server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/MemcachedSubsystemAdd.java
  server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/ModelKeys.java
  server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/ProtocolServerConnectorResource.java
  server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/ProtocolServiceSubsystemAdd.java
  server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/RouterConnectorResource.java
  server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/RouterService.java
  server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/RouterSubsystemAdd.java
  server/integration/endpoint/src/main/resources/org/infinispan/server/endpoint/subsystem/LocalDescriptions.properties
  server/integration/endpoint/src/main/resources/schema/jboss-infinispan-endpoint_9_4.xsd
  server/integration/endpoint/src/test/resources/org/infinispan/server/endpoint/endpoint-9.4.xml
  server/integration/testsuite/src/test/resources/config/parts/cachecontainer-endpoints-multitenancy.xml
  server/memcached/src/main/java/org/infinispan/server/memcached/configuration/MemcachedServerConfiguration.java
  server/memcached/src/main/java/org/infinispan/server/memcached/configuration/MemcachedServerConfigurationBuilder.java
  server/rest/src/main/java/org/infinispan/rest/configuration/RestServerConfiguration.java
  server/rest/src/main/java/org/infinispan/rest/configuration/RestServerConfigurationBuilder.java
  server/router/src/main/java/org/infinispan/server/router/configuration/HotRodRouterConfiguration.java
  server/router/src/main/java/org/infinispan/server/router/configuration/SinglePortRouterConfiguration.java
  server/router/src/main/java/org/infinispan/server/router/configuration/builder/HotRodRouterBuilder.java
  server/router/src/main/java/org/infinispan/server/router/router/impl/hotrod/HotRodEndpointRouter.java
  server/router/src/test/java/org/infinispan/server/router/configuration/ConfigurationTest.java
Labels: Question

#6190 ISPN-9387 Router connector default TCP keepalive should be false
  server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/RouterConnectorResource.java
Labels: Trivial :-)

#6193 StoreTypeMultimapCacheTest - was Ignored and should work now
  multimap/src/test/java/org/infinispan/multimap/impl/DistributedMultimapCacheTest.java
  multimap/src/test/java/org/infinispan/multimap/impl/StoreTypeMultimapCacheTest.java
Labels: Trivial :-)

#6207 ISPN-9436 expose getServerList
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/ConfigurationProperties.java
Labels: Trivial :-)

#6200 ISPN-9409 Fix HotRodMergeTest
  server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodServer.java
Labels: Test FIX

#6209 ISPN-8518 FunctionalDistributionTest.testDistributionFromNonOwner ran…
  core/src/test/java/org/infinispan/functional/FunctionalDistributionTest.java
Labels: Test FIX

#6214 ISPN-9398 & ISPN-9427 Hotrod configuration via properties file
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/package-info.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/ConfigurationProperties.java
Labels: Trivial :-)
