Repository infinispan/infinispan, pull requests merged in 2018-02, with the labels that each got.

#5751 ISPN-8800 Upgrade to jboss-logging 3.3.1.Final
  bom/pom.xml
  pom.xml
  server/integration/licenses/src/main/docs/licenses/licenses.xml
Labels: Trivial :-)

#5755 ISPN-8803 Upgrade Protostream to 4.2.0.CR1
  bom/pom.xml
  pom.xml
Labels: Trivial :-)

#5741 ISPN-8783 Remove duplicate property definitions in poms
  bom/pom.xml
  pom.xml
Labels: Trivial :-)

#5727 ISPN-8755 Incorrect local repository path in OSGi integration tests
  client/hotrod-client/pom.xml
  integrationtests/osgi/src/test/resources/maven.properties
Labels: Trivial :-)

#5676 ISPN-8657 Netty upgrade to 4.1.21
  all/embedded/pom.xml
  all/remote/pom.xml
  bom/pom.xml
  client/hotrod-client/src/main/resources/features.xml
  pom.xml
  server/core/src/main/java/io/netty/handler/ssl/AlpnHackedSslSession.java
  server/integration/feature-pack/pom.xml
  server/integration/feature-pack/src/main/resources/modules/system/layers/base/io/netty/main/module.xml
Labels: Changes Required

#5763 ISPN-8829 LockedStream doesn't override BaseCacheStream methods
  core/src/main/java/org/infinispan/LockedStream.java
  core/src/main/java/org/infinispan/stream/impl/LockedStreamImpl.java
Labels: Trivial :-)

#5760 ISPN-8808 Ensure that all methods in RemoteCacheAdmin return a RemoteCache
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManagerAdmin.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheManagerAdminImpl.java
Labels: Trivial :-)

#5770 ISPN-8843 Workaround for the IDE compiler
  pom.xml
  server/core/pom.xml
Labels: Urgent!

#5761 ISPN-8781 Do not fail on Dash Shell
  server/integration/feature-pack/src/main/resources/content/bin/jolokia.sh
Labels: Question

#5776 ISPN-8856 Exception eviction off heap size calculation always assumes
  core/src/main/java/org/infinispan/configuration/cache/MemoryConfiguration.java
  core/src/test/java/org/infinispan/eviction/impl/ExceptionEvictionTest.java
Labels: Trivial :-)

#5773 ISPN-8849 When rewrapping a SecureCache, don't lose the Subject
  core/src/main/java/org/infinispan/security/impl/SecureCacheImpl.java
Labels: Trivial :-)

#5793 ISPN-8866 Fixes documentation issues
  documentation/src/main/asciidoc/user_guide/cache_manager.adoc
  documentation/src/main/asciidoc/user_guide/extending.adoc
  documentation/src/main/asciidoc/user_guide/multimapcache.adoc
Labels: Trivial :-), Urgent!

#5799 ISPN-8888 Wrong warn message for eviction "EvictionConfigurationBuilder
  core/src/main/java/org/infinispan/configuration/cache/EvictionConfigurationBuilder.java
Labels: Trivial :-)
