Repository infinispan/infinispan, pull requests merged in 2019-10, with the labels that each got.

#7364 [9.4.x] ISPN-10679 expiration with xsite replication
  documentation/src/main/asciidoc/user_guide/cross_site_replication.adoc
Labels: Documentation

#7381 ISPN-10699 Add Transcoder name to log statements to aid debugging
  core/src/main/java/org/infinispan/util/logging/Log.java
  server/core/src/main/java/org/infinispan/server/core/dataconversion/JBossMarshallingTranscoder.java
  server/core/src/main/java/org/infinispan/server/core/dataconversion/JsonTranscoder.java
  server/core/src/main/java/org/infinispan/server/core/dataconversion/ProtostreamBinaryTranscoder.java
  server/core/src/main/java/org/infinispan/server/core/dataconversion/ProtostreamJsonTranscoder.java
  server/core/src/main/java/org/infinispan/server/core/dataconversion/ProtostreamObjectTranscoder.java
  server/core/src/main/java/org/infinispan/server/core/dataconversion/ProtostreamTextTranscoder.java
Labels: Trivial :-)

#7328 [9.4] ISPN-10630 Cluster wide cache stats do not work with exception based …
  core/src/main/java/org/infinispan/interceptors/impl/CacheMgmtInterceptor.java
  core/src/main/java/org/infinispan/interceptors/impl/TransactionalExceptionEvictionInterceptor.java
  core/src/main/java/org/infinispan/stats/impl/StatsCollector.java
  core/src/test/java/org/infinispan/stats/StatsMinNodeTest.java
Labels: Backport, On Hold

#7382 ISPN-10669 MurmurHash3 should have a special case for WrappedBytes
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/MultiServerStoreQueryTest.java
  commons/src/main/java/org/infinispan/commons/hash/MurmurHash3.java
Labels: Trivial :-)

#7397 ISPN-10715 removing unnecessary brandcli attribute
  build-configuration/pom.xml
  documentation/pom.xml
  documentation/src/main/asciidoc/topics/attributes/community-attributes.adoc
  documentation/src/main/asciidoc/topics/attributes/product-attributes.adoc
  documentation/src/main/asciidoc/topics/management_server.adoc
  documentation/src/main/asciidoc/topics/proc_accessing_health_cli.adoc
  documentation/src/main/asciidoc/topics/proc_syncing_data_source_clusters.adoc
Labels: Documentation

#7341 ISPN-10597 Docs: Configuring Hot Rod Java clients
  documentation/src/main/asciidoc/titles/hotrod_java/stories.adoc
  documentation/src/main/asciidoc/topics/code_examples/HotRodClientInstance.java
  documentation/src/main/asciidoc/topics/code_examples/HotRodClientProperties.java
  documentation/src/main/asciidoc/topics/config_examples/hotrod-client.properties
  documentation/src/main/asciidoc/topics/proc_configuring_hotrod_java_client_properties.adoc
  documentation/src/main/asciidoc/topics/proc_creating_hotrod_java_client_instances.adoc
  documentation/src/main/asciidoc/topics/server_protocols_hotrod.adoc
Labels: Changes Suggested, Documentation

#7386 ISPN-10704 updating HR client properties for 9.4.x
  documentation/src/main/asciidoc/user_guide/server_protocols_hotrod.adoc
Labels: Documentation

#7399 ISPN-10720 Update Caffeine to 2.8.x
  build-configuration/pom.xml
Labels: Trivial :-)

#7406 ISPN-10743 Serializer should only serialize user defined AdvancedExte…
  core/src/main/java/org/infinispan/configuration/serializing/Serializer.java
Labels: Trivial :-)

#7348 [9.4.x] ISPN-10618 Expiration creation/lastUsed timestamp are lost when prelo…
  core/src/main/java/org/infinispan/metadata/impl/InternalMetadataImpl.java
  core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java
  core/src/test/java/org/infinispan/distribution/BaseDistFunctionalTest.java
  core/src/test/java/org/infinispan/distribution/DistStorePreloadTest.java
  core/src/test/java/org/infinispan/scattered/store/ScatteredStorePreloadTest.java
Labels: Backport, On Hold

#7352 [9.4.x] ISPN-10650 Expiration should not be replicated cross site
  core/src/main/java/org/infinispan/cache/impl/CacheImpl.java
  core/src/test/java/org/infinispan/xsite/NonTxAsyncBackupTest.java
Labels: Backport, On Hold

#7359 [9.4.x] ISPN-10666 Eviction get stuck with <off-heap> configuration and optim…
  core/src/main/java/org/infinispan/container/offheap/OffHeapEntryFactoryImpl.java
  core/src/test/java/org/infinispan/container/offheap/OffHeapBoundedMultiNodeTest.java
  core/src/test/java/org/infinispan/container/offheap/OffHeapMultiNodeTest.java
Labels: Backport, On Hold

#7418 ISPN-10488 Infinispan Version is not printed in Quarkus native mode
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java
Labels: Trivial :-)

#7425 [9.4.x] ISPN-10722 Mgmt console: home page load fails with secured container
  core/src/main/java/org/infinispan/xsite/GlobalXSiteAdminOperations.java
Labels: Backport, Trivial :-)

#7412 ISPN-10724 Ignored caches per server causes a performance regression
  server/core/pom.xml
  server/core/src/main/java/org/infinispan/server/core/AbstractCacheIgnoreAware.java
  server/core/src/main/java/org/infinispan/server/core/AbstractProtocolServer.java
  server/core/src/main/java/org/infinispan/server/core/CacheIgnoreAware.java
  server/core/src/main/java/org/infinispan/server/core/CacheIgnoreManager.java
  server/core/src/main/java/org/infinispan/server/core/ProtocolServer.java
  server/core/src/main/java/org/infinispan/server/core/ServerManagement.java
  server/core/src/test/java/org/infinispan/server/core/AbstractProtocolServerTest.java
  server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodIgnoreCacheTest.java
  server/memcached/src/test/java/org/infinispan/server/memcached/MemcachedFunctionalTest.java
  server/rest/src/main/java/org/infinispan/rest/resources/ServerResource.java
  server/rest/src/test/java/org/infinispan/rest/helper/RestServerHelper.java
  server/runtime/src/main/java/org/infinispan/server/SecurityActions.java
  server/runtime/src/main/java/org/infinispan/server/Server.java
Labels: Performance ACK required!

#7433 ISPN-9600 ReflectionUtil.invokeAccessibly should not be public
  commons/src/main/java/org/infinispan/commons/util/ReflectionUtil.java
  core/src/main/java/org/infinispan/distribution/group/impl/GroupManagerImpl.java
  core/src/main/java/org/infinispan/factories/impl/SecurityActions.java
Labels: Trivial :-)

#7438 ISPN-10774 kill-server Ant task kills clients too
  server/runtime/src/main/ant/infinispan-server.xml
Labels: Trivial :-)

#7446 ISPN-10779 Fix RestConnectorTest.testUrlWithSSL failure
  cli/cli-client/src/test/java/org/infinispan/cli/connection/rest/RestConnectorTest.java
Labels: Test fix, Trivial :-)

#7453 [9.4.x] ISPN-10785 remove xsite expiration note
  documentation/src/main/asciidoc/user_guide/cross_site_replication.adoc
Labels: Documentation

#7450 ISPN-10280 Deprecate org.infinispan.commons.marshall.Externalizer and…
  commons/src/main/java/org/infinispan/commons/marshall/AdvancedExternalizer.java
  commons/src/main/java/org/infinispan/commons/marshall/Externalizer.java
  commons/src/main/java/org/infinispan/commons/marshall/SerializeWith.java
  core/src/main/java/org/infinispan/configuration/global/SerializationConfigurationBuilder.java
  core/src/main/java/org/infinispan/configuration/parsing/Parser.java
  core/src/main/java/org/infinispan/util/logging/Log.java
  core/src/main/resources/schema/infinispan-config-10.0.xsd
Labels: Trivial :-)

#7440 ISPN-10642 server health
  documentation/src/main/asciidoc/stories/assembly_monitoring_server_health.adoc
  documentation/src/main/asciidoc/titles/server/stories.adoc
  documentation/src/main/asciidoc/topics/con_server_health.adoc
  documentation/src/main/asciidoc/topics/proc_accessing_health_cli.adoc
  documentation/src/main/asciidoc/topics/proc_accessing_health_jmx.adoc
  documentation/src/main/asciidoc/topics/proc_accessing_health_rest.adoc
  documentation/src/main/asciidoc/topics/rest_examples/curl_domain_health.adoc
  documentation/src/main/asciidoc/topics/rest_examples/curl_standalone_health.adoc
  documentation/src/main/asciidoc/topics/rest_examples/rest_cache_health_response.json
  documentation/src/main/asciidoc/topics/rest_examples/server_health_rest.adoc
Labels: Documentation

#7463 ISPN-10783 Upgrade to latest Spring versions
  build-configuration/pom.xml
Labels: Trivial :-)

#7459 ISPN-10790 JDBCTableManipulation config is not validated
  persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/configuration/ConnectionFactoryConfigurationBuilder.java
  persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/configuration/JdbcStringBasedStoreConfigurationBuilder.java
  persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/configuration/ManagedConnectionFactoryConfigurationBuilder.java
  persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/configuration/SegmentColumnConfigurationBuilder.java
  persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/configuration/TableManipulationConfigurationBuilder.java
  persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/configuration/ConfigurationTest.java
  persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/stringbased/JdbcStringBasedStoreTest.java
  persistence/jdbc/src/test/resources/configs/string-based-jndi.xml
  tools/src/test/java/org/infinispan/tools/store/migrator/MigratorConfigurationTest.java
Labels: Changes Required, Suggestions please?

#7413 ISPN-10641 add details on server tasks
  documentation/src/main/asciidoc/stories/assembly_implementing_server_tasks.adoc
  documentation/src/main/asciidoc/titles/server/stories.adoc
  documentation/src/main/asciidoc/topics/proc_implementing_server_task.adoc
  documentation/src/main/asciidoc/topics/ref_server_task.adoc
  documentation/src/main/asciidoc/topics/server_tasks.adoc
Labels: Documentation

#7452 ISPN-10512 CLI User Guide
  documentation/src/main/asciidoc/index.asciidoc
  documentation/src/main/asciidoc/stories/assembly_cli_batch.adoc
  documentation/src/main/asciidoc/stories/assembly_cli_cache_operations.adoc
  documentation/src/main/asciidoc/stories/assembly_cli_command_reference.adoc
  documentation/src/main/asciidoc/stories/assembly_cli_counters.adoc
  documentation/src/main/asciidoc/stories/assembly_cli_protobuf_query.adoc
  documentation/src/main/asciidoc/stories/assembly_cli_starting.adoc
  documentation/src/main/asciidoc/stories/assembly_cli_tls.adoc
  documentation/src/main/asciidoc/stories/assembly_cli_xsite.adoc
  documentation/src/main/asciidoc/stories/assembly_server_quickstart.adoc
  documentation/src/main/asciidoc/stories/assembly_server_quickstart_cli.adoc
  documentation/src/main/asciidoc/titles/cli/cli-docinfo-footer.html
  documentation/src/main/asciidoc/titles/cli/cli-docinfo.html
  documentation/src/main/asciidoc/titles/cli/cli.asciidoc
  documentation/src/main/asciidoc/titles/cli/stories.adoc
  documentation/src/main/asciidoc/titles/server/server.html
  documentation/src/main/asciidoc/topics/attributes/product-attributes.adoc
  documentation/src/main/asciidoc/topics/proc_cli_adding_entries.adoc
  documentation/src/main/asciidoc/topics/proc_cli_batching_files.adoc
  documentation/src/main/asciidoc/topics/proc_cli_batching_interactive.adoc
  documentation/src/main/asciidoc/topics/proc_cli_configuring_media_types.adoc
  documentation/src/main/asciidoc/topics/proc_cli_connecting.adoc
  documentation/src/main/asciidoc/topics/proc_cli_creating_caches_files.adoc
  documentation/src/main/asciidoc/topics/proc_cli_creating_caches_templates.adoc
  documentation/src/main/asciidoc/topics/proc_cli_deleting_entries.adoc
  documentation/src/main/asciidoc/topics/proc_cli_navigating.adoc
  documentation/src/main/asciidoc/topics/proc_cli_querying_protobuf_schema.adoc
  documentation/src/main/asciidoc/topics/proc_cli_registering_protobuf_schema.adoc
  documentation/src/main/asciidoc/topics/proc_cli_starting.adoc
  documentation/src/main/asciidoc/topics/proc_cli_stopping.adoc
  documentation/src/main/asciidoc/topics/proc_creating_cache_cli.adoc
  documentation/src/main/asciidoc/topics/proc_creating_entry_cli.adoc
  documentation/src/main/asciidoc/topics/ref_cli_resource_tree.adoc
  documentation/src/main/asciidoc/topics/rest_api_v2.adoc
Labels: Documentation

#7377 ISPN-10695 Standardize the transport stack for the test suite
  core/src/test/java/org/infinispan/test/fwk/JGroupsConfigBuilder.java
  core/src/test/java/org/infinispan/test/fwk/SuiteResourcesAndLogTest.java
  documentation/src/main/asciidoc/topics/contributing/tests.adoc
  integrationtests/security-manager-it/pom.xml
  integrationtests/wildfly-modules/pom.xml
  jcache/tck-runner/pom.xml
  pom.xml
  server/runtime/pom.xml
  wildfly/infinispan/pom.xml
Labels: Needs Rebase

#7256 ISPN-10543 server logging docs
  documentation/src/main/asciidoc/stories/assembly_monitoring.adoc
  documentation/src/main/asciidoc/stories/assembly_server_logging.adoc
  documentation/src/main/asciidoc/titles/server/stories.adoc
  documentation/src/main/asciidoc/topics/con_access_logs.adoc
  documentation/src/main/asciidoc/topics/faq_content.adoc
  documentation/src/main/asciidoc/topics/proc_configuring_log_properties.adoc
  documentation/src/main/asciidoc/topics/proc_enabling_access_logs.adoc
  documentation/src/main/asciidoc/topics/proc_enabling_json_logging.adoc
  documentation/src/main/asciidoc/topics/ref_access_log_properties.adoc
  documentation/src/main/asciidoc/topics/ref_logging_framework.adoc
  documentation/src/main/asciidoc/topics/ref_logs_categories.adoc
  documentation/src/main/asciidoc/topics/ref_logs_formatters.adoc
  documentation/src/main/asciidoc/topics/ref_logs_handlers.adoc
  documentation/src/main/asciidoc/topics/ref_logs_levels.adoc
  documentation/src/main/asciidoc/topics/ref_logs_root.adoc
  documentation/src/main/asciidoc/topics/ref_logs_server.adoc
  server/runtime/src/main/server/server/conf/logging.properties
Labels: Documentation

#7468 [9.4] ISPN-10783 Upgrade to latest Spring versions
  build-configuration/pom.xml
  integrationtests/spring-boot2-it/pom.xml
  integrationtests/spring-boot2-it/src/test/java/org/infinispan/integrationtests/spring/boot/session/web/TestRESTController.java
Labels: Backport

#7481 ISPN-10815 Javadoc missing jboss-marshalling dependency
  javadoc/javadoc-all/pom.xml
Labels: Trivial :-), Urgent!

#7482 ISPN-10817 Use default HTTP/HTTPS port when using a URL for the CLI c…
  cli/cli-client/src/main/java/org/infinispan/cli/connection/rest/RestConnector.java
  cli/cli-client/src/test/java/org/infinispan/cli/connection/rest/RestConnectorTest.java
Labels: Trivial :-)

#7480 ISPN-10813 File Stores should notify user of being segmented can use many file descriptors
  core/src/main/java/org/infinispan/configuration/cache/SingleFileStoreConfigurationBuilder.java
  core/src/main/java/org/infinispan/util/logging/Log.java
  documentation/src/main/asciidoc/topics/upgrading.adoc
  persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/configuration/SoftIndexFileStoreConfigurationBuilder.java
Labels: Trivial :-)

#7490 ISPN-10828 updating for shutdown cmd
  documentation/src/main/asciidoc/stories/assembly_cli_command_reference.adoc
  documentation/src/main/asciidoc/stories/assembly_cli_starting.adoc
  documentation/src/main/asciidoc/stories/assembly_server_quickstart_cli.adoc
  documentation/src/main/asciidoc/topics/proc_cli_shutdown.adoc
  documentation/src/main/asciidoc/topics/proc_cli_stopping.adoc
Labels: Documentation

#7292 ISPN-10584 Create a new java rest client example with the new HttpClient API
  documentation/src/main/asciidoc/topics/server_protocols_rest.adoc
Labels: Documentation

#7503 [10.0.x] ISPN-10852 Upgrade to protostream-4.3.0.Final
  build-configuration/pom.xml
Labels: Backport

#7496 ISPN-10852 Upgrade to protostream-4.3.0.Final
  build-configuration/pom.xml
Labels: Trivial :-)

#7511 [10.0.x] ISPN-10862 SpringCache unwrapping NullValue singleton fails with Java…
  spring/spring5/spring5-common/src/main/java/org/infinispan/spring/common/provider/NullValue.java
Labels: Backport

#7514 ISPN-10867 AsyncStoreWithoutEvictionFunctionalTestsegmented creates d…
  core/src/test/java/org/infinispan/persistence/support/AsyncStoreWithoutEvictionFunctionalTest.java
Labels: Test fix, Trivial :-)

#7519 [10.0.x] ISPN-10867 AsyncStoreWithoutEvictionFunctionalTestsegmented creates d…
  core/src/test/java/org/infinispan/persistence/support/AsyncStoreWithoutEvictionFunctionalTest.java
Labels: Backport, Test fix, Trivial :-)

#7522 ISPN-10872 Update rxjava2 to 2.2.12
  build-configuration/pom.xml
Labels: Trivial :-)

#7323 [9.4] ISPN-9599 DefaultCacheManager.getGlobalComponentRegistry should require ADMIN permission
  core/src/test/java/org/infinispan/security/BaseAuthorizationTest.java
  core/src/test/java/org/infinispan/security/CacheAuthorizationTest.java
  core/src/test/java/org/infinispan/security/CacheManagerAuthorizationTest.java
Labels: Backport
