Repository infinispan/infinispan, pull requests merged in 2019-07, with the labels that each got.

#7110 ISPN-10378 Preload write is performed on persistence thread
  core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java
Labels: Trivial :-)

#7098 ISPN-10348 Migrate JDBC String based Cache Store from jdg-functional-tests to upstream
  persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/PooledConnectionFactoryTest.java
  persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/stringbased/AbstractStringBasedCacheStore.java
  persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/stringbased/StringStoreWithManagedConnectionFunctionalTest.java
  persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/stringbased/StringStoreWithPooledConnectionFunctionalTest.java
Labels: Changes Required

#7105 ISPN-10260 Invalid Javadoc Links
  documentation/src/main/asciidoc/topics/clustering.adoc
  documentation/src/main/asciidoc/topics/configuration.adoc
  documentation/src/main/asciidoc/topics/persistence_jdbc.adoc
Labels: Changes Suggested

#7130 ISPN-10393 Don't "require" socket-bindings when they are really optional
  server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/EndpointUtils.java
  server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/HotRodSubsystemAdd.java
  server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/MemcachedSubsystemAdd.java
  server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/RestService.java
  server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/RestSubsystemAdd.java
  server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/RouterSubsystemAdd.java
  server/integration/feature-pack/src/main/resources/configuration/domain/template.xml
  server/integration/feature-pack/src/main/resources/configuration/standalone/template.xml
Labels: Changes Required

#7131 [9.4] ISPN-10393 Don't "require" socket-bindings when they are really optional
  server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/EndpointUtils.java
  server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/HotRodSubsystemAdd.java
  server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/MemcachedSubsystemAdd.java
  server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/RestService.java
  server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/RestSubsystemAdd.java
  server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/RouterSubsystemAdd.java
  server/integration/feature-pack/src/main/resources/configuration/domain/template.xml
  server/integration/feature-pack/src/main/resources/configuration/standalone/template.xml
Labels: Changes Required

#7137 ISPN-10397 CacheStoreFactoryRegistry incorrect synchronization
  core/src/main/java/org/infinispan/persistence/factory/CacheStoreFactoryRegistry.java
Labels: Trivial :-)

#7139 [9.4.x] ISPN-10397 CacheStoreFactoryRegistry incorrect synchronization
  core/src/main/java/org/infinispan/persistence/factory/CacheStoreFactoryRegistry.java
Labels: Backport, Trivial :-)

#7021 [9.4.x] ISPN-10248 Allow users to customize NearCache behavior
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/near/NearCache.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/AssertsNearCache.java
Labels: Backport, On Hold

#6807 [9.4.x] ISPN-10070 DefaultCacheManager should stop components after start failure
  core/src/main/java/org/infinispan/factories/AbstractComponentRegistry.java
  core/src/main/java/org/infinispan/manager/DefaultCacheManager.java
  core/src/test/java/org/infinispan/commands/module/TestGlobalConfiguration.java
  core/src/test/java/org/infinispan/commands/module/TestGlobalConfigurationBuilder.java
  core/src/test/java/org/infinispan/commands/module/TestGlobalConfigurationSerializer.java
  core/src/test/java/org/infinispan/commands/module/TestModuleCommandExtensions.java
  core/src/test/java/org/infinispan/commands/module/TestModuleLifecycle.java
  core/src/test/java/org/infinispan/configuration/serializer/ConfigurationSerializerTest.java
  core/src/test/java/org/infinispan/manager/CacheManagerTest.java
  core/src/test/resources/META-INF/services/org.infinispan.commands.module.ModuleCommandExtensions
Labels: Backport

#7144 ISPN-10395 Fix missing version for ispn-cli
  pom.xml
Labels: Test fix, Urgent!

#7156 ISPN-10413 os-maven-plugin not setting 'os.detected.classifier' prope…
  pom.xml
  server/core/pom.xml
Labels: Trivial :-), Urgent!

#7171 ISPN-10430 Fix test suite thread leak error
  persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/stringbased/AbstractStringBasedCacheStore.java
Labels: Test fix, Trivial :-)

#7145 ISPN-10266 SpringCache clear when cache is removed
  spring/spring5/spring5-remote/src/main/java/org/infinispan/spring/remote/provider/SpringRemoteCacheManager.java
  spring/spring5/spring5-remote/src/test/java/org/infinispan/spring/remote/provider/SpringRemoteCacheManagerTest.java
Labels: Urgent!
