Repository infinispan/infinispan, pull requests merged in 2019-01, with the labels that each got.

#6585 ISPN-9395 Failures in karaf-maven-plugin on Windows
  pom.xml
Labels: Test FIX

#6586 ISPN-9395 Failures in karaf-maven-plugin on Windows
  pom.xml
Labels: Backport

#6478 [8.2.x] ISPN-9701 TransactionTable does not shutdown gracefully
  core/src/main/java/org/infinispan/transaction/impl/AbstractEnlistmentAdapter.java
  core/src/test/java/org/infinispan/lock/singlelock/AbstractInitiatorCrashTest.java
  core/src/test/java/org/infinispan/test/MultipleCacheManagersTest.java
Labels: Backport

#6600 ISPN-9874 Server Provisioning artifact overrides for Lucene and GSON …
  pom.xml
  server/integration/build/server-provisioning-fat.xml
  server/integration/build/server-provisioning-thin.xml
Labels: Urgent!

#6599 [9.4] ISPN-9874 Server Provisioning artifact overrides for Lucene and GSON …
  pom.xml
  server/integration/build/server-provisioning-fat.xml
  server/integration/build/server-provisioning-thin.xml
Labels: Urgent!

#6607 [9.4.x] ISPN-9625 Clustered Locks reliability and consistency XML config
  documentation/src/main/asciidoc/user_guide/clustered_lock.adoc
  lock/pom.xml
  lock/src/main/java/org/infinispan/lock/configuration/Attribute.java
  lock/src/main/java/org/infinispan/lock/configuration/ClusteredLockConfiguration.java
  lock/src/main/java/org/infinispan/lock/configuration/ClusteredLockConfigurationBuilder.java
  lock/src/main/java/org/infinispan/lock/configuration/ClusteredLockConfigurationParser.java
  lock/src/main/java/org/infinispan/lock/configuration/ClusteredLockManagerConfiguration.java
  lock/src/main/java/org/infinispan/lock/configuration/ClusteredLockManagerConfigurationBuilder.java
  lock/src/main/java/org/infinispan/lock/configuration/Element.java
  lock/src/main/java/org/infinispan/lock/configuration/Reliability.java
  lock/src/main/java/org/infinispan/lock/impl/ClusteredLockModuleLifecycle.java
  lock/src/main/java/org/infinispan/lock/impl/functions/IsLocked.java
  lock/src/main/java/org/infinispan/lock/impl/functions/LockFunction.java
  lock/src/main/java/org/infinispan/lock/impl/functions/UnlockFunction.java
  lock/src/main/java/org/infinispan/lock/impl/lock/ClusteredLockImpl.java
  lock/src/main/java/org/infinispan/lock/impl/lock/RequestExpirationScheduler.java
  lock/src/main/java/org/infinispan/lock/impl/manager/EmbeddedClusteredLockManager.java
  lock/src/main/java/org/infinispan/lock/logging/Log.java
  lock/src/main/resources/OSGI-INF/blueprint/blueprint.xml
  lock/src/main/resources/schema/infinispan-clustered-locks-config-9.4.xsd
  lock/src/test/java/org/infinispan/lock/AvailableReliabilitySplitBrainTest.java
  lock/src/test/java/org/infinispan/lock/BaseClusteredLockSplitBrainTest.java
  lock/src/test/java/org/infinispan/lock/BaseClusteredLockTest.java
  lock/src/test/java/org/infinispan/lock/ClusteredLockAvailableReliabilityTest.java
  lock/src/test/java/org/infinispan/lock/ClusteredLockTest.java
  lock/src/test/java/org/infinispan/lock/ClusteredLockWith2NodesTest.java
  lock/src/test/java/org/infinispan/lock/ConfigurationSerializerTest.java
  lock/src/test/java/org/infinispan/lock/ConfigurationTest.java
  lock/src/test/java/org/infinispan/lock/ConsistentReliabilitySplitBrainTest.java
  lock/src/test/java/org/infinispan/lock/impl/lock/ClusteredLockImplLowAvailableReliabilityTest.java
  lock/src/test/resources/config/clustered-locks-dist.xml
  lock/src/test/resources/config/clustered-locks-repl.xml
  server/integration/infinispan/src/main/resources/subsystem-templates/infinispan-core.xml
Labels: Backport

#6623 [9.4] ISPN-7333 Unwrap protobuf cache security for internal uses
  remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/ProtobufMetadataManagerImpl.java
  remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/SecurityActions.java
Labels: Backport

#6629 ISPN-4075 State transfer should preserve the timestamps of entries
  core/src/main/java/org/infinispan/commands/write/PutKeyValueCommand.java
  core/src/main/java/org/infinispan/commands/write/PutMapCommand.java
  core/src/main/java/org/infinispan/interceptors/impl/CallInterceptor.java
  core/src/main/java/org/infinispan/interceptors/impl/PrefetchInterceptor.java
  core/src/main/java/org/infinispan/metadata/impl/InternalMetadataImpl.java
  core/src/main/java/org/infinispan/scattered/impl/ScatteredStateConsumerImpl.java
  core/src/main/java/org/infinispan/statetransfer/StateConsumerImpl.java
  tasks/scripting/src/main/java/org/infinispan/scripting/impl/ScriptingInterceptor.java
Labels: Changes Required

#6630 [9.4.x] ISPN-4075 State transfer should preserve the timestamps of entries
  core/src/main/java/org/infinispan/commands/write/PutKeyValueCommand.java
  core/src/main/java/org/infinispan/commands/write/PutMapCommand.java
  core/src/main/java/org/infinispan/interceptors/impl/PrefetchInterceptor.java
  core/src/main/java/org/infinispan/metadata/impl/InternalMetadataImpl.java
  core/src/main/java/org/infinispan/scattered/impl/ScatteredStateConsumerImpl.java
  core/src/main/java/org/infinispan/statetransfer/StateConsumerImpl.java
  tasks/scripting/src/main/java/org/infinispan/scripting/impl/ScriptingInterceptor.java
Labels: Backport

#6632 [9.4] ISPN-9911 Fix JMX javadoc generation
  build-configuration/pom.xml
Labels: Urgent!

#6631 ISPN-9911 Fix JMX javadoc generation
  build-configuration/pom.xml
Labels: Urgent!

#6638 [9.4.x] ISPN-9657 multimap, lock and counter OSGI manifest
  counter/pom.xml
  lock/pom.xml
  multimap/pom.xml
Labels: Backport
