Repository infinispan/infinispan, pull requests merged in 2019-06, with the labels that each got.

#7004 ISPN-10230 Fix ExceptionInCommandTest
  core/src/test/java/org/infinispan/tx/exception/ExceptionInCommandTest.java
Labels: Test fix, Trivial :-)

#7011 ISPN-10267 Rethrow remote exceptions
  hibernate/cache-commons/src/main/java/org/infinispan/hibernate/cache/commons/access/UnorderedDistributionInterceptor.java
Labels: Urgent!

#7007 ISPN-10263 upgrade spring dependencies
  build-configuration/pom.xml
Labels: Trivial :-)

#7017 ISPN-10272 RocskDbStore BatchWrite org.rocksdb.RocksDBException: unkn…
  persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/RocksDBStore.java
Labels: Trivial :-)

#7014 ISPN-10234 Remove SingletonCacheWriter extras
  core/src/main/java/org/infinispan/configuration/parsing/Element.java
  core/src/main/java/org/infinispan/configuration/parsing/Parser.java
  server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/InfinispanMessages.java
  server/integration/infinispan/src/main/resources/org/jboss/as/clustering/infinispan/subsystem/LocalDescriptions.properties
Labels: Trivial :-)

#7008 ISPN-10264 Wrong time conversion for async xsite take-offline
  commons/src/main/java/org/infinispan/commons/time/DefaultTimeService.java
  commons/src/main/java/org/infinispan/commons/time/TimeService.java
  core/src/main/java/org/infinispan/remoting/rpc/RpcManagerImpl.java
  core/src/main/java/org/infinispan/remoting/transport/XSiteAsyncAckListener.java
  core/src/main/java/org/infinispan/xsite/BackupSenderImpl.java
  core/src/test/java/org/infinispan/remoting/transport/jgroups/JGroupsBackupResponseUnitTest.java
  core/src/test/java/org/infinispan/xsite/offline/AsyncTimeBasedOfflineTest.java
  extended-statistics/src/test/java/org/infinispan/stats/BaseTxClusterExtendedStatisticLogicTest.java
  extended-statistics/src/test/java/org/infinispan/stats/logic/LocalTxClusterExtendedStatisticLogicTest.java
  extended-statistics/src/test/java/org/infinispan/stats/logic/OptimisticLockingTxClusterExtendedStatisticLogicTest.java
  extended-statistics/src/test/java/org/infinispan/stats/logic/PessimisticLockingTxClusterExtendedStatisticLogicTest.java
Labels: Trivial :-)

#6985 [9.4.x] ISPN-10239 FineGrainedAtomicMap.clear() concurrency issues
  core/src/main/java/org/infinispan/atomic/impl/AtomicKeySetImpl.java
  core/src/main/java/org/infinispan/atomic/impl/FineGrainedAtomicMapProxyImpl.java
Labels: Test fix

#6795 [9.4.x] ISPN-10080 Test cache managers created in other threads cannot join the cluster with UDP
  core/src/test/java/org/infinispan/statetransfer/JoinInNewThreadTest.java
  core/src/test/java/org/infinispan/test/fwk/JGroupsConfigBuilder.java
Labels: Backport

#7009 [9.4.x] ISPN-10264 Wrong time conversion for async xsite take-offline
  commons/src/main/java/org/infinispan/commons/time/DefaultTimeService.java
  commons/src/main/java/org/infinispan/commons/time/TimeService.java
  core/src/main/java/org/infinispan/remoting/rpc/RpcManagerImpl.java
  core/src/main/java/org/infinispan/remoting/transport/XSiteAsyncAckListener.java
  core/src/main/java/org/infinispan/xsite/BackupSenderImpl.java
  core/src/test/java/org/infinispan/remoting/transport/jgroups/JGroupsBackupResponseUnitTest.java
  core/src/test/java/org/infinispan/xsite/offline/AsyncTimeBasedOfflineTest.java
  extended-statistics/src/test/java/org/infinispan/stats/BaseTxClusterExtendedStatisticLogicTest.java
  extended-statistics/src/test/java/org/infinispan/stats/logic/LocalTxClusterExtendedStatisticLogicTest.java
  extended-statistics/src/test/java/org/infinispan/stats/logic/OptimisticLockingTxClusterExtendedStatisticLogicTest.java
  extended-statistics/src/test/java/org/infinispan/stats/logic/PessimisticLockingTxClusterExtendedStatisticLogicTest.java
Labels: Backport, Trivial :-)

#7019 ISPN-10277 Fix Spring Schema location to account for both http and https
  spring/spring5/spring5-common/src/main/resources/META-INF/spring.schemas
  spring/spring5/spring5-common/src/main/resources/schema/infinispan-spring-10.0.xsd
  spring/spring5/spring5-embedded/src/test/resources/org/infinispan/spring/embedded/config/CacheLoaderNotFoundTest-context.xml
  spring/spring5/spring5-embedded/src/test/resources/org/infinispan/spring/embedded/config/InfinispanContainerCacheManagerDefinitionTest-context.xml
  spring/spring5/spring5-embedded/src/test/resources/org/infinispan/spring/embedded/config/InfinispanEmbeddedCacheManagerDefinitionTest-context.xml
  spring/spring5/spring5-embedded/src/test/resources/org/infinispan/spring/embedded/provider/sample/SampleEmbeddedCacheTestConfig.xml
  spring/spring5/spring5-embedded/src/test/resources/org/infinispan/spring/embedded/provider/sample/SampleTransactionIntegrationTestConfig.xml
  spring/spring5/spring5-embedded/src/test/resources/org/infinispan/spring/embedded/provider/sample/SampleXmlConfigurationTestConfig.xml
  spring/spring5/spring5-remote/src/test/resources/org/infinispan/spring/remote/config/InfinispanRemoteCacheManagerDefinitionTest-context.xml
  spring/spring5/spring5-remote/src/test/resources/org/infinispan/spring/remote/provider/sample/SampleRemoteCacheTestConfig.xml
Labels: Urgent!

#7020 [9.4] ISPN-10277 Fix Spring Schema location to account for both http and https
  spring/spring4/spring4-common/src/main/resources/META-INF/spring.schemas
  spring/spring4/spring4-embedded/src/test/resources/org/infinispan/spring/config/CacheLoaderNotFoundTest-context.xml
  spring/spring4/spring4-embedded/src/test/resources/org/infinispan/spring/config/InfinispanContainerCacheManagerDefinitionTest-context.xml
  spring/spring4/spring4-embedded/src/test/resources/org/infinispan/spring/config/InfinispanEmbeddedCacheManagerDefinitionTest-context.xml
  spring/spring4/spring4-embedded/src/test/resources/org/infinispan/spring/provider/sample/SampleEmbeddedCacheTestConfig.xml
  spring/spring4/spring4-embedded/src/test/resources/org/infinispan/spring/provider/sample/SampleTransactionIntegrationTestConfig.xml
  spring/spring4/spring4-embedded/src/test/resources/org/infinispan/spring/provider/sample/SampleXmlConfigurationTestConfig.xml
  spring/spring4/spring4-remote/src/test/resources/org/infinispan/spring/config/InfinispanRemoteCacheManagerDefinitionTest-context.xml
  spring/spring4/spring4-remote/src/test/resources/org/infinispan/spring/provider/sample/SampleRemoteCacheTestConfig.xml
  spring/spring5/spring5-common/src/main/resources/META-INF/spring.schemas
  spring/spring5/spring5-embedded/src/test/resources/org/infinispan/spring/embedded/config/CacheLoaderNotFoundTest-context.xml
  spring/spring5/spring5-embedded/src/test/resources/org/infinispan/spring/embedded/config/InfinispanContainerCacheManagerDefinitionTest-context.xml
  spring/spring5/spring5-embedded/src/test/resources/org/infinispan/spring/embedded/config/InfinispanEmbeddedCacheManagerDefinitionTest-context.xml
  spring/spring5/spring5-embedded/src/test/resources/org/infinispan/spring/embedded/provider/sample/SampleEmbeddedCacheTestConfig.xml
  spring/spring5/spring5-embedded/src/test/resources/org/infinispan/spring/embedded/provider/sample/SampleTransactionIntegrationTestConfig.xml
  spring/spring5/spring5-embedded/src/test/resources/org/infinispan/spring/embedded/provider/sample/SampleXmlConfigurationTestConfig.xml
  spring/spring5/spring5-remote/src/test/resources/org/infinispan/spring/remote/config/InfinispanRemoteCacheManagerDefinitionTest-context.xml
  spring/spring5/spring5-remote/src/test/resources/org/infinispan/spring/remote/provider/sample/SampleRemoteCacheTestConfig.xml
Labels: Urgent!

#7037 ISPN-10300 StateConsumerImpl needs to wait for segment addition to co…
  core/src/main/java/org/infinispan/statetransfer/StateConsumerImpl.java
Labels: Trivial :-)

#7039 ISPN-10300 StateConsumerImpl needs to wait for segment addition to co…
  core/src/test/java/org/infinispan/statetransfer/StateConsumerTest.java
Labels: Test fix, Trivial :-)

#7032 [9.4.x] ISPN-10296 SKIP_LISTENER_NOTIFICATION flag in hotrod
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/Flag.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/SkipNotificationsFlagTest.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/ClientEventsWithIgnoreNotificationsFlagTest.java
  core/src/main/java/org/infinispan/notifications/cachelistener/CacheNotifierImpl.java
  documentation/src/main/asciidoc/upgrading/upgrading-content.adoc
  server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodHeader.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/ProtocolFlag.java
Labels: Backport

#7030 ISPN-10295 Upgrade to JGroups 4.0.20.Final
  build-configuration/pom.xml
Labels: Backport

#7018 [9.4.x] ISPN-10272 RocskDbStore BatchWrite org.rocksdb.RocksDBException: unkn…
  persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/RocksDBStore.java
Labels: Backport, Trivial :-)

#7045 [9.4] ISPN-10307 Upgrade to Jackson Databind 2.9.8
  build-configuration/pom.xml
Labels: Urgent!

#7050 ISPN-10305 EmbeddedAllTest doesn't clean up its files
  commons-test/src/main/java/org/infinispan/commons/test/junit/TmpDir.java
  integrationtests/all-embedded-it/src/test/java/org/infinispan/all/embedded/EmbeddedAllTest.java
Labels: Test fix

#6982 [9.4] ISPN-10149 - Enable checkstyle plugin during the verify maven phase
  build-configuration/pom.xml
  checkstyle/pom.xml
  client/hotrod-client/src/test/resources/hotrod-client-replacement.properties
  core/src/test/resources/infinispan-features.properties
  documentation/src/main/asciidoc/contributing/building.adoc
  hibernate/cache-commons/pom.xml
  hibernate/cache-commons/src/test/resources/hibernate.properties
  hibernate/cache-commons/src/test/resources/log4j.properties
  hibernate/cache-spi/pom.xml
  hibernate/cache-v51/pom.xml
  integrationtests/as-lucene-directory/src/test/resources/module-versions.properties
  integrationtests/security-it/src/test/resources/jgroups-simple-auth.properties
  lucene/lucene-directory/pom.xml
  osgi/pom.xml
  persistence/jdbc/src/test/resources/c3p0.properties
  pom.xml
  server/integration/testsuite/src/test/resources/application-users.properties
  server/integration/testsuite/src/test/resources/filters/h2.properties
  server/integration/testsuite/src/test/resources/hotrod-client.properties
  server/integration/testsuite/src/test/resources/jul.properties
  server/integration/testsuite/src/test/resources/roles.properties
  spring/spring5/spring5-remote/src/test/resources/org/infinispan/spring/remote/provider/hotrod-client.properties
  spring/spring5/spring5-remote/src/test/resources/org/infinispan/spring/remote/support/hotrod-client.properties
Labels: Needs Rebase

#7058 ISPN-9677 Check tx running when updating query cache
  hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/NonTxQueryTest.java
  hibernate/cache-v53/src/main/java/org/infinispan/hibernate/cache/v53/impl/QueryResultsRegionImpl.java
Labels: Trivial :-), Urgent!

#7057 ISPN-10305 EmbeddedAllTest doesn't clean up its files
  commons-test/src/main/java/org/infinispan/commons/test/junit/TmpDir.java
  integrationtests/all-embedded-it/src/test/java/org/infinispan/all/embedded/EmbeddedAllTest.java
Labels: Backport

#7056 [9.4] ISPN-9291 BasePartitionHandlingTest.Partition.installMergeView()
  core/src/main/java/org/infinispan/conflict/impl/DefaultConflictManager.java
  core/src/test/java/org/infinispan/conflict/impl/CrashedNodeDuringConflictResolutionTest.java
  core/src/test/java/org/infinispan/partitionhandling/BasePartitionHandlingTest.java
Labels: Backport, Test fix

#7054 ISPN-10321 Jenkins ignores orphaned item strategy in UI
  Jenkinsfile
  Jenkinsfile-release
Labels: Trivial :-)

#7061 Small Spelling Correction
  documentation/src/main/asciidoc/user_guide/interceptors.adoc
Labels: Documentation

#7022 [9.4.x] ISPN-9886 JGRP-2301 Add UFC protocol even in TCP stacks
  cloud/src/main/resources/default-configs/default-jgroups-ec2.xml
  cloud/src/main/resources/default-configs/default-jgroups-google.xml
  cloud/src/main/resources/default-configs/default-jgroups-kubernetes.xml
  core/src/main/resources/default-configs/default-jgroups-tcp.xml
  core/src/test/resources/configs/xsite/bridge.xml
  core/src/test/resources/stacks/tcp.xml
  core/src/test/resources/stacks/tcp_mping/tcp1.xml
  core/src/test/resources/stacks/tcp_mping/tcp2.xml
  demos/gui/src/main/release/etc/config/jgroups-tcp.xml
  documentation/src/main/asciidoc/topics/jgroups/tcp_ping.adoc
  hibernate/cache-commons/src/test/resources/2lc-test-tcp.xml
  integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node0.xml
  integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node1-fail.xml
  integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node1.xml
  integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-node0.xml
  integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-node1.xml
  integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-user-node0.xml
  integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-prop-handler-node0.xml
  integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-prop-handler-node1.xml
  persistence/jdbc/src/test/resources/configs/as7/jdbc-standalone.xml
  server/integration/jgroups/src/main/resources/subsystem-templates/cloud-jgroups.xml
Labels: Backport, On Hold

#7074 ISPN-10314 Fixup: Remove debug logging
  bin/process_trace_logs.sh
Labels: Trivial :-)

#7072 ISPN-10330 BasicComponentRegistryImpl.findFactory() concurrency issue
  core/src/main/java/org/infinispan/factories/impl/BasicComponentRegistryImpl.java
Labels: Backport

#7070 [9.4.x] ISPN-10321 Jenkins ignores orphaned item strategy in UI
  Jenkinsfile
  Jenkinsfile-release
Labels: Trivial :-)

#7053 ISPN-10313 EvictInvalidatedNearCacheTest.testEvictAfterReachingMax ra…
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/near/BoundedConcurrentMapNearCache.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/AssertsNearCache.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/EvictInvalidatedNearCacheTest.java
Labels: Test fix

#7085 [9.4] ISPN-10337 JDBC Purge improvements
  persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/AbstractTableManager.java
  persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/stringbased/JdbcStringBasedStore.java
Labels: Backport, On Hold

#7096 ISPN-10363 LazyInitializingExecutorService is not thread-safe
  core/src/main/java/org/infinispan/executors/LazyInitializingBlockingTaskAwareExecutorService.java
  core/src/main/java/org/infinispan/executors/LazyInitializingExecutorService.java
  core/src/main/java/org/infinispan/executors/LazyInitializingScheduledExecutorService.java
  core/src/main/java/org/infinispan/factories/NamedExecutorsFactory.java
  core/src/main/java/org/infinispan/util/concurrent/BlockingTaskAwareExecutorServiceImpl.java
  core/src/test/java/org/infinispan/remoting/AsynchronousInvocationTest.java
Labels: Test fix

#7094 ISPN-9257 ClustertopologyManagerTest.testAbruptLeaveAfterGetStatus2
  core/src/test/java/org/infinispan/statetransfer/ClusterTopologyManagerTest.java
Labels: Test fix

#7097 [9.4.x] ISPN-9257 ClustertopologyManagerTest.testAbruptLeaveAfterGetStatus2
  core/src/test/java/org/infinispan/statetransfer/ClusterTopologyManagerTest.java
Labels: Backport, Test fix

#7100 ISPN-10364 Persistence (Blocking) thread pool should have a queue
  core/src/main/java/org/infinispan/factories/KnownComponentNames.java
Labels: Trivial :-)
