Repository infinispan/infinispan, pull requests merged in 2019-03, with the labels that each got.

#6733 ISPN-9373 Fix FunctionalListenersTest
  core/src/test/java/org/infinispan/functional/AbstractFunctionalTest.java
Labels: Test fix

#6737 ISPN-10020 PolarionJUnitXMLReporter assertion failure after configura…
  commons-test/src/main/java/org/infinispan/commons/test/PolarionJUnitXMLReporter.java
Labels: Trivial :-)

#6704 [9.4] ISPN-9908 Cache startup failure with server hinting and insufficient …
  core/src/main/java/org/infinispan/distribution/ch/impl/OwnershipStatistics.java
  core/src/main/java/org/infinispan/distribution/ch/impl/SyncConsistentHashFactory.java
  core/src/main/java/org/infinispan/distribution/ch/impl/TopologyAwareConsistentHashFactory.java
  core/src/main/java/org/infinispan/distribution/ch/impl/TopologyAwareSyncConsistentHashFactory.java
  core/src/main/java/org/infinispan/distribution/topologyaware/TopologyInfo.java
  core/src/test/java/org/infinispan/distribution/topologyaware/TopologyAwareConsistentHashFactoryTest.java
  core/src/test/java/org/infinispan/distribution/topologyaware/TopologyAwareSyncConsistentHashFactoryTest.java
Labels: Backport, On Hold

#6715 [9.4] ISPN-9997 Fix SecurityException when creating clustered secure cache …
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/AuthenticationConfigurationBuilder.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/admin/SecureRemoteCacheAdminTest.java
  core/src/main/java/org/infinispan/globalstate/impl/SecurityActions.java
  core/src/main/java/org/infinispan/globalstate/impl/VolatileLocalConfigurationStorage.java
  documentation/src/main/asciidoc/user_guide/security.adoc
  server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodServer.java
Labels: Backport

#6726 [9.4] ISPN-10007 Lucene directory module missing reactive-stream dependencies
  feature-pack/embedded-query/src/main/resources/modules/org/infinispan/lucene-directory/slot/module.xml
Labels: Backport, On Hold

#6740 [9.4.x] ISPN-10017 edits to bringing sites back online and state transfer
  documentation/src/main/asciidoc/user_guide/cross_site_replication.adoc
Labels: Backport, On Hold

#6743 [9.4.x] ISPN-10016 Provide a default Lucene analyzer for file names
  query/src/main/java/org/infinispan/query/impl/DefaultSearchMappingProvider.java
Labels: Backport, On Hold

#6747 [9.4.x] ISPN-10022 Tx compute command updates are not written to stores
  core/src/main/java/org/infinispan/interceptors/impl/TxBatchUpdater.java
  core/src/test/java/org/infinispan/interceptors/impl/CacheWriterTxModificationsTest.java
Labels: Backport

#6756 [9.4.x] ISPN-9867 Client listeners are removed when a notification occurs
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/RemoteContinuousQueryLeavingRemoteCacheManagerTest.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/ClientListenerRegistry.java
Labels: Backport

#6752 ISPN-10031 Remove doc regarding expiration not working with state tra…
  documentation/src/main/asciidoc/user_guide/eviction.adoc
Labels: Trivial :-)

#6762 ISPN-10049 Persistence Executor threads should use ProcessorInfo
  core/src/main/java/org/infinispan/factories/KnownComponentNames.java
Labels: Trivial :-)

#6763 ISPN-10049 Persistence Executor threads should use ProcessorInfo
  core/src/main/java/org/infinispan/factories/KnownComponentNames.java
Labels: Backport, Trivial :-)

#6698 [9.4] ISPN-9980 Upgrade Spring 5 dependencies
  build-configuration/pom.xml
Labels: Backport

#6739 ISPN-9191 ExceptionEvictionTest random failure during clearContent
  core/src/test/java/org/infinispan/eviction/impl/ExceptionEvictionTest.java
Labels: Test fix

#6767 [9.4] ISPN-10056 Client statistics javadoc
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/StatisticsConfigurationBuilder.java
Labels: Backport

#6775 ISPN-10060 Log netty transport epoll/nio messages as INFO
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/logging/Log.java
  server/core/src/main/java/org/infinispan/server/core/logging/Log.java
Labels: Trivial :-)

#6776 [9.4] ISPN-10060 Log netty transport epoll/nio messages as INFO
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/logging/Log.java
  server/core/src/main/java/org/infinispan/server/core/logging/Log.java
Labels: Trivial :-)

#6778 ISPN-10061 ThreadLeakChecker states that "ClassCache Reaper" is leake…
  commons-test/src/main/java/org/infinispan/commons/test/ThreadLeakChecker.java
Labels: Backport, Test fix, Trivial :-)

#6735 ISPN-10019 Avoid transport exception when using clustered locks
  counter/src/main/java/org/infinispan/counter/impl/CounterModuleLifecycle.java
  lock/src/main/java/org/infinispan/lock/EmbeddedClusteredLockManagerFactory.java
  lock/src/main/java/org/infinispan/lock/impl/ClusteredLockModuleLifecycle.java
  lock/src/main/java/org/infinispan/lock/logging/Log.java
  lock/src/test/java/org/infinispan/lock/ClusteredLockWithoutClusterTest.java
Labels: Trivial :-)

#6736 [9.4] ISPN-10019 Avoid transport exception when using clustered locks
  counter/src/main/java/org/infinispan/counter/impl/CounterModuleLifecycle.java
  lock/src/main/java/org/infinispan/lock/EmbeddedClusteredLockManagerFactory.java
  lock/src/main/java/org/infinispan/lock/impl/ClusteredLockModuleLifecycle.java
  lock/src/main/java/org/infinispan/lock/logging/Log.java
  lock/src/test/java/org/infinispan/lock/ClusteredLockWithoutClusterTest.java
Labels: Backport

#6713 ISPN-9306 - Unguarded lazy initialization of SQL statements in JDBCacheStore
  persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/AbstractTableManager.java
  persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/DB2TableManager.java
  persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/GenericTableManager.java
  persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/H2TableManager.java
  persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/MySQLTableManager.java
  persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/OracleTableManager.java
  persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/PostgresTableManager.java
  persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/SQLServerTableManager.java
  persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/SQLiteTableManager.java
  persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/SybaseTableManager.java
  persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/TableManager.java
  persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/TableManagerFactory.java
  persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/stringbased/JdbcStringBasedStore.java
  persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/TableManagerTest.java
  persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/TableNameUniquenessTest.java
  persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/stores/TxStoreTest.java
  persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/stringbased/JdbcStringBasedStoreTest.java
  tools/src/main/java/org/infinispan/tools/store/migrator/jdbc/JdbcStoreReader.java
Labels: Changes Required

#6790 ISPN-10020 PolarionJUnitXMLReporter assertion failure after configura…
  commons-test/src/main/java/org/infinispan/commons/test/PolarionJUnitXMLReporter.java
Labels: Backport

#6804 ISPN-10077 Fix ClientSocketReadTimeoutTest.testPutTimeout
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/ClientSocketReadTimeoutTest.java
Labels: Test fix, Trivial :-)

#6805 [9.4] ISPN-10077 Fix ClientSocketReadTimeoutTest.testPutTimeout
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/ClientSocketReadTimeoutTest.java
Labels: Test fix, Trivial :-)
