Repository infinispan/infinispan, pull requests merged in 2019-05, with the labels that each got.

#6870 ISPN-10154 Fix RESTCertSecurityIT.testInvalidCertificateAccess
  server/integration/testsuite/src/test/java/org/infinispan/server/test/security/rest/RESTCertSecurityIT.java
Labels: Test fix

#6869 [9.4] ISPN-10154 Fix RESTCertSecurityIT.testInvalidCertificateAccess
  server/integration/testsuite/src/test/java/org/infinispan/server/test/security/rest/RESTCertSecurityIT.java
Labels: Test fix

#6880 ISPN-10163 Optionally use the fat server when running tests
  README-Build.md
  distribution/package.xml
  distribution/pom.xml
  distribution/wildfly-provisioning.xml
  integrationtests/all-remote-it/pom.xml
  integrationtests/wildfly-modules/pom.xml
  jcache/tck-runner/pom.xml
  pom.xml
  server/integration/build/assembly-server.xml
  server/integration/build/bin/moddep.sh
  server/integration/build/pom.xml
  server/integration/build/server-provisioning-dist.xml
  server/integration/testsuite/pom.xml
Labels: Urgent!

#6881 [9.4] ISPN-10163 Optionally use the fat server when running tests
  README-Build.md
  distribution/package.xml
  distribution/pom.xml
  distribution/wildfly-provisioning.xml
  integrationtests/all-remote-it/pom.xml
  integrationtests/wildfly-modules/pom.xml
  jcache/tck-runner/pom.xml
  pom.xml
  server/integration/build/assembly-server.xml
  server/integration/build/bin/moddep.sh
  server/integration/build/pom.xml
  server/integration/build/server-provisioning-dist.xml
  server/integration/testsuite/pom.xml
Labels: Urgent!

#6879 [9.4] ISPN-10105 Reorder wildfly provisioning feature-packs to prevent hibe…
  distribution/wildfly-provisioning.xml
Labels: Backport

#6884 ISPN-10164 Ensure that all tests are running with the correct JVM ver…
  build-configuration/pom.xml
  commons-test/src/main/java/org/infinispan/commons/test/EnvironmentCheck.java
  commons-test/src/main/java/org/infinispan/commons/test/JUnitTestListener.java
  commons-test/src/main/java/org/infinispan/commons/test/TestNGSuiteChecksTest.java
  commons/pom.xml
  hibernate/cache-v51/pom.xml
  hibernate/cache-v53/pom.xml
  integrationtests/all-embedded-it/pom.xml
  integrationtests/all-embedded-query-it/pom.xml
  integrationtests/spring-boot-it/pom.xml
  lucene/directory-provider/pom.xml
  object-filter/pom.xml
  pom.xml
  query-dsl/pom.xml
  remote-query/remote-query-client/pom.xml
  server/integration/commons/pom.xml
  server/integration/endpoint/pom.xml
  server/integration/infinispan/pom.xml
  server/integration/infinispan/src/test/java/org/jboss/as/clustering/infinispan/subsystem/OperationSequencesTestCase.java
  server/integration/jgroups/pom.xml
  server/integration/jgroups/src/test/java/org/infinispan/server/jgroups/subsystem/OperationSequencesTestCase.java
  server/integration/versions/pom.xml
  server/router/pom.xml
Labels: Urgent!

#6888 [9.4] ISPN-10164 Ensure that all tests are running with the correct JVM ver…
  build-configuration/pom.xml
  commons-test/src/main/java/org/infinispan/commons/test/EnvironmentCheck.java
  commons-test/src/main/java/org/infinispan/commons/test/JUnitTestListener.java
  commons-test/src/main/java/org/infinispan/commons/test/TestNGSuiteChecksTest.java
  commons/pom.xml
  hibernate/cache-v51/pom.xml
  hibernate/cache-v53/pom.xml
  integrationtests/all-embedded-it/pom.xml
  integrationtests/all-embedded-query-it/pom.xml
  integrationtests/spring-boot-it/pom.xml
  lucene/directory-provider/pom.xml
  object-filter/pom.xml
  pom.xml
  query-dsl/pom.xml
  remote-query/remote-query-client/pom.xml
  server/integration/commons/pom.xml
  server/integration/endpoint/pom.xml
  server/integration/infinispan/pom.xml
  server/integration/infinispan/src/test/java/org/jboss/as/clustering/infinispan/subsystem/OperationSequencesTestCase.java
  server/integration/jgroups/pom.xml
  server/integration/jgroups/src/test/java/org/infinispan/server/jgroups/subsystem/OperationSequencesTestCase.java
  server/integration/versions/pom.xml
  server/router/pom.xml
Labels: Backport, Urgent!

#6883 [9.4.x] ISPN-10132 removing endpoint extensions module from downstream
  documentation/pom.xml
  documentation/src/main/asciidoc/topics/attributes/product-attributes.adoc
  documentation/src/main/asciidoc/topics/configuration/wfly_extensions.adoc
  documentation/src/main/asciidoc/user_guide/integrations.adoc
Labels: Backport, Documentation

#6903 ISPN-10175 Long test killer doesn't kill the JVM on Windows
  build.bat
  commons-test/src/main/java/org/infinispan/commons/test/RunningTestsRegistry.java
Labels: Test fix

#6904 [9.4] ISPN-10175 Long test killer doesn't kill the JVM on Windows
  build.bat
  commons-test/src/main/java/org/infinispan/commons/test/RunningTestsRegistry.java
Labels: Backport, Test fix

#6913 ISPN-10086 AllClusterExecutorTest.testExecutorTriConsumerTimeoutExcep…
  core/src/test/java/org/infinispan/manager/AllClusterExecutorTest.java
Labels: Test fix

#6919 ISPN-10197 SoftIndexFileStoreStressTest is broken
  persistence/soft-index/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreStressTest.java
Labels: Test fix, Trivial :-)

#6914 ISPN-10194 Store Migrator tests should pass when segmentation is disa…
  tools/src/test/java/org/infinispan/tools/store/migrator/AbstractReaderTest.java
Labels: Test fix

#6916 [9.4] ISPN-10196 Fixing java.lang.IllegalStateException: EntityManager is closed
  persistence/jpa/src/test/java/org/infinispan/persistence/jpa/BaseJpaStoreTest.java
Labels: Backport, Changes Required

#6827 [9.4] ISPN-9748 Default transport for the test suite should be same
  core/src/test/java/org/infinispan/functional/distribution/rehash/FunctionalTxTest.java
  core/src/test/java/org/infinispan/test/fwk/JGroupsConfigBuilder.java
  integrationtests/osgi/pom.xml
  integrationtests/wildfly-modules/pom.xml
  pom.xml
  server/integration/testsuite/README.txt
  server/integration/testsuite/pom.xml
Labels: Backport

#6861 [9.4] ISPN-10108 - Query Project - Store the test results using TestNG
  Jenkinsfile
  query/pom.xml
Labels: Backport

#6872 [9.4] ISPN-10155 Fix server counter manager configuration
  integrationtests/wildfly-modules/src/test/resources/as-config/standalone/configuration/standalone-test.xml
  server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheContainerAddHandler.java
  server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheContainerConfigurationBuilder.java
  server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheContainerCountersResource.java
  server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CounterManagerConfigurationBuilder.java
  server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CountersMetricsHandler.java
  server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/EmbeddedCacheManagerConfigurationService.java
  server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/InfinispanSubsystemXMLReader.java
  server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/InfinispanSubsystemXMLWriter.java
  server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/ModelKeys.java
  server/integration/infinispan/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/subsystem-infinispan_9_2.xml
  server/integration/infinispan/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/subsystem-infinispan_9_3.xml
  server/integration/infinispan/src/test/resources/org/jboss/as/clustering/infinispan/subsystem/subsystem-infinispan_9_4.xml
Labels: Backport, On Hold

#6873 [9.4.x] ISPN-10157 Counter client does not use CH to locate a counter
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/impl/BaseCounter.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/impl/CounterOperationFactory.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/impl/NotificationManager.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/impl/RemoteCounterManager.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/impl/StrongCounterImpl.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/impl/WeakCounterImpl.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/operation/AddListenerOperation.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/operation/AddOperation.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/operation/BaseCounterOperation.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/operation/CompareAndSwapOperation.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/operation/DefineCounterOperation.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/operation/GetConfigurationOperation.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/operation/GetCounterNamesOperation.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/operation/GetValueOperation.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/operation/IsDefinedOperation.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/operation/RemoveListenerOperation.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/operation/RemoveOperation.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/counter/operation/ResetOperation.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/counter/StrongCounterHitsAwareTest.java
Labels: Backport, On Hold

#6800 [9.4.x] ISPN-10074 DefaultDataContainer executeTask() should ignore maxIdle
  core/src/main/java/org/infinispan/container/impl/DefaultDataContainer.java
  core/src/main/java/org/infinispan/expiration/impl/ClusterExpirationManager.java
  core/src/test/java/org/infinispan/expiration/impl/ExpirationFunctionalTest.java
  core/src/test/java/org/infinispan/expiration/impl/ExpirationListenerFunctionalTest.java
  core/src/test/java/org/infinispan/expiration/impl/ExpirationSingleFileStoreDistListenerFunctionalTest.java
  core/src/test/java/org/infinispan/expiration/impl/ExpirationSingleFileStoreListenerFunctionalTest.java
  core/src/test/java/org/infinispan/expiration/impl/ExpirationStoreFunctionalTest.java
  core/src/test/java/org/infinispan/expiration/impl/ExpirationStoreListenerFunctionalTest.java
Labels: Backport, On Hold

#6912 [9.4] ISPN-9195 Reap Server Iterators
  commons/src/main/java/org/infinispan/commons/time/TimeServiceTicker.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/CacheRequestProcessor.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodServer.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/iteration/DefaultIterationManager.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/iteration/IterationManager.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/iteration/IterationReaper.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/iteration/IterationState.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/logging/Log.java
  server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodIteratorReapTest.java
  server/hotrod/src/test/java/org/infinispan/server/hotrod/test/HotRodClient.java
  server/hotrod/src/test/java/org/infinispan/server/hotrod/test/TestIteratorNextResponse.java
  server/hotrod/src/test/java/org/infinispan/server/hotrod/test/TestIteratorStartResponse.java
Labels: Backport, On Hold

#6915 ISPN-10194 Store Migrator tests should pass when segmentation is disa…
  tools/src/test/java/org/infinispan/tools/store/migrator/AbstractReaderTest.java
Labels: Backport, On Hold, Test fix

#6920 [9.4] ISPN-10164 Ensure that all tests are running with the correct JVM version
  integrationtests/wildfly-modules/pom.xml
  jcache/tck-runner/pom.xml
  server/integration/testsuite/pom.xml
Labels: Backport

#6921 ISPN-10171 Reuse SpringCache instances
  spring/spring5/spring5-embedded/src/main/java/org/infinispan/spring/embedded/provider/SpringEmbeddedCacheManager.java
  spring/spring5/spring5-embedded/src/test/java/org/infinispan/spring/embedded/provider/SpringEmbeddedCacheManagerTest.java
  spring/spring5/spring5-remote/src/main/java/org/infinispan/spring/remote/provider/SpringRemoteCacheManager.java
  spring/spring5/spring5-remote/src/test/java/org/infinispan/spring/remote/provider/SpringRemoteCacheManagerTest.java
Labels: Backport, On Hold

#6927 [9.4.x] ISPN-9457 ISPN-10180 Async Cross-Site Features
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/xsite/AbstractHotRodSiteFailoverTest.java
  core/src/main/java/org/infinispan/remoting/rpc/RpcManagerImpl.java
  core/src/main/java/org/infinispan/remoting/transport/AggregateBackupResponse.java
  core/src/main/java/org/infinispan/remoting/transport/BackupResponse.java
  core/src/main/java/org/infinispan/remoting/transport/XSiteAsyncAckListener.java
  core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsBackupResponse.java
  core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
  core/src/main/java/org/infinispan/xsite/BackupSenderImpl.java
  core/src/main/java/org/infinispan/xsite/OfflineStatus.java
  core/src/test/java/org/infinispan/jmx/RpcManagerMBeanTest.java
  core/src/test/java/org/infinispan/remoting/transport/jgroups/JGroupsBackupResponseUnitTest.java
  core/src/test/java/org/infinispan/xsite/AbstractXSiteTest.java
  core/src/test/java/org/infinispan/xsite/offline/AsyncOfflineTest.java
  core/src/test/java/org/infinispan/xsite/offline/DelegatingTransport.java
  documentation/src/main/asciidoc/user_guide/cross_site_replication.adoc
  server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheMetricsHandler.java
  server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/MetricKeys.java
  server/integration/infinispan/src/main/resources/org/jboss/as/clustering/infinispan/subsystem/LocalDescriptions.properties
Labels: Backport, On Hold

#6933 [9.4] ISPN-10114 Server managed transactional cache configuration cannot be…
  feature-pack/server/src/main/resources/modules/org/infinispan/extension/slot/module.xml
  server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/TransactionManagerProvider.java
  server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheConfigurationAdd.java
  server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheConfigurationService.java
Labels: Backport, On Hold

#6936 [9.4] ISPN-10205 Clustered Locks documentation should use EmbeddedClusteredLockManagerFactory
  documentation/src/main/asciidoc/user_guide/clustered_lock.adoc
  lock/src/main/java/org/infinispan/lock/impl/manager/EmbeddedClusteredLockManager.java
Labels: Backport

#6841 ISPN-10205 Clustered Locks documentation should use EmbeddedClusteredLockManagerFactory
  documentation/src/main/asciidoc/user_guide/clustered_lock.adoc
  lock/src/main/java/org/infinispan/lock/impl/manager/EmbeddedClusteredLockManager.java
Labels: Changes Required

#6809 [9.4.x] ISPN-10068 AllClusterExecutorTest.testExecutorTriConsumerTimeoutExcep…
  core/src/test/java/org/infinispan/distribution/rehash/NonTxBackupOwnerBecomingPrimaryOwnerTest.java
  core/src/test/java/org/infinispan/distribution/rehash/NonTxPrimaryOwnerBecomingNonOwnerTest.java
  core/src/test/java/org/infinispan/manager/AllClusterExecutorTest.java
  core/src/test/java/org/infinispan/partitionhandling/StreamDistPartitionHandlingTest.java
  core/src/test/java/org/infinispan/stream/DistributedStreamRehashTest.java
  core/src/test/java/org/infinispan/test/Mocks.java
  core/src/test/java/org/infinispan/test/fwk/CheckPoint.java
Labels: Backport, On Hold

#6945 [9.4] ISPN-10148 - Improve reported testName
  commons-test/src/main/java/org/infinispan/commons/test/PolarionJUnitXMLReporter.java
Labels: Backport

#6824 [9.4] ISPN-10103 Allow JpaStore batch deletes with EAP 6
  persistence/jpa/src/main/java/org/infinispan/persistence/jpa/JpaStore.java
Labels: Backport

#6949 [9.4] ISPN-10066 (addendum) ClusteredStatsFailureTest now uses awaitStrict
  core/src/test/java/org/infinispan/stats/ClusteredStatsFailureTest.java
Labels: Urgent!

#6959 [9.4] ISPN-10208 Don't disable surefire xml report generation for junit tes…
  commons/pom.xml
  integrationtests/all-embedded-it/pom.xml
  integrationtests/all-embedded-query-it/pom.xml
  integrationtests/spring-boot-it/pom.xml
  jcache/tck-runner/pom.xml
  lucene/directory-provider/pom.xml
  object-filter/pom.xml
  query-dsl/pom.xml
  remote-query/remote-query-client/pom.xml
  server/integration/commons/pom.xml
  server/integration/endpoint/pom.xml
  server/integration/infinispan/pom.xml
  server/integration/jgroups/pom.xml
  server/integration/testsuite/pom.xml
  server/router/pom.xml
Labels: Backport

#6820 [9.4] ISPN-10095 Shared stores should throw exception when cache is local
  core/src/main/java/org/infinispan/configuration/cache/AbstractStoreConfigurationBuilder.java
  core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java
  core/src/main/java/org/infinispan/util/logging/Log.java
  core/src/test/java/org/infinispan/persistence/LocalConditionalCommandTest.java
  core/src/test/java/org/infinispan/persistence/StoreConfigurationValidationTest.java
  persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/configuration/XmlFileParsingTest.java
  persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/stores/TxStoreTest.java
Labels: Backport

#6941 [9.4] ISPN-10206 Cache fails to stop due to unreleased persistence manager …
  core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java
  core/src/main/java/org/infinispan/stream/impl/local/LocalCacheStream.java
  core/src/main/java/org/infinispan/stream/impl/local/LocalDoubleCacheStream.java
  core/src/main/java/org/infinispan/stream/impl/local/LocalIntCacheStream.java
  core/src/main/java/org/infinispan/stream/impl/local/LocalLongCacheStream.java
  core/src/main/java/org/infinispan/stream/impl/local/PersistenceEntryStreamSupplier.java
  core/src/main/java/org/infinispan/stream/impl/local/PersistenceKeyStreamSupplier.java
  core/src/test/java/org/infinispan/persistence/PersistenceManagerTest.java
Labels: Backport, On Hold

#6942 [9.4] ISPN-10214 Remove non-existing properties in spring4 module
  spring/spring4/pom.xml
Labels: Backport

#6964 ISPN-10226 DeployedCacheStoreMetadataTest fixes
  server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/cs/factory/DeployedCacheStoreMetadata.java
  server/integration/infinispan/src/test/java/org/jboss/as/clustering/infinispan/cs/factory/DeployedCacheStoreMetadataTest.java
Labels: Test fix

#6965 [9.4] ISPN-10226 DeployedCacheStoreMetadataTest fixes
  server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/cs/factory/DeployedCacheStoreMetadata.java
  server/integration/infinispan/src/test/java/org/jboss/as/clustering/infinispan/cs/factory/DeployedCacheStoreMetadataTest.java
Labels: Backport, Test fix

#6976 ISPN-10086 AllClusterExecutorTest.testExecutorTriConsumerTimeoutExcep…
  core/src/test/java/org/infinispan/manager/AllClusterExecutorTest.java
Labels: Backport, Test fix

#6967 [9.4] ISPN-10229 Name of server licenses file should be licenses.xml
  distribution/package.xml
Labels: Backport

#6988 ISPN-8070 Remove deprecate flags, deprecate unused flags
  core/src/main/java/org/infinispan/context/Flag.java
  core/src/main/java/org/infinispan/context/impl/FlagBitSets.java
Labels: Trivial :-)

#6989 ISPN-8774 Drop delegating implementations in org.infinispan
  core/src/main/java/org/infinispan/AbstractDelegatingAdvancedCache.java
  core/src/main/java/org/infinispan/AbstractDelegatingCache.java
  core/src/main/java/org/infinispan/manager/AbstractDelegatingEmbeddedCacheManager.java
  hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/util/ClassLoaderAwareCache.java
Labels: Trivial :-)

#6991 ISPN-10241 ListenerExceptionTest random failures in async test methods
  core/src/test/java/org/infinispan/notifications/cachelistener/ListenerExceptionTest.java
Labels: Test fix, Trivial :-)

#6992 ISPN-10241 ListenerExceptionTest random failures in async test methods
  core/src/test/java/org/infinispan/notifications/cachelistener/ListenerExceptionTest.java
Labels: Test fix, Trivial :-)

#6984 ISPN-10239 FineGrainedAtomicMap.clear() concurrency issues
  core/src/main/java/org/infinispan/atomic/impl/AtomicKeySetImpl.java
  core/src/main/java/org/infinispan/atomic/impl/FineGrainedAtomicMapProxyImpl.java
Labels: Test fix

#6990 ISPN-8788 Move SingleKeyNonTxInvocationContext
  core/src/main/java/org/infinispan/context/AbstractInvocationContextFactory.java
  core/src/main/java/org/infinispan/context/impl/NonTransactionalInvocationContextFactory.java
  core/src/main/java/org/infinispan/context/impl/SingleKeyNonTxInvocationContext.java
  core/src/main/java/org/infinispan/context/impl/TransactionalInvocationContextFactory.java
  core/src/main/java/org/infinispan/factories/EmptyConstructorNamedCacheFactory.java
  core/src/main/java/org/infinispan/interceptors/impl/EntryWrappingInterceptor.java
  core/src/main/java/org/infinispan/xsite/statetransfer/XSiteStateConsumerImpl.java
  core/src/test/java/org/infinispan/context/impl/SingleKeyNonTxInvocationContextTest.java
  core/src/test/java/org/infinispan/interceptors/impl/AsyncInterceptorChainInvocationTest.java
  core/src/test/java/org/infinispan/interceptors/impl/CacheMgmtInterceptorTest.java
  core/src/test/java/org/infinispan/tx/TransactionXaAdapterTmIntegrationTest.java
Labels: Trivial :-)

#6981 [9.4] ISPN-10229 Ignore returns from other nodes and return stats
  hibernate/cache-commons/src/main/java/org/infinispan/hibernate/cache/commons/access/UnorderedDistributionInterceptor.java
  hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/AbstractFunctionalTest.java
  hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/BulkOperationsTest.java
  hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/ConcurrentWriteTest.java
  hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/EntitiesAndCollectionsInSameRegionTest.java
  hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/EqualityTest.java
  hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/LocalCacheTest.java
  hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/NonTxQueryTest.java
  hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/ReadOnlyTest.java
  hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/ReadWriteTest.java
  hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/VersionedTest.java
  hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/cluster/EntityCollectionInvalidationTest.java
  hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/cluster/NaturalIdInvalidationTest.java
  hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/cluster/SessionRefreshTest.java
  hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/util/TestConfigurationHook.java
  hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/util/TestRegionFactory.java
Labels: Backport
