Repository infinispan/infinispan, pull requests merged in 2019-04, with the labels that each got.

#6816 ISPN-10040 Embedded and server thread pool defaults should be the same
  commons/src/main/java/org/infinispan/commons/executors/BlockingThreadPoolExecutorFactory.java
  core/src/main/java/org/infinispan/factories/KnownComponentNames.java
  server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/ThreadPoolResource.java
Labels: Trivial :-)

#6817 [9.4.x] ISPN-10040 Embedded and server thread pool defaults should be the same
  commons/src/main/java/org/infinispan/commons/executors/BlockingThreadPoolExecutorFactory.java
  core/src/main/java/org/infinispan/factories/KnownComponentNames.java
  server/integration/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/ThreadPoolResource.java
Labels: Backport, Trivial :-)

#6793 [9.4.x] ISPN-10079 Upgrade to jboss-modules 1.8.7.Final
  pom.xml
Labels: Backport

#6823 [9.4] Module fixes
  build-configuration/pom.xml
  feature-pack/build.xml
  feature-pack/wf-modules/pom.xml
  feature-pack/wf-modules/src/main/resources/modules/org/hibernate/commons-annotations/slot/module.xml
  feature-pack/wf-modules/src/main/resources/modules/org/hibernate/search/engine/hibernate-search-slot/module.xml
  feature-pack/wf-modules/src/main/resources/modules/system/layers/base/org/hibernate/search/engine/hibernate-slot/module.xml
  server/integration/feature-pack/build.xml
Labels: Backport

#6819 ISPN-10095 Shared stores should throw exception when cache is local
  core/src/main/java/org/infinispan/configuration/cache/AbstractStoreConfigurationBuilder.java
  core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java
  core/src/main/java/org/infinispan/util/logging/Log.java
  core/src/test/java/org/infinispan/persistence/LocalConditionalCommandTest.java
  core/src/test/java/org/infinispan/persistence/StoreConfigurationValidationTest.java
  persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/configuration/XmlFileParsingTest.java
  persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/stores/TxStoreTest.java
Labels: Trivial :-)

#6832 ISPN-10099 Use execution default-test instead of java8-test
  pom.xml
Labels: Test fix

#6833 ISPN-10099 Use execution default-test instead of java8-test
  pom.xml
Labels: Backport

#6850 [9.4] ISPN-10133 Update Windows scripts
  server/integration/feature-pack/src/main/resources/content/bin/standalone.bat
  server/integration/feature-pack/src/main/resources/content/bin/standalone.conf.bat
  server/integration/feature-pack/src/main/resources/content/bin/standalone.conf.ps1
  server/integration/feature-pack/src/main/resources/content/bin/standalone.ps1
Labels: Urgent!

#6863 [9.4.x] ISPN-10145 Command execution error should log cache name
  core/src/main/java/org/infinispan/interceptors/impl/InvocationContextInterceptor.java
  core/src/main/java/org/infinispan/util/logging/Log.java
Labels: Backport
