Repository infinispan/infinispan, pull requests merged in 2019-02, with the labels that each got.

#6651 ISPN-9801 Fix spurious startup warning
  core/src/main/java/org/infinispan/topology/ClusterTopologyManagerImpl.java
Labels: Trivial :-), Urgent!

#6650 ISPN-9801 Fix spurious startup warning
  core/src/main/java/org/infinispan/topology/ClusterTopologyManagerImpl.java
Labels: Trivial :-), Urgent!

#6660 Fix trace log format
  core/src/main/java/org/infinispan/persistence/util/PersistenceManagerCloseableSupplier.java
Labels: Trivial :-)

#6662 ISPN-9921 Simple warning instead of error with zero capacity node
  lock/src/main/java/org/infinispan/lock/impl/ClusteredLockModuleLifecycle.java
  lock/src/main/java/org/infinispan/lock/logging/Log.java
  lock/src/test/java/org/infinispan/lock/ClusteredLockWithZeroCapacityIncorrectConfigTest.java
Labels: Trivial :-)

#6669 Should support the nextVersion feature in release
  Jenkinsfile-release
Labels: Trivial :-)

#6670 [9.4] Should support the nextVersion feature in release
  Jenkinsfile-release
Labels: Backport

#6642 [9.4.x] JDBC Flowable fixes
  persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/stringbased/JdbcStringBasedStore.java
Labels: Backport

#6668 ISPN-9953 Fix jaxb-runtime version property
  pom.xml
Labels: Backport

#6677 ISPN-9965 Fix HotRodRemoteCache#IT.testDataConversionsWithDefaultRemo…
  server/core/src/test/java/org/infinispan/server/core/dataconversion/XMLTranscoderTest.java
  server/integration/testsuite/src/test/java/org/infinispan/server/test/client/hotrod/AbstractRemoteCacheIT.java
  server/rest/src/test/java/org/infinispan/rest/RestOperationsTest.java
Labels: Test fix

#6665 ISPN-9939 brandname variable is not replaced in code blocks
  documentation/src/main/asciidoc/user_guide/cli.adoc
  documentation/src/main/asciidoc/user_guide/integrations.adoc
  documentation/src/main/asciidoc/user_guide/integrations_hibernate_cache.adoc
  documentation/src/main/asciidoc/user_guide/server_protocols_hotrod.adoc
  documentation/src/main/asciidoc/user_guide/server_protocols_rest.adoc
  documentation/src/main/asciidoc/user_guide/streams.adoc
Labels: Needs Rebase

#6663 [9.4] ISPN-9921 Simple warning instead of error with zero capacity node
  lock/src/main/java/org/infinispan/lock/impl/ClusteredLockModuleLifecycle.java
  lock/src/main/java/org/infinispan/lock/logging/Log.java
  lock/src/test/java/org/infinispan/lock/ClusteredLockWithZeroCapacityIncorrectConfigTest.java
Labels: Backport, On Hold

#6683 ISPN-9969 Configure statistics with the hotrod-client.properties
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationBuilder.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/StatisticsConfigurationBuilder.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/package-info.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/ConfigurationProperties.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/configuration/ConfigurationTest.java
Labels: Trivial :-)

#6684 [9.4] ISPN-9969 Configure statistics with the hotrod-client.properties
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationBuilder.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/StatisticsConfigurationBuilder.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/package-info.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/ConfigurationProperties.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/configuration/ConfigurationTest.java
Labels: Backport

#6688 ISPN-9971 Use the JDK ALPN support when Java > 9
  server/core/src/main/java/org/infinispan/server/core/utils/SecurityActions.java
  server/core/src/main/java/org/infinispan/server/core/utils/SslUtils.java
Labels: Test fix, Trivial :-)

#6689 ISPN-9971 Use the JDK ALPN support when Java > 9
  server/core/src/main/java/org/infinispan/server/core/utils/SecurityActions.java
  server/core/src/main/java/org/infinispan/server/core/utils/SslUtils.java
Labels: Backport, Test fix, Trivial :-)

#6694 ISPN-9975 Upgrade to asciidoctorj 1.6.2
  documentation/pom.xml
Labels: Trivial :-), Urgent!

#6693 [9.4] ISPN-9975 Upgrade to asciidoctorj 1.6.2
  documentation/pom.xml
Labels: Trivial :-), Urgent!

#6697 ISPN-9980 Upgrades spring dependencies
  build-configuration/pom.xml
Labels: Trivial :-)

#6702 ISPN-9985 JGroups 4.0.18
  build-configuration/pom.xml
Labels: Urgent!

#6701 [9.4] ISPN-9985 JGroups 4.0.18
  build-configuration/pom.xml
Labels: Backport, Urgent!

#6719 ISPN-10003 Default value is CONSISTENT
  lock/src/main/resources/schema/infinispan-clustered-locks-config-10.0.xsd
  lock/src/main/resources/schema/infinispan-clustered-locks-config-9.4.xsd
Labels: Trivial :-)

#6720 ISPN-10003 default value is CONSISTENT
  lock/src/main/resources/schema/infinispan-clustered-locks-config-9.4.xsd
Labels: Backport

#6722 [9.4] ISPN-9999 Update init.d scripts and brand them
  server/integration/build/build.xml
  server/integration/build/pom.xml
  server/integration/feature-pack/src/main/resources/content/bin/init.d/infinispan-server-lsb.sh
  server/integration/feature-pack/src/main/resources/content/bin/init.d/infinispan-server.conf
  server/integration/feature-pack/src/main/resources/content/bin/init.d/infinispan-server.sh
  server/integration/feature-pack/src/main/resources/content/bin/init.d/jboss-eap-rhel.sh
  server/integration/feature-pack/src/main/resources/content/bin/init.d/jboss-eap.conf
Labels: Backport

#6717 [9.4] ISPN-9998 Fix server CLI with Java 11
  server/integration/build/trim-delete.txt
  server/integration/feature-pack/src/main/resources/content/bin/ispn-cli-logging.properties
  server/integration/feature-pack/src/main/resources/content/bin/ispn-cli.bat
  server/integration/feature-pack/src/main/resources/content/bin/ispn-cli.sh
Labels: Backport

#6728 ISPN-10008 ScriptingTest.testNonSupportedScript fix
  tasks/scripting/src/test/java/org/infinispan/scripting/ScriptingTest.java
Labels: Backport, Test fix, Trivial :-)

#6727 ISPN-10008 ScriptingTest.testNonSupportedScript fix
  tasks/scripting/src/test/java/org/infinispan/scripting/ScriptingTest.java
Labels: Test fix, Trivial :-)
