Repository infinispan/infinispan, pull requests merged in 2019-08, with the labels that each got.

#7177 ISPN-10454 RemoteStore loaded entry has incorrect key
  persistence/remote/src/main/java/org/infinispan/persistence/remote/RemoteStore.java
Labels: Trivial :-)

#7178 ISPN-10455 XSLT server generation for example xml files doesn't work …
  server/integration/testsuite/src/test/resources/config/xslt/examples-modifier.xsl
Labels: Trivial :-)

#7179 ISPN-10425 Update Netty and RxJava2 to align with Quarkus dependencies
  build-configuration/pom.xml
Labels: Trivial :-)

#7146 [9.4.x] ISPN-10266 SpringCache clear when cache is removed
  spring/spring5/spring5-remote/src/main/java/org/infinispan/spring/remote/provider/SpringRemoteCacheManager.java
  spring/spring5/spring5-remote/src/test/java/org/infinispan/spring/remote/provider/SpringRemoteCacheManagerTest.java
Labels: Backport

#6773 ISPN-9422 Remove Worker Threads property
  documentation/src/main/asciidoc/topics/upgrading.adoc
  server/core/src/main/java/org/infinispan/server/core/AbstractProtocolServer.java
  server/core/src/main/java/org/infinispan/server/core/configuration/ProtocolServerConfiguration.java
  server/core/src/test/java/org/infinispan/server/core/AbstractProtocolServerTest.java
  server/core/src/test/java/org/infinispan/server/core/configuration/MockServerConfiguration.java
  server/core/src/test/java/org/infinispan/server/core/configuration/MockServerConfigurationBuilder.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodServer.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/configuration/HotRodServerConfiguration.java
  server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/EndpointSubsystemReader.java
  server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/EndpointSubsystemWriter.java
  server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/HotRodConnectorResource.java
  server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/HotRodSubsystemAdd.java
  server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/MemcachedConnectorResource.java
  server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/ProtocolServerConnectorResource.java
  server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/ProtocolServiceSubsystemAdd.java
  server/integration/endpoint/src/main/resources/org/infinispan/server/endpoint/subsystem/LocalDescriptions.properties
  server/integration/endpoint/src/test/java/org/infinispan/server/endpoint/EndpointSubsystemTestCase.java
  server/memcached/src/main/java/org/infinispan/server/memcached/MemcachedServer.java
  server/memcached/src/main/java/org/infinispan/server/memcached/configuration/MemcachedServerConfiguration.java
  server/rest/src/main/java/org/infinispan/rest/RestServer.java
  server/rest/src/main/java/org/infinispan/rest/configuration/RestServerConfiguration.java
  server/router/src/main/java/org/infinispan/server/router/configuration/SinglePortRouterConfiguration.java
  server/router/src/main/java/org/infinispan/server/router/configuration/builder/SinglePortRouterBuilder.java
  server/router/src/main/java/org/infinispan/server/router/router/impl/singleport/SinglePortEndpointRouter.java
Labels: Needs Rebase

#7089 [9.4] ISPN-10348 Migrate JDBC String based Cache Store from jdg-functional tests to upstream
  persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/PooledConnectionFactoryTest.java
  persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/stringbased/AbstractStringBasedCacheStore.java
  persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/stringbased/JdbcStringBasedStoreTest.java
  persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/stringbased/StringStoreWithManagedConnectionFunctionalTest.java
  persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/stringbased/StringStoreWithManagedConnectionTest.java
  persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/stringbased/StringStoreWithPooledConnectionFunctionalTest.java
Labels: Changes Required

#7180 ISPN-10432 Upgrade Protostream to 4.3.0.Alpha9
  build-configuration/bom/pom.xml
  build-configuration/pom.xml
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/marshall/ProtoStreamMarshallerWithAnnotationsTest.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/RemoteQueryWithProtostreamAnnotationsTest.java
  commons/src/main/java/org/infinispan/commons/dataconversion/MediaType.java
  core/src/main/java/org/infinispan/container/versioning/NumericVersion.java
  core/src/main/java/org/infinispan/functional/impl/MetaParamsInternalMetadata.java
  core/src/main/java/org/infinispan/marshall/persistence/impl/MarshalledValueImpl.java
  core/src/main/java/org/infinispan/metadata/EmbeddedMetadata.java
  counter/src/main/java/org/infinispan/counter/impl/strong/StrongCounterKey.java
  counter/src/main/java/org/infinispan/counter/impl/weak/WeakCounterKey.java
  integrationtests/endpoints-interop-it/src/test/java/org/infinispan/it/endpoints/CryptoCurrency.java
  lucene/lucene-directory/src/main/java/org/infinispan/lucene/ChunkCacheKey.java
  lucene/lucene-directory/src/main/java/org/infinispan/lucene/FileCacheKey.java
  lucene/lucene-directory/src/main/java/org/infinispan/lucene/impl/FileListCacheValue.java
  lucene/lucene-directory/src/test/java/org/infinispan/lucene/Key2StringMapperTest.java
  object-filter/src/main/java/org/infinispan/objectfilter/impl/predicateindex/ProtobufMatcherEvalContext.java
  pom.xml
  remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/IndexingMetadata.java
  server/integration/event-logger/src/main/java/org/infinispan/server/eventlogger/ServerEventImpl.java
  server/integration/testsuite/src/test/java/org/infinispan/server/test/query/RemoteQueryWithProtostreamAnnotationsIT.java
  server/integration/testsuite/src/test/java/org/infinispan/server/test/query/Transaction.java
  server/runtime/src/test/java/org/infinispan/server/functional/HotRodCacheQueries.java
  tasks/scripting/src/main/java/org/infinispan/scripting/impl/ScriptMetadata.java
Labels: Changes Required, Urgent!

#7170 [9.4] ISPN-10423 Fix RocksDB ReadOptions memory leak
  persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/RocksDBStore.java
Labels: Backport, On Hold

#7188 ISPN-10465 Improve jgroups stack-file configuration exceptions
  core/src/main/java/org/infinispan/configuration/parsing/Parser.java
  core/src/main/java/org/infinispan/util/logging/Log.java
Labels: Trivial :-)

#7194 [94x] ISPN-10403 Fix generics in query results, fix asserts in query tests
  query/src/test/java/org/infinispan/query/queries/phrases/EmbeddedQueryTest.java
  query/src/test/java/org/infinispan/query/queries/phrases/QueryPhrasesTest.java
  query/src/test/java/org/infinispan/query/test/Author.java
  query/src/test/java/org/infinispan/query/test/Book.java
Labels: Backport

#7198 ISPN-10474 Align logging versions with Quarkus
  build-configuration/pom.xml
Labels: Trivial :-)

#7199 ISPN-10475 Update jgroups to a version that supports Quarkus
  build-configuration/pom.xml
Labels: Trivial :-)

#7187 [9.4.x] ISPN-10463 Server uses disabled features
  commons/src/main/java/org/infinispan/commons/util/Features.java
Labels: Backport

#7208 ISPN-10465 NonExistingJGroupsConfigTest NPE fix
  core/src/test/java/org/infinispan/remoting/jgroups/NonExistingJGroupsConfigTest.java
Labels: Trivial :-)

#7210 ISPN-10490 Remove RemoveCacheCommand
  core/src/main/java/org/infinispan/commands/RemoteCommandsFactory.java
  core/src/main/java/org/infinispan/commands/RemoveCacheCommand.java
  core/src/main/java/org/infinispan/marshall/exts/CacheRpcCommandExternalizer.java
Labels: Trivial :-)

#7211 ISPN-10491 Deprecate Listenable.getListeners
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCache.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheImpl.java
  core/src/main/java/org/infinispan/cache/impl/AbstractDelegatingCache.java
  core/src/main/java/org/infinispan/cache/impl/CacheImpl.java
  core/src/main/java/org/infinispan/cache/impl/SimpleCacheImpl.java
  core/src/main/java/org/infinispan/manager/DefaultCacheManager.java
  core/src/main/java/org/infinispan/manager/impl/AbstractDelegatingEmbeddedCacheManager.java
  core/src/main/java/org/infinispan/notifications/Listenable.java
  core/src/main/java/org/infinispan/security/impl/SecureCacheImpl.java
  core/src/test/java/org/infinispan/functional/decorators/FunctionalAdvancedCache.java
  jcache/remote/src/main/java/org/infinispan/jcache/remote/RemoteCacheWrapper.java
Labels: Trivial :-)

#7216 ISPN-10498 Rest Body Content contains junk with HeapByteBuf
  server/rest/src/main/java/org/infinispan/rest/ByteBufContentSource.java
Labels: Trivial :-)

#7218 ISPN-10501 Various fixes for Quarkus compatibility in Server
  commons/src/main/java/org/infinispan/commons/dataconversion/StandardConversions.java
  server/core/src/main/java/org/infinispan/server/core/admin/AdminServerTask.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodServer.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/configuration/HotRodServerConfigurationBuilder.java
Labels: Trivial :-)

#7220 ISPN-10501 Various fixes for Quarkus compatibility in Server
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/EPollAvailable.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/TransportHelper.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/impl/transport/netty/EpollAvailabilityTest.java
  server/core/src/main/java/org/infinispan/server/core/transport/EPollAvailable.java
  server/core/src/main/java/org/infinispan/server/core/transport/NettyTransport.java
Labels: Changes Required

#7224 [9.4.x] ISPN-10472 ArrayIndexOutOfBoundsException in BoundedOffHeapDataContai…
  core/src/main/java/org/infinispan/container/offheap/BoundedOffHeapDataContainer.java
  core/src/test/java/org/infinispan/container/offheap/OffHeapBoundedMultiNodeTest.java
  core/src/test/java/org/infinispan/container/offheap/OffHeapMultiNodeTest.java
Labels: Urgent!

#7242 [9.4.x] ISPN-10534 SerializationContext ProtoStreamMarshaller.getSerializatio…
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/marshall/ProtoStreamMarshaller.java
  server/integration/testsuite/src/test/java/org/infinispan/server/test/client/hotrod/HotRodCustomMarshallerIteratorIT.java
Labels: Backport
