Repository infinispan/infinispan, pull requests merged in 2020-01, with the labels that each got.

#7715 [9.4.x] Fix checkstyle error
  core/src/main/java/org/infinispan/expiration/impl/ClusterExpirationManager.java
Labels: Trivial :-), Urgent!

#7712 ISPN-11116 Invalidation commands should not load the previous value
  core/src/main/java/org/infinispan/commands/write/InvalidateCommand.java
  core/src/main/java/org/infinispan/interceptors/impl/CacheLoaderInterceptor.java
  core/src/test/java/org/infinispan/invalidation/WriteStoreInvalidationTest.java
Labels: Urgent!

#7714 [9.3.x] ISPN-11116 Invalidation commands should not load the previous value
  core/src/main/java/org/infinispan/commands/write/InvalidateCommand.java
  core/src/main/java/org/infinispan/interceptors/impl/CacheLoaderInterceptor.java
  core/src/test/java/org/infinispan/invalidation/WriteStoreInvalidationTest.java
Labels: Backport

#7713 [9.4.x] ISPN-11116 Invalidation commands should not load the previous value
  core/src/main/java/org/infinispan/commands/write/InvalidateCommand.java
  core/src/main/java/org/infinispan/interceptors/impl/CacheLoaderInterceptor.java
  core/src/test/java/org/infinispan/invalidation/WriteStoreInvalidationTest.java
Labels: Backport, Urgent!

#7724 ISPN-11136 use imagesdir attribute in docs
  documentation/pom.xml
  documentation/src/main/asciidoc/titles/admin/admin.asciidoc
  documentation/src/main/asciidoc/titles/cli/cli.asciidoc
  documentation/src/main/asciidoc/titles/configuring/configuring.asciidoc
  documentation/src/main/asciidoc/titles/contributing/contributing.asciidoc
  documentation/src/main/asciidoc/titles/developing/developing.asciidoc
  documentation/src/main/asciidoc/titles/embedding/embedding.asciidoc
  documentation/src/main/asciidoc/titles/getting_started/getting_started.asciidoc
  documentation/src/main/asciidoc/titles/hotrod_java/hotrod_java.asciidoc
  documentation/src/main/asciidoc/titles/hotrod_protocol/hotrod_protocol.asciidoc
  documentation/src/main/asciidoc/titles/integrating/integrating.asciidoc
  documentation/src/main/asciidoc/titles/memcached/memcached.asciidoc
  documentation/src/main/asciidoc/titles/overview/overview.asciidoc
  documentation/src/main/asciidoc/titles/rest/rest.asciidoc
  documentation/src/main/asciidoc/titles/security/security.asciidoc
  documentation/src/main/asciidoc/titles/server/server.asciidoc
  documentation/src/main/asciidoc/titles/tuning/tuning.asciidoc
  documentation/src/main/asciidoc/titles/upgrading/upgrading.asciidoc
  documentation/src/main/asciidoc/titles/xsite/xsite.asciidoc
  documentation/src/main/asciidoc/topics/attributes/product-attributes.adoc
  documentation/src/main/asciidoc/topics/con_caches_distribution.adoc
  documentation/src/main/asciidoc/topics/con_caches_invalidation.adoc
  documentation/src/main/asciidoc/topics/con_caches_replicated.adoc
  documentation/src/main/asciidoc/topics/con_server_client_overview.adoc
  documentation/src/main/asciidoc/topics/con_server_using_client_mode.adoc
  documentation/src/main/asciidoc/topics/contributing/basics.adoc
  documentation/src/main/asciidoc/topics/contributing/source_control.adoc
  documentation/src/main/asciidoc/topics/cross_site_replication.adoc
  documentation/src/main/asciidoc/topics/gui_demo.adoc
  documentation/src/main/asciidoc/topics/ref_cache_modes_comparison.adoc
  documentation/src/main/asciidoc/topics/security.adoc
  documentation/src/main/asciidoc/topics/server_protocols_hotrod.adoc
  documentation/src/main/asciidoc/topics/transactions.adoc
Labels: Documentation, Trivial :-)

#7729 ISPN-10981 CacheWriterTest.shouldWriteThoughUsingPutAll_partialSucces…
  jcache/embedded/src/main/java/org/infinispan/jcache/embedded/JCache.java
Labels: Test fix

#7738 [9.4.x] ISPN-11159 QueryInterceptor uses the wrong logger
  query/src/main/java/org/infinispan/query/backend/QueryInterceptor.java
Labels: Backport, Trivial :-)

#7733 ISPN-10981 Fix JCache.removeAll regression
  jcache/embedded/src/main/java/org/infinispan/jcache/embedded/JCache.java
Labels: Test fix, Urgent!

#7735 ISPN-10369 InvalidatedNearCacheTest random failures
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/InvalidatedNearCacheTest.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/MockNearCacheService.java
  core/src/main/java/org/infinispan/notifications/cachelistener/CacheNotifierImpl.java
Labels: Test fix

#7745 ISPN 11166 SocketTimeoutFailureRetryTest random failures
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/retry/SocketTimeoutFailureRetryTest.java
Labels: Test fix, Trivial :-)

#7742 ISPN-11164 clustered max idle doc update
  documentation/src/main/asciidoc/topics/eviction.adoc
Labels: Documentation

#7749 [9.4.x] jdbc string based config examples
  documentation/src/main/asciidoc/user_guide/persistence_jdbc.adoc
Labels: Documentation

#7765 [10.1] ISPN-10310 Drop state transfer pool from the infinispan WF subsystem
  wildfly/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheContainerConfigurationBuilder.java
Labels: Test fix

#7771 ISPN-7744 ServerEventLoggerTest fails intermittently
  server/runtime/src/test/java/org/infinispan/server/test/Util.java
  server/runtime/src/test/java/org/infinispan/server/unit/configuration/ServerEventLoggerTest.java
Labels: Test fix

#7766 [9.4.x] ISPN-11196 capacity factor doc update
  documentation/src/main/asciidoc/user_guide/clustering.adoc
Labels: Documentation

#7780 [10.1.x] ISPN-11210 Classloading issues when using annotation generated marsha…
  build-configuration/pom.xml
Labels: Backport

#7791 HotRod client support transactions, changing the Protocol Comparison table
  documentation/src/main/asciidoc/topics/ref_endpoints_comparison.adoc
Labels: Documentation

#7781 [9.4.x] ISPN-11210 Classloading issues when using annotation generated marsha…
  build-configuration/pom.xml
Labels: Backport

#7783 ISPN-9784 Replace DistributedExecutor with ClusterExecutor for distri…
  server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodServer.java
  server/integration/infinispan/src/main/java/org/infinispan/server/infinispan/task/DistributedServerTask.java
  server/integration/infinispan/src/main/java/org/infinispan/server/infinispan/task/DistributedServerTaskRunner.java
  server/integration/infinispan/src/main/java/org/infinispan/server/infinispan/task/LocalServerTaskRunner.java
  server/integration/infinispan/src/main/java/org/infinispan/server/infinispan/task/SecurityActions.java
  tasks/scripting/src/main/java/org/infinispan/scripting/impl/DistributedRunner.java
  tasks/scripting/src/main/java/org/infinispan/scripting/impl/DistributedScript.java
Labels: Backport

#7798 ISPN-11242 HotRod server test client sends invalid iteration start request
  server/hotrod/src/test/java/org/infinispan/server/hotrod/test/HotRodClient.java
Labels: Trivial :-)

#7799 ISPN-11244 HotRodIteratorReapTest random failures
  server/hotrod/src/main/java/org/infinispan/server/hotrod/iteration/DefaultIterationManager.java
  server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodIteratorReapTest.java
Labels: Trivial :-)

#7790 [9.4.x] ISPN-10657 Handle async-xsite in parallel
  core/src/main/java/org/infinispan/remoting/LocalInvocation.java
  core/src/main/java/org/infinispan/remoting/inboundhandler/GlobalInboundInvocationHandler.java
  core/src/main/java/org/infinispan/util/concurrent/ActionSequencer.java
  core/src/main/java/org/infinispan/util/concurrent/CompletableFutures.java
  core/src/main/java/org/infinispan/xsite/BackupReceiver.java
  core/src/main/java/org/infinispan/xsite/BaseBackupReceiver.java
  core/src/main/java/org/infinispan/xsite/ClusteredCacheBackupReceiver.java
  core/src/main/java/org/infinispan/xsite/LocalCacheBackupReceiver.java
  core/src/main/java/org/infinispan/xsite/SingleXSiteRpcCommand.java
  core/src/main/java/org/infinispan/xsite/XSiteReplicateCommand.java
  core/src/main/java/org/infinispan/xsite/statetransfer/XSiteStatePushCommand.java
  core/src/main/java/org/infinispan/xsite/statetransfer/XSiteStateTransferControlCommand.java
  core/src/test/java/org/infinispan/jmx/PerCacheInboundHandlerMBeanTest.java
  core/src/test/java/org/infinispan/test/AbstractInfinispanTest.java
  core/src/test/java/org/infinispan/util/ActionSequencerUnitTest.java
  core/src/test/java/org/infinispan/xsite/BackupReceiverDelegator.java
  core/src/test/java/org/infinispan/xsite/RollbackNoPrepareOptimisticTest.java
  core/src/test/java/org/infinispan/xsite/statetransfer/BaseStateTransferTest.java
  core/src/test/java/org/infinispan/xsite/statetransfer/failures/RetryMechanismTest.java
  core/src/test/java/org/infinispan/xsite/statetransfer/failures/SiteConsumerTopologyChangeTest.java
Labels: Backport

#7805 ISPN-11253 Add task name to hotrod server log
  server/hotrod/src/main/resources/hotrod.gr
Labels: Trivial :-)

#7806 ISPN-11253 Add task name to hotrod access log
  server/hotrod/src/main/resources/hotrod.gr
Labels: Backport
