Repository infinispan/infinispan, pull requests merged in 2020-05, with the labels that each got.

#8269 ISPN-11607 Fix blocking LimitedExecutor#addPermit test failures
  core/src/main/java/org/infinispan/util/CoreBlockHoundIntegration.java
Labels: Test fix, Trivial :-)

#8246 [10.1.x] ISPN-10135 Performance Regression for HotRod-TX
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/OperationsFactory.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transaction/TransactionContext.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transaction/entry/Modification.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transaction/operations/PrepareTransactionOperation.java
Labels: Backport

#8272 ISPN-11761 Upgrade to 0.5.Final
  build-configuration/pom.xml
Labels: Trivial :-)

#8283 ISPN-11781 Log the JGroups stack name if one was provided
  core/src/main/java/org/infinispan/configuration/global/TransportConfiguration.java
  core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
  core/src/main/java/org/infinispan/util/logging/Log.java
Labels: Trivial :-)

#8279 ISPN-11773 Package org.infinispan.context is missing from javadocs of…
  core/src/main/java/org/infinispan/context/package-info.java
Labels: Trivial :-)

#8280 [10.1.x] ISPN-11773 Package org.infinispan.context is missing from javadocs of…
  core/src/main/java/org/infinispan/context/package-info.java
Labels: Backport, Trivial :-)

#8278 ISPN-11771 Change TCK Runner project name
  jcache/tck-runner-embedded/pom.xml
  jcache/tck-runner-remote/pom.xml
Labels: Trivial :-)

#8082 ISPN-11511 More consistent branding
  cli/cli-client/src/main/java/org/infinispan/cli/CLI.java
  commons/all/src/main/java/org/infinispan/commons/util/Version.java
  commons/all/src/main/resources/META-INF/infinispan-version.properties
  server/runtime/src/main/java/org/infinispan/server/Server.java
  server/runtime/src/main/java/org/infinispan/server/security/UserTool.java
  tools/src/main/java/org/infinispan/tools/store/migrator/StoreMigrator.java
Labels: Question

#8259 ISPN-11742 updating index page and integrations doc
  documentation/src/main/asciidoc/index.asciidoc
  documentation/src/main/asciidoc/stories/assembly_integrating.adoc
  documentation/src/main/asciidoc/titles/getting_started/getting_started.asciidoc
  documentation/src/main/asciidoc/titles/integrating/integrating.asciidoc
  documentation/src/main/asciidoc/titles/overview/overview.asciidoc
  documentation/src/main/asciidoc/topics/integrations_apache_lucene.adoc
  documentation/src/main/asciidoc/topics/integrations_hibernate_cache.adoc
  documentation/src/main/asciidoc/topics/integrations_hibernate_ogm.adoc
  documentation/src/main/asciidoc/topics/integrations_hibernate_search.adoc
  documentation/src/main/asciidoc/topics/integrations_spring.adoc
Labels: Documentation

#8293 ISPN-11805 Fix tests in Infinispan Anchored Keys
  anchored-keys/src/test/java/org/infinispan/anchored/ScaleUpWithoutStateTransferTest.java
  anchored-keys/src/test/resources/config/anchored.xml
Labels: Test fix, Trivial :-)

#8294 ISPN-11806 AsyncStoreWithoutEvictionFunctionalTest remove data from core
  core/src/test/java/org/infinispan/persistence/support/AsyncStoreWithoutEvictionFunctionalTest.java
Labels: Test fix, Trivial :-)

#8292 ISPN-11788 Remove preferContainerExposedPorts
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/AbstractInfinispanServerDriver.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerRemoteCacheManager.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/EmbeddedInfinispanServerDriver.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/TestSystemPropertyNames.java
Labels: Backport, On Hold

#8290 ISPN-11706 Use XidImpl internally
  commons/all/src/main/java/org/infinispan/commons/marshall/Ids.java
  commons/all/src/main/java/org/infinispan/commons/marshall/PersistenceContextInitializer.java
  commons/all/src/main/java/org/infinispan/commons/marshall/ProtoStreamTypeIds.java
  commons/all/src/main/java/org/infinispan/commons/tx/XidImpl.java
  core/src/main/java/org/infinispan/marshall/core/InternalExternalizers.java
  core/src/main/java/org/infinispan/marshall/persistence/impl/PersistenceContextInitializer.java
  core/src/main/java/org/infinispan/transaction/xa/recovery/InDoubtTxInfo.java
Labels: Trivial :-)

#8302 [10.1.x] ISPN-11667 Deal with ignore caches. Status Ignored
  server/rest/src/main/java/org/infinispan/rest/resources/CacheManagerResource.java
  server/rest/src/test/java/org/infinispan/rest/resources/AbstractRestResourceTest.java
  server/rest/src/test/java/org/infinispan/rest/resources/CacheManagerResourceTest.java
Labels: Backport

#8304 ISPN-11814 Hibernate Search annotations are not really neede…
  server/rest/src/test/java/org/infinispan/rest/search/entity/Gender.java
  server/rest/src/test/java/org/infinispan/rest/search/entity/Person.java
Labels: Trivial :-)

#8306 [10.1.x] ISPN-11785 server patching docs
  cli/cli-client/src/main/resources/help/patch.adoc
  documentation/src/main/asciidoc/stories/assembly_cli_command_reference.adoc
  documentation/src/main/asciidoc/stories/assembly_server_patching.adoc
  documentation/src/main/asciidoc/stories/assembly_server_quickstart.adoc
  documentation/src/main/asciidoc/stories/assembly_server_rolling_upgrades.adoc
  documentation/src/main/asciidoc/titles/server/stories.adoc
  documentation/src/main/asciidoc/titles/upgrading/stories.adoc
  documentation/src/main/asciidoc/topics/con_cache_authorization.adoc
  documentation/src/main/asciidoc/topics/proc_server_creating_patches.adoc
  documentation/src/main/asciidoc/topics/proc_server_downloading_patches.adoc
  documentation/src/main/asciidoc/topics/proc_server_installing_patches.adoc
  documentation/src/main/asciidoc/topics/proc_server_rolling_back_patches.adoc
  documentation/src/main/asciidoc/topics/ref_cache_authorization.adoc
  documentation/src/main/asciidoc/topics/ref_server_patches.adoc
Labels: Backport, Documentation

#8296 ISPN-11785 server patching docs
  cli/cli-client/src/main/resources/help/patch.adoc
  documentation/src/main/asciidoc/stories/assembly_cli_command_reference.adoc
  documentation/src/main/asciidoc/stories/assembly_server_patching.adoc
  documentation/src/main/asciidoc/stories/assembly_server_quickstart.adoc
  documentation/src/main/asciidoc/stories/assembly_server_rolling_upgrades.adoc
  documentation/src/main/asciidoc/titles/server/stories.adoc
  documentation/src/main/asciidoc/titles/upgrading/stories.adoc
  documentation/src/main/asciidoc/topics/con_cache_authorization.adoc
  documentation/src/main/asciidoc/topics/proc_disabling_server_authentication.adoc
  documentation/src/main/asciidoc/topics/proc_server_creating_patches.adoc
  documentation/src/main/asciidoc/topics/proc_server_downloading_patches.adoc
  documentation/src/main/asciidoc/topics/proc_server_installing_patches.adoc
  documentation/src/main/asciidoc/topics/proc_server_rolling_back_patches.adoc
  documentation/src/main/asciidoc/topics/ref_cache_authorization.adoc
  documentation/src/main/asciidoc/topics/ref_server_patches.adoc
Labels: Documentation

#8315 [10.1.x] add versioned operator and spring boot docs
  documentation/src/main/asciidoc/index.asciidoc
Labels: Documentation

#8321 ISPN-11829 Persistence configuration allows for preload and purgeOnSt…
  core/src/main/java/org/infinispan/configuration/cache/AbstractStoreConfigurationBuilder.java
  core/src/main/java/org/infinispan/util/logging/Log.java
  core/src/test/java/org/infinispan/configuration/ConfigurationUnitTest.java
  core/src/test/java/org/infinispan/configuration/XmlFileParsingTest.java
  core/src/test/resources/configs/named-cache-test.xml
  distribution/src/main/release/common/configs/config-samples/sample.xml
  query/src/test/java/org/infinispan/query/persistence/EntryActivatingTest.java
Labels: Trivial :-)

#8320 ISPN-11826 topic for deleting caches via CLI
  documentation/src/main/asciidoc/stories/assembly_cli_cache_operations.adoc
  documentation/src/main/asciidoc/topics/proc_cli_adding_entries.adoc
  documentation/src/main/asciidoc/topics/proc_cli_creating_caches_files.adoc
  documentation/src/main/asciidoc/topics/proc_cli_creating_caches_templates.adoc
  documentation/src/main/asciidoc/topics/proc_cli_deleting_entries.adoc
  documentation/src/main/asciidoc/topics/proc_cli_dropping_caches.adoc
  documentation/src/main/asciidoc/topics/proc_cli_resetting_dropping_counters.adoc
Labels: Documentation

#8336 ISPN-11840 HotRodMergeTest updated to use numOwners=2
  server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodMergeTest.java
Labels: Test fix

#8341 [10.1.x] ISPN-11826 topic for deleting caches via CLI
  documentation/src/main/asciidoc/stories/assembly_cli_cache_operations.adoc
  documentation/src/main/asciidoc/topics/proc_cli_adding_entries.adoc
  documentation/src/main/asciidoc/topics/proc_cli_creating_caches_files.adoc
  documentation/src/main/asciidoc/topics/proc_cli_creating_caches_templates.adoc
  documentation/src/main/asciidoc/topics/proc_cli_deleting_entries.adoc
  documentation/src/main/asciidoc/topics/proc_cli_dropping_caches.adoc
  documentation/src/main/asciidoc/topics/proc_cli_resetting_dropping_counters.adoc
Labels: Backport, Documentation

#8338 ISPN-11848 remote jcache dependency
  documentation/src/main/asciidoc/topics/dependencies_maven/jcache-remote.xml
  documentation/src/main/asciidoc/topics/jcache.adoc
Labels: Documentation

#8343 [10.1.x] ISPN-11848 remote jcache dependency
  documentation/src/main/asciidoc/topics/dependencies_maven/jcache-remote.xml
  documentation/src/main/asciidoc/topics/jcache.adoc
Labels: Backport, Documentation

#8243 ISPN-11626 Server report
  cli/cli-client/src/main/java/org/infinispan/cli/commands/Batch.java
  cli/cli-client/src/main/java/org/infinispan/cli/commands/Server.java
  cli/cli-client/src/main/java/org/infinispan/cli/connection/rest/RestConnection.java
  cli/cli-client/src/main/java/org/infinispan/cli/logging/Messages.java
  client/rest-client/src/main/java/org/infinispan/client/rest/RestServerClient.java
  client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestServerClientOkHttp.java
  commons/all/src/main/java/org/infinispan/commons/jdkspecific/ProcessInfo.java
  commons/all/src/main/java/org/infinispan/commons/util/OS.java
  commons/jdk11/src/main/java/org/infinispan/commons/jdkspecific/ProcessInfo.java
  documentation/src/main/asciidoc/stories/assembly_cli_starting.adoc
  documentation/src/main/asciidoc/stories/assembly_server_troubleshooting.adoc
  documentation/src/main/asciidoc/titles/server/stories.adoc
  documentation/src/main/asciidoc/topics/proc_cli_getting_server_reports.adoc
  documentation/src/main/asciidoc/topics/proc_cli_logging.adoc
  documentation/src/main/asciidoc/topics/ref_rest_servers.adoc
  server/core/src/main/java/org/infinispan/server/core/ServerManagement.java
  server/rest/src/main/java/org/infinispan/rest/resources/ServerResource.java
  server/runtime/src/main/java/org/infinispan/server/Bootstrap.java
  server/runtime/src/main/java/org/infinispan/server/Server.java
  server/runtime/src/main/java/org/infinispan/server/logging/Log.java
  server/runtime/src/main/server/bin/report.sh
Labels: Needs Rebase

#8329 ISPN-11842 Upgrade Spring Boot 2.3 dependencies
  build-configuration/pom.xml
Labels: Trivial :-)

#8352 ISPN-11532 Replace HotRod worker thread pool
  server/hotrod/src/test/java/org/infinispan/server/hotrod/logging/HotRodAccessLoggingTest.java
Labels: Test fix, Trivial :-)

#8314 add versioned operator docs
  documentation/src/main/asciidoc/index.asciidoc
Labels: Documentation

#8311 [10.1.x] ISPN-11819 Prevent ContainerInfinispanServerDriver erroneous state with provided server directory
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java
Labels: Backport

#8355 Fix patch help file
  cli/cli-client/src/main/resources/help/patch.adoc
Labels: Trivial :-)

#8357 ISPN-7180 ClientClusterExpirationEventsTest.testNullValueMetadataExpi…
  core/src/main/java/org/infinispan/notifications/cachelistener/CacheNotifierImpl.java
Labels: Test fix, Trivial :-)

#8354 ISPN-11872 CertificateTest test blocking
  server/core/src/main/java/org/infinispan/server/core/ServerCoreBlockHoundIntegration.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/ServerHotRodBlockHoundIntegration.java
Labels: Test fix, Trivial :-)

#8348 ISPN-11865 Deprecate the @Store annotation
  commons/all/src/main/java/org/infinispan/commons/persistence/Store.java
Labels: Trivial :-)

#8360 ISPN-11877 Remove PartitionHandling.ENABLED
  core/src/main/java/org/infinispan/configuration/cache/PartitionHandlingConfiguration.java
  core/src/main/java/org/infinispan/configuration/cache/PartitionHandlingConfigurationBuilder.java
  core/src/main/java/org/infinispan/configuration/parsing/Parser.java
  core/src/test/java/org/infinispan/configuration/parsing/UnifiedXmlFileParsingTest.java
Labels: Trivial :-)

#8365 Fix CliIT thread leak
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/AeshTestConnection.java
Labels: Test fix, Trivial :-)

#8368 ISPN-11882 LimitedExecutor.tryExecute blocking call causing random te…
  core/src/main/java/org/infinispan/executors/LimitedExecutor.java
  core/src/main/java/org/infinispan/util/CoreBlockHoundIntegration.java
Labels: Test fix

#8363 ISPN-11880 Remove unused files from distribution dir
  bin/reversion.sh
  core/src/test/java/org/infinispan/configuration/SampleConfigFilesCorrectnessTest.java
  distribution/src/main/release/common/bin/functions.sh
  distribution/src/main/release/common/configs/config-samples/distributed-ec2.xml
  distribution/src/main/release/common/configs/config-samples/distributed-udp.xml
  distribution/src/main/release/common/configs/config-samples/minimal.xml
  distribution/src/main/release/common/configs/config-samples/sample.xml
  distribution/src/main/release/common/configs/log4j/log4j2.xml
Labels: Trivial :-)

#8376 ISPN-11205 DataSource support in the Server
  server/runtime/src/main/resources/schema/infinispan-server-11.0.xsd
Labels: Trivial :-)

#8371 ISPN-11887 Remove remaining Equivalence classes
  commons/all/src/main/java/org/infinispan/commons/equivalence/AnyEquivalence.java
  commons/all/src/main/java/org/infinispan/commons/equivalence/AnyServerEquivalence.java
  commons/all/src/main/java/org/infinispan/commons/equivalence/ByteArrayEquivalence.java
  commons/all/src/main/java/org/infinispan/commons/equivalence/Equivalence.java
  commons/all/src/main/java/org/infinispan/commons/equivalence/EquivalentHashMap.java
  commons/all/src/main/java/org/infinispan/commons/equivalence/EquivalentHashSet.java
  commons/all/src/main/java/org/infinispan/commons/equivalence/EquivalentLinkedHashMap.java
  commons/all/src/main/java/org/infinispan/commons/equivalence/IdentityEquivalence.java
  commons/all/src/main/java/org/infinispan/commons/equivalence/package-info.java
  commons/all/src/main/java/org/infinispan/commons/marshall/exts/EquivalenceExternalizer.java
  core/src/main/java/org/infinispan/marshall/core/InternalExternalizers.java
  core/src/main/java/org/infinispan/marshall/exts/MapExternalizer.java
  core/src/test/java/org/infinispan/commons/EquivalentLinkedHashMapTest.java
  core/src/test/java/org/infinispan/util/EquivalentHashMapTest.java
  core/src/test/java/org/infinispan/util/EquivalentHashSetTest.java
Labels: Trivial :-)

#8372 ISPN-11888 InvocationContext cleanup
  core/src/main/java/org/infinispan/context/InvocationContext.java
  core/src/main/java/org/infinispan/context/InvocationContextContainer.java
  core/src/main/java/org/infinispan/context/impl/AbstractInvocationContext.java
  core/src/main/java/org/infinispan/context/impl/AbstractInvocationContextFactory.java
  core/src/main/java/org/infinispan/context/impl/ImmutableContext.java
  core/src/main/java/org/infinispan/context/impl/NonTransactionalInvocationContextFactory.java
  core/src/main/java/org/infinispan/context/impl/SingleKeyNonTxInvocationContext.java
  core/src/main/java/org/infinispan/context/impl/TransactionalInvocationContextFactory.java
Labels: Trivial :-)

#8369 ISPN-11871 cli user command instead of user-tool
  documentation/src/main/asciidoc/topics/cmd_examples/user_tool_authz_nix.adoc
  documentation/src/main/asciidoc/topics/cmd_examples/user_tool_authz_win.adoc
  documentation/src/main/asciidoc/topics/cmd_examples/user_tool_nix.adoc
  documentation/src/main/asciidoc/topics/cmd_examples/user_tool_win.adoc
  documentation/src/main/asciidoc/topics/proc_adding_server_users.adoc
  documentation/src/main/asciidoc/topics/proc_server_user_tool.adoc
  documentation/src/main/asciidoc/topics/proc_starting_server.adoc
  documentation/src/main/asciidoc/topics/ref_rest_security.adoc
  server/runtime/src/main/server/README.md
Labels: Documentation

#8383 ISPN-11630 Server and client get out of sync after multimap get with …
  commons/all/src/main/java/org/infinispan/commons/util/Util.java
Labels: Test fix, Trivial :-)

#8379 Console 0.6.Final
  build-configuration/pom.xml
Labels: Trivial :-)

#8380 ISPN-11897 Internal Caches with persistence don't need availability c…
  core/src/main/java/org/infinispan/registry/impl/InternalCacheRegistryImpl.java
Labels: Trivial :-)

#8395 ISPN-11919 Patch tool should use the brand version
  cli/cli-client/src/main/java/org/infinispan/cli/patching/PatchTool.java
  commons/all/src/main/java/org/infinispan/commons/util/Version.java
Labels: Trivial :-)

#8373 ISPN-11889 Remove deprecated parser attributes
  core/src/main/java/org/infinispan/configuration/parsing/Parser.java
Labels: Trivial :-)

#8397 ISPN-11921 Add org.apache.lucene:lucene-misc back
  pom.xml
Labels: Trivial :-)

#8396 ISPN-11922 Upgrade org.reactivestreams:reactive-streams to 1.0.3
  build-configuration/pom.xml
  client/infinispan-key-value-store-hotrod/pom.xml
  pom.xml
Labels: Trivial :-)

#8402 ISPN-11924 Protostream Processor Dependency XML is incorrect
  documentation/src/main/asciidoc/topics/dependencies_maven/protostream-processor.xml
Labels: Documentation

#8385 ISPN-11896 non blocking cache store SPI docs
  core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java
  core/src/main/java/org/infinispan/persistence/spi/InitializationContext.java
  core/src/main/java/org/infinispan/persistence/spi/NonBlockingStore.java
  core/src/main/java/org/infinispan/util/concurrent/BlockingManager.java
  core/src/main/java/org/infinispan/util/concurrent/NonBlockingManager.java
Labels: Documentation

#8390 ISPN-11891 MassIndexingTest#testOverlappingMassIndexers random failures
  query/src/main/java/org/infinispan/query/impl/massindex/DistributedExecutorMassIndexer.java
  query/src/test/java/org/infinispan/query/distributed/MassIndexingTest.java
Labels: Test fix

#8413 ISPN-11891 MassIndexingTest#testOverlappingMassIndexers failures
  query/src/test/java/org/infinispan/query/distributed/MassIndexingTest.java
Labels: Test fix
