Repository infinispan/infinispan, pull requests merged in 2020-09, with the labels that each got.

#8655 ISPN-12263 RemoteCacheMetricBinderTest fails
  server/testdriver/junit5/src/main/java/org/infinispan/server/test/junit5/InfinispanServerExtension.java
  spring/spring-boot/remote/src/test/java/test/org/infinispan/spring/starter/remote/actuator/RemoteCacheMetricBinderTest.java
  spring/spring-boot/remote/src/test/resources/infinispan.xml
Labels: Test fix

#8658 ISPN-12272 clarify xsite docs
  documentation/src/main/asciidoc/topics/con_xsite_auto_offline.adoc
  documentation/src/main/asciidoc/topics/config_examples/jgroups-relay.xml
  documentation/src/main/asciidoc/topics/ref_xsite_jgroups_relay_custom.adoc
Labels: Documentation

#8664 [11.0.x] ISPN-12272 clarify xsite docs
  documentation/src/main/asciidoc/topics/con_xsite_auto_offline.adoc
  documentation/src/main/asciidoc/topics/config_examples/jgroups-relay.xml
  documentation/src/main/asciidoc/topics/ref_xsite_jgroups_relay_custom.adoc
Labels: Backport, Documentation

#8661 ISPN-12274 Component annotation processor injection method single line
  component-processor/src/main/java/org/infinispan/component/processor/Generator.java
Labels: Trivial :-)

#8669 ISPN-12284 InfinispanRuleBasicTest thread leak
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/AbstractInfinispanServerDriver.java
  server/testdriver/junit4/pom.xml
  server/testdriver/junit5/pom.xml
  server/testdriver/pom.xml
Labels: Test fix

#8668 ISPN-12088 Correctly document group properties
  documentation/src/main/asciidoc/topics/config_examples/server_groups.properties
  server/runtime/src/main/server/server/conf/groups.properties
Labels: Documentation, Trivial :-)

#8673 ISPN-12287 Console 0.9.Final
  build-configuration/pom.xml
Labels: Trivial :-)

#8650 ISPN-12257 RemoteSpringSessionTest.testCreatingSessionWhenUsingREST
  spring/spring-boot/remote/src/main/java/org/infinispan/spring/starter/remote/InfinispanRemoteAutoConfiguration.java
  spring/spring5/spring5-remote/src/main/java/org/infinispan/spring/remote/AbstractRemoteCacheManagerFactory.java
Labels: Test fix

#8674 ISPN-12234 remove infinispan-cachestore-rest final bits
  build-configuration/bom/pom.xml
  distribution/pom.xml
  documentation/pom.xml
  javadoc/pom.xml
  tools/pom.xml
Labels: Documentation, Urgent!

#8678 ISPN-12305 functional map conditionals
  documentation/src/main/asciidoc/user_guide/cache_api.adoc
  documentation/src/main/asciidoc/user_guide/functional_api.adoc
Labels: Documentation, Trivial :-)

#8666 [11.0.x] ISPN-12273 Potential race condition during wiring of EncoderCache
  core/src/main/java/org/infinispan/factories/impl/BasicComponentRegistryImpl.java
  core/src/main/java/org/infinispan/marshall/persistence/PersistenceMarshaller.java
  core/src/test/java/org/infinispan/factories/impl/BasicComponentRegistryImplTest.java
  core/src/test/java/org/infinispan/factories/impl/FactoryAutoInstantiationTest.java
Labels: Backport

#8596 [11.0.x] ISPN-11924 Advise on using protostream-processor as a 'provided' dependenc
  build-configuration/bom/pom.xml
  documentation/src/main/asciidoc/topics/dependencies_maven/protostream-processor.xml
  documentation/src/main/asciidoc/topics/proc_generating_serial_cxt_initializer.adoc
Labels: Backport

#8557 [11.0.x] ISPN-11286 compute(...) is not working without any error message if e…
  core/src/main/java/org/infinispan/cache/impl/SimpleCacheImpl.java
  core/src/test/java/org/infinispan/api/APINonTxTest.java
Labels: Backport

#8684 ISPN-12317 WildFly modules integration tests do not start
  integrationtests/server-integration/server-integration-commons/src/test/java/org/infinispan/test/integration/commons/client/AbstractHotRodClientIT.java
  integrationtests/server-integration/third-party-server/src/test/java/org/infinispan/test/integration/thirdparty/HotRodClientIT.java
  integrationtests/server-integration/wildfly-modules/src/test/java/org/infinispan/test/integration/as/client/HotRodClientIT.java
  pom.xml
Labels: Test fix

#8681 [11.0.x] ISPN-12249 Better exception handling for cross-site requests
  core/src/main/java/org/infinispan/remoting/inboundhandler/GlobalInboundInvocationHandler.java
  core/src/main/java/org/infinispan/util/logging/Log.java
  core/src/main/java/org/infinispan/xsite/status/DefaultTakeOfflineManager.java
  core/src/test/java/org/infinispan/xsite/AbstractXSiteTest.java
  core/src/test/java/org/infinispan/xsite/offline/InvalidConfigurationOfflineTest.java
Labels: Backport

#8686 ISPN-12321 Leaked thread: mysql-cj-abandoned-connection-cleanup
  commons-test/src/main/java/org/infinispan/commons/test/ThreadLeakChecker.java
Labels: Test fix, Trivial :-)

#8679 ISPN-12314 lsof check is too expensive
  server/runtime/src/main/ant/infinispan-server.xml
Labels: Trivial :-)

#8689 ISPN-12322 GetAllCommandNodeCrashTest.test random failures
  core/src/test/java/org/infinispan/commands/GetAllCommandNodeCrashTest.java
Labels: Test fix

#8695 ISPN-12334 Fix configdocs
  distribution/pom.xml
  persistence/jpa/src/main/resources/schema/infinispan-cachestore-jpa-config-12.0.xsd
Labels: Trivial :-)

#8694 ISPN-12334 Fix configdocs
  distribution/pom.xml
  persistence/jpa/src/main/resources/schema/infinispan-cachestore-jpa-config-11.0.xsd
Labels: Backport, Trivial :-)

#8706 ISPN-12345 Dump JGroups stack on startup
  core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
Labels: Trivial :-)

#8705 ISPN-12344 cannot preload shared remote stores
  core/src/main/resources/schema/infinispan-config-12.0.xsd
  documentation/src/main/asciidoc/topics/ref_cache_store_remote.adoc
Labels: Documentation, Trivial :-)

#8708 [11.x] ISPN-12344 cannot preload shared remote stores
  core/src/main/resources/schema/infinispan-config-11.0.xsd
  documentation/src/main/asciidoc/topics/ref_cache_store_remote.adoc
Labels: Backport, Documentation, Trivial :-)

#8713 [11.x] ISPN-12352 Set license information when missing
  tools/src/main/java/org/infinispan/tools/Dependency.java
  tools/src/main/java/org/infinispan/tools/ToolUtils.java
  tools/src/main/java/org/infinispan/tools/licenses/LicenseMerger.java
  tools/src/main/java/org/infinispan/tools/licenses/LicenseReplacer.java
Labels: Backport

#8710 [11.x] ISPN-12330 Fix licenses for Infinispan Server
  distribution/src/main/resources/licenses/bsd-0-clause.txt
  distribution/src/main/resources/licenses/isc-license.txt
  distribution/src/main/resources/licenses/ofl-1.1.txt
  distribution/src/main/resources/template/licenses.xsl
  server/runtime/build.xml
  server/runtime/pom.xml
  server/runtime/src/main/server/docs/licenses/licenses.css
  server/runtime/src/main/server/docs/licenses/licenses.xsl
Labels: Backport

#8614 ISPN-12206 Create an InfinispanXSiteServerRule and increase the tests coverage
  server/testdriver/core/src/main/java/org/infinispan/server/test/api/TestClientXSiteDriver.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/AbstractServerConfigBuilder.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/TestServer.java
  server/testdriver/junit4/src/main/java/org/infinispan/server/test/junit4/InfinispanXSiteServerRule.java
  server/testdriver/junit4/src/main/java/org/infinispan/server/test/junit4/InfinispanXSiteServerRuleBuilder.java
  server/testdriver/junit4/src/main/java/org/infinispan/server/test/junit4/InfinispanXSiteServerTestMethodRule.java
  server/testdriver/junit5/src/main/java/org/infinispan/server/test/junit5/InfinispanXSiteServerExtension.java
  server/testdriver/junit5/src/main/java/org/infinispan/server/test/junit5/InfinispanXSiteServerExtensionBuilder.java
  server/testdriver/junit5/src/test/java/org/infinispan/server/test/junit5/InfinispanXSiteServerTest.java
  server/testdriver/junit5/src/test/resources/XSiteServerTest.xml
  server/testdriver/junit5/src/test/resources/cache-container/clustered.xml
  server/testdriver/junit5/src/test/resources/endpoints/default.xml
  server/testdriver/junit5/src/test/resources/interfaces/default.xml
  server/testdriver/junit5/src/test/resources/jgroups/xsite-stacks.xml
  server/testdriver/junit5/src/test/resources/security/none.xml
  server/testdriver/junit5/src/test/resources/socket-bindings/default.xml
  server/tests/src/test/java/org/infinispan/server/functional/XSiteHotRodCacheOperations.java
  server/tests/src/test/java/org/infinispan/server/functional/XSiteIT.java
  server/tests/src/test/java/org/infinispan/server/functional/XSiteRestCacheOperations.java
Labels: Changes Required

#8715 ISPN-12221 Update zero-capacity-node docs
  documentation/src/main/asciidoc/topics/con_caches_distribution.adoc
Labels: Documentation

#8716 ISPN-12355 fix broken links in User Guide
  documentation/src/main/asciidoc/user_guide/architecture.adoc
  documentation/src/main/asciidoc/user_guide/introduction.adoc
Labels: Documentation, Trivial :-)

#8717 ISPN-12356 ScatteredStreamIteratorTest random failure
  core/src/main/java/org/infinispan/reactive/publisher/impl/ClusterPublisherManagerImpl.java
Labels: Trivial :-)

#8700 ISPN-12338 Unzip tomcat only during the test phase
  integrationtests/server-integration/third-party-server/pom.xml
Labels: Trivial :-)

#8720 ISPN-12360 Upgrade Server Console to 0.10.Final
  build-configuration/pom.xml
Labels: Trivial :-)

#8696 ISPN-6901 ConsistentHashV2IntegrationTest.testCorrectBalancingOfKeysA…
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/ConsistentHashV2IntegrationTest.java
Labels: Test fix

#8723 ISPN-12365 Don't log io.netty.handler.ssl.NotSslRecordException: not …
  server/runtime/src/main/server/server/conf/log4j2.xml
Labels: Trivial :-)

#8724 [11.0] ISPN-12365 Don't log io.netty.handler.ssl.NotSslRecordException: not …
  server/runtime/src/main/server/server/conf/log4j2.xml
Labels: Backport, Trivial :-)
