Repository infinispan/infinispan, pull requests merged in 2020-02, with the labels that each got.

#7813 ISPN-10836 deserialization whitelist per cache manager
  documentation/src/main/asciidoc/topics/marshalling.adoc
Labels: Changes Required, Documentation, Trivial :-)

#7810 ISPN-11258 Proto Compatibility check should not fail on unknown OS
  build-configuration/pom.xml
Labels: Trivial :-)

#7812 [10.1.x] ISPN-11258 Proto Compatibility check should not fail on unknown OS
  build-configuration/pom.xml
Labels: Backport

#7820 [10.1.x] ISPN-11231 Transcoder lookup is inefficient
  commons/src/main/java/org/infinispan/commons/dataconversion/EncoderIds.java
  commons/src/main/java/org/infinispan/commons/dataconversion/Transcoder.java
  commons/src/main/java/org/infinispan/commons/dataconversion/WrapperIds.java
  core/src/main/java/org/infinispan/encoding/DataConversion.java
  core/src/main/java/org/infinispan/factories/EncoderRegistryFactory.java
  core/src/main/java/org/infinispan/factories/InternalCacheFactory.java
  core/src/main/java/org/infinispan/marshall/core/EncoderRegistry.java
  core/src/main/java/org/infinispan/marshall/core/EncoderRegistryImpl.java
Labels: Backport

#7830 [10.1.x] ISPN-11278 Deprecate SiteConfiguration
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/xsite/AbstractHotRodSiteFailoverTest.java
  core/src/main/java/org/infinispan/configuration/global/SiteConfiguration.java
  core/src/main/java/org/infinispan/configuration/global/SiteConfigurationBuilder.java
  core/src/main/java/org/infinispan/configuration/parsing/Parser.java
  core/src/main/java/org/infinispan/configuration/serializing/Serializer.java
  core/src/main/java/org/infinispan/factories/EmptyConstructorNamedCacheFactory.java
  core/src/main/java/org/infinispan/remoting/transport/AbstractDelegatingTransport.java
  core/src/main/java/org/infinispan/remoting/transport/Transport.java
  core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
  core/src/main/java/org/infinispan/util/logging/Log.java
  core/src/main/java/org/infinispan/xsite/BackupSenderImpl.java
  core/src/test/java/org/infinispan/configuration/serializer/AbstractConfigurationSerializerTest.java
  core/src/test/java/org/infinispan/remoting/transport/MockTransport.java
  core/src/test/java/org/infinispan/test/fwk/TestCacheManagerFactory.java
  core/src/test/java/org/infinispan/test/fwk/TransportFlags.java
  core/src/test/java/org/infinispan/xsite/AbstractMultipleSitesTest.java
  core/src/test/java/org/infinispan/xsite/AbstractTwoSitesTest.java
  core/src/test/java/org/infinispan/xsite/AbstractXSiteTest.java
  core/src/test/java/org/infinispan/xsite/BackupForConfigTest.java
  core/src/test/java/org/infinispan/xsite/BackupForNotSpecifiedTest.java
  core/src/test/java/org/infinispan/xsite/BaseSiteUnreachableTest.java
  core/src/test/java/org/infinispan/xsite/XSiteFileParsing2Test.java
  core/src/test/java/org/infinispan/xsite/XSiteFileParsing3Test.java
  core/src/test/java/org/infinispan/xsite/XSiteFileParsingTest.java
  core/src/test/java/org/infinispan/xsite/XSiteInlineConfigFileParsingTest.java
  core/src/test/java/org/infinispan/xsite/XSiteStateTransferFileParsingTest.java
  core/src/test/java/org/infinispan/xsite/offline/AsyncOfflineTest.java
  core/src/test/java/org/infinispan/xsite/offline/AsyncTimeBasedOfflineTest.java
  core/src/test/java/org/infinispan/xsite/statetransfer/LocalCacheStateTransferTest.java
  wildfly/infinispan/src/main/java/org/jboss/as/clustering/infinispan/subsystem/CacheContainerConfigurationBuilder.java
Labels: Backport

#7740 ISPN-10804 JCache tck-runner does not run interception tests
  jcache/tck-runner-embedded/pom.xml
  jcache/tck-runner-embedded/src/test/resources/META-INF/beans.xml
Labels: Changes Required

#7807 [10.1] ISPN-11253 Add task name to hotrod access log
  server/hotrod/src/main/resources/hotrod.gr
Labels: Backport, Trivial :-)

#7836 [10.1] ISPN-11284 Make the containerized server timeout configurable
  server/runtime/src/test/java/org/infinispan/server/test/ContainerInfinispanServerDriver.java
Labels: Backport

#7837 ISPN-11282 CLI: site command isn't working properly
  cli/cli-client/src/main/java/org/infinispan/cli/commands/Site.java
  cli/cli-client/src/main/java/org/infinispan/cli/connection/rest/RestConnection.java
  cli/cli-client/src/main/resources/help/site.adoc
Labels: Trivial :-)

#7838 [10.1.x] ISPN-11282 CLI: site command isn't working properly
  cli/cli-client/src/main/java/org/infinispan/cli/commands/Site.java
  cli/cli-client/src/main/java/org/infinispan/cli/connection/rest/RestConnection.java
  cli/cli-client/src/main/resources/help/site.adoc
Labels: Backport, Trivial :-)

#7831 [10.1] ISPN-11168 Use manifest dependencies in DuplicatedDomainsCdiIT
  integrationtests/wildfly-modules/src/test/java/org/infinispan/test/integration/as/cdi/DuplicatedDomainsCdiIT.java
Labels: Backport

#7774 ISPN-10839 Configuration Doc Updates
  documentation/src/main/asciidoc/stories/assembly_configuration.adoc
  documentation/src/main/asciidoc/stories/assembly_configuring_declaratively.adoc
  documentation/src/main/asciidoc/stories/assembly_configuring_prog.adoc
  documentation/src/main/asciidoc/titles/configuring/stories.adoc
  documentation/src/main/asciidoc/topics/attributes/community-attributes.adoc
  documentation/src/main/asciidoc/topics/attributes/product-attributes.adoc
  documentation/src/main/asciidoc/topics/code_examples/ConfigDefaultRegisterManager.java
  documentation/src/main/asciidoc/topics/code_examples/ConfigRegisterManager.java
  documentation/src/main/asciidoc/topics/code_examples/ConfigReplicatedRegisterManager.java
  documentation/src/main/asciidoc/topics/code_examples/ConfigThreadPools.java
  documentation/src/main/asciidoc/topics/code_examples/GetSomeNamedCache.java
  documentation/src/main/asciidoc/topics/config_examples/config_template_inherit.xml
  documentation/src/main/asciidoc/topics/config_examples/config_template_wildcard.xml
  documentation/src/main/asciidoc/topics/config_examples/config_xinclude.xml
  documentation/src/main/asciidoc/topics/config_examples/infinispan.xml
  documentation/src/main/asciidoc/topics/config_examples/ispn_datasource.xml
  documentation/src/main/asciidoc/topics/config_examples/ispn_h2_ds.xml
  documentation/src/main/asciidoc/topics/config_examples/local_template_config.xml
  documentation/src/main/asciidoc/topics/config_examples/locking.xml
  documentation/src/main/asciidoc/topics/config_examples/simple_config_cache_types.xml
  documentation/src/main/asciidoc/topics/config_examples/state_transfer.xml
  documentation/src/main/asciidoc/topics/proc_configuring_declaratively.adoc
  documentation/src/main/asciidoc/topics/proc_configuring_prog.adoc
  documentation/src/main/asciidoc/topics/ref_cache_containers.adoc
  documentation/src/main/asciidoc/topics/ref_cache_declarations.adoc
  documentation/src/main/asciidoc/topics/ref_config_declarative.adoc
  documentation/src/main/asciidoc/topics/ref_config_programmatic.adoc
  documentation/src/main/asciidoc/topics/ref_config_programmatic_objects.adoc
  documentation/src/main/asciidoc/topics/ref_config_templates.adoc
  documentation/src/main/asciidoc/topics/ref_config_wildcards.adoc
  documentation/src/main/asciidoc/topics/ref_config_xinclude.adoc
  documentation/src/main/asciidoc/topics/ref_datasource_config.adoc
  documentation/src/main/asciidoc/topics/ref_ispn_subsystem.adoc
  documentation/src/main/asciidoc/topics/ref_locking_config.adoc
  documentation/src/main/asciidoc/topics/ref_state_xfer_config.adoc
Labels: Documentation

#7827 [10.1.x] ISPN-10839 Configuration Doc Updates
  documentation/src/main/asciidoc/stories/assembly_configuration.adoc
  documentation/src/main/asciidoc/stories/assembly_configuring_declaratively.adoc
  documentation/src/main/asciidoc/stories/assembly_configuring_prog.adoc
  documentation/src/main/asciidoc/titles/configuring/stories.adoc
  documentation/src/main/asciidoc/topics/attributes/community-attributes.adoc
  documentation/src/main/asciidoc/topics/attributes/product-attributes.adoc
  documentation/src/main/asciidoc/topics/code_examples/ConfigDefaultRegisterManager.java
  documentation/src/main/asciidoc/topics/code_examples/ConfigRegisterManager.java
  documentation/src/main/asciidoc/topics/code_examples/ConfigReplicatedRegisterManager.java
  documentation/src/main/asciidoc/topics/code_examples/ConfigThreadPools.java
  documentation/src/main/asciidoc/topics/code_examples/GetSomeNamedCache.java
  documentation/src/main/asciidoc/topics/config_examples/config_template_inherit.xml
  documentation/src/main/asciidoc/topics/config_examples/config_template_wildcard.xml
  documentation/src/main/asciidoc/topics/config_examples/config_xinclude.xml
  documentation/src/main/asciidoc/topics/config_examples/infinispan.xml
  documentation/src/main/asciidoc/topics/config_examples/ispn_datasource.xml
  documentation/src/main/asciidoc/topics/config_examples/ispn_h2_ds.xml
  documentation/src/main/asciidoc/topics/config_examples/local_template_config.xml
  documentation/src/main/asciidoc/topics/config_examples/locking.xml
  documentation/src/main/asciidoc/topics/config_examples/simple_config_cache_types.xml
  documentation/src/main/asciidoc/topics/config_examples/state_transfer.xml
  documentation/src/main/asciidoc/topics/proc_configuring_declaratively.adoc
  documentation/src/main/asciidoc/topics/proc_configuring_prog.adoc
  documentation/src/main/asciidoc/topics/ref_cache_containers.adoc
  documentation/src/main/asciidoc/topics/ref_cache_declarations.adoc
  documentation/src/main/asciidoc/topics/ref_config_declarative.adoc
  documentation/src/main/asciidoc/topics/ref_config_programmatic.adoc
  documentation/src/main/asciidoc/topics/ref_config_programmatic_objects.adoc
  documentation/src/main/asciidoc/topics/ref_config_templates.adoc
  documentation/src/main/asciidoc/topics/ref_config_wildcards.adoc
  documentation/src/main/asciidoc/topics/ref_config_xinclude.adoc
  documentation/src/main/asciidoc/topics/ref_datasource_config.adoc
  documentation/src/main/asciidoc/topics/ref_ispn_subsystem.adoc
  documentation/src/main/asciidoc/topics/ref_locking_config.adoc
  documentation/src/main/asciidoc/topics/ref_state_xfer_config.adoc
Labels: Documentation

#7817 ISPN-11219 update capacity factors doc
  documentation/src/main/asciidoc/topics/con_caches_distribution.adoc
Labels: Documentation

#7818 [10.1.x] ISPN-11219 update capacity factors doc
  documentation/src/main/asciidoc/topics/con_caches_distribution.adoc
Labels: Documentation

#7847 [10.1.x] ISPN-10991 DistributedStreamTest.testObjFlatMapIterator[DIST_SYNC, tx…
  core/src/main/java/org/infinispan/reactive/publisher/impl/PublisherHandler.java
  core/src/test/java/org/infinispan/stream/BaseStreamTest.java
Labels: Backport

#7821 ISPN-11197 Server JMX Docs
  documentation/src/main/asciidoc/stories/assembly_server_jmx.adoc
  documentation/src/main/asciidoc/stories/assembly_server_monitoring.adoc
  documentation/src/main/asciidoc/topics/jmx.adoc
  documentation/src/main/asciidoc/topics/jmx_server.adoc
  documentation/src/main/asciidoc/topics/proc_enabling_jmx_statistics.adoc
  documentation/src/main/asciidoc/topics/proc_naming_cache_managers.adoc
  documentation/src/main/asciidoc/topics/proc_registering_jmx_mbeans.adoc
  documentation/src/main/asciidoc/topics/ref_jmx_mbeans.adoc
Labels: Documentation

#7852 [10.1] ISPN-11294 Prevent 'cd' under a cache
  cli/cli-client/src/main/java/org/infinispan/cli/connection/rest/RestConnection.java
Labels: Backport

#7844 [10.1] ISPN-11290 Optionally use a prebuilt server from the supplied container
  pom.xml
  server/runtime/TESTING.md
  server/runtime/src/test/java/org/infinispan/server/test/ContainerInfinispanServerDriver.java
  server/runtime/src/test/java/org/infinispan/server/test/ServerRunMode.java
  server/runtime/src/test/java/org/infinispan/server/test/TestSystemPropertyNames.java
Labels: Backport

#7794 ISPN-10725 Server Security Doc Updates
  documentation/src/main/asciidoc/stories/assembly_server_endpoint_authentication.adoc
  documentation/src/main/asciidoc/stories/assembly_server_security.adoc
  documentation/src/main/asciidoc/stories/assembly_server_security_identity.adoc
  documentation/src/main/asciidoc/stories/assembly_server_security_realm.adoc
  documentation/src/main/asciidoc/topics/attributes/community-attributes.adoc
  documentation/src/main/asciidoc/topics/attributes/product-attributes.adoc
  documentation/src/main/asciidoc/topics/cmd_examples/krb5.adoc
  documentation/src/main/asciidoc/topics/con_cache_authorization.adoc
  documentation/src/main/asciidoc/topics/config_examples/hotrod_connector_policies.xml
  documentation/src/main/asciidoc/topics/config_examples/hotrod_connector_sasl.xml
  documentation/src/main/asciidoc/topics/config_examples/hotrod_connector_sasl_kerberos.xml
  documentation/src/main/asciidoc/topics/config_examples/krb5.conf
  documentation/src/main/asciidoc/topics/config_examples/rest_connector_authentication.xml
  documentation/src/main/asciidoc/topics/config_examples/rest_connector_authentication_spnego.xml
  documentation/src/main/asciidoc/topics/config_examples/server_endpoint_require_client_cert.xml
  documentation/src/main/asciidoc/topics/config_examples/server_groups.properties
  documentation/src/main/asciidoc/topics/config_examples/server_identities_kerberos.xml
  documentation/src/main/asciidoc/topics/config_examples/server_ldap_realm.xml
  documentation/src/main/asciidoc/topics/config_examples/server_ldap_realm_connection.xml
  documentation/src/main/asciidoc/topics/config_examples/server_ldap_realm_rewriter.xml
  documentation/src/main/asciidoc/topics/config_examples/server_properties_realm.xml
  documentation/src/main/asciidoc/topics/config_examples/server_ssl_identity.xml
  documentation/src/main/asciidoc/topics/config_examples/server_ssl_identity_engine.xml
  documentation/src/main/asciidoc/topics/config_examples/server_ssl_identity_generated.xml
  documentation/src/main/asciidoc/topics/config_examples/server_token_realm_oauth.xml
  documentation/src/main/asciidoc/topics/config_examples/server_truststore_realm.xml
  documentation/src/main/asciidoc/topics/config_examples/server_users.properties
  documentation/src/main/asciidoc/topics/proc_configure_clients_trust_server.adoc
  documentation/src/main/asciidoc/topics/proc_server_configuring_ssl_engine.adoc
  documentation/src/main/asciidoc/topics/proc_server_endpoint_hotrod_auth.adoc
  documentation/src/main/asciidoc/topics/proc_server_endpoint_rest_auth.adoc
  documentation/src/main/asciidoc/topics/proc_server_generating_keystores.adoc
  documentation/src/main/asciidoc/topics/proc_server_identity_kerberos.adoc
  documentation/src/main/asciidoc/topics/proc_server_identity_ssl.adoc
  documentation/src/main/asciidoc/topics/proc_server_require_client_cert.adoc
  documentation/src/main/asciidoc/topics/proc_server_ssl_keytool.adoc
  documentation/src/main/asciidoc/topics/proc_server_user_tool.adoc
  documentation/src/main/asciidoc/topics/ref_cache_authorization.adoc
  documentation/src/main/asciidoc/topics/ref_endpoints_hotrod_auth_config.adoc
  documentation/src/main/asciidoc/topics/ref_endpoints_hotrod_authentication.adoc
  documentation/src/main/asciidoc/topics/ref_endpoints_hotrod_sasl_policies.adoc
  documentation/src/main/asciidoc/topics/ref_endpoints_hotrod_sasl_qop.adoc
  documentation/src/main/asciidoc/topics/ref_endpoints_ref_auth_config.adoc
  documentation/src/main/asciidoc/topics/ref_endpoints_rest_authentication.adoc
  documentation/src/main/asciidoc/topics/ref_server_identity_kerberos.adoc
  documentation/src/main/asciidoc/topics/ref_server_identity_ssl.adoc
  documentation/src/main/asciidoc/topics/ref_server_realm_ldap.adoc
  documentation/src/main/asciidoc/topics/ref_server_realm_ldap_rewrite.adoc
  documentation/src/main/asciidoc/topics/ref_server_realm_property.adoc
  documentation/src/main/asciidoc/topics/ref_server_realm_token.adoc
  documentation/src/main/asciidoc/topics/ref_server_realm_trust.adoc
  documentation/src/main/asciidoc/topics/ref_server_ssl_engine.adoc
  documentation/src/main/asciidoc/topics/security_server.adoc
Labels: Changes Required, Documentation

#7854 ISPN-11291 MultipleCachesDuringConflictResolutionTest.testPartitionMergePolicy
  core/src/main/java/org/infinispan/conflict/impl/DefaultConflictManager.java
Labels: Test fix

#7777 [9.4.x] REPL read opt perf
  core/src/main/java/org/infinispan/container/impl/AbstractInternalDataContainer.java
  core/src/main/java/org/infinispan/container/impl/BoundedSegmentedDataContainer.java
  core/src/main/java/org/infinispan/container/impl/DefaultDataContainer.java
  core/src/main/java/org/infinispan/container/impl/DefaultSegmentedDataContainer.java
  core/src/main/java/org/infinispan/container/impl/L1SegmentedDataContainer.java
  core/src/main/java/org/infinispan/container/impl/PeekableTouchableContainerMap.java
  core/src/main/java/org/infinispan/container/impl/PeekableTouchableMap.java
  core/src/main/java/org/infinispan/container/impl/TouchableMap.java
  core/src/main/java/org/infinispan/container/offheap/OffHeapConcurrentMap.java
  core/src/main/java/org/infinispan/container/offheap/OffHeapDataContainer.java
  core/src/main/java/org/infinispan/container/offheap/SegmentedBoundedOffHeapDataContainer.java
  core/src/main/java/org/infinispan/factories/InternalCacheFactory.java
Labels: On Hold

#7809 ISPN-10604 Eviction and Expiration Docs
  core/src/main/resources/schema/infinispan-config-11.0.xsd
  documentation/src/main/asciidoc/stories/assembly_eviction.adoc
  documentation/src/main/asciidoc/stories/assembly_eviction_expiration.adoc
  documentation/src/main/asciidoc/titles/configuring/stories.adoc
  documentation/src/main/asciidoc/topics/code_examples/EvictionLifespanExample.java
  documentation/src/main/asciidoc/topics/con_evict_vs_expire.adoc
  documentation/src/main/asciidoc/topics/con_eviction.adoc
  documentation/src/main/asciidoc/topics/con_eviction_custom_types.adoc
  documentation/src/main/asciidoc/topics/con_eviction_overview.adoc
  documentation/src/main/asciidoc/topics/con_expiration.adoc
  documentation/src/main/asciidoc/topics/con_expiration_maxidle.adoc
  documentation/src/main/asciidoc/topics/con_expiration_overview.adoc
  documentation/src/main/asciidoc/topics/con_expiration_reaper.adoc
  documentation/src/main/asciidoc/topics/eviction.adoc
  documentation/src/main/asciidoc/topics/ref_eviction_examples.adoc
  documentation/src/main/asciidoc/topics/ref_expiration_examples.adoc
Labels: Documentation

#7828 [10.1.x] ISPN-10604 Eviction and Expiration Docs
  core/src/main/resources/schema/infinispan-config-10.1.xsd
  documentation/src/main/asciidoc/stories/assembly_eviction.adoc
  documentation/src/main/asciidoc/stories/assembly_eviction_expiration.adoc
  documentation/src/main/asciidoc/titles/configuring/stories.adoc
  documentation/src/main/asciidoc/topics/code_examples/EvictionLifespanExample.java
  documentation/src/main/asciidoc/topics/con_evict_vs_expire.adoc
  documentation/src/main/asciidoc/topics/con_eviction.adoc
  documentation/src/main/asciidoc/topics/con_eviction_custom_types.adoc
  documentation/src/main/asciidoc/topics/con_eviction_overview.adoc
  documentation/src/main/asciidoc/topics/con_expiration.adoc
  documentation/src/main/asciidoc/topics/con_expiration_maxidle.adoc
  documentation/src/main/asciidoc/topics/con_expiration_overview.adoc
  documentation/src/main/asciidoc/topics/con_expiration_reaper.adoc
  documentation/src/main/asciidoc/topics/eviction.adoc
  documentation/src/main/asciidoc/topics/ref_eviction_examples.adoc
  documentation/src/main/asciidoc/topics/ref_expiration_examples.adoc
Labels: Documentation

#7864 [10.1.x] IISPN-11275 expose local site name
  core/src/main/java/org/infinispan/manager/CacheManagerInfo.java
  server/rest/src/test/java/org/infinispan/rest/resources/AbstractRestResourceTest.java
  server/rest/src/test/java/org/infinispan/rest/resources/CacheManagerResourceTest.java
Labels: Backport

#7862 [9.4.x] ISPN-11303 Local non-blocking get breaks hit/miss statistics
  server/hotrod/src/main/java/org/infinispan/server/hotrod/CacheRequestProcessor.java
Labels: Backport

#7881 [10.1.x] ISPN-11323 Isolate JGroupsTransport MBean references to private methods
  core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
Labels: Backport

#7883 Upgrade Console to 0.2.Final
  build-configuration/pom.xml
Labels: Trivial :-)

#7882 [10.1.x] Upgrade Console to 0.2.Final
  build-configuration/pom.xml
Labels: Backport, Trivial :-)

#7885 [10.1.x] ISPN-11291 MultipleCachesDuringConflictResolutionTest.testPartitionMe…
  core/src/main/java/org/infinispan/conflict/impl/DefaultConflictManager.java
Labels: Backport

#7884 [10.1.x] ISPN-11302 Add infinispan.client.hotrod.context-initializers property
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/package-info.java
Labels: Backport

#7866 ISPN-11004 SQL server exception purging data
  persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/SQLServerTableManager.java
Labels: Trivial :-)

#7863 ISPN-11172 Remap container uid/gid to fix permissions with mounted vo…
  core/src/main/java/org/infinispan/topology/LocalTopologyManagerImpl.java
  pom.xml
  server/runtime/TESTING.md
  server/runtime/pom.xml
  server/runtime/src/test/java/org/infinispan/server/resilience/GracefulShutdownRestartIT.java
  server/runtime/src/test/java/org/infinispan/server/test/ContainerInfinispanServerDriver.java
  server/runtime/src/test/java/org/infinispan/server/test/EmbeddedInfinispanServerDriver.java
  server/runtime/src/test/java/org/infinispan/server/test/InfinispanServerDriver.java
  tasks/scripting/src/main/java/org/infinispan/scripting/impl/LifecycleCallbacks.java
Labels: Test fix

#7888 ISPN-11340 Upgrade JNA to 5.5.0
  pom.xml
Labels: Trivial :-)

#7889 [10.1.x] ISPN-11340 Upgrade JNA to 5.5.0
  pom.xml
Labels: Backport, Trivial :-)

#7890 [10.1] ISPN-11224 Add plain-text="true" to the default property realms
  documentation/src/main/asciidoc/topics/upgrading.adoc
  server/runtime/src/main/java/org/infinispan/server/logging/Messages.java
  server/runtime/src/main/java/org/infinispan/server/security/UserTool.java
  server/runtime/src/main/server/server/conf/infinispan-local.xml
  server/runtime/src/main/server/server/conf/infinispan-xsite.xml
  server/runtime/src/main/server/server/conf/infinispan.xml
  server/runtime/src/test/java/org/infinispan/server/usertool/UserToolTest.java
Labels: Backport

#7895 [10.1] ISPN-11342 Use UserTool to genrate test users/groups property files
  server/runtime/src/main/java/org/infinispan/server/tool/Main.java
  server/runtime/src/test/java/org/infinispan/server/test/InfinispanServerDriver.java
  server/runtime/src/test/java/org/infinispan/server/usertool/UserToolTest.java
Labels: Backport

#7880 [10.1.x] ISPN-11209 Max Idle changes caused a REPL read performance regression
  core/src/main/java/org/infinispan/container/impl/AbstractInternalDataContainer.java
  core/src/main/java/org/infinispan/container/impl/BoundedSegmentedDataContainer.java
  core/src/main/java/org/infinispan/container/impl/DefaultDataContainer.java
  core/src/main/java/org/infinispan/container/impl/DefaultSegmentedDataContainer.java
  core/src/main/java/org/infinispan/container/impl/L1SegmentedDataContainer.java
  core/src/main/java/org/infinispan/container/impl/PeekableTouchableContainerMap.java
  core/src/main/java/org/infinispan/container/impl/PeekableTouchableMap.java
  core/src/main/java/org/infinispan/container/offheap/OffHeapConcurrentMap.java
  core/src/main/java/org/infinispan/container/offheap/OffHeapDataContainer.java
  core/src/main/java/org/infinispan/container/offheap/SegmentedBoundedOffHeapDataContainer.java
  core/src/main/java/org/infinispan/factories/DataContainerFactory.java
  core/src/main/java/org/infinispan/factories/InternalCacheFactory.java
Labels: Backport

#7899 ISPN-11346 upgrade console to 0.3.Final
  build-configuration/pom.xml
Labels: Trivial :-)

#7900 [10.1.x] ISPN-11346 upgrade console to 0.3.Final
  build-configuration/pom.xml
Labels: Backport

#7893 ISPN-11343 Use LOCAL_PING in server used in WildFly modules IT
  integrationtests/wildfly-modules/src/test/resources/infinispan-custom.xml
Labels: Test fix, Trivial :-)

#7892 [10.1] ISPN-11343 Use LOCAL_PING in server used in WildFly modules IT
  integrationtests/wildfly-modules/src/test/resources/infinispan-custom.xml
Labels: Backport, Test fix, Trivial :-)

#7896 [10.1] ISPN-11297 Prevent creating clustered caches incompatible with global…
  core/src/main/java/org/infinispan/globalstate/impl/GlobalConfigurationManagerImpl.java
  core/src/test/java/org/infinispan/globalstate/GlobalStateTest.java
Labels: Backport

#7903 [9.4.x] ISPN-1004 backport fixed to use correct method overriding
  persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/impl/table/SQLServerTableManager.java
Labels: Trivial :-), Urgent!

#7901 ISPN-11347 Change default TOS for UDP
  core/src/main/resources/default-configs/default-jgroups-udp.xml
  core/src/test/resources/stacks/udp.xml
  tools/src/test/resources/udp.xml
  wildfly/jgroups/src/main/resources/jgroups-defaults.xml
Labels: Performance ACK required!

#7906 [10.1.x] ISPN-11347 Change default TOS for UDP
  core/src/main/resources/default-configs/default-jgroups-udp.xml
  core/src/test/resources/stacks/udp.xml
  tools/src/test/resources/udp.xml
  wildfly/jgroups/src/main/resources/jgroups-defaults.xml
Labels: Backport

#7907 [9.4.x] ISPN-11347 Change default TOS for UDP
  core/src/main/resources/default-configs/default-jgroups-udp.xml
  core/src/test/resources/stacks/udp.xml
  demos/gui/src/main/release/etc/config/jgroups-relay1.xml
  demos/gui/src/main/release/etc/config/jgroups-relay2.xml
  server/integration/jgroups/src/main/resources/jgroups-defaults.xml
Labels: Backport

#7905 [10.1.x] ISPN-11349 lock leak in SIFS FileProvider
  persistence/soft-index/src/main/java/org/infinispan/persistence/sifs/FileProvider.java
Labels: Backport

#7914 [10.1] ISPN-11172 Fork 'id' to get uid/gid
  pom.xml
  server/runtime/pom.xml
  server/runtime/src/test/java/org/infinispan/server/test/ContainerInfinispanServerDriver.java
Labels: Backport

#7909 [9.4] ISPN-11352 JGroups Subssytem: persist properties in the relay element
  server/integration/jgroups/src/main/java/org/infinispan/server/jgroups/subsystem/JGroupsSubsystemXMLWriter.java
  server/integration/jgroups/src/main/resources/schema/jboss-infinispan-jgroups_9_4.xsd
  server/integration/jgroups/src/test/resources/org/infinispan/server/jgroups/subsystem/subsystem-infinispan_server_jgroups-9_4.xml
Labels: Trivial :-)

#7910 [10.1] ISPN-11352 JGroups Subssytem: persist properties in the relay element
  wildfly/jgroups/src/main/java/org/infinispan/server/jgroups/subsystem/JGroupsSubsystemXMLWriter.java
  wildfly/jgroups/src/main/resources/schema/jboss-infinispan-jgroups_10_1.xsd
  wildfly/jgroups/src/test/resources/org/infinispan/server/jgroups/subsystem/subsystem-infinispan_server_jgroups-10_0.xml
  wildfly/jgroups/src/test/resources/org/infinispan/server/jgroups/subsystem/subsystem-infinispan_server_jgroups-10_1.xml
  wildfly/jgroups/src/test/resources/org/infinispan/server/jgroups/subsystem/subsystem-infinispan_server_jgroups-9_4.xml
Labels: Trivial :-)

#7908 ISPN-11352 JGroups Subssytem: persist properties in the relay element
  wildfly/jgroups/src/main/java/org/infinispan/server/jgroups/subsystem/JGroupsSubsystemXMLWriter.java
  wildfly/jgroups/src/main/resources/schema/jboss-infinispan-jgroups_11_0.xsd
  wildfly/jgroups/src/test/resources/org/infinispan/server/jgroups/subsystem/subsystem-infinispan_server_jgroups-10_0.xml
  wildfly/jgroups/src/test/resources/org/infinispan/server/jgroups/subsystem/subsystem-infinispan_server_jgroups-10_1.xml
  wildfly/jgroups/src/test/resources/org/infinispan/server/jgroups/subsystem/subsystem-infinispan_server_jgroups-11_0.xml
  wildfly/jgroups/src/test/resources/org/infinispan/server/jgroups/subsystem/subsystem-infinispan_server_jgroups-9_4.xml
Labels: Trivial :-)

#7919 ISPN-11369 RetryMechanismTest.testRetryLocally fails randomly
  core/src/main/java/org/infinispan/xsite/commands/XSiteStateTransferFinishSendCommand.java
  core/src/test/java/org/infinispan/xsite/statetransfer/failures/RetryMechanismTest.java
Labels: Test fix, Trivial :-)

#7926 ISPN-11292 Add in (non)blocking thread pools
  core/src/test/java/org/infinispan/lock/LockManagerTest.java
Labels: Test fix, Trivial :-)

#7930 ISPN-11334 do not change REST context path
  server/runtime/src/main/resources/schema/infinispan-server-11.0.xsd
Labels: Documentation

#7931 [10.1.x] ISPN-11334 do not change REST context path
  server/runtime/src/main/resources/schema/infinispan-server-10.1.xsd
Labels: Documentation

#7925 ISPN-11372 AsyncTimeBasedOfflineTest.testSFOOffline() random failures
  core/src/test/java/org/infinispan/xsite/offline/AsyncTimeBasedOfflineTest.java
Labels: Test fix, Trivial :-)

#7933 ISPN-11174 Fix RestMetricsResource test failure
  server/runtime/src/test/java/org/infinispan/server/functional/RestMetricsResource.java
Labels: Test fix, Trivial :-)

#7927 ISPN-10842 store migrator docs
  documentation/src/main/asciidoc/stories/assembly_migrating_cache_stores.adoc
  documentation/src/main/asciidoc/stories/assembly_migrating_data.adoc
  documentation/src/main/asciidoc/titles/upgrading/stories.adoc
  documentation/src/main/asciidoc/topics/con_store_migrator.adoc
  documentation/src/main/asciidoc/topics/config_examples/persistence_rocksdb_example.xml
  documentation/src/main/asciidoc/topics/dependencies_maven/persistence_storemigrator.xml
  documentation/src/main/asciidoc/topics/persistence_storemigrator.adoc
  documentation/src/main/asciidoc/topics/proc_configuring_store_migrator.adoc
  documentation/src/main/asciidoc/topics/proc_getting_store_migrator.adoc
  documentation/src/main/asciidoc/topics/proc_migrating_cache_stores.adoc
  documentation/src/main/asciidoc/topics/ref_cache_store_rocksdb.adoc
  documentation/src/main/asciidoc/topics/ref_store_migrator_properties.adoc
Labels: Documentation

#7953 ISPN-11263 CDI extension doc updates
  documentation/src/main/asciidoc/stories/assembly_cdi.adoc
  documentation/src/main/asciidoc/stories/assembly_developing.adoc
  documentation/src/main/asciidoc/topics/cdi.adoc
  documentation/src/main/asciidoc/topics/dependencies_maven/cdi_embedded.xml
  documentation/src/main/asciidoc/topics/dependencies_maven/cdi_remote.xml
  documentation/src/main/asciidoc/topics/proc_cdi_cache_events.adoc
  documentation/src/main/asciidoc/topics/proc_cdi_injecting_embedded.adoc
  documentation/src/main/asciidoc/topics/proc_cdi_injecting_remote.adoc
  documentation/src/main/asciidoc/topics/proc_cdi_jcaching_annotations.adoc
  documentation/src/main/asciidoc/topics/ref_cdi_dependencies.adoc
Labels: Documentation

#7961 [10.1.x] ISPN-11263 CDI extension doc updates
  documentation/src/main/asciidoc/stories/assembly_cdi.adoc
  documentation/src/main/asciidoc/stories/assembly_developing.adoc
  documentation/src/main/asciidoc/topics/cdi.adoc
  documentation/src/main/asciidoc/topics/dependencies_maven/cdi_embedded.xml
  documentation/src/main/asciidoc/topics/dependencies_maven/cdi_remote.xml
  documentation/src/main/asciidoc/topics/proc_cdi_cache_events.adoc
  documentation/src/main/asciidoc/topics/proc_cdi_injecting_embedded.adoc
  documentation/src/main/asciidoc/topics/proc_cdi_injecting_remote.adoc
  documentation/src/main/asciidoc/topics/proc_cdi_jcaching_annotations.adoc
  documentation/src/main/asciidoc/topics/ref_cdi_dependencies.adoc
Labels: Documentation

#7939 [10.1.x] ISPN-10842 store migrator docs
  documentation/src/main/asciidoc/stories/assembly_migrating_cache_stores.adoc
  documentation/src/main/asciidoc/stories/assembly_migrating_data.adoc
  documentation/src/main/asciidoc/titles/upgrading/stories.adoc
  documentation/src/main/asciidoc/topics/con_store_migrator.adoc
  documentation/src/main/asciidoc/topics/config_examples/persistence_rocksdb_example.xml
  documentation/src/main/asciidoc/topics/dependencies_maven/persistence_storemigrator.xml
  documentation/src/main/asciidoc/topics/persistence_storemigrator.adoc
  documentation/src/main/asciidoc/topics/proc_configuring_store_migrator.adoc
  documentation/src/main/asciidoc/topics/proc_getting_store_migrator.adoc
  documentation/src/main/asciidoc/topics/proc_migrating_cache_stores.adoc
  documentation/src/main/asciidoc/topics/ref_cache_store_rocksdb.adoc
  documentation/src/main/asciidoc/topics/ref_store_migrator_properties.adoc
Labels: Documentation

#7960 ISPN-11386 Use blocking thread pool in Persistent preload
  core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java
Labels: Trivial :-)

#7937 ISPN-11376 Deprecate JGroupsChannelLookup
  core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsChannelLookup.java
Labels: Trivial :-)

#7957 ISPN-11383 upgrade spring versions
  build-configuration/pom.xml
Labels: Trivial :-)

#7959 [10.1.x] ISPN-11383 upgrade spring versions
  build-configuration/pom.xml
Labels: Backport

#7932 [10.1.x] ISPN-11280 ConcurrentModificationException in ConditionFuture
  core/src/main/java/org/infinispan/util/concurrent/ConditionFuture.java
  core/src/test/java/org/infinispan/test/Exceptions.java
  core/src/test/java/org/infinispan/util/concurrent/ConditionFutureTest.java
Labels: Backport

#7938 ISPN-11377 Change default flow control back to UFC/MFC
  core/src/main/resources/default-configs/default-jgroups-azure.xml
  core/src/main/resources/default-configs/default-jgroups-ec2.xml
  core/src/main/resources/default-configs/default-jgroups-google.xml
  core/src/main/resources/default-configs/default-jgroups-kubernetes.xml
  core/src/main/resources/default-configs/default-jgroups-tcp.xml
  core/src/main/resources/default-configs/default-jgroups-udp.xml
  core/src/test/resources/configs/config-with-jgroups-stack.xml
  core/src/test/resources/configs/unified/10.0.xml
  core/src/test/resources/configs/unified/10.1.xml
  core/src/test/resources/configs/unified/11.0.xml
  core/src/test/resources/configs/xsite/bridge.xml
  core/src/test/resources/configs/xsite/xsite-inline-test.xml
  core/src/test/resources/stacks/tcp.xml
  core/src/test/resources/stacks/tcp_mping/tcp1.xml
  core/src/test/resources/stacks/tcp_mping/tcp2.xml
  core/src/test/resources/stacks/udp.xml
  documentation/src/main/asciidoc/topics/config_examples/config_inline_jgroups.xml
  documentation/src/main/asciidoc/topics/config_examples/jgroups_default_stack.xml
  documentation/src/main/asciidoc/topics/config_examples/tcp_ping.xml
  documentation/src/main/asciidoc/topics/config_examples/wfly_jgroups.xml
  hibernate/cache-commons/src/test/resources/2lc-test-tcp.xml
  integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node0.xml
  integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node1-fail.xml
  integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node1.xml
  integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-node0.xml
  integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-node1.xml
  integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-user-node0.xml
  integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-prop-handler-node0.xml
  integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-prop-handler-node1.xml
  integrationtests/wildfly-modules/src/test/resources/as-config/standalone/configuration/standalone-test.xml
  persistence/jdbc/src/test/resources/configs/as7/jdbc-standalone.xml
  server/runtime/src/test/resources/configuration/test-jgroups-tcp.xml
  tools/src/test/resources/udp.xml
  wildfly/jgroups/src/main/resources/jgroups-defaults.xml
  wildfly/jgroups/src/main/resources/subsystem-templates/cloud-jgroups.xml
  wildfly/jgroups/src/main/resources/subsystem-templates/infinispan-jgroups.xml
  wildfly/jgroups/src/test/resources/org/infinispan/server/jgroups/subsystem/subsystem-infinispan_server_jgroups-10_0.xml
  wildfly/jgroups/src/test/resources/org/infinispan/server/jgroups/subsystem/subsystem-infinispan_server_jgroups-10_1.xml
  wildfly/jgroups/src/test/resources/org/infinispan/server/jgroups/subsystem/subsystem-infinispan_server_jgroups-11_0.xml
  wildfly/jgroups/src/test/resources/org/infinispan/server/jgroups/subsystem/subsystem-infinispan_server_jgroups-9_4.xml
Labels: Performance ACK required!

#7948 [10.1.x] ISPN-11377 Change default flow control back to UFC/MFC
  core/src/main/resources/default-configs/default-jgroups-azure.xml
  core/src/main/resources/default-configs/default-jgroups-ec2.xml
  core/src/main/resources/default-configs/default-jgroups-google.xml
  core/src/main/resources/default-configs/default-jgroups-kubernetes.xml
  core/src/main/resources/default-configs/default-jgroups-tcp.xml
  core/src/main/resources/default-configs/default-jgroups-udp.xml
  core/src/test/resources/configs/config-with-jgroups-stack.xml
  core/src/test/resources/configs/unified/10.0.xml
  core/src/test/resources/configs/unified/10.1.xml
  core/src/test/resources/configs/xsite/bridge.xml
  core/src/test/resources/configs/xsite/xsite-inline-test.xml
  core/src/test/resources/stacks/tcp.xml
  core/src/test/resources/stacks/tcp_mping/tcp1.xml
  core/src/test/resources/stacks/tcp_mping/tcp2.xml
  core/src/test/resources/stacks/udp.xml
  documentation/src/main/asciidoc/topics/config_examples/config_inline_jgroups.xml
  documentation/src/main/asciidoc/topics/config_examples/jgroups_default_stack.xml
  documentation/src/main/asciidoc/topics/config_examples/tcp_ping.xml
  documentation/src/main/asciidoc/topics/config_examples/wfly_jgroups.xml
  hibernate/cache-commons/src/test/resources/2lc-test-tcp.xml
  integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node0.xml
  integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node1-fail.xml
  integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node1.xml
  integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-node0.xml
  integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-node1.xml
  integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-user-node0.xml
  integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-prop-handler-node0.xml
  integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-prop-handler-node1.xml
  integrationtests/wildfly-modules/src/test/resources/as-config/standalone/configuration/standalone-test.xml
  persistence/jdbc/src/test/resources/configs/as7/jdbc-standalone.xml
  server/runtime/src/test/resources/configuration/test-jgroups-tcp.xml
  tools/src/test/resources/udp.xml
  wildfly/jgroups/src/main/resources/jgroups-defaults.xml
  wildfly/jgroups/src/main/resources/subsystem-templates/cloud-jgroups.xml
  wildfly/jgroups/src/main/resources/subsystem-templates/infinispan-jgroups.xml
  wildfly/jgroups/src/test/resources/org/infinispan/server/jgroups/subsystem/subsystem-infinispan_server_jgroups-10_0.xml
  wildfly/jgroups/src/test/resources/org/infinispan/server/jgroups/subsystem/subsystem-infinispan_server_jgroups-10_1.xml
  wildfly/jgroups/src/test/resources/org/infinispan/server/jgroups/subsystem/subsystem-infinispan_server_jgroups-9_4.xml
Labels: Backport

#7947 [9.4.x] ISPN-11377 Change default flow control back to UFC/MFC
  cloud/src/main/resources/default-configs/default-jgroups-ec2.xml
  cloud/src/main/resources/default-configs/default-jgroups-google.xml
  cloud/src/main/resources/default-configs/default-jgroups-kubernetes.xml
  core/src/main/resources/default-configs/default-jgroups-tcp.xml
  core/src/main/resources/default-configs/default-jgroups-udp.xml
  core/src/test/resources/configs/xsite/bridge.xml
  core/src/test/resources/stacks/tcp.xml
  core/src/test/resources/stacks/tcp_mping/tcp1.xml
  core/src/test/resources/stacks/tcp_mping/tcp2.xml
  core/src/test/resources/stacks/udp.xml
  demos/gui/src/main/release/etc/config/jgroups-relay1.xml
  demos/gui/src/main/release/etc/config/jgroups-relay2.xml
  demos/gui/src/main/release/etc/config/jgroups-tcp.xml
  documentation/src/main/asciidoc/topics/jgroups/jgroups_default_stack.adoc
  hibernate/cache-commons/src/test/resources/2lc-test-tcp.xml
  integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node0.xml
  integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node1-fail.xml
  integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node1.xml
  integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-node0.xml
  integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-node1.xml
  integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-user-node0.xml
  integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-prop-handler-node0.xml
  integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-prop-handler-node1.xml
  integrationtests/wildfly-modules/src/test/resources/as-config/standalone/configuration/standalone-test.xml
  persistence/jdbc/src/test/resources/configs/as7/jdbc-standalone.xml
  server/integration/jgroups/src/main/resources/jgroups-defaults.xml
  server/integration/jgroups/src/main/resources/subsystem-templates/infinispan-jgroups.xml
Labels: Backport

#7958 [9.4.x] ISPN-11383 upgrade spring versions
  build-configuration/pom.xml
Labels: Backport
