Repository infinispan/infinispan, pull requests merged in 2021-03, with the labels that each got.

#9083 ISPN-12773 query doc fixes
  documentation/src/main/asciidoc/topics/ref_query_embedded.adoc
  documentation/src/main/asciidoc/topics/ref_query_remote.adoc
Labels: Documentation, Trivial :-)

#9104 [9.4.x] ISPN-12807 Simple cache does not update eviction statistics
  core/src/main/java/org/infinispan/eviction/impl/EvictionManagerImpl.java
  core/src/main/java/org/infinispan/factories/InterceptorChainFactory.java
  core/src/main/java/org/infinispan/stats/impl/StatsCollector.java
  core/src/test/java/org/infinispan/api/SimpleCacheTest.java
Labels: Backport

#9111 ISPN-12818 HotRod client leaks memory with an exception until the soc…
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/HotRodOperation.java
Labels: Trivial :-)

#9112 [11.0.x] ISPN-12818 HotRod client leaks memory with an exception until the soc…
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/HotRodOperation.java
Labels: Backport

#9113 [9.4.x] ISPN-12818 HotRod client leaks memory with an exception until the soc…
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/HotRodOperation.java
Labels: Backport

#9110 ISPN-12817 Fix path when packaging licenses
  distribution/package.xml
Labels: Trivial :-)

#9109 ISPN-12816 Create alias for GPL v2 + CE license
  distribution/src/main/resources/template/licenses.xsl
Labels: Trivial :-)

#9064 ISPN-12050 consistency edits for Query docs
  query/src/main/java/org/infinispan/query/Indexer.java
  query/src/main/java/org/infinispan/query/Search.java
  query/src/main/java/org/infinispan/query/Transformable.java
  query/src/main/java/org/infinispan/query/Transformer.java
  query/src/main/java/org/infinispan/query/package-info.java
Labels: Documentation

#9115 ISPN-12819 CLI invalid connection string results in zero exit code
  cli/src/main/java/org/infinispan/cli/commands/CLI.java
Labels: Trivial :-)

#9100 ISPN-128806 BlockingManagerImpl#thenRunBlocking doesn't join
  core/src/main/java/org/infinispan/util/concurrent/BlockingManagerImpl.java
Labels: Trivial :-)

#9107 ISPN-12261 protocol mgmt doc update
  documentation/src/main/asciidoc/stories/assembly_server_endpoint_ipfilter.adoc
  documentation/src/main/asciidoc/topics/proc_server_ipfilter_cli.adoc
  documentation/src/main/asciidoc/topics/ref_server_ipfilter.adoc
  documentation/src/main/asciidoc/topics/ref_server_ipfilter_cli.adoc
Labels: Documentation, Trivial :-)

#9082 ISPN-12771 Clarify HR onaccess
  documentation/src/main/asciidoc/topics/proc_creating_caches_hotrod_onaccess.adoc
Labels: Documentation, Trivial :-)

#9079 ISPN-12603 link to image getting started
  documentation/src/main/asciidoc/stories/assembly_server_getting_started.adoc
Labels: Documentation

#9121 ISPN-12821 CLI connection url does not support url-encoding in auth s…
  cli/src/main/java/org/infinispan/cli/connection/rest/RestConnector.java
Labels: Trivial :-)

#9120 ISPN-12820 JdbcStringBasedStore closed statement on exceptional code …
  persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/stringbased/JdbcStringBasedStore.java
Labels: Trivial :-)

#9119 [11.0.x] ISPN-12820 JdbcStringBasedStore closed statement on exceptional code …
  persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/stringbased/JdbcStringBasedStore.java
Labels: Backport, Trivial :-)

#9128 ISPN-12827 upgrade to console 0.13.2.Final
  build-configuration/pom.xml
Labels: Trivial :-)

#9102 ISPN-12812 Set the server cache manager class loader
  commons/all/src/main/java/org/infinispan/commons/configuration/ClassAllowList.java
  commons/all/src/main/java/org/infinispan/commons/configuration/ClassWhiteList.java
  commons/all/src/main/java/org/infinispan/commons/marshall/CheckedInputStream.java
  core/src/main/java/org/infinispan/configuration/global/AllowListConfiguration.java
  core/src/main/java/org/infinispan/configuration/global/AllowListConfigurationBuilder.java
  core/src/main/java/org/infinispan/configuration/global/SerializationConfigurationBuilder.java
  core/src/main/java/org/infinispan/configuration/parsing/ConfigurationBuilderHolder.java
  server/runtime/src/main/java/org/infinispan/server/Server.java
  server/tests/src/test/java/org/infinispan/server/extensions/ExtensionsIT.java
  server/tests/src/test/java/org/infinispan/server/extensions/Person.java
  server/tests/src/test/java/org/infinispan/server/extensions/PojoMarshalling.java
  server/tests/src/test/resources/configuration/cache-container/clustered.xml
Labels: Question

#9127 [12.0.x] ISPN-12808 Per-cache Hot Rod client marshaller
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/DataFormat.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/Configuration.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/RemoteCacheConfiguration.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/RemoteCacheConfigurationBuilder.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/ConfigurationProperties.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/DelegatingRemoteCache.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/InternalRemoteCache.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheImpl.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/iteration/RemotePublisher.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/configuration/ConfigurationTest.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/marshall/MarshallerPerCacheTest.java
  client/hotrod-client/src/test/resources/hotrod-client-percache.properties
Labels: Backport

#9136 [12.0.x] ISPN-12833 Remove outdated integrations from the docs
  documentation/src/main/asciidoc/stories/assembly_integrating.adoc
  documentation/src/main/asciidoc/topics/code_examples/LuceneDirectoryExampleQuery.java
  documentation/src/main/asciidoc/topics/config_examples/lucene_indexes_data.xml
  documentation/src/main/asciidoc/topics/config_examples/lucene_indexes_locking.xml
  documentation/src/main/asciidoc/topics/config_examples/lucene_indexes_metadata.xml
  documentation/src/main/asciidoc/topics/config_examples/lucene_key_string_mapper.xml
  documentation/src/main/asciidoc/topics/dependencies_maven/hibernate_directory_provider.xml
  documentation/src/main/asciidoc/topics/dependencies_maven/lucene_directory.xml
  documentation/src/main/asciidoc/topics/integrations_apache_lucene.adoc
  documentation/src/main/asciidoc/topics/integrations_hibernate_ogm.adoc
  documentation/src/main/asciidoc/topics/integrations_hibernate_search.adoc
Labels: Backport

#9040 ISPN-12628 All REST response descriptions should contain possible HTTP response codes
  documentation/src/main/asciidoc/stories/assembly_rest_api.adoc
  documentation/src/main/asciidoc/topics/ref_rest_cache_managers.adoc
  documentation/src/main/asciidoc/topics/ref_rest_caches.adoc
  documentation/src/main/asciidoc/topics/ref_rest_clusters.adoc
  documentation/src/main/asciidoc/topics/ref_rest_counters.adoc
  documentation/src/main/asciidoc/topics/ref_rest_logging.adoc
  documentation/src/main/asciidoc/topics/ref_rest_protobuf.adoc
  documentation/src/main/asciidoc/topics/ref_rest_rolling.adoc
  documentation/src/main/asciidoc/topics/ref_rest_server_tasks.adoc
  documentation/src/main/asciidoc/topics/ref_rest_servers.adoc
  documentation/src/main/asciidoc/topics/ref_rest_xsite.adoc
  documentation/src/main/asciidoc/topics/rest_examples/get_v2_tasks_exec.adoc
  server/rest/src/main/java/org/infinispan/rest/resources/BackupManagerResource.java
  server/rest/src/main/java/org/infinispan/rest/resources/BaseCacheResource.java
  server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
  server/rest/src/main/java/org/infinispan/rest/resources/ProtobufResource.java
  server/rest/src/main/java/org/infinispan/rest/resources/SearchAdminResource.java
  server/rest/src/main/java/org/infinispan/rest/resources/XSiteResource.java
Labels: Documentation

#9071 ISPN-12757 PartitionHandlingManagerImpl is unable to release locks
  core/src/main/java/org/infinispan/partitionhandling/impl/PartitionHandlingManagerImpl.java
  core/src/test/java/org/infinispan/lock/ExplicitUnlockTest.java
  core/src/test/java/org/infinispan/partitionhandling/PessimisticTxPartitionHandlingReleaseLockTest.java
Labels: Trivial :-)

#9151 ISPN-12848 Upgrade jboss-marshalling to 2.0.11.Final
  build-configuration/pom.xml
Labels: Trivial :-)

#9152 ISPN-12849 & ISPN-12851 Upgrade xstream & snakeyaml
  pom.xml
Labels: Trivial :-)

#9149 ISPN-12836 Implicit Authorization documentation
  cli/src/main/resources/help/user.adoc
  documentation/src/main/asciidoc/stories/assembly_authorization.adoc
  documentation/src/main/asciidoc/stories/assembly_cli_command_reference.adoc
  documentation/src/main/asciidoc/stories/assembly_security_authorization.adoc
  documentation/src/main/asciidoc/stories/assembly_server_authorization.adoc
  documentation/src/main/asciidoc/stories/assembly_server_endpoint_authentication.adoc
  documentation/src/main/asciidoc/stories/assembly_server_logging.adoc
  documentation/src/main/asciidoc/stories/assembly_server_monitoring.adoc
  documentation/src/main/asciidoc/stories/assembly_server_security.adoc
  documentation/src/main/asciidoc/titles/security/security.asciidoc
  documentation/src/main/asciidoc/titles/security/stories.adoc
  documentation/src/main/asciidoc/titles/server/stories.adoc
  documentation/src/main/asciidoc/topics/con_access_logs.adoc
  documentation/src/main/asciidoc/topics/con_audit_logs.adoc
  documentation/src/main/asciidoc/topics/con_cache_authorization.adoc
  documentation/src/main/asciidoc/topics/con_server_logs.adoc
  documentation/src/main/asciidoc/topics/config_examples/cache_authorization.xml
  documentation/src/main/asciidoc/topics/config_examples/infinispan_authz_custom.xml
  documentation/src/main/asciidoc/topics/config_examples/infinispan_authz_default.xml
  documentation/src/main/asciidoc/topics/config_examples/security_combined_permission.xml
  documentation/src/main/asciidoc/topics/config_examples/server_audit_custom.xml
  documentation/src/main/asciidoc/topics/config_examples/server_audit_logging.xml
  documentation/src/main/asciidoc/topics/proc_configuring_audit_logs.adoc
  documentation/src/main/asciidoc/topics/proc_configuring_authz_declarative.adoc
  documentation/src/main/asciidoc/topics/proc_configuring_log_properties.adoc
  documentation/src/main/asciidoc/topics/proc_customizing_audit_logs.adoc
  documentation/src/main/asciidoc/topics/proc_customizing_authorization.adoc
  documentation/src/main/asciidoc/topics/proc_enabling_access_logs.adoc
  documentation/src/main/asciidoc/topics/proc_enabling_audit_logs.adoc
  documentation/src/main/asciidoc/topics/proc_enabling_default_authorization.adoc
  documentation/src/main/asciidoc/topics/proc_enabling_json_logging.adoc
  documentation/src/main/asciidoc/topics/ref_authz_default_roles.adoc
  documentation/src/main/asciidoc/topics/ref_authz_permissions.adoc
  documentation/src/main/asciidoc/topics/ref_authz_role_mappers.adoc
  documentation/src/main/asciidoc/topics/ref_role_mappers.adoc
  documentation/src/main/asciidoc/topics/upgrading.adoc
Labels: Documentation

#9154 ISPN-12852 Remove duplicated opentracing dependencies
  pom.xml
Labels: Trivial :-)

#9159 ISPN-12862 Upgrade server to console 0.14.Final
  build-configuration/pom.xml
Labels: Trivial :-)

#9162 ISPN-12864 test driver should be test scope
  spring/spring-boot/remote/pom.xml
Labels: Trivial :-)

#9170 ISPN-12877 ConfigurationSerializerTest.testParser fails randomly
  counter/src/test/resources/config/counters-9.4.xml
Labels: Test fix, Trivial :-)

#9171 ISPN-12878 LicenseTest.testLicense fails regex No match found
  server/runtime/src/test/java/org/infinispan/server/license/LicenseTest.java
Labels: Test fix

#9166 ISPN-12870 Add mxparser license
  distribution/src/main/resources/licenses/indiana university extreme! lab software license, version 1.1.1 - license.txt
  distribution/src/main/resources/licenses/indiana university extreme! lab software license, vesion 1.1.1 - license.txt
  distribution/src/main/resources/template/licenses.xsl
  server/runtime/build.xml
Labels: Trivial :-)

#9177 ISPN-12886 Fix Stream iteration Undelievered test failures
  core/src/main/java/org/infinispan/reactive/RxJavaInterop.java
  core/src/main/java/org/infinispan/reactive/publisher/impl/ClusterPublisherManagerImpl.java
  core/src/main/java/org/infinispan/reactive/publisher/impl/PartitionAwareClusterPublisherManager.java
Labels: Test fix

#9188 ISPN-12889 ClusteredLockTest.destroyLock random failures
  core/src/test/java/org/infinispan/util/CoreTestBlockHoundIntegration.java
  lock/src/test/java/org/infinispan/lock/ClusteredLockTest.java
Labels: Test fix, Trivial :-)

#9190 ISPN-12892 Exclude MXParser dependency
  server/core/pom.xml
Labels: Trivial :-)

#9189 ISPN-12891 CertWithoutAuthenticationTest using the wrong configuration
  server/tests/src/test/java/org/infinispan/server/security/CertWithoutAuthenticationIT.java
Labels: Trivial :-)

#9179 ISPN-12888 CLI batch failuires result in zero exit code
  cli/src/main/java/org/infinispan/cli/commands/CLI.java
Labels: Trivial :-)

#9195 ISPN-12893 Fix SiteDownFailoverTest.ThreadLeakChecker
  server/core/src/main/java/org/infinispan/server/core/transport/NettyTransport.java
Labels: Test fix, Trivial :-)

#9200 ISPN-12890 DistributedStreamIterator tests can throw unhandled except…
  core/src/main/java/org/infinispan/reactive/publisher/impl/InnerPublisherSubscription.java
Labels: Test fix

#9198 ISPN-12896 updating docs for xml fragments
  documentation/src/main/asciidoc/topics/code_examples/ConfigSingleFileStoreRemote.java
  documentation/src/main/asciidoc/topics/code_examples/HotRodIndexRemoteCache.java
  documentation/src/main/asciidoc/topics/con_ispn_subsystem.adoc
  documentation/src/main/asciidoc/topics/config_examples/clustered_counters_config.xml
  documentation/src/main/asciidoc/topics/config_examples/clustered_lock_manager.xml
  documentation/src/main/asciidoc/topics/config_examples/custom_marshaller.xml
  documentation/src/main/asciidoc/topics/config_examples/deserialization_allowlist.xml
  documentation/src/main/asciidoc/topics/config_examples/dnsping.xml
  documentation/src/main/asciidoc/topics/config_examples/endpoints_hotrod_connector.xml
  documentation/src/main/asciidoc/topics/config_examples/endpoints_rest_connector.xml
  documentation/src/main/asciidoc/topics/config_examples/indexed_entities_proto.xml
  documentation/src/main/asciidoc/topics/config_examples/indexing_dist_cache_books.xml
  documentation/src/main/asciidoc/topics/config_examples/indexing_enable.xml
  documentation/src/main/asciidoc/topics/config_examples/indexing_entities.xml
  documentation/src/main/asciidoc/topics/config_examples/indexing_file_system.xml
  documentation/src/main/asciidoc/topics/config_examples/indexing_index_reader.xml
  documentation/src/main/asciidoc/topics/config_examples/indexing_index_writer.xml
  documentation/src/main/asciidoc/topics/config_examples/indexing_jvm_heap.xml
  documentation/src/main/asciidoc/topics/config_examples/indexing_key_transformer.xml
  documentation/src/main/asciidoc/topics/config_examples/indexing_person_cache.xml
  documentation/src/main/asciidoc/topics/config_examples/indexing_proto_cache_books.xml
  documentation/src/main/asciidoc/topics/config_examples/indexing_repl_cache_books.xml
  documentation/src/main/asciidoc/topics/config_examples/infinispan_authz_custom.xml
  documentation/src/main/asciidoc/topics/config_examples/infinispan_authz_default.xml
  documentation/src/main/asciidoc/topics/config_examples/infinispan_distributed_cache.xml
  documentation/src/main/asciidoc/topics/config_examples/infinispan_distributed_cache_books.xml
  documentation/src/main/asciidoc/topics/config_examples/infinispan_eviction_passivation.xml
  documentation/src/main/asciidoc/topics/config_examples/ispn_second_level_cache.xml
  documentation/src/main/asciidoc/topics/config_examples/ispn_subsystem.xml
  documentation/src/main/asciidoc/topics/config_examples/ispn_subsystem_containers.xml
  documentation/src/main/asciidoc/topics/config_examples/jboss_user_marshaller.xml
  documentation/src/main/asciidoc/topics/config_examples/jdbc_ping.xml
  documentation/src/main/asciidoc/topics/config_examples/jgroups_external_stack.xml
  documentation/src/main/asciidoc/topics/config_examples/max_size_offheap.xml
  documentation/src/main/asciidoc/topics/config_examples/mping.xml
  documentation/src/main/asciidoc/topics/config_examples/non_indexed_entities_proto.xml
  documentation/src/main/asciidoc/topics/config_examples/persistence_unit_example.xml
  documentation/src/main/asciidoc/topics/config_examples/ping.xml
  documentation/src/main/asciidoc/topics/config_examples/serialization_marshaller.xml
  documentation/src/main/asciidoc/topics/config_examples/server_network_anyaddress.xml
  documentation/src/main/asciidoc/topics/config_examples/server_network_fallback.xml
  documentation/src/main/asciidoc/topics/config_examples/server_network_global.xml
  documentation/src/main/asciidoc/topics/config_examples/server_network_inetaddress.xml
  documentation/src/main/asciidoc/topics/config_examples/server_network_linklocal.xml
  documentation/src/main/asciidoc/topics/config_examples/server_network_loopback.xml
  documentation/src/main/asciidoc/topics/config_examples/server_network_matchaddress.xml
  documentation/src/main/asciidoc/topics/config_examples/server_network_matchhost.xml
  documentation/src/main/asciidoc/topics/config_examples/server_network_matchinterface.xml
  documentation/src/main/asciidoc/topics/config_examples/server_network_nonloopback.xml
  documentation/src/main/asciidoc/topics/config_examples/server_network_sitelocal.xml
  documentation/src/main/asciidoc/topics/config_examples/simple_cache.xml
  documentation/src/main/asciidoc/topics/config_examples/tcpgossip.xml
  documentation/src/main/asciidoc/topics/config_examples/tcpping.xml
  documentation/src/main/asciidoc/topics/config_examples/xsite_backup_timeout.xml
  documentation/src/main/asciidoc/topics/proc_cli_configuring_media_types.adoc
  documentation/src/main/asciidoc/topics/proc_creating_caches_hotrod_onaccess.adoc
  documentation/src/main/asciidoc/topics/ref_query_embedded.adoc
  documentation/src/main/asciidoc/topics/ref_query_remote.adoc
Labels: Documentation

#9163 ISPN-12836 authz docs for user create
  documentation/src/main/asciidoc/stories/assembly_authorization.adoc
  documentation/src/main/asciidoc/stories/assembly_cli_starting.adoc
  documentation/src/main/asciidoc/stories/assembly_server_endpoint_authentication.adoc
  documentation/src/main/asciidoc/stories/assembly_server_getting_started.adoc
  documentation/src/main/asciidoc/stories/assembly_server_scripts.adoc
  documentation/src/main/asciidoc/topics/cmd_examples/user_tool_authz_nix.adoc
  documentation/src/main/asciidoc/topics/cmd_examples/user_tool_authz_win.adoc
  documentation/src/main/asciidoc/topics/config_examples/application.properties
  documentation/src/main/asciidoc/topics/config_examples/endpoints_authentication_disabled.xml
  documentation/src/main/asciidoc/topics/proc_adding_deserialization_allowlist.adoc
  documentation/src/main/asciidoc/topics/proc_adding_server_tasks.adoc
  documentation/src/main/asciidoc/topics/proc_cli_adding_scripts.adoc
  documentation/src/main/asciidoc/topics/proc_cli_creating_users.adoc
  documentation/src/main/asciidoc/topics/proc_configuring_hotrod_marshalling.adoc
  documentation/src/main/asciidoc/topics/proc_configuring_script_manager_role.adoc
  documentation/src/main/asciidoc/topics/proc_disabling_authentication.adoc
  documentation/src/main/asciidoc/topics/proc_disabling_authorization.adoc
  documentation/src/main/asciidoc/topics/proc_disabling_server_authentication.adoc
  documentation/src/main/asciidoc/topics/proc_enabling_default_authorization.adoc
  documentation/src/main/asciidoc/topics/proc_server_user_tool.adoc
  documentation/src/main/asciidoc/topics/proc_starting_server.adoc
  documentation/src/main/asciidoc/topics/proc_using_custom_marshallers.adoc
  documentation/src/main/asciidoc/topics/proc_using_java_serialization.adoc
  documentation/src/main/asciidoc/topics/proc_using_jboss_marshaller.adoc
  documentation/src/main/asciidoc/topics/proc_using_kyro_marshaller.adoc
  documentation/src/main/asciidoc/topics/proc_using_protostuff_marshaller.adoc
  documentation/src/main/asciidoc/topics/ref_authz_default_roles.adoc
  documentation/src/main/asciidoc/topics/ref_authz_permissions.adoc
  documentation/src/main/asciidoc/topics/ref_authz_role_mappers.adoc
  documentation/src/main/asciidoc/topics/ref_query_remote.adoc
  documentation/src/main/asciidoc/topics/ref_user_roles_permissions.adoc
Labels: Documentation

#9199 ISPN-12897 bloom filter doc edits
  documentation/src/main/asciidoc/stories/assembly_hotrod_client_configuration.adoc
  documentation/src/main/asciidoc/topics/code_examples/HotRodNearCaching.java
  documentation/src/main/asciidoc/topics/con_near_caches.adoc
  documentation/src/main/asciidoc/topics/proc_configuring_hotrod_nearcaching.adoc
Labels: Documentation

#9192 [11.0.x] ISPN-12787 Non-transactional cache needs to be invalidated after comm…
  hibernate/cache-commons/src/main/java/org/infinispan/hibernate/cache/commons/access/AccessDelegate.java
  hibernate/cache-commons/src/main/java/org/infinispan/hibernate/cache/commons/access/InvalidationCacheAccessDelegate.java
  hibernate/cache-commons/src/main/java/org/infinispan/hibernate/cache/commons/access/NonStrictAccessDelegate.java
  hibernate/cache-commons/src/main/java/org/infinispan/hibernate/cache/commons/access/NonTxInvalidationCacheAccessDelegate.java
  hibernate/cache-commons/src/main/java/org/infinispan/hibernate/cache/commons/access/PutFromLoadValidator.java
  hibernate/cache-commons/src/main/java/org/infinispan/hibernate/cache/commons/access/TombstoneAccessDelegate.java
  hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/InvalidationTest.java
  hibernate/cache-v51/src/main/java/org/infinispan/hibernate/cache/v51/access/AbstractAccess.java
  hibernate/cache-v53/src/main/java/org/infinispan/hibernate/cache/v53/impl/AbstractAccess.java
Labels: Backport

#9194 [9.4.x] ISPN-12787 Non-transactional cache needs to be invalidated after comm…
  hibernate/cache-commons/src/main/java/org/infinispan/hibernate/cache/commons/access/AccessDelegate.java
  hibernate/cache-commons/src/main/java/org/infinispan/hibernate/cache/commons/access/InvalidationCacheAccessDelegate.java
  hibernate/cache-commons/src/main/java/org/infinispan/hibernate/cache/commons/access/NonStrictAccessDelegate.java
  hibernate/cache-commons/src/main/java/org/infinispan/hibernate/cache/commons/access/NonTxInvalidationCacheAccessDelegate.java
  hibernate/cache-commons/src/main/java/org/infinispan/hibernate/cache/commons/access/PutFromLoadValidator.java
  hibernate/cache-commons/src/main/java/org/infinispan/hibernate/cache/commons/access/TombstoneAccessDelegate.java
  hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/InvalidationTest.java
  hibernate/cache-v51/src/main/java/org/infinispan/hibernate/cache/v51/access/AbstractAccess.java
  hibernate/cache-v53/src/main/java/org/infinispan/hibernate/cache/v53/impl/AbstractAccess.java
Labels: Backport

#9206 ISPN-12904 Fix RestLoggingResource.testListAppenders failure
  server/tests/src/test/java/org/infinispan/server/functional/RestLoggingResource.java
Labels: Trivial :-)
