Repository infinispan/infinispan, pull requests merged in 2021-09, with the labels that each got.

#9475 ISPN-12598 Log warning when switching to initial server list
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelFactory.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/logging/Log.java
Labels: Trivial :-)

#9523 remove unused asciidoc role attribute
  documentation/src/main/asciidoc/topics/ref_rest_rolling.adoc
Labels: Trivial :-), Documentation

#9517 ISPN-13275 Queries throw NPE with old client
  remote-query/remote-query-client/src/main/java/org/infinispan/query/remote/client/impl/QueryRequest.java
Labels: Trivial :-)

#9521 ISPN-13192 Fix TCP start port
  core/src/test/java/org/infinispan/test/fwk/JGroupsConfigBuilder.java
Labels: Trivial :-)

#9531 ISPN-13291 Upgrade to console 0.15.2.Final
  build-configuration/pom.xml
Labels: Urgent!, Trivial :-)

#9533 ISPN-12974 Add RemoteCacheImpl toString() implementation
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheImpl.java
Labels: Trivial :-)

#9534 ISPN-12937 counter schema docs
  counter/src/main/resources/schema/infinispan-counters-config-13.0.xsd
Labels: Trivial :-), Documentation

#9530 ISPN-13288 correct doc headings
  documentation/src/main/asciidoc/stories/assembly_cdi.adoc
  documentation/src/main/asciidoc/stories/assembly_developing.adoc
  documentation/src/main/asciidoc/topics/cache_api.adoc
  documentation/src/main/asciidoc/topics/locking.adoc
  documentation/src/main/asciidoc/topics/transactions.adoc
Labels: Documentation

#9536 [12.1.x] ISPN-13288 correct doc headings
  documentation/src/main/asciidoc/stories/assembly_cdi.adoc
  documentation/src/main/asciidoc/stories/assembly_developing.adoc
  documentation/src/main/asciidoc/topics/cache_api.adoc
  documentation/src/main/asciidoc/topics/locking.adoc
  documentation/src/main/asciidoc/topics/transactions.adoc
Labels: Trivial :-), Backport, Documentation

#9549 ISPN-13233 Server JSON/YAML docs
  documentation/src/main/asciidoc/topics/json/server_authentication.json
  documentation/src/main/asciidoc/topics/json/server_authentication_endpoints.json
  documentation/src/main/asciidoc/topics/json/server_credentials.json
  documentation/src/main/asciidoc/topics/json/server_credentials_datasource.json
  documentation/src/main/asciidoc/topics/json/server_credentials_ldap.json
  documentation/src/main/asciidoc/topics/json/server_datasources.json
  documentation/src/main/asciidoc/topics/json/server_ipfilter.json
  documentation/src/main/asciidoc/topics/json/server_ldap_realm.json
  documentation/src/main/asciidoc/topics/json/server_ldap_realm_rewriter.json
  documentation/src/main/asciidoc/topics/json/server_properties_realm.json
  documentation/src/main/asciidoc/topics/json/server_token_realm_oauth.json
  documentation/src/main/asciidoc/topics/json/server_truststore_realm.json
  documentation/src/main/asciidoc/topics/ref_server_authentication.adoc
  documentation/src/main/asciidoc/topics/ref_server_credentials.adoc
  documentation/src/main/asciidoc/topics/ref_server_datasources.adoc
  documentation/src/main/asciidoc/topics/ref_server_ipfilter.adoc
  documentation/src/main/asciidoc/topics/ref_server_realm_ldap.adoc
  documentation/src/main/asciidoc/topics/ref_server_realm_ldap_rewrite.adoc
  documentation/src/main/asciidoc/topics/ref_server_realm_property.adoc
  documentation/src/main/asciidoc/topics/ref_server_realm_token.adoc
  documentation/src/main/asciidoc/topics/ref_server_realm_trust.adoc
  documentation/src/main/asciidoc/topics/xml/server_authentication.xml
  documentation/src/main/asciidoc/topics/xml/server_authentication_endpoints.xml
  documentation/src/main/asciidoc/topics/xml/server_credentials_ldap.xml
  documentation/src/main/asciidoc/topics/xml/server_ipfilter.xml
  documentation/src/main/asciidoc/topics/yaml/server_authentication.yaml
  documentation/src/main/asciidoc/topics/yaml/server_authentication_endpoints.yaml
  documentation/src/main/asciidoc/topics/yaml/server_credentials.yaml
  documentation/src/main/asciidoc/topics/yaml/server_credentials_datasource.yaml
  documentation/src/main/asciidoc/topics/yaml/server_credentials_ldap.yaml
  documentation/src/main/asciidoc/topics/yaml/server_datasources.yaml
  documentation/src/main/asciidoc/topics/yaml/server_ipfilter.yaml
  documentation/src/main/asciidoc/topics/yaml/server_ldap_realm.yaml
  documentation/src/main/asciidoc/topics/yaml/server_ldap_realm_rewriter.yaml
  documentation/src/main/asciidoc/topics/yaml/server_properties_realm.yaml
  documentation/src/main/asciidoc/topics/yaml/server_token_realm_oauth.yaml
  documentation/src/main/asciidoc/topics/yaml/server_truststore_realm.yaml
Labels: Documentation

#9553 ISPN-13318 Sql Store jar is not included in server distribution
  persistence/sql/pom.xml
  pom.xml
  server/runtime/pom.xml
Labels: Trivial :-), Changes Required
