Repository infinispan/infinispan, pull requests merged in 2021-12, with the labels that each got.

#9703 ISPN-13511 Stores gets cleared when the cache is deleted even if read…
  core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java
Labels: Trivial :-)

#9697 ISPN-13536 Fix Irac3SitesConflictTest.testConditionalRemove() random …
  core/src/test/java/org/infinispan/xsite/AbstractMultipleSitesTest.java
Labels: Trivial :-), Test fix

#9690 [13.0.x] ISPN-13473 Improve SingleSiteRequest.sitesUnreachable()
  core/src/main/java/org/infinispan/remoting/rpc/RpcManagerImpl.java
  core/src/main/java/org/infinispan/remoting/transport/impl/SiteUnreachableXSiteResponse.java
  core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
  core/src/main/java/org/infinispan/remoting/transport/jgroups/SingleSiteRequest.java
Labels: Trivial :-), Backport

#9704 [13.0.x] ISPN-13511 Stores gets cleared when the cache is deleted even if
  core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java
Labels: Backport

#9685 [13.0.x] ISPN-13519 upgrade console to 0.15.4.Final
  build-configuration/pom.xml
Labels: Urgent!

#9711 [13.0] ISPN-13494 Don't register Elytron's security providers globally
  cli/src/main/java/org/infinispan/cli/user/UserTool.java
  cli/src/test/java/org/infinispan/cli/user/UserToolTest.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/SecurityActions.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelInitializer.java
  commons/all/src/main/java/org/infinispan/commons/util/SaslUtils.java
  server/core/src/main/java/org/infinispan/server/core/security/ServerAuthenticationProvider.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/configuration/Attribute.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/configuration/SaslConfigurationBuilder.java
  server/runtime/src/main/java/org/infinispan/server/SecurityActions.java
  server/runtime/src/main/java/org/infinispan/server/Server.java
  server/runtime/src/main/java/org/infinispan/server/configuration/security/CredentialStoreConfiguration.java
  server/runtime/src/main/java/org/infinispan/server/security/ElytronHTTPAuthenticator.java
  server/runtime/src/main/java/org/infinispan/server/security/ElytronSASLAuthenticationProvider.java
  server/runtime/src/main/java/org/infinispan/server/security/realm/EncryptedPropertiesSecurityRealm.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/TestSystemPropertyNames.java
Labels: Backport

#9712 [12.1] ISPN-13494 Don't register Elytron's security providers globally
  cli/src/main/java/org/infinispan/cli/user/UserTool.java
  cli/src/test/java/org/infinispan/cli/user/UserToolTest.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/SecurityActions.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelInitializer.java
  commons/all/src/main/java/org/infinispan/commons/util/SaslUtils.java
  server/core/src/main/java/org/infinispan/server/core/security/ServerAuthenticationProvider.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/configuration/SaslConfigurationBuilder.java
  server/runtime/src/main/java/org/infinispan/server/SecurityActions.java
  server/runtime/src/main/java/org/infinispan/server/Server.java
  server/runtime/src/main/java/org/infinispan/server/configuration/hotrod/Attribute.java
  server/runtime/src/main/java/org/infinispan/server/configuration/security/CredentialStoreConfiguration.java
  server/runtime/src/main/java/org/infinispan/server/security/ElytronHTTPAuthenticator.java
  server/runtime/src/main/java/org/infinispan/server/security/ElytronSASLAuthenticationProvider.java
  server/runtime/src/main/java/org/infinispan/server/security/realm/EncryptedPropertiesSecurityRealm.java
Labels: Backport

#9700 ISPN-9161 Incorrect description StateTransferManager attributes
  core/src/main/java/org/infinispan/statetransfer/StateTransferManagerImpl.java
  core/src/main/java/org/infinispan/util/logging/Log.java
Labels: Changes Suggested

#9724 [13.0] ISPN-13500 CLI install
  build-configuration/pom.xml
  cli/pom.xml
  cli/src/main/java/org/infinispan/cli/activators/InstallFeatureActivator.java
  cli/src/main/java/org/infinispan/cli/artifacts/AbstractArtifact.java
  cli/src/main/java/org/infinispan/cli/artifacts/Artifact.java
  cli/src/main/java/org/infinispan/cli/artifacts/LocalArtifact.java
  cli/src/main/java/org/infinispan/cli/artifacts/MavenArtifact.java
  cli/src/main/java/org/infinispan/cli/artifacts/MavenSettings.java
  cli/src/main/java/org/infinispan/cli/artifacts/URLArtifact.java
  cli/src/main/java/org/infinispan/cli/commands/Batch.java
  cli/src/main/java/org/infinispan/cli/commands/CLI.java
  cli/src/main/java/org/infinispan/cli/commands/Install.java
  cli/src/main/java/org/infinispan/cli/commands/Patch.java
  cli/src/main/java/org/infinispan/cli/logging/Messages.java
  cli/src/main/java/org/infinispan/cli/patching/PatchTool.java
  cli/src/main/java/org/infinispan/cli/util/Utils.java
  cli/src/main/resources/help/install.adoc
  cli/src/test/java/org/infinispan/cli/patching/PatchToolTest.java
  documentation/src/main/asciidoc/stories/assembly_cli_command_reference.adoc
  pom.xml
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/InfinispanContainer.java
Labels: Backport

#9725 ISPN-13500 Allow install from batches
  cli/src/main/java/org/infinispan/cli/commands/Batch.java
Labels: Trivial :-)

#9701 [11.0.x] ISPN-13445 NearCache factory
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/NearCacheConfiguration.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/NearCacheConfigurationBuilder.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/RemoteCacheConfiguration.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/RemoteCacheConfigurationBuilder.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/ConfigurationProperties.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/near/DefaultNearCacheFactory.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/near/NearCacheFactory.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/near/NearCacheService.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/InvalidatedNearCacheTest.java
Labels: Backport

#9710 [13.0.x] ISPN-13483 Create global commands for site CLI command
  cli/src/main/java/org/infinispan/cli/commands/rest/Site.java
  cli/src/main/java/org/infinispan/cli/resources/ContainerResource.java
  cli/src/main/resources/help/site.adoc
  client/rest-client/src/main/java/org/infinispan/client/rest/RestCacheManagerClient.java
  client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestCacheManagerClientOkHttp.java
  documentation/src/main/asciidoc/topics/proc_cli_xsite_push.adoc
  documentation/src/main/asciidoc/topics/proc_cli_xsite_sites.adoc
  documentation/src/main/asciidoc/topics/ref_rest_xsite_cache_managers.adoc
  server/rest/src/main/java/org/infinispan/rest/resources/XSiteResource.java
  server/rest/src/test/java/org/infinispan/rest/resources/XSiteResourceTest.java
Labels: Backport

#9686 [13.0.x] ConfigurationListener Fixes
  documentation/src/main/asciidoc/topics/ref_rest_cache_managers.adoc
  server/rest/src/main/java/org/infinispan/rest/resources/ContainerResource.java
  server/rest/src/test/java/org/infinispan/rest/resources/ContainerResourceTest.java
Labels: Backport

#9688 ISPN-13488 Fail fast if site connection is down
  core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
Labels: Trivial :-)

#9650 [13.0.x] ISPN-13454 Ickle DELETE should not allow usage of Query.startOffset/maxResults
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/RemoteQueryStringTest.java
  query-core/src/main/java/org/infinispan/query/core/impl/EmbeddedQuery.java
  query-core/src/main/java/org/infinispan/query/core/impl/EmptyResultQuery.java
  query-core/src/main/java/org/infinispan/query/core/impl/HybridQuery.java
  query-core/src/main/java/org/infinispan/query/core/impl/Log.java
  query-core/src/main/java/org/infinispan/query/core/impl/QueryResultImpl.java
  query-dsl/src/main/java/org/infinispan/query/dsl/Query.java
  query-dsl/src/main/java/org/infinispan/query/dsl/QueryResult.java
  query-dsl/src/main/java/org/infinispan/query/dsl/impl/BaseQuery.java
  query/src/main/java/org/infinispan/query/clustered/DistributedIndexedQueryImpl.java
  query/src/main/java/org/infinispan/query/clustered/commandworkers/CQCreateEagerQuery.java
  query/src/main/java/org/infinispan/query/clustered/commandworkers/CQDelete.java
  query/src/main/java/org/infinispan/query/dsl/embedded/impl/SearchQueryBuilder.java
  query/src/main/java/org/infinispan/query/impl/IndexedQuery.java
  query/src/main/java/org/infinispan/query/impl/IndexedQueryImpl.java
  query/src/main/java/org/infinispan/query/logging/Log.java
  query/src/test/java/org/infinispan/query/dsl/embedded/QueryStringTest.java
Labels: Backport

#9726 ISPN-13561 Fix JsonTranscoderTest.testTranscoderTranscode failure
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/event/JsonKeyValueRawEventsTest.java
  server/core/src/test/java/org/infinispan/server/core/dataconversion/JsonTranscoderTest.java
Labels: Trivial :-), Test fix

#9731 ISPN-13563 JGroupsConfigurationBuilder should merge stacks on read()
  core/src/main/java/org/infinispan/configuration/global/JGroupsConfigurationBuilder.java
  core/src/main/java/org/infinispan/configuration/global/StackBuilder.java
  core/src/main/java/org/infinispan/configuration/global/StackConfigurationBuilder.java
  core/src/main/java/org/infinispan/configuration/global/StackFileConfigurationBuilder.java
Labels: Trivial :-), Test fix

#9732 ISPN-13560 Local publisher handler not closed properly
  core/src/main/java/org/infinispan/reactive/publisher/impl/ClusterPublisherManagerImpl.java
  core/src/test/java/org/infinispan/stream/DistributedStreamIteratorTest.java
Labels: Urgent!

#9713 [12.1.x] ISPN-13511 Stores gets cleared when the cache is deleted even if
  core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java
Labels: Backport

#9733 [13.0.x] ISPN-13560 Local publisher handler not closed properly
  core/src/main/java/org/infinispan/reactive/publisher/impl/ClusterPublisherManagerImpl.java
  core/src/test/java/org/infinispan/stream/DistributedStreamIteratorTest.java
Labels: Urgent!, Backport

#9719 ISPN-13553 Netty 4.1.70
  build-configuration/pom.xml
Labels: Changes Suggested

#9741 [13.0] ISPN-13578 Workaround for Elytron not using supplied providers
  server/runtime/src/main/java/org/infinispan/server/SecurityActions.java
  server/runtime/src/main/java/org/infinispan/server/Server.java
Labels: Urgent!

#9740 [12.1] ISPN-13578 Workaround for Elytron not using supplied providers
  server/runtime/src/main/java/org/infinispan/server/SecurityActions.java
  server/runtime/src/main/java/org/infinispan/server/Server.java
Labels: Urgent!

#9739 ISPN-13260 Docs - remove redundant backslash from formulas in the tuning guide
  documentation/src/main/asciidoc/topics/con_calculate_size_data_set.adoc
Labels: Trivial :-), Documentation

#9743 [13.0.x] ISPN-13260 Docs fix -remove redundant backslash from formulas
  documentation/src/main/asciidoc/topics/con_calculate_size_data_set.adoc
Labels: Trivial :-), Backport, Documentation

#9748 ISPN-13586 Upgrade JGroups to 4.2.18.Final
  build-configuration/pom.xml
Labels: Trivial :-)

#9749 [13.0.x] ISPN-13586 Upgrade JGroups to 4.2.18.Final
  build-configuration/pom.xml
Labels: Trivial :-), Backport

#9755 ISPN-13589 Move state from IracManager
  core/src/main/java/org/infinispan/util/concurrent/CountDownRunnable.java
  core/src/main/java/org/infinispan/xsite/irac/DefaultIracManager.java
  core/src/main/java/org/infinispan/xsite/irac/IracManagerKeyChangedState.java
  core/src/main/java/org/infinispan/xsite/irac/IracManagerKeyInfo.java
  core/src/main/java/org/infinispan/xsite/irac/IracManagerKeyInfoImpl.java
  core/src/main/java/org/infinispan/xsite/irac/IracManagerKeyState.java
  core/src/main/java/org/infinispan/xsite/irac/IracManagerStateTransferState.java
  core/src/main/java/org/infinispan/xsite/irac/IracResponseCollector.java
Labels: Trivial :-)

#9752 [13.0.x] ISPN-13588 SIFS startup with a dirty index is really slow
  core/src/main/java/org/infinispan/persistence/sifs/NonBlockingSoftIndexFileStore.java
Labels: Backport

#9758 ISPN-13595 add sectanchors attribute to titles
  documentation/src/main/asciidoc/titles/cli/cli.asciidoc
  documentation/src/main/asciidoc/titles/configuring/configuring.asciidoc
  documentation/src/main/asciidoc/titles/contributing/contributing.asciidoc
  documentation/src/main/asciidoc/titles/developing/developing.asciidoc
  documentation/src/main/asciidoc/titles/embedding/embedding.asciidoc
  documentation/src/main/asciidoc/titles/getting_started/getting_started.asciidoc
  documentation/src/main/asciidoc/titles/hotrod_java/hotrod_java.asciidoc
  documentation/src/main/asciidoc/titles/hotrod_protocol/hotrod_protocol.asciidoc
  documentation/src/main/asciidoc/titles/memcached/memcached.asciidoc
  documentation/src/main/asciidoc/titles/overview/overview.asciidoc
  documentation/src/main/asciidoc/titles/rest/rest.asciidoc
  documentation/src/main/asciidoc/titles/security/security.asciidoc
  documentation/src/main/asciidoc/titles/server/server.asciidoc
  documentation/src/main/asciidoc/titles/spring_boot/starter.asciidoc
  documentation/src/main/asciidoc/titles/tuning/tuning.asciidoc
  documentation/src/main/asciidoc/titles/upgrading/upgrading.asciidoc
  documentation/src/main/asciidoc/titles/xsite/xsite.asciidoc
Labels: Trivial :-), Documentation

#9759 [13.0.x] ISPN-13595 add sectanchors attribute to titles
  documentation/src/main/asciidoc/titles/cli/cli.asciidoc
  documentation/src/main/asciidoc/titles/configuring/configuring.asciidoc
  documentation/src/main/asciidoc/titles/contributing/contributing.asciidoc
  documentation/src/main/asciidoc/titles/developing/developing.asciidoc
  documentation/src/main/asciidoc/titles/embedding/embedding.asciidoc
  documentation/src/main/asciidoc/titles/getting_started/getting_started.asciidoc
  documentation/src/main/asciidoc/titles/hotrod_java/hotrod_java.asciidoc
  documentation/src/main/asciidoc/titles/hotrod_protocol/hotrod_protocol.asciidoc
  documentation/src/main/asciidoc/titles/memcached/memcached.asciidoc
  documentation/src/main/asciidoc/titles/overview/overview.asciidoc
  documentation/src/main/asciidoc/titles/rest/rest.asciidoc
  documentation/src/main/asciidoc/titles/security/security.asciidoc
  documentation/src/main/asciidoc/titles/server/server.asciidoc
  documentation/src/main/asciidoc/titles/spring_boot/starter.asciidoc
  documentation/src/main/asciidoc/titles/tuning/tuning.asciidoc
  documentation/src/main/asciidoc/titles/upgrading/upgrading.asciidoc
  documentation/src/main/asciidoc/titles/xsite/xsite.asciidoc
Labels: Backport, Documentation

#9756 ISPN-13590 include source.version field in migrator example
  documentation/src/main/asciidoc/stories/assembly_migrating_data.adoc
  documentation/src/main/asciidoc/topics/attributes/store_migrator_source_versions.adoc
  documentation/src/main/asciidoc/topics/proc_configuring_store_migrator.adoc
  documentation/src/main/asciidoc/topics/ref_store_migrator_properties.adoc
Labels: Trivial :-), Documentation

#9760 [13.0.x] ISPN-13590 include source.version field in migrator example
  documentation/src/main/asciidoc/stories/assembly_migrating_data.adoc
  documentation/src/main/asciidoc/topics/attributes/store_migrator_source_versions.adoc
  documentation/src/main/asciidoc/topics/proc_configuring_store_migrator.adoc
  documentation/src/main/asciidoc/topics/ref_store_migrator_properties.adoc
Labels: Documentation

#9717 ISPN-13545 Documentation improvements to SQL store configuration
  documentation/src/main/asciidoc/stories/assembly_configuring_persistent_storage.adoc
  documentation/src/main/asciidoc/stories/assembly_server_datasources.adoc
  documentation/src/main/asciidoc/topics/code_examples/PersistenceSqlQuery.java
  documentation/src/main/asciidoc/topics/code_examples/PersistenceSqlTable.java
  documentation/src/main/asciidoc/topics/con_cache_store_sql.adoc
  documentation/src/main/asciidoc/topics/con_shared_cache_stores.adoc
  documentation/src/main/asciidoc/topics/json/persistence_sql_query.json
  documentation/src/main/asciidoc/topics/json/persistence_sql_table.json
  documentation/src/main/asciidoc/topics/json/server_datasources.json
  documentation/src/main/asciidoc/topics/proc_configuring_sql_stores_query.adoc
  documentation/src/main/asciidoc/topics/proc_configuring_sql_stores_table.adoc
  documentation/src/main/asciidoc/topics/proc_server_configuring_datasources.adoc
  documentation/src/main/asciidoc/topics/proc_server_testing_datasources.adoc
  documentation/src/main/asciidoc/topics/proc_server_using_datasources.adoc
  documentation/src/main/asciidoc/topics/ref_cache_store_sql_protobuf_schema.adoc
  documentation/src/main/asciidoc/topics/ref_cache_store_sql_query_parameters.adoc
  documentation/src/main/asciidoc/topics/ref_server_datasources.adoc
  documentation/src/main/asciidoc/topics/ref_sql_store_configuration_examples.adoc
  documentation/src/main/asciidoc/topics/ref_sql_store_troubleshooting.adoc
  documentation/src/main/asciidoc/topics/xml/persistence_sql_query.xml
  documentation/src/main/asciidoc/topics/xml/persistence_sql_table.xml
  documentation/src/main/asciidoc/topics/xml/server_datasources.xml
  documentation/src/main/asciidoc/topics/xml/server_jdbc_cache_stores.xml
  documentation/src/main/asciidoc/topics/yaml/persistence_sql_query.yaml
  documentation/src/main/asciidoc/topics/yaml/persistence_sql_table.yaml
  documentation/src/main/asciidoc/topics/yaml/server_datasources.yaml
Labels: Documentation

#9761 [13.0.x] ISPN-13545 sql store doc improvements
  documentation/src/main/asciidoc/stories/assembly_configuring_persistent_storage.adoc
  documentation/src/main/asciidoc/stories/assembly_server_datasources.adoc
  documentation/src/main/asciidoc/topics/code_examples/PersistenceSqlQuery.java
  documentation/src/main/asciidoc/topics/code_examples/PersistenceSqlTable.java
  documentation/src/main/asciidoc/topics/con_cache_store_sql.adoc
  documentation/src/main/asciidoc/topics/con_shared_cache_stores.adoc
  documentation/src/main/asciidoc/topics/json/persistence_sql_query.json
  documentation/src/main/asciidoc/topics/json/persistence_sql_table.json
  documentation/src/main/asciidoc/topics/json/server_datasources.json
  documentation/src/main/asciidoc/topics/proc_configuring_sql_stores_query.adoc
  documentation/src/main/asciidoc/topics/proc_configuring_sql_stores_table.adoc
  documentation/src/main/asciidoc/topics/proc_server_configuring_datasources.adoc
  documentation/src/main/asciidoc/topics/proc_server_testing_datasources.adoc
  documentation/src/main/asciidoc/topics/proc_server_using_datasources.adoc
  documentation/src/main/asciidoc/topics/ref_cache_store_sql_protobuf_schema.adoc
  documentation/src/main/asciidoc/topics/ref_cache_store_sql_query_parameters.adoc
  documentation/src/main/asciidoc/topics/ref_server_datasources.adoc
  documentation/src/main/asciidoc/topics/ref_sql_store_configuration_examples.adoc
  documentation/src/main/asciidoc/topics/ref_sql_store_troubleshooting.adoc
  documentation/src/main/asciidoc/topics/xml/persistence_sql_query.xml
  documentation/src/main/asciidoc/topics/xml/persistence_sql_table.xml
  documentation/src/main/asciidoc/topics/xml/server_datasources.xml
  documentation/src/main/asciidoc/topics/xml/server_jdbc_cache_stores.xml
  documentation/src/main/asciidoc/topics/yaml/persistence_sql_query.yaml
  documentation/src/main/asciidoc/topics/yaml/persistence_sql_table.yaml
  documentation/src/main/asciidoc/topics/yaml/server_datasources.yaml
Labels: Backport, Documentation

#9734 ISPN-13568 MemcachedFunctionalTest.testTouchWithExpiryUnixTime fix
  commons/all/src/test/java/org/infinispan/commons/time/ControlledTimeService.java
  server/memcached/src/main/java/org/infinispan/server/memcached/MemcachedDecoder.java
  server/memcached/src/test/java/org/infinispan/server/memcached/MemcachedFunctionalTest.java
  server/memcached/src/test/java/org/infinispan/server/memcached/MemcachedSingleNodeTest.java
  server/memcached/src/test/java/org/infinispan/server/memcached/MemcachedStatsTest.java
Labels: Changes Suggested, Test fix

#9718 [13.0.x] ISPN-13121 Cache persistent state is not deleted after successful restart
  core/src/main/java/org/infinispan/topology/CacheTopology.java
  core/src/main/java/org/infinispan/topology/ClusterCacheStatus.java
  core/src/main/java/org/infinispan/topology/LocalTopologyManagerImpl.java
  core/src/test/java/org/infinispan/globalstate/AbstractGlobalStateRestartTest.java
  core/src/test/java/org/infinispan/globalstate/ThreeNodeDistGlobalStateRestartTest.java
Labels: Changes Required, Backport

#9696 [13.0.x] ISPN-13532 Cache store properties shouldn't be changed
  commons/all/src/main/java/org/infinispan/commons/configuration/io/ConfigurationWriter.java
  commons/all/src/main/java/org/infinispan/commons/configuration/io/xml/XmlConfigurationWriter.java
  commons/all/src/main/java/org/infinispan/commons/configuration/io/yaml/YamlConfigurationWriter.java
  core/src/main/java/org/infinispan/configuration/cache/ClusterLoaderConfigurationBuilder.java
  core/src/main/java/org/infinispan/configuration/parsing/CacheParser.java
  core/src/test/java/org/infinispan/configuration/parsing/UnifiedXmlFileParsingTest.java
  core/src/test/resources/configs/all/13.0.xml
  persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/configuration/JdbcStringBasedStoreConfigurationBuilder.java
Labels: Backport

#9769 ISPN-13600 Transfer IRAC state in batches
  commons/all/src/main/java/org/infinispan/commons/marshall/Ids.java
  core/src/main/java/org/infinispan/commands/CommandInvocationId.java
  core/src/main/java/org/infinispan/commands/CommandsFactory.java
  core/src/main/java/org/infinispan/commands/CommandsFactoryImpl.java
  core/src/main/java/org/infinispan/commands/irac/IracStateResponseCommand.java
  core/src/main/java/org/infinispan/marshall/core/InternalExternalizers.java
  core/src/main/java/org/infinispan/xsite/irac/DefaultIracManager.java
  core/src/main/java/org/infinispan/xsite/irac/IracManager.java
  core/src/main/java/org/infinispan/xsite/irac/IracManagerKeyInfoImpl.java
  core/src/main/java/org/infinispan/xsite/irac/NoOpIracManager.java
  core/src/test/java/org/infinispan/util/mocks/ControlledCommandFactory.java
  core/src/test/java/org/infinispan/xsite/irac/ControlledIracManager.java
  core/src/test/java/org/infinispan/xsite/irac/ManualIracManager.java
Labels: Trivial :-), Changes Required
