Repository infinispan/infinispan, pull requests merged in 2021-08, with the labels that each got.

#9468 ISPN-13211 Upgrade Hibernate Core to 5.3.21.Final
  build-configuration/pom.xml
Labels: Trivial :-)

#9469 ISPN-13213 Upgrade Jackson to 2.12.4
  build-configuration/pom.xml
Labels: Trivial :-)

#9472 ISPN-13215 MarshallableEntryImpl should not eagerly unmarshall object…
  core/src/main/java/org/infinispan/marshall/persistence/impl/MarshallableEntryImpl.java
Labels: Changes Required, Trivial :-)

#9473 ISPN-13217 Upgrade WildFly Elytron to 1.15.5.Final
  build-configuration/pom.xml
Labels: Trivial :-)

#9478 ISPN-13224 Release Console 0.15.1.Final
  build-configuration/pom.xml
Labels: Urgent!, Trivial :-)

#9447 ISPN-7140 Concurrent modifications succeed in pessimistic cache
  core/src/main/java/org/infinispan/distribution/ch/impl/DefaultConsistentHash.java
  core/src/main/java/org/infinispan/distribution/ch/impl/ReplicatedConsistentHash.java
  core/src/main/java/org/infinispan/distribution/ch/impl/SyncConsistentHashFactory.java
  core/src/main/java/org/infinispan/scattered/impl/ScatteredStateConsumerImpl.java
  core/src/main/java/org/infinispan/statetransfer/StateConsumerImpl.java
  core/src/main/java/org/infinispan/topology/CacheTopology.java
  core/src/test/java/org/infinispan/distribution/ch/impl/DefaultConsistentHashFactoryTest.java
  core/src/test/java/org/infinispan/distribution/ch/impl/SyncConsistentHashFactoryTest.java
  core/src/test/java/org/infinispan/tx/locking/NoConcurrentLockPessimistTxTest.java
  core/src/test/java/org/infinispan/tx/locking/PrimaryOwnerChangePessimistTxTest.java
Labels: Question

#9483 ISPN-13231 Join command with older view id causes NullPointerException
  core/src/main/java/org/infinispan/topology/ClusterTopologyManagerImpl.java
  core/src/test/java/org/infinispan/topology/ClusterTopologyManagerImplTest.java
Labels: Trivial :-), Test fix

#9337 ISPN-13059: Add description annotations to logging utility
  build-configuration/bom/pom.xml
  commons/all/pom.xml
  documentation/collect-logs.xml
  documentation/logging-report.xsl
  documentation/logs.html
  documentation/pom.xml
  logging/logging-annotations/pom.xml
  logging/logging-annotations/src/main/java/org/infinispan/logging/annotations/Description.java
  logging/logging-processor/pom.xml
  logging/logging-processor/src/main/java/org/infinispan/logging/processor/InfinispanLoggingProcessor.java
  logging/logging-processor/src/main/java/org/infinispan/logging/processor/report/IndentingXmlWriter.java
  logging/logging-processor/src/main/java/org/infinispan/logging/processor/report/XmlReportWriter.java
  pom.xml
Labels: Documentation

#9491 ISPN-13244 Remove infinispan-logging-* modules from bom
  build-configuration/bom/pom.xml
  pom.xml
Labels: Trivial :-)

#9464 ISPN-13202 Log SCI registration as debug
  remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/ProtobufMetadataManagerImpl.java
  remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/logging/Log.java
Labels: Trivial :-)

#9226 ISPN-12931 Server configuration overlay
  commons/all/src/main/java/org/infinispan/commons/configuration/io/yaml/YamlConfigurationReader.java
  server/runtime/src/main/java/org/infinispan/server/Bootstrap.java
  server/runtime/src/main/java/org/infinispan/server/Server.java
  server/runtime/src/main/java/org/infinispan/server/logging/Messages.java
  server/runtime/src/test/java/org/infinispan/server/configuration/ServerConfigurationParserTest.java
  server/runtime/src/test/java/org/infinispan/server/configuration/ServerOverlayConfigurationTest.java
  server/runtime/src/test/resources/configuration/Base.xml
  server/runtime/src/test/resources/configuration/Overlay.yml
Labels: Needs Rebase
