Repository infinispan/infinispan, pull requests merged in 2022-06, with the labels that each got.

#10163 ISPN-13940 BlockingManager#runBlockingOperation doesn't return stage
  core/src/main/java/org/infinispan/util/concurrent/BlockingManagerImpl.java
Labels: Trivial :-)

#10173 ISPN-13958 Add destination in ISPN000427 - Timeout after 60 seconds waiting for acks
  core/src/main/java/org/infinispan/util/concurrent/CommandAckCollector.java
  core/src/main/java/org/infinispan/util/logging/Log.java
Labels: Changes Required

#10179 ISPN-13965 Set bind_port=0 for cross-site tests
  core/src/test/resources/configs/xsite/bridge.xml
Labels: Trivial :-), Test fix

#10192 ISPN-13971 Add the Netty IOUring transport
  javadoc/pom.xml
Labels: Trivial :-), Test fix, Documentation

#10187 ISPN-13972: Update property realm note in Security realms doc
  documentation/src/main/asciidoc/topics/ref_server_realm_property.adoc
Labels: Backport, Documentation

#10193 Fixed hotrod PING response format
  documentation/src/main/asciidoc/topics/hotrod_protocol.adoc
Labels: Documentation

#10199 ISPN-13980 Licenses: check for CC0 word before public domain
  distribution/src/main/resources/template/licenses.xsl
Labels: Trivial :-)

#10197 ISPN-13978 Align dependencies between projects
  build/configuration/pom.xml
  core/src/test/java/org/infinispan/expiration/impl/ExpirationManagerTest.java
  core/src/test/java/org/infinispan/notifications/cachelistener/BaseCacheNotifierImplInitialTransferTest.java
  core/src/test/java/org/infinispan/notifications/cachelistener/CacheNotifierTest.java
  core/src/test/java/org/infinispan/notifications/cachelistener/CacheNotifierTxTest.java
  core/src/test/java/org/infinispan/notifications/cachelistener/SimpleCacheNotifierTest.java
  core/src/test/java/org/infinispan/remoting/jgroups/ChannelLookupTest.java
  core/src/test/java/org/infinispan/replication/ForceSyncAsyncFlagsTest.java
  core/src/test/java/org/infinispan/replication/SyncReplTest.java
  core/src/test/java/org/infinispan/stream/DistributedStreamIteratorWithPassivationTest.java
  core/src/test/java/org/infinispan/stream/LocalStreamIteratorWithPassivationTest.java
  core/src/test/java/org/infinispan/util/concurrent/BlockingManagerTest.java
  documentation/pom.xml
  hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/AbstractRegionAccessStrategyTest.java
  hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/collection/CollectionRegionAccessStrategyTest.java
  hibernate/cache-commons/src/test/java/org/infinispan/test/hibernate/cache/commons/functional/cluster/EntityCollectionInvalidationTest.java
  lock/src/test/java/org/infinispan/lock/impl/lock/RequestExpirationSchedulerTest.java
  persistence/remote/src/test/java/org/infinispan/persistence/remote/upgrade/HotRodUpgradeSynchronizerTest.java
  pom.xml
  server/runtime/pom.xml
Labels: Trivial :-)
