Repository infinispan/infinispan, pull requests merged in 2022-08, with the labels that each got.

#10247 ISPN-14041 Upgrade Protostream to 4.5.0.Dev05
  build/configuration/pom.xml
Labels: Trivial :-)

#10252 ISPN-14053 Upgrade WildFly OpenSSL 2.2.5.Final
  build/configuration/pom.xml
Labels: Trivial :-)

#10261 ISPN-14065 Upgrade JGroups to 5.2.5.Final
  build/configuration/pom.xml
Labels: Trivial :-)

#10255 ISPN-14056 Increase default frag and bundle size
  core/src/main/resources/default-configs/default-jgroups-azure.xml
  core/src/main/resources/default-configs/default-jgroups-ec2.xml
  core/src/main/resources/default-configs/default-jgroups-google.xml
  core/src/main/resources/default-configs/default-jgroups-kubernetes.xml
  core/src/main/resources/default-configs/default-jgroups-tcp.xml
  core/src/main/resources/default-configs/default-jgroups-udp.xml
  documentation/src/main/asciidoc/topics/ref_jgroups_system_properties.adoc
Labels: Trivial :-)

#10182 ISPN-14031 Create a logger category for container tests
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/JBossLoggingConsumer.java
  server/tests/src/test/resources/log/log4j2-trace.xml
Labels: Changes Required

#10264 ISPN-14071 Start defined caches in a determinstic order
  core/src/main/java/org/infinispan/globalstate/impl/GlobalConfigurationManagerImpl.java
Labels: Image Required

#10256 ISPN-14036 Server restart if a cache with SQL store is configured wit…
  core/src/main/java/org/infinispan/manager/DefaultCacheManager.java
  persistence/sql/src/test/java/org/infinispan/persistence/sql/AbstractSQLStoreFunctionalTest.java
  persistence/sql/src/test/java/org/infinispan/persistence/sql/QueriesJdbcStoreFunctionalTest.java
Labels: Suggestions please?

#10279 ISPN-14102 JVM GC Logs never set on the server
  server/runtime/src/main/server/bin/common.sh
Labels: Trivial :-)
