Repository infinispan/infinispan, pull requests merged in 2022-01, with the labels that each got.

#9780 ISPN-13610 Upgrade log4j to 2.17.1
  build-configuration/pom.xml
Labels: Trivial :-)

#9781 [13.0.x] ISPN-13610 Upgrade log4j to 2.17.1
  build-configuration/pom.xml
Labels: Trivial :-), Backport

#9782 [12.1.x] ISPN-13610 Upgrade log4j to 2.17.1
  build-configuration/pom.xml
Labels: Trivial :-), Backport

#9659 ISPN-12598 Hot Rod java client retries too many times
  server/testdriver/core/src/main/java/org/infinispan/server/test/api/HotRodTestClientDriver.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/TestServer.java
  server/tests/src/test/java/org/infinispan/server/resilience/ResilienceMaxRetryIT.java
Labels: Changes Required

#9800 ISPN-13627 Doc fix minor formatting issue
  documentation/src/main/asciidoc/topics/proc_cli_xsite_sites.adoc
Labels: Trivial :-), Documentation

#9801 [13.0.x] ISPN-13627 Doc fix minor formatting issue
  documentation/src/main/asciidoc/topics/proc_cli_xsite_sites.adoc
Labels: Trivial :-), Documentation

#9768 ISPN-13163 Allow blocking ScatteredStateConsumerImpl.blockingSubscribe()
  core/src/main/java/org/infinispan/util/CoreBlockHoundIntegration.java
Labels: Trivial :-)

#9804 [13.0.x] ISPN-13625 Scaling up 8.3 cluster with payload is slower compared to 8.2
  core/src/main/resources/default-configs/default-jgroups-azure.xml
  core/src/main/resources/default-configs/default-jgroups-ec2.xml
  core/src/main/resources/default-configs/default-jgroups-google.xml
  core/src/main/resources/default-configs/default-jgroups-kubernetes.xml
  core/src/main/resources/default-configs/default-jgroups-tcp.xml
  core/src/test/resources/configs/all/10.0.xml
  core/src/test/resources/configs/all/10.1.xml
  core/src/test/resources/configs/all/11.0.xml
  core/src/test/resources/configs/all/12.0.xml
  core/src/test/resources/configs/all/12.1.xml
  core/src/test/resources/configs/all/13.0.xml
  core/src/test/resources/configs/config-with-jgroups-stack.xml
  core/src/test/resources/configs/xsite/bridge.xml
  core/src/test/resources/configs/xsite/xsite-inline-test.xml
  core/src/test/resources/stacks/tcp.xml
  core/src/test/resources/stacks/tcp_mping/tcp1.xml
  core/src/test/resources/stacks/tcp_mping/tcp2.xml
  documentation/src/main/asciidoc/topics/xml/jgroups_inline_stack.xml
  integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node0.xml
  integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node1-fail.xml
  integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-krb-node1.xml
  integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-node0.xml
  integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-node1.xml
  integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-md5-user-node0.xml
  integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-prop-handler-node0.xml
  integrationtests/security-it/src/test/resources/jgroups-tcp-sasl-prop-handler-node1.xml
Labels: Backport

#9784 ISPN-13611 REST server invokes potentially blocking operations
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/admin/RemoteCacheAdminTest.java
  commons/all/src/main/java/org/infinispan/commons/internal/BlockHoundUtil.java
  commons/all/src/main/java/org/infinispan/commons/internal/CommonsBlockHoundIntegration.java
  core/src/main/java/org/infinispan/health/impl/CacheHealthImpl.java
  core/src/main/java/org/infinispan/health/impl/ClusterHealthImpl.java
  core/src/main/java/org/infinispan/health/impl/HealthImpl.java
  core/src/main/java/org/infinispan/health/impl/SecurityActions.java
  core/src/main/java/org/infinispan/manager/DefaultCacheManager.java
  core/src/main/java/org/infinispan/security/actions/GetPersistenceManagerAction.java
  core/src/main/java/org/infinispan/stats/impl/CacheContainerStatsImpl.java
  core/src/main/java/org/infinispan/topology/ClusterCacheStatus.java
  core/src/main/java/org/infinispan/topology/ClusterTopologyManagerImpl.java
  core/src/test/java/org/infinispan/health/impl/CacheHealthImplTest.java
  core/src/test/java/org/infinispan/health/impl/ClusterHealthImplTest.java
  core/src/test/java/org/infinispan/manager/DefaultCacheManagerHelper.java
  core/src/test/java/org/infinispan/partitionhandling/PreferConsistencyStrategyTest.java
  core/src/test/java/org/infinispan/scattered/statetransfer/PrefetchTest.java
  core/src/test/java/org/infinispan/statetransfer/WriteSkewDuringStateTransferTest.java
  core/src/test/java/org/infinispan/topology/ClusterCacheStatusTest.java
  core/src/test/java/org/infinispan/util/BlockingLocalTopologyManager.java
  core/src/test/java/org/infinispan/util/CoreTestBlockHoundIntegration.java
  lock/src/main/java/org/infinispan/lock/impl/manager/EmbeddedClusteredLockManager.java
  persistence/remote/src/test/java/org/infinispan/persistence/remote/RemoteStoreSSLTest.java
  persistence/remote/src/test/java/org/infinispan/persistence/remote/RemoteStoreTest.java
  query/src/test/java/org/infinispan/query/blackbox/IndexedCacheRestartTest.java
  server/core/src/main/java/org/infinispan/server/core/AbstractProtocolServer.java
  server/core/src/main/java/org/infinispan/server/core/backup/resources/CacheResource.java
  server/rest/src/main/java/org/infinispan/rest/BaseHttpRequestHandler.java
  server/rest/src/main/java/org/infinispan/rest/authentication/impl/BasicAuthenticator.java
  server/rest/src/main/java/org/infinispan/rest/cachemanager/RestCacheManager.java
  server/rest/src/main/java/org/infinispan/rest/logging/Log.java
  server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
  server/rest/src/main/java/org/infinispan/rest/resources/ContainerResource.java
  server/rest/src/main/java/org/infinispan/rest/resources/ServerResource.java
  server/rest/src/test/java/org/infinispan/rest/cachemanager/RestCacheManagerTest.java
  server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
  server/rest/src/test/java/org/infinispan/rest/resources/ContainerResourceTest.java
  server/rest/src/test/java/org/infinispan/rest/resources/SSEListener.java
  server/rest/src/test/java/org/infinispan/rest/search/MultiNodeRestTest.java
  server/rest/src/test/java/org/infinispan/rest/search/SearchCountClusteredTest.java
  server/router/src/test/java/org/infinispan/server/router/utils/RestTestingUtil.java
  server/runtime/src/main/java/org/infinispan/server/security/ElytronHTTPAuthenticator.java
  server/runtime/src/test/java/org/infinispan/server/configuration/ServerConfigurationSerializerTest.java
Labels: Changes Suggested

#9772 ISPN-13604 Should use IntSet.set whenever possible instead of IntSet.add
  core/src/main/java/org/infinispan/interceptors/distribution/NonTxDistributionInterceptor.java
  core/src/main/java/org/infinispan/interceptors/impl/EntryWrappingInterceptor.java
  core/src/main/java/org/infinispan/reactive/publisher/impl/ClusterPublisherManagerImpl.java
  core/src/main/java/org/infinispan/reactive/publisher/impl/PublisherHandler.java
  core/src/main/java/org/infinispan/scattered/impl/ScatteredStateConsumerImpl.java
  core/src/main/java/org/infinispan/statetransfer/StateConsumerImpl.java
  query/src/main/java/org/infinispan/query/backend/SegmentListener.java
Labels: Trivial :-)

#9809 Fix netty tcnative license report
  distribution/src/main/resources/template/licenses-overwrite.xml
Labels: Urgent!, Trivial :-)

#9810 [13.x] Fix netty tcnative license report
  distribution/src/main/resources/template/licenses-overwrite.xml
Labels: Urgent!, Trivial :-), Backport

#9818 ISPN-13545 - Docs: SQL store doc updates
  documentation/src/main/asciidoc/topics/code_examples/PersistenceSqlQuery.java
  documentation/src/main/asciidoc/topics/json/persistence_sql_query.json
  documentation/src/main/asciidoc/topics/yaml/persistence_sql_query.yaml
Labels: Documentation

#9829 [13.0.x] ISPN-13611 REST server invokes potentially blocking operations on Net…
  server/rest/src/main/java/org/infinispan/rest/resources/ClusterResource.java
  server/rest/src/main/java/org/infinispan/rest/resources/ContainerResource.java
  server/rest/src/main/java/org/infinispan/rest/resources/ServerResource.java
Labels: Backport

#9833 [13.0] ISPN-10603 partition handling docs
  core/src/main/resources/schema/infinispan-config-13.0.xsd
  documentation/src/main/asciidoc/stories/assembly_deployment_planning.adoc
  documentation/src/main/asciidoc/stories/assembly_partition_handling.adoc
  documentation/src/main/asciidoc/topics/code_examples/AdvancedCacheAvailibilityMode.java
  documentation/src/main/asciidoc/topics/code_examples/CustomMergePolicy.java
  documentation/src/main/asciidoc/topics/code_examples/CustomMergePolicyEntryMerge.java
  documentation/src/main/asciidoc/topics/code_examples/EmbeddedConflictManager.java
  documentation/src/main/asciidoc/topics/code_examples/PartitionHandling.java
  documentation/src/main/asciidoc/topics/con_partition_handling.adoc
  documentation/src/main/asciidoc/topics/con_partition_handling_data_consistency.adoc
  documentation/src/main/asciidoc/topics/con_partition_handling_degraded_example.adoc
  documentation/src/main/asciidoc/topics/con_partition_handling_degraded_mode.adoc
  documentation/src/main/asciidoc/topics/con_partition_handling_garbage_collection.adoc
  documentation/src/main/asciidoc/topics/con_performance_partition_handling.adoc
  documentation/src/main/asciidoc/topics/images/partition-handling-merging.png
  documentation/src/main/asciidoc/topics/images/partition-handling-partitioning.png
  documentation/src/main/asciidoc/topics/json/custom_merge_policy.json
  documentation/src/main/asciidoc/topics/json/partition_handling.json
  documentation/src/main/asciidoc/topics/proc_changing_cache_availability.adoc
  documentation/src/main/asciidoc/topics/proc_checking_cache_availability.adoc
  documentation/src/main/asciidoc/topics/proc_configuring_custom_merge_policies.adoc
  documentation/src/main/asciidoc/topics/proc_configuring_partition_handling.adoc
  documentation/src/main/asciidoc/topics/proc_merging_partitions_manually.adoc
  documentation/src/main/asciidoc/topics/ref_cache_modes.adoc
  documentation/src/main/asciidoc/topics/ref_partition_handling_merge_policies.adoc
  documentation/src/main/asciidoc/topics/ref_partition_handling_strategies.adoc
  documentation/src/main/asciidoc/topics/xml/custom_merge_policy.xml
  documentation/src/main/asciidoc/topics/xml/partition_handling.xml
  documentation/src/main/asciidoc/topics/yaml/custom_merge_policy.yaml
  documentation/src/main/asciidoc/topics/yaml/partition_handling.yaml
Labels: Backport, Documentation

#9842 [13.0] ISPN-13500 cli install doc conditionals
  documentation/src/main/asciidoc/stories/assembly_cli_command_reference.adoc
  documentation/src/main/asciidoc/topics/proc_configuring_custom_merge_policies.adoc
  documentation/src/main/asciidoc/topics/proc_configuring_sql_stores_query.adoc
  documentation/src/main/asciidoc/topics/proc_configuring_sql_stores_table.adoc
  documentation/src/main/asciidoc/topics/proc_server_configuring_datasources.adoc
Labels: Documentation

#9843 [9.4.x] ISPN-13663 conditionalize docs for JGroups SASL
  documentation/src/main/asciidoc/server_guide/configuration.adoc
Labels: Documentation

#9844 NonBlockingStore javadoc fixes
  core/src/main/java/org/infinispan/persistence/spi/NonBlockingStore.java
Labels: Trivial :-)
