Repository infinispan/infinispan, pull requests merged in 2022-02, with the labels that each got.

#9861 [13.0.x] ISPN-10603 Fixing a typo in the docs
  documentation/src/main/asciidoc/topics/xml/local_cache.xml
Labels: Backport, Documentation

#9855 ISPN-13674 make caches available from console
  documentation/src/main/asciidoc/stories/assembly_partition_handling.adoc
  documentation/src/main/asciidoc/topics/proc_making_caches_available.adoc
Labels: Documentation

#9865 ISPN-13674 make caches available docs
  documentation/src/main/asciidoc/stories/assembly_partition_handling.adoc
  documentation/src/main/asciidoc/topics/proc_making_caches_available.adoc
Labels: Backport, Documentation

#9867 ISPN-13590 StoreMigrator source version field
  documentation/src/main/asciidoc/topics/attributes/store_migrator_source_versions.adoc
  documentation/src/main/asciidoc/topics/proc_configuring_store_migrator.adoc
  documentation/src/main/asciidoc/topics/ref_store_migrator_properties.adoc
Labels: Documentation

#9868 [13.0.x] ISPN-13590 StoreMigrator source version field
  documentation/src/main/asciidoc/topics/attributes/store_migrator_source_versions.adoc
  documentation/src/main/asciidoc/topics/proc_configuring_store_migrator.adoc
  documentation/src/main/asciidoc/topics/ref_store_migrator_properties.adoc
Labels: Backport, Documentation

#9834 ISPN-13236 Spring docs: revision for style, structure, and accuracy
  documentation/src/main/asciidoc/stories/assembly_externalizing_sessions_spring.adoc
  documentation/src/main/asciidoc/stories/assembly_spring_cache_provider.adoc
  documentation/src/main/asciidoc/stories/assembly_spring_cache_sessions.adoc
  documentation/src/main/asciidoc/titles/spring/spring.asciidoc
  documentation/src/main/asciidoc/titles/spring/stories.adoc
  documentation/src/main/asciidoc/topics/code_examples/SpringCacheEvictAllEntriesExample.java
  documentation/src/main/asciidoc/topics/code_examples/SpringCacheEvictEntryExample.java
  documentation/src/main/asciidoc/topics/code_examples/SpringCacheEvictExample.java
  documentation/src/main/asciidoc/topics/code_examples/SpringExternalizeSessions.java
  documentation/src/main/asciidoc/topics/con_spring_cache_annotations.adoc
  documentation/src/main/asciidoc/topics/dependencies_maven/spring5_session_dependencies.xml
  documentation/src/main/asciidoc/topics/dependencies_maven/spring_cache_embedded.xml
  documentation/src/main/asciidoc/topics/dependencies_maven/spring_cache_remote.xml
  documentation/src/main/asciidoc/topics/proc_adding_spring_cache.adoc
  documentation/src/main/asciidoc/topics/proc_configuring_cache_operation_timeouts.adoc
  documentation/src/main/asciidoc/topics/proc_externalizing_sessions_spring.adoc
  documentation/src/main/asciidoc/topics/proc_setting_up_spring_cache.adoc
  documentation/src/main/asciidoc/topics/proc_using_spring_cache_provider.adoc
  documentation/src/main/asciidoc/topics/properties/hotrod-client-remote.properties
Labels: Documentation

#9870 [13.0.x] ISPN-13236 Spring docs: revision for style, structure, and accuracy #9834
  documentation/src/main/asciidoc/stories/assembly_externalizing_sessions_spring.adoc
  documentation/src/main/asciidoc/stories/assembly_spring_cache_provider.adoc
  documentation/src/main/asciidoc/stories/assembly_spring_cache_sessions.adoc
  documentation/src/main/asciidoc/titles/spring/spring.asciidoc
  documentation/src/main/asciidoc/titles/spring/stories.adoc
  documentation/src/main/asciidoc/topics/code_examples/SpringCacheEvictAllEntriesExample.java
  documentation/src/main/asciidoc/topics/code_examples/SpringCacheEvictEntryExample.java
  documentation/src/main/asciidoc/topics/code_examples/SpringCacheEvictExample.java
  documentation/src/main/asciidoc/topics/code_examples/SpringExternalizeSessions.java
  documentation/src/main/asciidoc/topics/con_spring_cache_annotations.adoc
  documentation/src/main/asciidoc/topics/dependencies_maven/spring5_session_dependencies.xml
  documentation/src/main/asciidoc/topics/dependencies_maven/spring_cache_embedded.xml
  documentation/src/main/asciidoc/topics/dependencies_maven/spring_cache_remote.xml
  documentation/src/main/asciidoc/topics/proc_adding_spring_cache.adoc
  documentation/src/main/asciidoc/topics/proc_configuring_cache_operation_timeouts.adoc
  documentation/src/main/asciidoc/topics/proc_externalizing_sessions_spring.adoc
  documentation/src/main/asciidoc/topics/proc_setting_up_spring_cache.adoc
  documentation/src/main/asciidoc/topics/proc_using_spring_cache_provider.adoc
  documentation/src/main/asciidoc/topics/properties/hotrod-client-remote.properties
Labels: Backport, Documentation

#9871 ISPN-13683 Close files in UserToolTest
  cli/src/test/java/org/infinispan/cli/user/UserToolTest.java
  commons/all/src/main/java/org/infinispan/commons/util/Util.java
Labels: Test fix

#9873 ISPN-13693 Fix AsyncBackupTest.testClear test
  core/src/main/java/org/infinispan/xsite/irac/DefaultIracManager.java
Labels: Test fix

#9874 ISPN-13697 HotRodEventsTest random failures
  server/hotrod/src/test/java/org/infinispan/server/hotrod/ServerHotRodTestBlockHoundIntegration.java
Labels: Trivial :-)

#9880 [13.0.x] ISPN-13700 ConfigurationTest fails on 13.0.x
  persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/configuration/ConfigurationTest.java
Labels: Test fix

#9863 ISPN-13677 SQL cache store composite keys and values
  documentation/src/main/asciidoc/stories/assembly_configuring_persistent_storage.adoc
  documentation/src/main/asciidoc/topics/attributes/community-attributes.adoc
  documentation/src/main/asciidoc/topics/code_examples/PersistenceSqlQuery.java
  documentation/src/main/asciidoc/topics/code_examples/PersistenceSqlTable.java
  documentation/src/main/asciidoc/topics/con_cache_store_sql.adoc
  documentation/src/main/asciidoc/topics/con_cache_store_sql_composites.adoc
  documentation/src/main/asciidoc/topics/con_cache_store_sql_data_types.adoc
  documentation/src/main/asciidoc/topics/con_cache_store_sql_embedded_keys.adoc
  documentation/src/main/asciidoc/topics/json/persistence_sql_query.json
  documentation/src/main/asciidoc/topics/json/persistence_sql_table.json
  documentation/src/main/asciidoc/topics/proc_configuring_sql_stores_query.adoc
  documentation/src/main/asciidoc/topics/proc_configuring_sql_stores_table.adoc
  documentation/src/main/asciidoc/topics/proc_registering_sci_remote_caches.adoc
  documentation/src/main/asciidoc/topics/protobuf/address-db-table.proto
  documentation/src/main/asciidoc/topics/protobuf/books_embedded_keys.protobuf
  documentation/src/main/asciidoc/topics/protobuf/person-db-table.proto
  documentation/src/main/asciidoc/topics/ref_cache_store_sql_protobuf_schema.adoc
  documentation/src/main/asciidoc/topics/ref_cache_store_sql_protobuf_types.adoc
  documentation/src/main/asciidoc/topics/ref_sql_store_configuration_examples.adoc
  documentation/src/main/asciidoc/topics/ref_sql_store_query_configuration.adoc
  documentation/src/main/asciidoc/topics/sql/address.sql
  documentation/src/main/asciidoc/topics/sql/person.sql
  documentation/src/main/asciidoc/topics/xml/persistence_sql_query.xml
  documentation/src/main/asciidoc/topics/xml/persistence_sql_table.xml
  documentation/src/main/asciidoc/topics/yaml/persistence_sql_query.yaml
  documentation/src/main/asciidoc/topics/yaml/persistence_sql_table.yaml
Labels: Changes Suggested, Documentation

#9881 [13.0.x] ISPN-13677 composite keys and values in cache config
  documentation/src/main/asciidoc/stories/assembly_configuring_persistent_storage.adoc
  documentation/src/main/asciidoc/topics/attributes/community-attributes.adoc
  documentation/src/main/asciidoc/topics/code_examples/PersistenceSqlQuery.java
  documentation/src/main/asciidoc/topics/code_examples/PersistenceSqlTable.java
  documentation/src/main/asciidoc/topics/con_cache_store_sql.adoc
  documentation/src/main/asciidoc/topics/con_cache_store_sql_composites.adoc
  documentation/src/main/asciidoc/topics/con_cache_store_sql_data_types.adoc
  documentation/src/main/asciidoc/topics/con_cache_store_sql_embedded_keys.adoc
  documentation/src/main/asciidoc/topics/json/persistence_sql_query.json
  documentation/src/main/asciidoc/topics/json/persistence_sql_table.json
  documentation/src/main/asciidoc/topics/proc_configuring_sql_stores_query.adoc
  documentation/src/main/asciidoc/topics/proc_configuring_sql_stores_table.adoc
  documentation/src/main/asciidoc/topics/proc_registering_sci_remote_caches.adoc
  documentation/src/main/asciidoc/topics/protobuf/address-db-table.proto
  documentation/src/main/asciidoc/topics/protobuf/books_embedded_keys.protobuf
  documentation/src/main/asciidoc/topics/protobuf/person-db-table.proto
  documentation/src/main/asciidoc/topics/ref_cache_store_sql_protobuf_schema.adoc
  documentation/src/main/asciidoc/topics/ref_cache_store_sql_protobuf_types.adoc
  documentation/src/main/asciidoc/topics/ref_sql_store_configuration_examples.adoc
  documentation/src/main/asciidoc/topics/ref_sql_store_query_configuration.adoc
  documentation/src/main/asciidoc/topics/sql/address.sql
  documentation/src/main/asciidoc/topics/sql/person.sql
  documentation/src/main/asciidoc/topics/xml/persistence_sql_query.xml
  documentation/src/main/asciidoc/topics/xml/persistence_sql_table.xml
  documentation/src/main/asciidoc/topics/yaml/persistence_sql_query.yaml
  documentation/src/main/asciidoc/topics/yaml/persistence_sql_table.yaml
Labels: Backport, Documentation

#9783 ISPN-13613 Convert CounterManagerNotificationManager to component
  core/src/main/java/org/infinispan/functional/FunctionalMap.java
  core/src/main/java/org/infinispan/functional/impl/AbstractFunctionalMap.java
  core/src/main/java/org/infinispan/functional/impl/FunctionalMapImpl.java
  counter/src/main/java/org/infinispan/counter/impl/CounterModuleLifecycle.java
  counter/src/main/java/org/infinispan/counter/impl/listener/CounterManagerNotificationManager.java
  counter/src/main/java/org/infinispan/counter/impl/manager/EmbeddedCounterManager.java
  counter/src/main/java/org/infinispan/counter/impl/strong/AbstractStrongCounter.java
Labels: Trivial :-)

#9882 ISPN-13677 sql query config correction
  documentation/src/main/asciidoc/topics/code_examples/PersistenceSqlQuery.java
  documentation/src/main/asciidoc/topics/json/persistence_sql_query.json
  documentation/src/main/asciidoc/topics/xml/persistence_sql_query.xml
  documentation/src/main/asciidoc/topics/yaml/persistence_sql_query.yaml
Labels: Trivial :-), Documentation

#9883 [13.0.x] ISPN-13677 sql query config correction
  documentation/src/main/asciidoc/topics/code_examples/PersistenceSqlQuery.java
  documentation/src/main/asciidoc/topics/json/persistence_sql_query.json
  documentation/src/main/asciidoc/topics/xml/persistence_sql_query.xml
  documentation/src/main/asciidoc/topics/yaml/persistence_sql_query.yaml
Labels: Trivial :-), Backport, Documentation

#9806 ISPN-13630 Do not send cross-site requests to local site
  core/src/main/java/org/infinispan/container/versioning/irac/DefaultIracTombstoneManager.java
  core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
  core/src/main/java/org/infinispan/xsite/status/DefaultTakeOfflineManager.java
  core/src/test/java/org/infinispan/xsite/AbstractTwoSitesTest.java
Labels: Trivial :-)

#9858 [13.0] ISPN-13676 XStream 1.4.19
  build-configuration/pom.xml
  pom.xml
  server/core/src/main/java/org/infinispan/server/core/dataconversion/XMLTranscoder.java
Labels: On Hold

#9879 [13.0.x] ISPN-13698 Wildfly integration test - module java.base does not "opens java.*"
  integrationtests/server-integration/third-party-server/src/test/resources/arquillian.xml
Labels: Backport

#9836 ISPN-13661 Deprecate unused cross-site configuration
  core/src/main/java/org/infinispan/configuration/cache/BackupConfiguration.java
  core/src/main/java/org/infinispan/configuration/cache/BackupConfigurationBuilder.java
  core/src/main/java/org/infinispan/configuration/cache/SitesConfiguration.java
  core/src/main/java/org/infinispan/configuration/cache/SitesConfigurationBuilder.java
  core/src/main/java/org/infinispan/configuration/cache/TakeOfflineConfiguration.java
  core/src/main/java/org/infinispan/configuration/cache/TakeOfflineConfigurationBuilder.java
  core/src/main/java/org/infinispan/configuration/cache/XSiteStateTransferConfiguration.java
  core/src/main/java/org/infinispan/configuration/cache/XSiteStateTransferConfigurationBuilder.java
  core/src/main/java/org/infinispan/configuration/parsing/CacheParser.java
  core/src/main/java/org/infinispan/factories/EmptyConstructorNamedCacheFactory.java
  core/src/main/java/org/infinispan/factories/InterceptorChainFactory.java
  core/src/main/java/org/infinispan/factories/InternalCacheFactory.java
  core/src/main/java/org/infinispan/interceptors/distribution/TxDistributionInterceptor.java
  core/src/main/java/org/infinispan/util/logging/Log.java
  core/src/main/java/org/infinispan/xsite/metrics/DefaultXSiteMetricsCollector.java
  core/src/main/java/org/infinispan/xsite/status/DefaultTakeOfflineManager.java
  core/src/main/resources/schema/infinispan-config-14.0.xsd
  core/src/test/java/org/infinispan/configuration/parsing/UnifiedXmlFileParsingTest.java
  core/src/test/java/org/infinispan/xsite/AbstractTwoSitesTest.java
  core/src/test/java/org/infinispan/xsite/BackupForNotSpecifiedTest.java
  core/src/test/java/org/infinispan/xsite/BaseSiteUnreachableTest.java
  core/src/test/java/org/infinispan/xsite/PreloadWithXSiteTest.java
  core/src/test/java/org/infinispan/xsite/XSiteFileParsing2Test.java
  core/src/test/java/org/infinispan/xsite/XSiteFileParsing3Test.java
  core/src/test/java/org/infinispan/xsite/XSiteFileParsingTest.java
  core/src/test/java/org/infinispan/xsite/XSiteInlineConfigFileParsingTest.java
  core/src/test/java/org/infinispan/xsite/XSiteStateTransferFileParsingTest.java
  core/src/test/java/org/infinispan/xsite/irac/persistence/IracMetadataStoreTest.java
  core/src/test/java/org/infinispan/xsite/irac/statetransfer/IracLocalStateTransferTest.java
  core/src/test/java/org/infinispan/xsite/offline/AsyncOfflineTest.java
  core/src/test/java/org/infinispan/xsite/offline/AsyncTimeBasedOfflineTest.java
  server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
  server/rest/src/main/java/org/infinispan/rest/resources/ContainerResource.java
Labels: Trivial :-)

#9891 ISPN-13664 NullPointerException in PersistenceManagerImpl.stop()
  core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java
Labels: Trivial :-)

#9887 [13.0.x] ISPN-13703 test and fix for clustered DIST_SYNC transactional cache f…
  core/src/main/java/org/infinispan/commands/functional/Mutations.java
  core/src/test/java/org/infinispan/distribution/DistSyncTxFuncTest.java
Labels: Backport

#9846 [13.0.x] ISPN-13664 Deadlock on closing of PersistenceManagerImpl
  core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java
  core/src/test/java/org/infinispan/persistence/BaseStoreFunctionalTest.java
  core/src/test/java/org/infinispan/persistence/manager/PersistenceManagerTest.java
Labels: Backport

#9889 ISPN-13207 Jakarta Jars
  client/hotrod-client/pom.xml
  commons/all/pom.xml
  core/pom.xml
  extended-statistics/pom.xml
  persistence/jdbc-common/pom.xml
  persistence/jdbc/pom.xml
  persistence/sql/pom.xml
  pom.xml
  query/pom.xml
  server/hotrod/pom.xml
  server/tests/pom.xml
  tools/pom.xml
Labels: Trivial :-)

#9817 ISPN-13646 Upgrade Kafka client to version 2.8.1
  build-configuration/pom.xml
  cloudevents-integration/src/test/java/org/infinispan/cloudevents/MockKafkaEventSender.java
Labels: Trivial :-)

#9897 ISPN-13714 downstream revision of WildFly modules content
  documentation/src/main/asciidoc/stories/assembly_wildfly_modules.adoc
Labels: Trivial :-), Documentation

#9909 [13.0.x] ISPN-13714 downstream revision of WildFly modules content
  documentation/src/main/asciidoc/stories/assembly_wildfly_modules.adoc
Labels: Trivial :-), Documentation

#9907 [13.0.x] ISPN-13719 Register NettyTransport metrics
  server/core/src/main/java/org/infinispan/server/core/AbstractProtocolServer.java
  server/router/src/main/java/org/infinispan/server/router/router/impl/singleport/SinglePortEndpointRouter.java
Labels: Backport

#9912 ISPN-13730 NullPointerException when computing Netty global connections
  server/router/src/main/java/org/infinispan/server/router/router/impl/singleport/SecurityActions.java
  server/router/src/main/java/org/infinispan/server/router/router/impl/singleport/SinglePortEndpointRouter.java
Labels: Trivial :-)

#9913 [13.0.x] ISPN-13730 NullPointerException when computing Netty global connections
  server/router/src/main/java/org/infinispan/server/router/router/impl/singleport/SecurityActions.java
  server/router/src/main/java/org/infinispan/server/router/router/impl/singleport/SinglePortEndpointRouter.java
Labels: Trivial :-), Backport

#9917 Fix maven build warnings
  build/checkstyle/pom.xml
  build/component-annotations/pom.xml
  build/logging-annotations/pom.xml
  pom.xml
Labels: Trivial :-)

#9915 [13.0] ISPN-13463 Expose JGroups metrics
  component-annotations/src/main/java/org/infinispan/external/JGroupsProtocolComponent.java
  component-processor/pom.xml
  component-processor/src/main/java/org/infinispan/component/processor/external/JGroupsComponentProcessor.java
  core/pom.xml
  core/src/main/java/org/infinispan/metrics/impl/AbstractMetricsRegistration.java
  core/src/main/java/org/infinispan/metrics/impl/CacheManagerMetricsRegistration.java
  core/src/main/java/org/infinispan/metrics/impl/CacheMetricsRegistration.java
  core/src/main/java/org/infinispan/metrics/impl/MetricsCollector.java
  core/src/main/java/org/infinispan/remoting/transport/jgroups/AbstractJGroupsChannelConfigurator.java
  core/src/main/java/org/infinispan/remoting/transport/jgroups/EmbeddedJGroupsChannelConfigurator.java
  core/src/main/java/org/infinispan/remoting/transport/jgroups/FileJGroupsChannelConfigurator.java
  core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsChannelConfigurator.java
  core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
  server/core/src/main/java/org/infinispan/server/core/AbstractProtocolServer.java
Labels: Backport
