Repository infinispan/infinispan, pull requests merged in 2022-03, with the labels that each got.

#9854 ISPN-13672 Infinispan use cases
  documentation/src/main/asciidoc/stories/assembly_architecture_use_cases.adoc
  documentation/src/main/asciidoc/stories/assembly_xsite_replication.adoc
  documentation/src/main/asciidoc/titles/tuning/stories.adoc
  documentation/src/main/asciidoc/topics/attributes/community-attributes.adoc
  documentation/src/main/asciidoc/topics/con_cross_site_replication.adoc
  documentation/src/main/asciidoc/topics/con_distributed_memory.adoc
  documentation/src/main/asciidoc/topics/con_in_line_caching.adoc
  documentation/src/main/asciidoc/topics/con_infinispan_deployment_models.adoc
  documentation/src/main/asciidoc/topics/con_platforms_automation_tooling.adoc
  documentation/src/main/asciidoc/topics/con_session_externalization.adoc
  documentation/src/main/asciidoc/topics/con_side_caching.adoc
  documentation/src/main/asciidoc/topics/con_xsite_replication.adoc
  documentation/src/main/asciidoc/topics/images/cross-site-replication.png
  documentation/src/main/asciidoc/topics/images/cross-site-replication.svg
  documentation/src/main/asciidoc/topics/images/distributed-cache.png
  documentation/src/main/asciidoc/topics/images/distributed-cache.svg
  documentation/src/main/asciidoc/topics/images/in-line-cache.png
  documentation/src/main/asciidoc/topics/images/in-line-cache.svg
  documentation/src/main/asciidoc/topics/images/remote-caches.png
  documentation/src/main/asciidoc/topics/images/remote-caches.svg
  documentation/src/main/asciidoc/topics/images/session-externalization.png
  documentation/src/main/asciidoc/topics/images/session-externalization.svg
  documentation/src/main/asciidoc/topics/images/side-cache.png
  documentation/src/main/asciidoc/topics/images/side-cache.svg
Labels: Documentation

#9923 ISPN-13735 Actions to keep docs in sync
  .github/workflows/sync_docs.yml
Labels: Suggestions please?

#9943 [13.0] ISPN-13737 Allow configuring file-less keystores
  documentation/src/main/asciidoc/stories/assembly_server_encryption.adoc
  documentation/src/main/asciidoc/topics/json/server_ssl_identity_fips.json
  documentation/src/main/asciidoc/topics/proc_configuring_server_fips.adoc
  documentation/src/main/asciidoc/topics/xml/server_ssl_identity_fips.xml
  documentation/src/main/asciidoc/topics/yaml/server_ssl_identity_fips.yaml
  server/runtime/src/main/java/org/infinispan/server/configuration/ServerConfigurationParser.java
  server/runtime/src/main/java/org/infinispan/server/configuration/security/KeyStoreConfiguration.java
  server/runtime/src/main/java/org/infinispan/server/configuration/security/KeyStoreConfigurationBuilder.java
  server/runtime/src/main/java/org/infinispan/server/logging/Log.java
  server/runtime/src/main/java/org/infinispan/server/security/KeyStoreUtils.java
  server/runtime/src/main/resources/schema/infinispan-server-13.0.xsd
Labels: Backport

#9948 [13.0.x] ISPN-13591 Backups fail if a proto schema key contains forward slashes
  server/core/src/main/java/org/infinispan/server/core/backup/BackupManagerImpl.java
  server/core/src/main/java/org/infinispan/server/core/backup/resources/InternalCacheResource.java
  server/tests/src/test/java/org/infinispan/server/functional/BackupManagerIT.java
Labels: Backport

#9945 ISPN-13754 BlockingManager should not blocking invoking thread if sta…
  core/src/main/java/org/infinispan/util/concurrent/BlockingManager.java
  core/src/main/java/org/infinispan/util/concurrent/BlockingManagerImpl.java
Labels: Trivial :-)

#9965 [13.0.x] ISPN-13765 Unable to start full JGroups stacks
  core/src/main/java/org/infinispan/configuration/global/JGroupsConfiguration.java
  core/src/main/java/org/infinispan/remoting/transport/jgroups/EmbeddedJGroupsChannelConfigurator.java
  core/src/test/java/org/infinispan/configuration/XmlFileParsingTest.java
  core/src/test/resources/configs/config-with-jgroups-stack.xml
Labels: Backport

#9960 ISPN-13763 fix typo
  documentation/src/main/asciidoc/topics/ref_executing_secure_caches.adoc
Labels: Trivial :-), Documentation

#9963 [13.0.x] ISPN-12973 RemoveExpiredCommand will not remove entries on backup if …
  core/src/main/java/org/infinispan/interceptors/impl/CallInterceptor.java
  core/src/test/java/org/infinispan/expiration/impl/ClusterExpirationLifespanTest.java
  core/src/test/java/org/infinispan/expiration/impl/ExpirationFileStoreDistListenerFunctionalTest.java
  core/src/test/java/org/infinispan/expiration/impl/ExpirationFileStoreListenerFunctionalTest.java
  core/src/test/java/org/infinispan/expiration/impl/ExpirationFunctionalTest.java
  core/src/test/java/org/infinispan/test/TestDataSCI.java
Labels: Backport

#9973 ISPN-13773 Upgrade Jackson to 2.13.1
  build/configuration/pom.xml
Labels: Trivial :-)

#9971 ISPN-13776 Upgrade Kubernetes Client to 5.7.4
  build/configuration/pom.xml
Labels: Trivial :-)

#9972 ISPN-13774 Upgrade AWS java SDK to 1.12.180
  pom.xml
Labels: Trivial :-)

#9974 ISPN-13775 Upgrade Jaeger to 1.6.0
  pom.xml
Labels: Trivial :-)

#9980 [13.0.x] ISPN-13777 NullPointerException in JGroupsTransport when metrics are …
  core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
Labels: Backport

#9975 ISPN-13772 Upgrade mojo-executor to 2.4.0
  build/configuration/pom.xml
  build/infinispan-defaults-maven-plugin/pom.xml
  pom.xml
Labels: Trivial :-)

#9966 ISPN-13771 Remove org.jboss.remotingjmx:remoting-jmx from CLI
  cli/pom.xml
  pom.xml
Labels: Trivial :-)

#9967 [13.0.x] ISPN-13771 Remove org.jboss.remotingjmx:remoting-jmx from CLI
  cli/pom.xml
  pom.xml
Labels: Trivial :-), Backport

#9954 [13.0.x] ISPN-13446 IRAC: configure the tombstone cleanup task
  commons/all/src/main/java/org/infinispan/commons/configuration/attributes/AttributeSet.java
  commons/all/src/main/java/org/infinispan/commons/configuration/attributes/AttributeValidator.java
  commons/all/src/main/java/org/infinispan/commons/logging/Log.java
  core/src/main/java/org/infinispan/configuration/cache/SitesConfiguration.java
  core/src/main/java/org/infinispan/configuration/cache/SitesConfigurationBuilder.java
  core/src/main/java/org/infinispan/configuration/parsing/Attribute.java
  core/src/main/java/org/infinispan/configuration/parsing/CacheParser.java
  core/src/main/java/org/infinispan/configuration/serializing/CoreConfigurationSerializer.java
  core/src/main/java/org/infinispan/container/versioning/irac/DefaultIracTombstoneManager.java
  core/src/main/java/org/infinispan/container/versioning/irac/IracTombstoneManager.java
  core/src/main/java/org/infinispan/container/versioning/irac/NoOpIracTombstoneManager.java
  core/src/main/java/org/infinispan/xsite/irac/DefaultIracManager.java
  core/src/main/java/org/infinispan/xsite/irac/IracExecutor.java
  core/src/main/resources/schema/infinispan-config-13.0.xsd
  core/src/test/java/org/infinispan/configuration/serializer/AbstractConfigurationSerializerTest.java
  core/src/test/java/org/infinispan/xsite/XSiteFileParsingTest.java
  core/src/test/java/org/infinispan/xsite/XSiteParsingTest.java
  core/src/test/java/org/infinispan/xsite/irac/IracTombstoneUnitTest.java
  core/src/test/resources/configs/all/13.0.xml
  core/src/test/resources/configs/xsite/xsite-test.xml
  documentation/src/main/asciidoc/stories/assembly_xsite_configuring.adoc
  documentation/src/main/asciidoc/topics/json/xsite_tombstone_cleanup.json
  documentation/src/main/asciidoc/topics/proc_xsite_cleaning_tombstones.adoc
  documentation/src/main/asciidoc/topics/xml/xsite_tombstone_cleanup.xml
  documentation/src/main/asciidoc/topics/yaml/xsite_tombstone_cleanup.yaml
Labels: Backport

#9981 ISPN-13606 Fix NPE in PooledConnectionDeployIT
  integrationtests/server-integration/third-party-server/src/test/java/org/infinispan/test/integration/thirdparty/persistence/jdbc/util/BaseJdbcDeploy.java
Labels: Test fix

#9994 ISPN-13785 Remove jboss-remoting and xnio
  build/configuration/pom.xml
  cli/pom.xml
  pom.xml
Labels: Trivial :-)

#9991 [13.0.x] ISPN-13723 Create metric for site status
  core/src/main/java/org/infinispan/metrics/impl/MetricsCollector.java
  core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
  core/src/main/java/org/infinispan/xsite/XSiteAdminOperations.java
  core/src/main/java/org/infinispan/xsite/status/DefaultTakeOfflineManager.java
  core/src/main/java/org/infinispan/xsite/status/TakeOfflineManager.java
  server/tests/src/test/java/org/infinispan/server/functional/XSiteIT.java
  server/tests/src/test/java/org/infinispan/server/functional/XSiteRestMetricsOperations.java
Labels: Backport

#9995 [13.0.x] ISPN-13785 Remove jboss-remoting and xnio
  build-configuration/pom.xml
  cli/pom.xml
  pom.xml
Labels: Trivial :-), Backport

#9992 [13.0.x] Upgrade Kafka client to version 2.7.2
  build-configuration/pom.xml
  cloudevents-integration/src/test/java/org/infinispan/cloudevents/MockKafkaEventSender.java
Labels: Trivial :-)

#9996 [13.0.x] ISPN-13781 Hot Rod client configuration values
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/package-info.java
Labels: Backport, Documentation

#9978 [13.0.x] ISPN-13747 Compactor throws null pointer exception and stops working
  core/src/main/java/org/infinispan/persistence/sifs/Compactor.java
  core/src/main/java/org/infinispan/persistence/sifs/Index.java
  core/src/main/java/org/infinispan/persistence/sifs/Log.java
  core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreFunctionalTest.java
Labels: Backport

#10000 ISPN-13789 Avoid copying XaResource list when commit transactions
  commons/all/src/main/java/org/infinispan/commons/tx/TransactionImpl.java
Labels: Trivial :-), Performance ACK required!

#9999 ISPN-13788 Create ModificationList for transactions
  core/src/main/java/org/infinispan/commands/control/LockControlCommand.java
  core/src/main/java/org/infinispan/commands/tx/PrepareCommand.java
  core/src/main/java/org/infinispan/commands/tx/VersionedPrepareCommand.java
  core/src/main/java/org/infinispan/context/impl/AbstractTxInvocationContext.java
  core/src/main/java/org/infinispan/interceptors/distribution/TxDistributionInterceptor.java
  core/src/main/java/org/infinispan/interceptors/impl/AbstractIracLocalSiteInterceptor.java
  core/src/main/java/org/infinispan/interceptors/impl/EntryWrappingInterceptor.java
  core/src/main/java/org/infinispan/interceptors/impl/InvalidationInterceptor.java
  core/src/main/java/org/infinispan/interceptors/impl/PessimisticTxIracLocalInterceptor.java
  core/src/main/java/org/infinispan/interceptors/impl/TxInterceptor.java
  core/src/main/java/org/infinispan/interceptors/xsite/PessimisticBackupInterceptor.java
  core/src/main/java/org/infinispan/statetransfer/StateProviderImpl.java
  core/src/main/java/org/infinispan/statetransfer/TransactionInfo.java
  core/src/main/java/org/infinispan/transaction/impl/AbstractCacheTransaction.java
  core/src/main/java/org/infinispan/transaction/impl/LocalTransaction.java
  core/src/main/java/org/infinispan/transaction/impl/ModificationList.java
  core/src/main/java/org/infinispan/transaction/impl/RemoteTransaction.java
  core/src/main/java/org/infinispan/transaction/impl/TransactionTable.java
  core/src/main/java/org/infinispan/transaction/xa/CacheTransaction.java
  core/src/main/java/org/infinispan/transaction/xa/TransactionFactory.java
  core/src/main/java/org/infinispan/transaction/xa/recovery/RecoveryAwareRemoteTransaction.java
  core/src/test/java/org/infinispan/marshall/VersionAwareMarshallerTest.java
  core/src/test/java/org/infinispan/tx/ModificationListUnitTest.java
  hibernate/cache-commons/src/main/java/org/infinispan/hibernate/cache/commons/access/TxInvalidationInterceptor.java
Labels: Performance ACK required!

#10005 [13.0.x] ISPN-13496 IRAC batch tombstone cleanup command
  core/src/main/java/org/infinispan/commands/CommandsFactory.java
  core/src/main/java/org/infinispan/commands/CommandsFactoryImpl.java
  core/src/main/java/org/infinispan/commands/irac/IracTombstoneCleanupCommand.java
  core/src/main/java/org/infinispan/commands/irac/IracTombstonePrimaryCheckCommand.java
  core/src/main/java/org/infinispan/commands/irac/IracTombstoneRemoteSiteCheckCommand.java
  core/src/main/java/org/infinispan/container/versioning/irac/DefaultIracTombstoneManager.java
  core/src/main/java/org/infinispan/util/concurrent/BlockingManager.java
  core/src/main/java/org/infinispan/util/concurrent/BlockingManagerImpl.java
  core/src/main/java/org/infinispan/xsite/BackupSenderImpl.java
  core/src/test/java/org/infinispan/util/mocks/ControlledCommandFactory.java
  core/src/test/java/org/infinispan/xsite/irac/IracTombstoneCleanupTest.java
  core/src/test/java/org/infinispan/xsite/irac/IracTombstoneUnitTest.java
Labels: Backport
