Repository infinispan/infinispan, pull requests merged in 2023-08, with the labels that each got.

#11174 [14.x] ISPN-15085 Upgrade to Fabric8 kubernetes client 6.3.1
  build/configuration/pom.xml
  cli/src/main/java/org/infinispan/cli/commands/kubernetes/Uninstall.java
Labels: Backport

#11178 Cheat sheet: authorization config changes
  documentation/src/main/asciidoc/cheat-sheets/cache-configuration.asciidoc
Labels: Documentation

#11175 ISPN-15087 Increase default persistence availability interval to 30 s…
  core/src/main/java/org/infinispan/configuration/cache/PersistenceConfiguration.java
  documentation/src/main/asciidoc/topics/upgrading.adoc
Labels: Trivial :-)

#11172 ISPN-15080 Fix name-as-tags default in XSD
  core/src/main/resources/schema/infinispan-config-15.0.xsd
Labels: 14.0.x

#11181 ISPN-14994 JGroups 5.2.17.Final
  build/configuration/pom.xml
Labels: Trivial :-), 14.0.x

#11165 ISPN-15078 ParserRegistry.parse(InputStream is, MediaType mediaType)
  core/src/main/java/org/infinispan/configuration/parsing/ParserRegistry.java
Labels: 14.0.x

#11191 ISPN-15092 Apache SSHD 2.10.0
  build/configuration/pom.xml
Labels: 14.0.x

#11173 [9.4] ISPN-13105 ConsistentHash.getPrimarySegmentsForOwner() throws an IAE
  core/src/main/java/org/infinispan/distribution/ch/ConsistentHash.java
  core/src/main/java/org/infinispan/distribution/ch/impl/DefaultConsistentHash.java
  core/src/main/java/org/infinispan/distribution/ch/impl/ReplicatedConsistentHash.java
  core/src/main/java/org/infinispan/distribution/ch/impl/ScatteredConsistentHash.java
  core/src/main/java/org/infinispan/scattered/impl/BiasManagerImpl.java
  core/src/main/java/org/infinispan/scattered/impl/ScatteredStateProviderImpl.java
  core/src/main/java/org/infinispan/statetransfer/StateConsumerImpl.java
Labels: Backport

#11197 ISPN-15068 RESP Server should always use OCTET key media type storage
  server/resp/src/main/java/org/infinispan/server/resp/RespServer.java
Labels: Trivial :-)

#11195 ISPN-13612 InvalidatedNearRemoteCache can persist stale values in cas…
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/InvalidatedNearRemoteCache.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/near/BoundedConcurrentMapNearCache.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/near/ConcurrentMapNearCache.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/near/NearCache.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/near/NearCacheService.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/AssertsNearCache.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/ClusterInvalidatedNearCacheBloomTest.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/ClusterInvalidatedNearCacheTest.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/EvictInvalidatedNearCacheTest.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/InvalidatedFailoverNearCacheTest.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/InvalidatedNearCacheBloomTest.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/InvalidatedNearCacheTest.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/InvalidationNearCacheConcurrencyTest.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/MockNearCacheService.java
  client/hotrod/src/main/java/org/infinispan/hotrod/configuration/NearCache.java
  client/hotrod/src/main/java/org/infinispan/hotrod/impl/cache/InvalidatedNearRemoteCache.java
  client/hotrod/src/main/java/org/infinispan/hotrod/near/BoundedConcurrentMapNearCache.java
  client/hotrod/src/main/java/org/infinispan/hotrod/near/ConcurrentMapNearCache.java
  client/hotrod/src/main/java/org/infinispan/hotrod/near/NearCacheService.java
  documentation/src/main/asciidoc/topics/upgrading.adoc
  server/hotrod/src/main/java/org/infinispan/server/hotrod/CacheRequestProcessor.java
Labels: 14.0.x

#11200 Fix deploy without compiling sources
  Jenkinsfile
  build/configuration/pom.xml
Labels: Trivial :-)

#11201 [14.0.x] Enable snapshot deployment
  Jenkinsfile
  build/configuration/pom.xml
Labels: Trivial :-)

#11220 ISPN-15072 Only local statistics should be registered with Micrometer
  build/component-annotations/src/main/java/org/infinispan/jmx/annotations/ManagedAttribute.java
  build/component-processor/src/main/java/org/infinispan/component/processor/Generator.java
  core/src/main/java/org/infinispan/factories/EmptyConstructorFactory.java
  core/src/main/java/org/infinispan/factories/EmptyConstructorNamedCacheFactory.java
  core/src/main/java/org/infinispan/factories/GlobalComponentRegistry.java
  core/src/main/java/org/infinispan/factories/impl/MBeanMetadata.java
  core/src/main/java/org/infinispan/metrics/impl/MetricsCollector.java
  core/src/main/java/org/infinispan/stats/ClusterContainerStats.java
  core/src/main/java/org/infinispan/stats/ContainerStats.java
  core/src/main/java/org/infinispan/stats/impl/AbstractClusterStats.java
  core/src/main/java/org/infinispan/stats/impl/AbstractContainerStats.java
  core/src/main/java/org/infinispan/stats/impl/AbstractStats.java
  core/src/main/java/org/infinispan/stats/impl/ClusterCacheStatsFactory.java
  core/src/main/java/org/infinispan/stats/impl/ClusterCacheStatsImpl.java
  core/src/main/java/org/infinispan/stats/impl/ClusterContainerStatsFactory.java
  core/src/main/java/org/infinispan/stats/impl/ClusterContainerStatsImpl.java
  core/src/main/java/org/infinispan/stats/impl/LocalContainerStatsImpl.java
  core/src/test/java/org/infinispan/metrics/ClusteredCacheManagerMetricsTest.java
  server/rest/src/main/java/org/infinispan/rest/distribution/NodeDistributionInfo.java
Labels: 14.0.x

#11194 ISPN-15032 Use site and channel names as tag for metrics
  core/src/main/java/org/infinispan/factories/impl/MBeanMetadata.java
  core/src/main/java/org/infinispan/metrics/Constants.java
  core/src/main/java/org/infinispan/metrics/impl/AbstractMetricsRegistration.java
  core/src/main/java/org/infinispan/metrics/impl/CustomMetricsSupplier.java
  core/src/main/java/org/infinispan/metrics/impl/MetricUtils.java
  core/src/main/java/org/infinispan/metrics/impl/MetricsCollector.java
  core/src/main/java/org/infinispan/remoting/rpc/RpcManagerImpl.java
  core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
  core/src/main/java/org/infinispan/xsite/XSiteAdminOperations.java
  core/src/main/java/org/infinispan/xsite/status/DefaultTakeOfflineManager.java
  core/src/main/java/org/infinispan/xsite/status/TakeOfflineManager.java
  documentation/src/main/asciidoc/topics/upgrading.adoc
Labels: Needs Rebase

#11231 ISPN-15123 Ability to see which entries are evicted by log messages (…
  core/src/main/java/org/infinispan/container/impl/AbstractInternalDataContainer.java
Labels: Trivial :-), 14.0.x

#11230 [14.x] ISPN-15032 Use site and channel names as tag for metrics
  core/src/main/java/org/infinispan/factories/impl/MBeanMetadata.java
  core/src/main/java/org/infinispan/metrics/Constants.java
  core/src/main/java/org/infinispan/metrics/impl/AbstractMetricsRegistration.java
  core/src/main/java/org/infinispan/metrics/impl/CustomMetricsSupplier.java
  core/src/main/java/org/infinispan/metrics/impl/MetricUtils.java
  core/src/main/java/org/infinispan/metrics/impl/MetricsCollector.java
  core/src/main/java/org/infinispan/remoting/rpc/RpcManagerImpl.java
  core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
  core/src/main/java/org/infinispan/xsite/XSiteAdminOperations.java
  core/src/main/java/org/infinispan/xsite/status/DefaultTakeOfflineManager.java
  core/src/main/java/org/infinispan/xsite/status/TakeOfflineManager.java
  documentation/src/main/asciidoc/topics/upgrading.adoc
Labels: Backport

#11235 ISPN-15126 Touch command not handling SuspectException
  core/src/main/java/org/infinispan/interceptors/impl/BaseStateTransferInterceptor.java
  core/src/main/java/org/infinispan/interceptors/impl/ClusteringInterceptor.java
  core/src/test/java/org/infinispan/remoting/RemoteShutdownDuringOperationTest.java
Labels: 14.0.x

#11244 [14.0.x]ISPN-15134 update statement about memcached in Infinispan 15
  documentation/src/main/asciidoc/topics/con_server_endpoints.adoc
Labels: Documentation

#11228 [14.x] ISPN-15072 Only local statistics should be registered with Micrometer
  build/component-annotations/src/main/java/org/infinispan/jmx/annotations/ManagedAttribute.java
  build/component-processor/src/main/java/org/infinispan/component/processor/Generator.java
  core/src/main/java/org/infinispan/factories/EmptyConstructorFactory.java
  core/src/main/java/org/infinispan/factories/EmptyConstructorNamedCacheFactory.java
  core/src/main/java/org/infinispan/factories/GlobalComponentRegistry.java
  core/src/main/java/org/infinispan/metrics/impl/MetricsCollector.java
  core/src/main/java/org/infinispan/stats/ClusterContainerStats.java
  core/src/main/java/org/infinispan/stats/ContainerStats.java
  core/src/main/java/org/infinispan/stats/impl/AbstractClusterStats.java
  core/src/main/java/org/infinispan/stats/impl/AbstractContainerStats.java
  core/src/main/java/org/infinispan/stats/impl/AbstractStats.java
  core/src/main/java/org/infinispan/stats/impl/ClusterCacheStatsFactory.java
  core/src/main/java/org/infinispan/stats/impl/ClusterCacheStatsImpl.java
  core/src/main/java/org/infinispan/stats/impl/ClusterContainerStatsFactory.java
  core/src/main/java/org/infinispan/stats/impl/ClusterContainerStatsImpl.java
  core/src/main/java/org/infinispan/stats/impl/LocalContainerStatsImpl.java
  core/src/test/java/org/infinispan/metrics/ClusteredCacheManagerMetricsTest.java
  server/rest/src/main/java/org/infinispan/rest/distribution/NodeDistributionInfo.java
Labels: Needs Rebase, Changes Required, Backport

#11240 ISPN-15132 Updates to protostream 4.6.4.Final
  build/configuration/pom.xml
  core/src/test/java/org/infinispan/stats/SingleStatsTest.java
Labels: Trivial :-), 14.0.x

#11188 ISPN-15008 add overview of config files in the server README
  server/runtime/src/main/server/README.adoc
  server/runtime/src/main/server/server/conf/infinispan-dev-mode.xml
  server/runtime/src/main/server/server/conf/infinispan-xsite.xml
Labels: Documentation, 14.0.x

#11249 ISPN-15116 Remove unused BigObject.java
  core/src/test/java/org/infinispan/statetransfer/BigObject.java
Labels: Trivial :-)

#11167 ISPN-15079 Remove old code from CommandAckCollector
  core/src/main/java/org/infinispan/commands/CommandsFactory.java
  core/src/main/java/org/infinispan/commands/CommandsFactoryImpl.java
  core/src/main/java/org/infinispan/commands/write/BackupAckCommand.java
  core/src/main/java/org/infinispan/commands/write/BackupMultiKeyAckCommand.java
  core/src/main/java/org/infinispan/commands/write/ExceptionAckCommand.java
  core/src/main/java/org/infinispan/interceptors/distribution/BiasedCollector.java
  core/src/main/java/org/infinispan/marshall/exts/TriangleAckExternalizer.java
  core/src/main/java/org/infinispan/remoting/inboundhandler/TrianglePerCacheInboundInvocationHandler.java
  core/src/main/java/org/infinispan/util/concurrent/CommandAckCollector.java
  core/src/main/java/org/infinispan/util/logging/Log.java
  core/src/test/java/org/infinispan/util/mocks/ControlledCommandFactory.java
Labels: Trivial :-)
