Repository infinispan/infinispan, pull requests merged in 2023-09, with the labels that each got.

#11260 [14.0.x] ISPN-14814 ServerEventLogger blocks when creating a cache
  server/runtime/src/main/java/org/infinispan/server/LifecycleCallbacks.java
  server/runtime/src/main/java/org/infinispan/server/logging/events/ServerEventLogger.java
Labels: Image Required

#11264 Remove redundant test
  server/tests/src/test/java/org/infinispan/server/functional/MainIT.java
Labels: Trivial :-)

#11265 [14.0.x] ISPN-15089 Restart does not start cache from persisted configuration …
  core/src/main/java/org/infinispan/globalstate/impl/GlobalConfigurationManagerImpl.java
Labels: Image Required

#11270 ISPN-15144 Protostream 4.6.5
  core/src/test/java/org/infinispan/stats/SingleStatsTest.java
Labels: Trivial :-), Test fix, 14.0.x

#11269 ISPN-15155 Missing cross-site metrics
  core/src/main/java/org/infinispan/remoting/rpc/RpcManagerImpl.java
  server/tests/src/test/java/org/infinispan/server/functional/rest/XSiteRestMetricsOperations.java
  server/tests/src/test/resources/configuration/XSiteServerTest.xml
  server/tests/src/test/resources/configuration/cache-container/clustered-metric-names-as-tags.xml
Labels: 14.0.x

#11267 [14.0.x] ISPN-15151 Unable to upgrade if a backup has been restored on the older server
  core/src/main/java/org/infinispan/configuration/parsing/CacheParser.java
  server/runtime/src/main/java/org/infinispan/server/Server.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/AbstractInfinispanServerDriver.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/AbstractServerConfigBuilder.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/EmbeddedInfinispanServerDriver.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/InfinispanServerTestConfiguration.java
  server/tests/src/test/java/org/infinispan/server/functional/AbstractMultiClusterIT.java
  server/tests/src/test/java/org/infinispan/server/functional/DuplicateTemplateIT.java
  server/tests/src/test/resources/data/templates.xml
Labels: Backport, Image Required

#11262 ISPN-15147 DefaultExecutorFactory can create multiple ThreadGroups
  core/src/main/java/org/infinispan/executors/DefaultExecutorFactory.java
Labels: 14.0.x

#11278 [14.x] ISPN-15155 Missing cross-site metrics
  core/src/main/java/org/infinispan/remoting/rpc/RpcManagerImpl.java
  server/tests/src/test/java/org/infinispan/server/functional/XSiteRestMetricsOperations.java
  server/tests/src/test/resources/configuration/XSiteServerTest.xml
  server/tests/src/test/resources/configuration/cache-container/clustered-metric-names-as-tags.xml
Labels: Backport

#11268 ISPN-15111 mapping of HS5 annotations to Infinispan native
  documentation/src/main/asciidoc/stories/assembly_migrating_data.adoc
  documentation/src/main/asciidoc/topics/upgrading.adoc
Labels: Documentation, 14.0.x

#11248 ISPN-14731 dns resolver docs review
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/package-info.java
  client/hotrod/src/main/java/org/infinispan/hotrod/configuration/package-info.java
Labels: Trivial :-), Documentation, 14.0.x

#11151 ISPN-15026 Automatically map ADMIN and MONITOR permissions to JMX roles
  documentation/src/main/asciidoc/topics/proc_enabling_jmx_port.adoc
  quarkus/server/runtime/src/main/java/org/infinispan/quarkus/server/runtime/graal/SubstituteElytronClasses.java
  server/runtime/src/main/java/org/infinispan/server/Server.java
  server/runtime/src/main/java/org/infinispan/server/security/ElytronJMXAuthenticator.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/api/HotRodTestClientDriver.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/api/JmxTestClient.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/api/TestClientDriver.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/AbstractInfinispanServerDriver.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/EmbeddedInfinispanServerDriver.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/ForkedInfinispanServerDriver.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/ForkedServer.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/InfinispanServerDriver.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/TestClient.java
  server/testdriver/junit4/src/main/java/org/infinispan/server/test/junit4/InfinispanServerTestMethodRule.java
  server/testdriver/junit4/src/main/java/org/infinispan/server/test/junit4/InfinispanXSiteServerTestMethodRule.java
  server/testdriver/junit5/src/main/java/org/infinispan/server/test/junit5/AbstractServerExtension.java
  server/testdriver/junit5/src/main/java/org/infinispan/server/test/junit5/InfinispanServerExtension.java
  server/tests/src/test/java/org/infinispan/server/security/authorization/AuthorizationJMXIT.java
  server/tests/src/test/resources/configuration/AuthorizationJMXTest.xml
  server/tests/src/test/resources/configuration/cache-container/clustered-authz-jmx.xml
Labels: Changes Required

#11148 ISPN-15069 CVE-2023-4586 Hot Rod TLS Hostname validation
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheContainer.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ClusterConfiguration.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ClusterConfigurationBuilder.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/SslConfiguration.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/SslConfigurationBuilder.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/package-info.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/ConfigurationProperties.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/topology/ClusterInfo.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelFactory.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelInitializer.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/tcp/RoundRobinBalancingStrategy.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/jmx/RemoteCacheManagerMXBean.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/logging/Log.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/configuration/ConfigurationTest.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/impl/transport/netty/TestChannelFactory.java
  client/hotrod/src/main/java/org/infinispan/hotrod/configuration/ClusterConfiguration.java
  client/hotrod/src/main/java/org/infinispan/hotrod/configuration/ClusterConfigurationBuilder.java
  client/hotrod/src/main/java/org/infinispan/hotrod/configuration/SslConfiguration.java
  client/hotrod/src/main/java/org/infinispan/hotrod/configuration/SslConfigurationBuilder.java
  client/hotrod/src/main/java/org/infinispan/hotrod/configuration/package-info.java
  client/hotrod/src/main/java/org/infinispan/hotrod/impl/ConfigurationProperties.java
  client/hotrod/src/main/java/org/infinispan/hotrod/impl/logging/Log.java
  client/hotrod/src/main/java/org/infinispan/hotrod/impl/topology/ClusterInfo.java
  client/hotrod/src/main/java/org/infinispan/hotrod/impl/transport/netty/ChannelFactory.java
  client/hotrod/src/main/java/org/infinispan/hotrod/impl/transport/netty/ChannelInitializer.java
  client/hotrod/src/test/java/org/infinispan/hotrod/impl/transport/netty/HotRodTestTransport.java
  commons-test/src/main/java/org/infinispan/commons/test/security/TestCertificates.java
  documentation/src/main/asciidoc/topics/cmd_examples/keytool.adoc
  documentation/src/main/asciidoc/topics/proc_configuring_hotrod_encryption.adoc
  documentation/src/main/asciidoc/topics/proc_configuring_server_keystores.adoc
  documentation/src/main/asciidoc/topics/properties/hotrod-client-tls.properties
  documentation/src/main/asciidoc/topics/upgrading.adoc
  persistence/remote/src/main/java/org/infinispan/persistence/remote/RemoteStore.java
  persistence/remote/src/main/java/org/infinispan/persistence/remote/configuration/SslConfiguration.java
  persistence/remote/src/main/java/org/infinispan/persistence/remote/configuration/SslConfigurationBuilder.java
  persistence/remote/src/test/java/org/infinispan/persistence/remote/RemoteStoreSSLTest.java
  persistence/remote/src/test/java/org/infinispan/persistence/remote/upgrade/HotRodUpgradeDynamicWithSSLTest.java
  persistence/remote/src/test/java/org/infinispan/persistence/remote/upgrade/TestCluster.java
  server/core/src/main/java/org/infinispan/server/core/AbstractProtocolServer.java
  server/core/src/main/java/org/infinispan/server/core/transport/NettyChannelInitializer.java
  server/router/src/test/java/org/infinispan/server/router/integration/SinglePortTest.java
  server/runtime/src/main/java/org/infinispan/server/configuration/security/KeyStoreConfiguration.java
  server/runtime/src/main/java/org/infinispan/server/logging/Log.java
  server/runtime/src/main/java/org/infinispan/server/security/KeyStoreUtils.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/AbstractInfinispanServerDriver.java
  server/tests/src/test/java/org/infinispan/server/security/AuthenticationCertIT.java
  server/tests/src/test/java/org/infinispan/server/security/AuthenticationMultiRealmIT.java
  server/tests/src/test/java/org/infinispan/server/security/AuthenticationTLSBouncyCastleIT.java
  server/tests/src/test/java/org/infinispan/server/security/AuthenticationTLSIT.java
  server/tests/src/test/java/org/infinispan/server/security/CertWithoutAuthenticationIT.java
  server/tests/src/test/java/org/infinispan/server/security/TLSWithoutAuthenticationIT.java
  server/tests/src/test/java/org/infinispan/server/security/authorization/AuthorizationCertIT.java
Labels: 14.0.x

#11234 ISPN-15124 Better describe SQL store limitations
  documentation/src/main/asciidoc/topics/con_cache_store_sql.adoc
Labels: Documentation, 14.0.x

#11289 ISPN-15167 Upgrade JGroups to 5.2.19.Final
  build/configuration/pom.xml
Labels: Trivial :-), 14.0.x

#11292 ISPN-15169 SIFS PMEM logs exception every file opening in dev
  core/src/main/java/org/infinispan/persistence/sifs/FileProvider.java
Labels: Trivial :-)

#11284 ISPN-15166 SIFS rebuild index cannot compact file
  core/src/main/java/org/infinispan/persistence/sifs/Compactor.java
  core/src/main/java/org/infinispan/persistence/sifs/Index.java
  core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreRestartTest.java
Labels: 14.0.x

#11304 Fix RemoteSpringSessionTest
  spring/spring-boot-3/tests/src/test/java/test/infinispan/integration/remote/RemoteSpringSessionTest.java
Labels: Trivial :-), Test fix, 14.0.x

#11311 ISPN-15182 Quarkus 3.3.3
  build/configuration/pom.xml
Labels: Trivial :-)

#11312 ISPN-15183 SIFS remove with no key can cause stats to not track free …
  core/src/main/java/org/infinispan/persistence/sifs/Compactor.java
  core/src/main/java/org/infinispan/persistence/sifs/Index.java
  core/src/main/java/org/infinispan/persistence/sifs/IndexRequest.java
  core/src/main/java/org/infinispan/persistence/sifs/LogAppender.java
  core/src/main/java/org/infinispan/persistence/sifs/LogRequest.java
  core/src/main/java/org/infinispan/persistence/sifs/NonBlockingSoftIndexFileStore.java
  core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreRestartTest.java
Labels: 14.0.x

#11315 ISPN-15185 Updates console to 15.0.0.Dev03
  build/configuration/pom.xml
Labels: Trivial :-)

#11301 ISPN-15172 SIFS throws exception if told to compact a partially writt…
  core/src/main/java/org/infinispan/persistence/sifs/Compactor.java
  core/src/main/java/org/infinispan/persistence/sifs/EntryRecord.java
  core/src/main/java/org/infinispan/persistence/sifs/Log.java
  core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreCorruptRestartTest.java
Labels: 14.0.x

#11316 ISPN-15184 SIFS can leave many data files left around
  core/src/main/java/org/infinispan/persistence/sifs/Compactor.java
  core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreFileStatsTest.java
Labels: 14.0.x

#11293 ISPN-15173 Exceptional HEAD requests return a non-zero Content-Length…
  server/rest/src/main/java/org/infinispan/rest/ResponseWriter.java
  server/rest/src/main/java/org/infinispan/rest/RestRequestHandler.java
  server/rest/src/main/java/org/infinispan/rest/operations/exceptions/ServerInternalException.java
  server/rest/src/main/java/org/infinispan/rest/resources/BackupManagerResource.java
  server/rest/src/test/java/org/infinispan/rest/resources/ResourceExceptionHandlingTest.java
Labels: 14.0.x

#11328 ISPN-15192 Brand JavaDoc header and window title
  build/configuration/pom.xml
  javadoc/pom.xml
Labels: Trivial :-), 14.0.x

#11313 ISPN-15181 Deadlock when creating caches with a zero-capacity node an…
  core/src/main/java/org/infinispan/globalstate/impl/GlobalConfigurationStateListener.java
  core/src/main/java/org/infinispan/topology/CacheJoinInfo.java
  core/src/main/java/org/infinispan/topology/ClusterCacheStatus.java
  core/src/test/java/org/infinispan/distribution/ZeroCapacityAdministrationTest.java
Labels: 14.0.x

#11335 ISPN-15195 Support x86_64 for mac
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/Containers.java
Labels: Trivial :-), 14.0.x

#11302 [14.0] ISPN-11125 Convert L1 to be non blocking
  core/src/main/java/org/infinispan/interceptors/distribution/L1NonTxInterceptor.java
  core/src/main/java/org/infinispan/util/concurrent/CompletionStages.java
Labels: Backport

#11337 ISPN-15197 Near Cache With Bloom Filter enabled doesn't work properly…
  client/hotrod-client/pom.xml
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/InvalidatedNearRemoteCache.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/NearCacheMarshallingTest.java
  core/src/main/java/org/infinispan/notifications/cachelistener/filter/KeyValueFilterConverterAsCacheEventFilterConverter.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/ClientListenerRegistry.java
Labels: 14.0.x
