Repository infinispan/infinispan, pull requests merged in 2023-10, with the labels that each got.

#11272 ISPN-15156 Avoid to spam DEBUG log when OpenTelemetry is not found on the client
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/OperationsFactory.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/logging/Log.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/telemetry/impl/TelemetryService.java
  client/hotrod/src/main/java/org/infinispan/hotrod/impl/logging/Log.java
  client/hotrod/src/main/java/org/infinispan/hotrod/impl/operations/CacheOperationsFactory.java
  client/hotrod/src/main/java/org/infinispan/hotrod/telemetry/impl/TelemetryService.java
Labels: 14.0.x

#11350 Update Hibernate Search to 6.2.2.Final
  build/configuration/pom.xml
Labels: Trivial :-)

#11347 ISPN-15205 RemoteStoreConfigWithContainersTest test failure
  persistence/remote/src/test/java/org/infinispan/persistence/remote/RemoteStoreConfigTest.java
  persistence/remote/src/test/java/org/infinispan/persistence/remote/RemoteStoreConfigWithContainersTest.java
  persistence/remote/src/test/resources/remotestore-with-containers.xml
Labels: Trivial :-), Test fix

#11351 ISPN-15206 Fix ClusterListenerReplTest#testPrimaryOwnerGoesDownBefore…
  core/src/test/java/org/infinispan/notifications/cachelistener/cluster/AbstractClusterListenerNonTxTest.java
  core/src/test/java/org/infinispan/notifications/cachelistener/cluster/ClusterListenerReplTest.java
Labels: Test fix, 14.0.x

#11353 ISPN-15201 PreferConsistencyStrategy throws UnsupportedOperationExcep…
  core/src/main/java/org/infinispan/partitionhandling/impl/PreferConsistencyStrategy.java
  core/src/test/java/org/infinispan/distribution/ZeroCapacityNodeTest.java
Labels: 14.0.x

#11325 [11.0] ISPN-15147 DefaultExecutorFactory can create multiple ThreadGroups
  core/src/main/java/org/infinispan/factories/threads/BlockingThreadFactory.java
  core/src/main/java/org/infinispan/factories/threads/NonBlockingThreadFactory.java
Labels: Backport

#11342 ISPN-15199 Expose needed parameters for the console
  documentation/src/main/asciidoc/topics/json/rest_full_cache_detail.json
  server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
  server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
Labels: Urgent!, 14.0.x

#11361 ISPN-15197 Near Cache With Bloom Filter enabled doesn't work properly…
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/ClusterNearCacheMarshallingTest.java
  core/src/main/java/org/infinispan/notifications/cachelistener/filter/KeyValueFilterConverterAsCacheEventFilterConverter.java
Labels: 14.0.x

#11297 [14.0] ISPN-15069 More flexible SNI from the client
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheContainer.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ClusterConfiguration.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ClusterConfigurationBuilder.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/SslConfiguration.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/SslConfigurationBuilder.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/package-info.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/ConfigurationProperties.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/topology/ClusterInfo.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelFactory.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelInitializer.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/tcp/RoundRobinBalancingStrategy.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/jmx/RemoteCacheManagerMXBean.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/logging/Log.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/configuration/ConfigurationTest.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/impl/transport/netty/TestChannelFactory.java
  client/hotrod/src/main/java/org/infinispan/hotrod/configuration/ClusterConfiguration.java
  client/hotrod/src/main/java/org/infinispan/hotrod/configuration/ClusterConfigurationBuilder.java
  client/hotrod/src/main/java/org/infinispan/hotrod/configuration/SslConfiguration.java
  client/hotrod/src/main/java/org/infinispan/hotrod/configuration/SslConfigurationBuilder.java
  client/hotrod/src/main/java/org/infinispan/hotrod/configuration/package-info.java
  client/hotrod/src/main/java/org/infinispan/hotrod/impl/ConfigurationProperties.java
  client/hotrod/src/main/java/org/infinispan/hotrod/impl/logging/Log.java
  client/hotrod/src/main/java/org/infinispan/hotrod/impl/topology/ClusterInfo.java
  client/hotrod/src/main/java/org/infinispan/hotrod/impl/transport/netty/ChannelFactory.java
  client/hotrod/src/main/java/org/infinispan/hotrod/impl/transport/netty/ChannelInitializer.java
  client/hotrod/src/test/java/org/infinispan/hotrod/impl/transport/netty/HotRodTestTransport.java
  commons-test/src/main/java/org/infinispan/commons/test/security/TestCertificates.java
  documentation/src/main/asciidoc/topics/cmd_examples/keytool.adoc
  documentation/src/main/asciidoc/topics/proc_configuring_server_keystores.adoc
  documentation/src/main/asciidoc/topics/upgrading.adoc
  persistence/remote/src/main/java/org/infinispan/persistence/remote/RemoteStore.java
  persistence/remote/src/main/java/org/infinispan/persistence/remote/configuration/SslConfiguration.java
  persistence/remote/src/main/java/org/infinispan/persistence/remote/configuration/SslConfigurationBuilder.java
  persistence/remote/src/test/java/org/infinispan/persistence/remote/RemoteStoreSSLTest.java
  persistence/remote/src/test/java/org/infinispan/persistence/remote/upgrade/HotRodUpgradeDynamicWithSSLTest.java
  persistence/remote/src/test/java/org/infinispan/persistence/remote/upgrade/TestCluster.java
  server/core/src/main/java/org/infinispan/server/core/AbstractProtocolServer.java
  server/core/src/main/java/org/infinispan/server/core/transport/NettyChannelInitializer.java
  server/router/src/test/java/org/infinispan/server/router/integration/SinglePortTest.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/AbstractInfinispanServerDriver.java
  server/tests/src/test/java/org/infinispan/server/security/AuthenticationCertIT.java
  server/tests/src/test/java/org/infinispan/server/security/AuthenticationMultiRealmIT.java
  server/tests/src/test/java/org/infinispan/server/security/AuthenticationTLSBouncyCastleIT.java
  server/tests/src/test/java/org/infinispan/server/security/AuthenticationTLSIT.java
  server/tests/src/test/java/org/infinispan/server/security/CertWithoutAuthenticationIT.java
  server/tests/src/test/java/org/infinispan/server/security/TLSWithoutAuthenticationIT.java
  server/tests/src/test/java/org/infinispan/server/security/authorization/AuthorizationCertIT.java
Labels: Backport

#11339 [14.0] ISPN-14759 SoftIndexFileStore Index can lag behind LogAppender under heavy load
  core/src/main/java/org/infinispan/persistence/sifs/Index.java
  core/src/main/java/org/infinispan/persistence/sifs/IndexNode.java
Labels: Backport

#11370 [14.0] RemoteSpringSessionTest fix
  integrationtests/spring-boot-it/src/test/java/org/infinispan/integrationtests/spring/boot/session/remote/RemoteSpringSessionTest.java
Labels: Trivial :-), Test fix

#11372 [14.0] ISPN-15223 updates console to 14.0.12.Final
  build/configuration/pom.xml
Labels: Trivial :-)

#11363 [14.0.x] ISPN-15208 IRAC state transfer may skip data
  core/src/main/java/org/infinispan/xsite/irac/DefaultIracManager.java
Labels: Backport

#11376 [14.0] ISPN-15223 updates console to 14.0.13.Final
  build/configuration/pom.xml
Labels: Urgent!

#11378 [14.0] ISPN-15229 CVE-2023-4487 HTTP/2 Rapid Reset Attack
  build/configuration/pom.xml
Labels: CVE

#11379 [13.0] ISPN-15229 CVE-2023-4487 HTTP/2 Rapid Reset Attack
  build-configuration/pom.xml
Labels: CVE

#11380 [12.0] ISPN-15229 CVE-2023-4487 HTTP/2 Rapid Reset Attack
  build-configuration/pom.xml
Labels: CVE

#11377 ISPN-15229 CVE-2023-4487 HTTP/2 Rapid Reset Attack
  build/configuration/pom.xml
Labels: CVE

#11364 ISPN-15214 Do not instantiate TriangleOrderManager if not required.
  core/src/main/java/org/infinispan/statetransfer/StateConsumerImpl.java
  core/src/test/java/org/infinispan/statetransfer/StateConsumerTest.java
Labels: Trivial :-), Changes Required

#11394 [14.x] ISPN-15214 Do not instantiate TriangleOrderManager if not required.
  core/src/main/java/org/infinispan/scattered/impl/ScatteredStateConsumerImpl.java
  core/src/main/java/org/infinispan/statetransfer/StateConsumerImpl.java
  core/src/test/java/org/infinispan/statetransfer/StateConsumerTest.java
Labels: Backport

#11390 [14.0] ISPN-15227 SIFS expiration compation writes WARN message for concurre…
  core/src/main/java/org/infinispan/persistence/sifs/Compactor.java
  core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreTest.java
Labels: Backport

#11393 ISPN-15238 Backup write operations should ignore previous value
  core/src/main/java/org/infinispan/interceptors/distribution/BaseDistributionInterceptor.java
Labels: 14.0.x

#11391 ISPN-15232 Index may receive NegativeArraySizeException
  core/src/main/java/org/infinispan/persistence/sifs/IndexNode.java
Labels: 14.0.x

#11400 ISPN-15248 Use @DirtiesContext on Spring tests to force cache manager…
  spring/spring-boot-3/tests/src/test/java/test/infinispan/autoconfigure/CacheDisabledTest.java
  spring/spring-boot-3/tests/src/test/java/test/infinispan/autoconfigure/CacheManagerTest.java
  spring/spring-boot-3/tests/src/test/java/test/infinispan/integration/embedded/EmbeddedSpringSessionTest.java
  spring/spring-boot-3/tests/src/test/java/test/infinispan/integration/remote/RemoteSpringSessionTest.java
Labels: Trivial :-), Test fix, 14.0.x

#11404 ISPN-15351 Resp TIME command
  documentation/src/main/asciidoc/topics/ref_redis_commands.adoc
  server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java
  server/resp/src/main/java/org/infinispan/server/resp/commands/generic/TIME.java
  server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java
Labels: Needs Rebase

#11407 [14.0] ISPN-14784 Use java.security.manager=allow to run SecurityManager tes…
  integrationtests/security-manager-it/pom.xml
Labels: Test fix

#11403 fixing rest path in the docs
  documentation/src/main/asciidoc/topics/proc_making_caches_available.adoc
  documentation/src/main/asciidoc/topics/proc_query_getting_statistics.adoc
  documentation/src/main/asciidoc/topics/proc_setting_up_target_clusters.adoc
  documentation/src/main/asciidoc/topics/proc_synchronizing_data_target_clusters.adoc
  documentation/src/main/asciidoc/topics/ref_rest_caches_query.adoc
  documentation/src/main/asciidoc/topics/upgrading.adoc
Labels: Documentation, 14.0.x

#11402 ISPN-15241 fix property name to connection-pooling
  documentation/src/main/asciidoc/topics/ref_server_realm_ldap.adoc
  server/runtime/src/main/resources/schema/infinispan-server-15.0.xsd
Labels: Documentation, 14.0.x

#11417 [14.0] ISPN-15260 SingleStatsTest failure
  core/src/test/java/org/infinispan/stats/SingleStatsTest.java
Labels: Test fix

#11426 [14.0] ISPN-14849 ChannelLookupTest is failing
  build/configuration/pom.xml
  core/src/test/java/org/infinispan/remoting/jgroups/ChannelLookupTest.java
Labels: Test fix

#11422 ISPN-15239 HotRod client repeatedly retries iteration operation again…
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/iteration/RemoteInnerPublisherHandler.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/iteration/RemotePublisher.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/impl/iteration/BaseIterationFailOverTest.java
  client/hotrod/src/main/java/org/infinispan/hotrod/impl/iteration/RemoteInnerPublisherHandler.java
Labels: 14.0.x

#11435 ISPN-15270 WriteSkewConsistencyTest random failures
  core/src/test/java/org/infinispan/container/versioning/WriteSkewConsistencyTest.java
Labels: Test fix, 14.0.x

#11436 ISPN-15273 XSiteMBeanTest fails randomly
  core/src/test/java/org/infinispan/jmx/XSiteMBeanTest.java
Labels: Test fix, 14.0.x

#11433 ISPN-15262 IndexedTests can fail on clear due to blocking call
  core/src/main/java/org/infinispan/util/CoreBlockHoundIntegration.java
Labels: 14.0.x

#11411 ISPN-15255 Use clustered stats component
  core/src/main/java/org/infinispan/stats/Stats.java
  core/src/main/java/org/infinispan/stats/impl/ClusterCacheStatsImpl.java
  core/src/main/java/org/infinispan/stats/impl/StatsImpl.java
  server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
Labels: 14.0.x
