Repository infinispan/infinispan, pull requests merged in 2023-12, with the labels that each got.

#11510 ISPN-15322 Server iteration manager using wrong storage and request t…
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/impl/iteration/BaseMultiServerRemoteIteratorTest.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/impl/iteration/MediaTypeMultiServerRemoteIteratorTest.java
  server/core/src/main/java/org/infinispan/server/iteration/DefaultIterationManager.java
Labels: 14.0.x

#11556 [14.0.x] ISPN-15240 Improve cross-site message handling
  commons-test/src/main/java/org/infinispan/commons/test/ThreadLeakChecker.java
  commons/all/src/main/java/org/infinispan/commons/CrossSiteIllegalLifecycleStateException.java
  core/src/main/java/org/infinispan/commands/irac/IracCleanupKeysCommand.java
  core/src/main/java/org/infinispan/factories/GlobalComponentRegistry.java
  core/src/main/java/org/infinispan/remoting/inboundhandler/GlobalInboundInvocationHandler.java
  core/src/main/java/org/infinispan/remoting/transport/ResponseCollectors.java
  core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
  core/src/main/java/org/infinispan/util/logging/Log.java
  core/src/main/java/org/infinispan/xsite/commands/remote/XSiteCacheRequest.java
  core/src/main/java/org/infinispan/xsite/events/XSiteEventSender.java
  core/src/main/java/org/infinispan/xsite/events/XSiteEventsManagerImpl.java
  core/src/main/java/org/infinispan/xsite/status/DefaultTakeOfflineManager.java
  core/src/test/java/org/infinispan/util/ControlledRpcManager.java
  core/src/test/java/org/infinispan/xsite/offline/InvalidConfigurationOfflineTest.java
  core/src/test/java/org/infinispan/xsite/statetransfer/XSiteAutoStateTransferTest.java
Labels: Backport

#11562 ISPN-14974 Fix opentelemetry-sdk-common dep version
  pom.xml
Labels: Urgent!

#11550 ISPN-15351 Check if MetricsRegistry is enabled before trying to regis…
  core/src/main/java/org/infinispan/metrics/impl/MetricsComponentFactory.java
  core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
Labels: Trivial :-), 14.0.x

#11563 ISPN-14974 Try to remove AndroidFriendlyRandomHolder from native
  quarkus/pom.xml
  quarkus/server/runtime/src/main/java/org/infinispan/quarkus/server/runtime/graal/DeleteOpenTelemetryUnused.java
Labels: Urgent!

#11560 [10.1.x] ISPN-13229 LocalPublisherManagerImpl doesn't clean up changeListener …
  core/src/main/java/org/infinispan/reactive/publisher/impl/LocalPublisherManagerImpl.java
Labels: Changes Required

#11566 ISPN-15379 Quarkus build args are ignored when the distribution profi…
  quarkus/cli/pom.xml
  quarkus/pom.xml
Labels: Trivial :-)

#11568 ISPN-15380 Remove unused org.infinispan.distribution.group.impl.Group…
  core/src/main/java/org/infinispan/distribution/group/impl/GroupFilter.java
Labels: Trivial :-)

#11547 ISPN-15076 CacheStream NPE in a tx with entryReduction
  core/src/main/java/org/infinispan/reactive/RxJavaInterop.java
  core/src/main/java/org/infinispan/reactive/publisher/impl/LocalClusterPublisherManagerImpl.java
  core/src/test/java/org/infinispan/stream/BaseStreamTest.java
  core/src/test/java/org/infinispan/stream/LocalTxStreamTest.java
Labels: 14.0.x

#11567 ISPN-15372 infinispan-tools artifact is included in BOM but not publi…
  pom.xml
  tools/pom.xml
Labels: 14.0.x

#11571 [14.0.x] ISPN-15373 Enable insight profile is community release profile is dis…
  Jenkinsfile
  Jenkinsfile-release
  build/bom/pom.xml
  build/configuration/pom.xml
  client/marshaller/kryo/kryo-marshaller-compatibility-bundle/pom.xml
  client/marshaller/pom.xml
  client/marshaller/protostuff/protostuff-marshaller-compatibility-bundle/pom.xml
  pom.xml
  server/runtime/pom.xml
  server/tests/pom.xml
Labels: Trivial :-), Backport

#11555 ISPN-15202 Mask Hot Rod and database credentials when serializing con…
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/HotRodURI.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/configuration/ConfigurationTest.java
  client/hotrod/src/main/java/org/infinispan/hotrod/impl/HotRodURI.java
  commons/all/src/main/java/org/infinispan/commons/configuration/BasicConfiguration.java
  commons/all/src/main/java/org/infinispan/commons/configuration/StringConfiguration.java
  commons/all/src/main/java/org/infinispan/commons/configuration/attributes/AttributeSerializer.java
  core/src/main/java/org/infinispan/configuration/cache/Configuration.java
  core/src/main/java/org/infinispan/globalstate/impl/GlobalConfigurationManagerImpl.java
  persistence/jdbc-common/src/main/java/org/infinispan/persistence/jdbc/common/configuration/AbstractJdbcStoreConfigurationSerializer.java
  persistence/jdbc-common/src/main/java/org/infinispan/persistence/jdbc/common/configuration/AbstractUnmanagedConnectionFactoryConfiguration.java
  persistence/jdbc-common/src/main/java/org/infinispan/persistence/jdbc/common/configuration/ConnectionFactoryConfiguration.java
  persistence/jdbc-common/src/main/java/org/infinispan/persistence/jdbc/common/configuration/PooledConnectionFactoryConfigurationBuilder.java
  persistence/jdbc-common/src/main/java/org/infinispan/persistence/jdbc/common/configuration/SimpleConnectionFactoryConfigurationBuilder.java
  persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/configuration/ConfigurationSerializerTest.java
  persistence/remote/src/main/java/org/infinispan/persistence/remote/configuration/KeyStoreConfiguration.java
  persistence/remote/src/main/java/org/infinispan/persistence/remote/configuration/MechanismConfiguration.java
  persistence/remote/src/main/java/org/infinispan/persistence/remote/configuration/RemoteStoreConfiguration.java
  persistence/remote/src/main/java/org/infinispan/persistence/remote/configuration/SslConfiguration.java
  persistence/remote/src/main/java/org/infinispan/persistence/remote/configuration/TrustStoreConfiguration.java
  persistence/remote/src/main/java/org/infinispan/persistence/remote/upgrade/SerializationUtils.java
  persistence/sql/src/test/java/org/infinispan/persistence/sql/configuration/ConfigurationSerializerTest.java
  server/tests/src/test/java/org/infinispan/server/persistence/JdbcConfigurationUtil.java
  server/tests/src/test/java/org/infinispan/server/persistence/JdbcStringBasedCacheStorePassivation.java
Labels: CVE

#11548 ISPN-15362 SoftIndexFileStoreFileStatsTest#testExpirationCompactionOn…
  core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreFileStatsTest.java
Labels: 14.0.x

#11616 ISPN-15406-The TLS v1.2 and v1.3 supported ciphers Updated
  documentation/src/main/asciidoc/topics/json/server_ssl_identity_engine.json
  documentation/src/main/asciidoc/topics/xml/server_ssl_identity_engine.xml
Labels: Documentation, 14.0.x

#11622 ISPN-15401 Remove worker-threads section from tuning guide
  documentation/src/main/asciidoc/topics/ref_performance_tuning.adoc
  documentation/src/main/asciidoc/topics/xml/hotrod_worker_threads.xml
  server/hotrod/src/main/java/org/infinispan/server/hotrod/configuration/HotRodServerConfiguration.java
Labels: Trivial :-), Documentation, 14.0.x

#11624 ISPN-15402 JGroups Raft 1.0.12.Final
  build/configuration/pom.xml
Labels: dependencies, java

#11621 ISPN-15403 JGroupsTransport: address generator impl misses method
  core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTopologyAwareAddress.java
  core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
  server/runtime/src/main/server/server/conf/infinispan-xsite.xml
Labels: Trivial :-), 14.0.x
