Repository infinispan/infinispan, pull requests merged in 2023-11, with the labels that each got.

#11452 ISPN-15293 Upgrade JGroups to 5.3.0.Final
  build/configuration/pom.xml
Labels: Trivial :-)

#11398 ISPN-14877 Added possibility to configure REST client using properties
  cli/src/main/java/org/infinispan/cli/Context.java
  cli/src/main/java/org/infinispan/cli/commands/Connect.java
  cli/src/main/java/org/infinispan/cli/connection/ConnectionFactory.java
  cli/src/main/java/org/infinispan/cli/connection/Connector.java
  cli/src/main/java/org/infinispan/cli/connection/rest/RestConnector.java
  cli/src/main/java/org/infinispan/cli/impl/ContextImpl.java
  cli/src/main/resources/help/connect.adoc
  cli/src/test/java/org/infinispan/cli/connection/rest/RestConnectorTest.java
  client/rest-client/src/main/java/org/infinispan/client/rest/configuration/RestClientConfigurationBuilder.java
  client/rest-client/src/main/java/org/infinispan/client/rest/configuration/RestClientConfigurationProperties.java
  client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestClientOkHttp.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/api/RestTestClientDriver.java
  server/tests/src/test/java/org/infinispan/server/cli/CliIT.java
  server/tests/src/test/java/org/infinispan/server/security/AuthenticationMultiEndpointIT.java
  server/tests/src/test/resources/configuration/AuthorizationImplicitTest.xml
  server/tests/src/test/resources/configuration/endpoints/alternate-hotrod.xml
Labels: Question, 14.0.x

#11443 ISPN-15277 Default ConcurrentMap methods should ensure they close Ite…
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheEntrySet.java
Labels: 14.0.x

#11382 [14.x] ISPN-15029 Create metrics for latency between nodes
  build/component-processor/src/main/java/org/infinispan/component/processor/external/JGroupsComponentProcessor.java
  commons/all/src/main/java/org/infinispan/commons/stat/BaseMetricInfo.java
  commons/all/src/main/java/org/infinispan/commons/stat/BaseSetterMetricInfo.java
  commons/all/src/main/java/org/infinispan/commons/stat/CounterMetricInfo.java
  commons/all/src/main/java/org/infinispan/commons/stat/CounterTracker.java
  commons/all/src/main/java/org/infinispan/commons/stat/DistributionSummaryMetricInfo.java
  commons/all/src/main/java/org/infinispan/commons/stat/DistributionSummaryTracker.java
  commons/all/src/main/java/org/infinispan/commons/stat/FunctionTimerMetricInfo.java
  commons/all/src/main/java/org/infinispan/commons/stat/GaugeMetricInfo.java
  commons/all/src/main/java/org/infinispan/commons/stat/MetricInfo.java
  commons/all/src/main/java/org/infinispan/commons/stat/TimeGaugeMetricInfo.java
  commons/all/src/main/java/org/infinispan/commons/stat/TimerMetricInfo.java
  core/src/main/java/org/infinispan/factories/impl/MBeanMetadata.java
  core/src/main/java/org/infinispan/metrics/Constants.java
  core/src/main/java/org/infinispan/metrics/impl/AbstractMetricsRegistration.java
  core/src/main/java/org/infinispan/metrics/impl/CacheManagerMetricsRegistration.java
  core/src/main/java/org/infinispan/metrics/impl/CacheMetricsRegistration.java
  core/src/main/java/org/infinispan/metrics/impl/CounterTrackerImpl.java
  core/src/main/java/org/infinispan/metrics/impl/CustomMetricsSupplier.java
  core/src/main/java/org/infinispan/metrics/impl/DistributionSummaryTrackerImpl.java
  core/src/main/java/org/infinispan/metrics/impl/FunctionTimerTrackerImpl.java
  core/src/main/java/org/infinispan/metrics/impl/MetricUtils.java
  core/src/main/java/org/infinispan/metrics/impl/MetricsCollector.java
  core/src/main/java/org/infinispan/metrics/impl/MetricsCollectorFactory.java
  core/src/main/java/org/infinispan/metrics/impl/MetricsComponentFactory.java
  core/src/main/java/org/infinispan/metrics/impl/MetricsRegistry.java
  core/src/main/java/org/infinispan/metrics/impl/MetricsRegistryImpl.java
  core/src/main/java/org/infinispan/metrics/impl/NoMetricRegistry.java
  core/src/main/java/org/infinispan/remoting/rpc/RpcManagerImpl.java
  core/src/main/java/org/infinispan/remoting/transport/impl/MultiTargetRequest.java
  core/src/main/java/org/infinispan/remoting/transport/impl/SingleTargetRequest.java
  core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsMetricsManager.java
  core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsMetricsManagerImpl.java
  core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
  core/src/main/java/org/infinispan/remoting/transport/jgroups/NoOpJGroupsMetricManager.java
  core/src/main/java/org/infinispan/remoting/transport/jgroups/NoOpRequestTracker.java
  core/src/main/java/org/infinispan/remoting/transport/jgroups/RequestTracker.java
  core/src/main/java/org/infinispan/remoting/transport/jgroups/StaggeredRequest.java
  core/src/main/java/org/infinispan/util/logging/Log.java
  core/src/main/java/org/infinispan/xsite/XSiteAdminOperations.java
  core/src/main/java/org/infinispan/xsite/status/DefaultTakeOfflineManager.java
  core/src/main/java/org/infinispan/xsite/status/TakeOfflineManager.java
  core/src/test/java/org/infinispan/metrics/ClusteredCacheManagerMetricsTest.java
  core/src/test/java/org/infinispan/remoting/jgroups/ChannelLookupTest.java
  server/rest/src/main/java/org/infinispan/rest/InvocationHelper.java
  server/rest/src/main/java/org/infinispan/rest/resources/MetricsResource.java
  server/tests/src/test/java/org/infinispan/server/functional/rest/RestMetricsResource.java
  server/tests/src/test/java/org/infinispan/server/functional/rest/XSiteRestMetricsOperations.java
Labels: Backport

#11420 The fix solves the problem with an invalid connection to the jdbc dat…
  persistence/jdbc-common/src/main/java/org/infinispan/persistence/jdbc/common/impl/connectionfactory/PooledConnectionFactory.java
Labels: 14.0.x

#11469 ISPN-15299 PutAll during rebalance can get a ClassCastException
  core/src/main/java/org/infinispan/commands/write/PutMapCommand.java
  core/src/main/java/org/infinispan/interceptors/distribution/BaseDistributionInterceptor.java
  core/src/test/java/org/infinispan/statetransfer/PutAllDuringJoinTest.java
Labels: 14.0.x

#11477 [14.0] ISPN-13986 Fix test to search on remote query
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/aggregation/RemoteQueryAggregationCountTest.java
Labels: Test fix

#11473 ISPN-15307 Reduce the number of servers in cross-site IT tests
  server/tests/src/test/java/org/infinispan/server/functional/ClusteredIT.java
  server/tests/src/test/java/org/infinispan/server/functional/XSiteIT.java
  server/tests/src/test/java/org/infinispan/server/functional/rest/RestMetricsResourceIT.java
  server/tests/src/test/java/org/infinispan/server/functional/rest/XSiteRestMetricsOperations.java
Labels: Trivial :-), 14.0.x

#11476 ISPN-15310 Fix object-filter shaded dependencies
  build/configuration/pom.xml
  object-filter/pom.xml
Labels: 14.0.x

#11483 ISPN-15072 Exclude global connections from Micrometer
  server/core/src/main/java/org/infinispan/server/core/transport/NettyTransport.java
Labels: 14.0.x

#11471 ISPN-15272 Deadlock during expiration of entries with local cache and…
  commons-test/src/main/java/org/infinispan/commons/test/ThreadLeakChecker.java
  core/src/main/java/org/infinispan/expiration/impl/ExpirationManagerImpl.java
  core/src/test/java/org/infinispan/persistence/BaseStoreFunctionalTest.java
  persistence/remote/src/test/java/org/infinispan/persistence/remote/RemoteStoreFunctionalTest.java
Labels: 14.0.x

#11486 [14.0.x] ISPN-15304 Virtual Threads improvements
  commons/all/src/main/java/org/infinispan/commons/jdkspecific/ThreadCreator.java
  commons/jdk21/src/main/java/org/infinispan/commons/jdk21/ThreadCreatorImpl.java
  commons/spi/src/main/java/org/infinispan/commons/spi/ThreadCreator.java
  core/src/main/java/org/infinispan/factories/threads/DefaultThreadFactory.java
  core/src/main/java/org/infinispan/factories/threads/EnhancedQueueExecutorFactory.java
  core/src/main/resources/default-configs/default-jgroups-azure.xml
  core/src/main/resources/default-configs/default-jgroups-ec2.xml
  core/src/main/resources/default-configs/default-jgroups-google.xml
  core/src/main/resources/default-configs/default-jgroups-kubernetes.xml
  core/src/main/resources/default-configs/default-jgroups-tcp.xml
  core/src/main/resources/default-configs/default-jgroups-udp.xml
  core/src/test/java/org/infinispan/test/AbstractInfinispanTest.java
  core/src/test/resources/configs/config-with-jgroups-stack.xml
  core/src/test/resources/configs/xsite/bridge.xml
  core/src/test/resources/stacks/tcp.xml
  core/src/test/resources/stacks/tcp_mping/tcp1.xml
  core/src/test/resources/stacks/tcp_mping/tcp2.xml
  core/src/test/resources/stacks/udp.xml
  hibernate/cache-commons/src/test/resources/2lc-test-tcp.xml
  pom.xml
  server/core/src/main/java/org/infinispan/server/core/factories/NettyEventLoopFactory.java
  server/testdriver/junit5/src/test/resources/jgroups/xsite-stacks.xml
  server/tests/src/test/resources/configuration/jgroups/xsite-stacks.xml
Labels: Backport

#11446 ISPN-15282 Handle varying numeric precision in SQL store
  core/src/test/java/org/infinispan/test/TestDataSCI.java
  core/src/test/java/org/infinispan/test/data/Numerics.java
  persistence/sql/src/main/java/org/infinispan/persistence/sql/AbstractSchemaJdbcStore.java
  persistence/sql/src/main/java/org/infinispan/persistence/sql/QueriesJdbcStore.java
  persistence/sql/src/main/java/org/infinispan/persistence/sql/TableJdbcStore.java
  persistence/sql/src/test/java/org/infinispan/persistence/sql/AbstractSQLStoreFunctionalTest.java
  persistence/sql/src/test/java/org/infinispan/persistence/sql/QueriesJdbcStoreFunctionalTest.java
Labels: 14.0.x

#11480 ISPN-15309 Hot Rod client should use server key media-type to route r…
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/DataFormat.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/DelegatingRemoteCache.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/InternalRemoteCache.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheImpl.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/StreamingRemoteCacheImpl.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/iteration/SegmentKeyTracker.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/operations/AbstractKeyOperation.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelFactory.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelOperation.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/logging/Log.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/marshall/MediaTypeMarshaller.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/hash/ConsistentHashTest.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/impl/iteration/BaseMultiServerRemoteIteratorTest.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/impl/iteration/MediaTypeMultiServerRemoteIteratorTest.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/impl/iteration/MultiServerDistRemoteIteratorTest.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/impl/iteration/Util.java
Labels: 14.0.x

#11501 ISPN-15327 Cleanup server/resp/pom.xml from metadata
  server/resp/pom.xml
Labels: Trivial :-)

#11428 ISPN-15240 Improve cross-site message handling
  commons-test/src/main/java/org/infinispan/commons/test/ThreadLeakChecker.java
  commons/all/src/main/java/org/infinispan/commons/CrossSiteIllegalLifecycleStateException.java
  core/src/main/java/org/infinispan/commands/irac/IracCleanupKeysCommand.java
  core/src/main/java/org/infinispan/factories/GlobalComponentRegistry.java
  core/src/main/java/org/infinispan/remoting/inboundhandler/GlobalInboundInvocationHandler.java
  core/src/main/java/org/infinispan/remoting/transport/ResponseCollectors.java
  core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
  core/src/main/java/org/infinispan/util/logging/Log.java
  core/src/main/java/org/infinispan/xsite/commands/remote/XSiteCacheRequest.java
  core/src/main/java/org/infinispan/xsite/events/XSiteEventSender.java
  core/src/main/java/org/infinispan/xsite/events/XSiteEventsManagerImpl.java
  core/src/main/java/org/infinispan/xsite/status/DefaultTakeOfflineManager.java
  core/src/test/java/org/infinispan/util/ControlledRpcManager.java
  core/src/test/java/org/infinispan/xsite/offline/InvalidConfigurationOfflineTest.java
  core/src/test/java/org/infinispan/xsite/statetransfer/XSiteAutoStateTransferTest.java
Labels: 14.0.x

#11492 ISPN-15315 docs refinement to upgraidng guide, HR property defaults
  documentation/src/main/asciidoc/topics/upgrading.adoc
Labels: Trivial :-), Documentation, 14.0.x

#11515 ISPN-15338 Updates to console 15.0.0.Dev04
  build/configuration/pom.xml
Labels: Trivial :-)

#11518 ISPN-15342 Custom Keycloak images may not have admin console enabled
  server/tests/src/test/java/org/infinispan/server/test/core/KeyCloakServerExtension.java
Labels: 14.0.x

#11494 ISPN-15328 Use -XX:EnableDynamicAgentLoading on JDK 21 for ByteBuddy
  pom.xml
Labels: Changes Required

#11523 fix html rendering in HR package-info.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/package-info.java
  client/hotrod/src/main/java/org/infinispan/hotrod/configuration/package-info.java
Labels: Documentation, 14.0.x

#11511 ISPN-15317 Unable to query cached records with custom key objects tha…
  persistence/sql/src/test/java/org/infinispan/persistence/sql/AbstractSQLStoreFunctionalTest.java
  persistence/sql/src/test/java/org/infinispan/persistence/sql/QueriesJdbcStoreFunctionalTest.java
Labels: 14.0.x

#11526 ISPN-15315 fix property names in upgrading doc
  documentation/src/main/asciidoc/topics/upgrading.adoc
Labels: Trivial :-), Documentation, 14.0.x

#11531 ISPN-15117 Cache local address after connect
  core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
  core/src/test/java/org/infinispan/test/transport/DelayedViewJGroupsTransport.java
Labels: Trivial :-), 14.0.x

#11527 [12.1.x]fix documentation build for Embedded guide
  documentation/src/main/asciidoc/stories/assembly_embedding.adoc
Labels: Documentation

#11535 ISPN-15349 NPE from stats with multimap in server mode
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/multimap/RemoteMultimapStateTransferTest.java
  core/src/main/java/org/infinispan/interceptors/distribution/BaseDistributionInterceptor.java
Labels: 14.0.x

#11536 ISPN-15303 JGroupsTransport.getMembersPhysicalAddresses() throws an I…
  core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
Labels: Trivial :-), 14.0.x

#11540 ISPN-15349 NPE from stats with multimap in server mode
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/multimap/RemoteMultimapStateTransferTest.java
Labels: Trivial :-), Test fix
