Repository infinispan/infinispan, pull requests merged in 2023-02, with the labels that each got.

#10600 ISPN-14468 REST: return error if failed to create counter
  server/rest/src/main/java/org/infinispan/rest/resources/CounterResource.java
  server/rest/src/test/java/org/infinispan/rest/resources/CounterResourceTest.java
Labels: Trivial :-)

#10622 [14.x] ISPN-14476: Bump JGroups to 5.2.12.Final
  build/configuration/pom.xml
Labels: Trivial :-), Backport

#10613 [14.0] ISPN-14492 Java 17 instead of 11
  Jenkinsfile
  Jenkinsfile-release
  build/configuration/pom.xml
  documentation/src/main/asciidoc/topics/contributing/basics.adoc
  documentation/src/main/asciidoc/topics/contributing/building.adoc
  documentation/src/main/asciidoc/topics/proc_adding_hotrod_client_dependencies.adoc
  documentation/src/main/asciidoc/topics/ref_quick_start.adoc
Labels: Backport

#10603 [14.0.x] ISPN-14479 SQL Cache store initiation fails on Sql type CHAR
  core/src/test/java/org/infinispan/persistence/BaseStoreFunctionalTest.java
  core/src/test/java/org/infinispan/test/data/Address.java
  core/src/test/java/org/infinispan/test/data/Person.java
  persistence/sql/src/main/java/org/infinispan/persistence/sql/AbstractSchemaJdbcStore.java
  persistence/sql/src/test/java/org/infinispan/persistence/sql/AbstractSQLStoreFunctionalTest.java
Labels: Backport

#10639 [14.x] ISPN-14513 Upgrade Narayana to 5.13.1.Final
  build/configuration/pom.xml
  pom.xml
  spring/spring-boot-3/pom.xml
  spring/spring6/pom.xml
Labels: Backport

#10631 ISPN-14510 Fix CliIT.testCliInteractive failure
  server/rest/src/main/java/org/infinispan/rest/resources/ContainerResource.java
Labels: Trivial :-), Test fix

#10632 [14.0] ISPN-14510 Fix CliIT.testCliInteractive failure
  server/rest/src/main/java/org/infinispan/rest/resources/ContainerResource.java
Labels: Trivial :-), Test fix

#10637 [14.x] ISPN-14512 Fix *-jakarta modules
  build/configuration/pom.xml
  hibernate/cache-commons/pom.xml
  hibernate/cache-v60/pom.xml
  pom.xml
  spring/spring-boot-3/pom.xml
  spring/spring6/pom.xml
Labels: Backport

#10643 [14.x] ISPN-14270 & ISPN-13424 Spring Boot 3 & Spring 6
  build/component-annotations/pom.xml
  build/component-processor/pom.xml
  build/configuration/pom.xml
  build/logging-annotations/pom.xml
  build/logging-processor/pom.xml
  commons/all/pom.xml
  commons/jdk19/pom.xml
  javadoc/pom.xml
  pom.xml
  spring/spring-boot-3/embedded/pom.xml
  spring/spring-boot-3/pom.xml
  spring/spring-boot-3/remote/pom.xml
  spring/spring-boot-3/tests/pom.xml
  spring/spring-boot-3/tests/src/test/java/test/infinispan/integration/embedded/EmbeddedSessionApp.java
  spring/spring6/pom.xml
Labels: Backport

#10633 ISPN-14511 Fix RestOperations.testCounter[HTTP_20]
  server/testdriver/core/src/main/java/org/infinispan/server/test/api/TestClientDriver.java
  server/testdriver/junit4/src/main/java/org/infinispan/server/test/junit4/InfinispanServerTestMethodRule.java
  server/testdriver/junit5/src/main/java/org/infinispan/server/test/junit5/InfinispanServerExtension.java
  server/tests/src/test/java/org/infinispan/server/functional/RestOperations.java
Labels: Test fix

#10644 [14.0] ISPN-14477 Tests for concurrent Spring session access
  spring/spring5/spring5-common/src/main/java/org/infinispan/spring/common/session/SessionUpdateRemappingFunctionProtoAdapter.java
  spring/spring5/spring5-common/src/test/java/org/infinispan/spring/common/session/InfinispanSessionRepositoryTCK.java
  spring/spring5/spring5-embedded/src/test/java/org/infinispan/spring/embedded/session/InfinispanEmbeddedSessionRepositoryTest.java
  spring/spring5/spring5-remote/src/test/java/org/infinispan/spring/remote/session/InfinispanRemoteSessionRepositoryTest.java
  spring/spring6/spring6-common/src/main/java/org/infinispan/spring/common/session/SessionUpdateRemappingFunctionProtoAdapter.java
  spring/spring6/spring6-common/src/test/java/org/infinispan/spring/common/session/InfinispanSessionRepositoryTCK.java
  spring/spring6/spring6-embedded/src/test/java/org/infinispan/spring/embedded/session/InfinispanEmbeddedProtostreamSessionRepositoryTest.java
  spring/spring6/spring6-embedded/src/test/java/org/infinispan/spring/embedded/session/InfinispanEmbeddedSessionRepositoryTest.java
  spring/spring6/spring6-remote/src/test/java/org/infinispan/spring/remote/session/InfinispanRemoteProtostreamSessionRepositoryTest.java
  spring/spring6/spring6-remote/src/test/java/org/infinispan/spring/remote/session/InfinispanRemoteSessionRepositoryTest.java
Labels: Backport

#10634 [14.0] ISPN-14511 Fix RestOperations.testCounter[HTTP_20]
  server/testdriver/core/src/main/java/org/infinispan/server/test/api/TestClientDriver.java
  server/testdriver/junit4/src/main/java/org/infinispan/server/test/junit4/InfinispanServerTestMethodRule.java
  server/testdriver/junit5/src/main/java/org/infinispan/server/test/junit5/InfinispanServerExtension.java
  server/tests/src/test/java/org/infinispan/server/functional/RestOperations.java
Labels: Test fix

#10647 [14.x] ISPN-14516 Wrong versions in spring-boot-3-tests module
  spring/spring-boot-3/embedded/pom.xml
  spring/spring-boot-3/remote/pom.xml
  spring/spring-boot-3/tests/pom.xml
  spring/spring-boot-3/tests/src/test/java/test/infinispan/integration/remote/RemoteSpringSessionTest.java
Labels: Backport

#10651 ISPN-13424 RemoteSession test fix
  spring/spring-boot-3/tests/src/test/java/test/infinispan/integration/remote/RemoteSpringSessionTest.java
Labels: Urgent!, Test fix

#10652 ISPN-14520 Upgrade Protostream to 4.6.1.Final
  build/configuration/pom.xml
Labels: Trivial :-)

#10653 [14.x] ISPN-14520 Upgrade Protostream to 4.6.1.Final
  build/configuration/pom.xml
Labels: Trivial :-), Backport

#10649 [14.0] ISPN-13424 RemoteSession test fix
  spring/spring-boot-3/tests/src/test/java/test/infinispan/integration/remote/RemoteSpringSessionTest.java
Labels: Urgent!, Backport, Test fix

#10650 ISPN-14517 Generate test certificates from code
  client/hotrod-client/pom.xml
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/SslAuthenticationTest.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/SslTest.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/configuration/SSLClassPathConfigurationTest.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/test/HotRodClientTestingUtil.java
  commons-test/pom.xml
  commons-test/src/main/java/org/infinispan/commons/test/security/TestCertificates.java
  persistence/remote/pom.xml
  persistence/remote/src/test/java/org/infinispan/persistence/remote/RemoteStoreSSLTest.java
  persistence/remote/src/test/java/org/infinispan/persistence/remote/upgrade/HotRodUpgradeDynamicWithSSLTest.java
  persistence/remote/src/test/java/org/infinispan/persistence/remote/upgrade/HotRodUpgradeWithSSLTest.java
  server/hotrod/pom.xml
  server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodSniFunctionalTest.java
  server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodSslFunctionalTest.java
  server/hotrod/src/test/java/org/infinispan/server/hotrod/test/HotRodSslWithCertPasswdTest.java
  server/hotrod/src/test/java/org/infinispan/server/hotrod/test/HotRodTestingUtil.java
  server/rest/pom.xml
  server/rest/src/test/java/org/infinispan/rest/CertificateTest.java
  server/rest/src/test/java/org/infinispan/rest/Http2Test.java
  server/rest/src/test/java/org/infinispan/rest/helper/RestServerHelper.java
  server/rest/src/test/java/org/infinispan/rest/profiling/Http11VsHttp20Benchmark.java
  server/rest/src/test/java/org/infinispan/rest/resources/AbstractRestResourceTest.java
  server/router/pom.xml
  server/router/src/test/java/org/infinispan/server/router/integration/ProtocolServerEndpointRouterTest.java
  server/router/src/test/java/org/infinispan/server/router/integration/SinglePortTest.java
Labels: Changes Required
