Repository infinispan/infinispan, pull requests merged in 2023-07, with the labels that each got.

#11081 ISPN-15011 Remove Shrinkwrap resolver
  build/configuration/pom.xml
  cdi/remote/pom.xml
  pom.xml
Labels: Trivial :-)

#11083 Reduce testsuite timeout to 2h
  Jenkinsfile
Labels: Trivial :-)

#11067 ISPN-14610 ZCOUNT
  documentation/src/main/asciidoc/topics/ref_redis_commands.adoc
  multimap/src/main/java/org/infinispan/multimap/impl/EmbeddedMultimapSortedSetCache.java
  multimap/src/main/java/org/infinispan/multimap/impl/ExternalizerIds.java
  multimap/src/main/java/org/infinispan/multimap/impl/MultimapModuleLifecycle.java
  multimap/src/main/java/org/infinispan/multimap/impl/SortedSetBucket.java
  multimap/src/main/java/org/infinispan/multimap/impl/function/sortedset/CountFunction.java
  multimap/src/main/java/org/infinispan/multimap/impl/internal/MultimapObjectWrapper.java
  multimap/src/test/java/org/infinispan/multimap/impl/DistributedMultimapSortedSetCacheTest.java
  multimap/src/test/java/org/infinispan/multimap/impl/EmbeddedMultimapSortedSetCacheTest.java
  multimap/src/test/java/org/infinispan/multimap/impl/MultimapTestUtils.java
  server/resp/src/main/java/org/infinispan/server/resp/commands/ArgumentUtils.java
  server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java
  server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/ZCOUNT.java
  server/resp/src/test/java/org/infinispan/server/resp/SortedSetCommandsTest.java
Labels: Waiting for CI

#11049 ISPN-14978 EXPIRE / ISPN-14979 EXPIREAT / ISPN-14980 EXPIRETIME / ISPN-14981 PEXPIRETIME
  server/resp/src/main/java/org/infinispan/server/resp/RespServer.java
  server/resp/src/main/java/org/infinispan/server/resp/Util.java
  server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java
  server/resp/src/main/java/org/infinispan/server/resp/commands/generic/EXPIRE.java
  server/resp/src/main/java/org/infinispan/server/resp/commands/generic/EXPIREAT.java
  server/resp/src/main/java/org/infinispan/server/resp/commands/generic/EXPIRETIME.java
  server/resp/src/main/java/org/infinispan/server/resp/commands/generic/PEXPIRETIME.java
  server/resp/src/main/java/org/infinispan/server/resp/commands/generic/PTTL.java
  server/resp/src/main/java/org/infinispan/server/resp/commands/generic/TTL.java
  server/resp/src/main/java/org/infinispan/server/resp/commands/string/SET.java
  server/resp/src/main/java/org/infinispan/server/resp/operation/RespExpiration.java
  server/resp/src/main/java/org/infinispan/server/resp/operation/SetOperation.java
  server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java
  server/resp/src/test/java/org/infinispan/server/resp/SingleNodeRespBaseTest.java
Labels: Waiting for CI

#11056 [14.0] ISPN-14992 Spring Boot 3.1.1 and Spring Session 3.1.1
  build/configuration/pom.xml
Labels: Backport

#11036 [14.0] ISPN-14972 Updates to console 14.0.11.Final
  build/configuration/pom.xml
Labels: Backport

#10996 ISPN-14529 query docs: clarify attributes for sorting queries
  documentation/src/main/asciidoc/topics/con_indexing_annotations.adoc
  documentation/src/main/asciidoc/topics/protobuf/indexed_field.protobuf
Labels: Documentation

#11042 [14.0] ISPN-14957 Allow to get internal cache info using rest
  server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
  server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
Labels: Backport

#11089 ISPN-15020 Updates server console to dev02
  build/configuration/pom.xml
Labels: Trivial :-)

#11088 ISPN-14195 Fix security action getting query configuration
  server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceQueryAction.java
Labels: Urgent!

#11063 [14.x] ISPN-14982 State transfer never completes
  core/src/main/java/org/infinispan/scattered/impl/ScatteredStateConsumerImpl.java
  core/src/main/java/org/infinispan/statetransfer/StateConsumerImpl.java
  core/src/test/java/org/infinispan/statetransfer/StateConsumerTest.java
Labels: Backport

#11087 ISPN-14615 ZPOPMAX, ZPOPMIN
  documentation/src/main/asciidoc/topics/ref_redis_commands.adoc
  multimap/src/main/java/org/infinispan/multimap/impl/EmbeddedMultimapSortedSetCache.java
  multimap/src/main/java/org/infinispan/multimap/impl/ExternalizerIds.java
  multimap/src/main/java/org/infinispan/multimap/impl/MultimapModuleLifecycle.java
  multimap/src/main/java/org/infinispan/multimap/impl/SortedSetBucket.java
  multimap/src/main/java/org/infinispan/multimap/impl/function/sortedset/PopFunction.java
  multimap/src/test/java/org/infinispan/multimap/impl/DistributedMultimapSortedSetCacheTest.java
  multimap/src/test/java/org/infinispan/multimap/impl/EmbeddedMultimapSortedSetCacheTest.java
  server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java
  server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/ZPOPMAX.java
  server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/ZPOPMIN.java
  server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/internal/POP.java
  server/resp/src/test/java/org/infinispan/server/resp/SortedSetCommandsTest.java
Labels: Waiting for CI

#11093 [14.0] ISPN-15004 URLConfigurationResourceResolver waiting on the Class init…
  cli/src/main/java/org/infinispan/cli/commands/Config.java
  commons/all/src/main/java/org/infinispan/commons/configuration/io/ConfigurationReader.java
  commons/all/src/main/java/org/infinispan/commons/configuration/io/ConfigurationResourceResolver.java
  commons/all/src/main/java/org/infinispan/commons/configuration/io/ConfigurationResourceResolvers.java
  core/src/main/java/org/infinispan/configuration/parsing/ParserRegistry.java
  core/src/main/java/org/infinispan/manager/DefaultCacheManager.java
  core/src/test/java/org/infinispan/configuration/ConfigurationConversionTest.java
  core/src/test/java/org/infinispan/configuration/EvictionConfigurationTest.java
  core/src/test/java/org/infinispan/configuration/parsing/XmlFileParsingTest.java
  core/src/test/java/org/infinispan/configuration/serializer/AbstractConfigurationSerializerTest.java
  core/src/test/java/org/infinispan/test/fwk/TestCacheManagerFactory.java
  hibernate/cache-commons/src/main/java/org/infinispan/hibernate/cache/commons/DefaultCacheManagerProvider.java
  persistence/remote/src/main/java/org/infinispan/persistence/remote/upgrade/SerializationUtils.java
  query/src/test/java/org/infinispan/query/config/QueryParsingTest.java
  server/core/src/main/java/org/infinispan/server/core/backup/resources/CacheConfigResource.java
  server/core/src/main/java/org/infinispan/server/core/backup/resources/CacheResource.java
  server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
  server/runtime/src/test/java/org/infinispan/server/configuration/ServerConfigurationSerializerTest.java
Labels: Backport

#11097 [14.0] ISPN-14983 Ensure ClusterRoleMapper and ClusterPermissionMapper are i…
  build/component-annotations/src/main/java/org/infinispan/factories/annotations/PostStart.java
  build/component-processor/src/main/java/org/infinispan/component/processor/ComponentAnnotationProcessor.java
  build/component-processor/src/main/java/org/infinispan/component/processor/Generator.java
  build/component-processor/src/main/java/org/infinispan/component/processor/Model.java
  core/src/main/java/org/infinispan/factories/EmptyConstructorFactory.java
  core/src/main/java/org/infinispan/factories/GlobalComponentRegistry.java
  core/src/main/java/org/infinispan/factories/impl/BasicComponentRegistry.java
  core/src/main/java/org/infinispan/factories/impl/BasicComponentRegistryImpl.java
  core/src/main/java/org/infinispan/globalstate/GlobalConfigurationManager.java
  core/src/main/java/org/infinispan/globalstate/impl/GlobalConfigurationManagerImpl.java
  core/src/main/java/org/infinispan/manager/DefaultCacheManager.java
  core/src/main/java/org/infinispan/registry/InternalCacheRegistry.java
  core/src/main/java/org/infinispan/registry/impl/InternalCacheRegistryImpl.java
  core/src/main/java/org/infinispan/registry/impl/SecurityActions.java
  core/src/main/java/org/infinispan/security/PrincipalRoleMapper.java
  core/src/main/java/org/infinispan/security/RolePermissionMapper.java
  core/src/main/java/org/infinispan/security/mappers/ClusterPermissionMapper.java
  core/src/main/java/org/infinispan/security/mappers/ClusterRoleMapper.java
  core/src/main/java/org/infinispan/security/mappers/CommonNameRoleMapper.java
  core/src/main/java/org/infinispan/security/mappers/IdentityRoleMapper.java
  core/src/test/java/org/infinispan/globalstate/NoOpGlobalConfigurationManager.java
  core/src/test/java/org/infinispan/manager/CacheDependencyTest.java
  core/src/test/java/org/infinispan/security/DynamicRBACRestartTest.java
  core/src/test/java/org/infinispan/statetransfer/ReadAfterLostDataTest.java
  server/rest/src/test/java/org/infinispan/rest/profiling/Http11VsHttp20Benchmark.java
Labels: Backport

#11045 [14.0] ISPN-14977 Log ProtoStream entities on reindexing operations
  query/src/main/java/org/infinispan/query/impl/massindex/IndexUpdater.java
  query/src/main/java/org/infinispan/query/impl/massindex/IndexWorker.java
  query/src/main/java/org/infinispan/query/impl/massindex/MassIndexerProgressMonitor.java
  query/src/main/java/org/infinispan/query/impl/massindex/MassIndexerProgressNotifier.java
  query/src/main/java/org/infinispan/query/logging/Log.java
Labels: Backport

#11101 ISPN-15018 temporary remove programmatic mapping of entities docs
  documentation/src/main/asciidoc/stories/assembly_query_embedded.adoc
Labels: Trivial :-), Documentation

#11102 [14.0.x]ISPN-15018 remove programmatic mapping of entities from docs
  documentation/src/main/asciidoc/stories/assembly_query_embedded.adoc
  documentation/src/main/asciidoc/topics/ref_query_programmatic_entity_mapping.adoc
Labels: Trivial :-), Documentation

#10910 ISPN-14834 Implement CRC16 for hash function option
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationBuilder.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/consistenthash/CRC16ConsistentHashV2.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/consistenthash/ConsistentHashV2.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/ConsistentHashFactoryTest.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/ConsistentHashPerformanceTest.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/ConsistentHashV2Test.java
  client/hotrod/src/main/java/org/infinispan/hotrod/impl/consistenthash/CRC16ConsistentHashV2.java
  client/hotrod/src/main/java/org/infinispan/hotrod/impl/consistenthash/ConsistentHash.java
  client/hotrod/src/main/java/org/infinispan/hotrod/impl/consistenthash/ConsistentHashV2.java
  core/src/main/java/org/infinispan/configuration/cache/HashConfiguration.java
  core/src/main/java/org/infinispan/configuration/cache/HashConfigurationBuilder.java
  core/src/main/java/org/infinispan/configuration/parsing/CacheParser.java
  core/src/main/java/org/infinispan/configuration/serializing/CoreConfigurationSerializer.java
  core/src/main/java/org/infinispan/distribution/ch/impl/CRC16HashFunctionPartitioner.java
  core/src/main/java/org/infinispan/distribution/ch/impl/HashFunctionPartitioner.java
  core/src/main/resources/schema/infinispan-config-15.0.xsd
  core/src/test/java/org/infinispan/configuration/parsing/UnifiedXmlFileParsingTest.java
  core/src/test/resources/configs/all/15.0.xml
  graalvm/core/src/main/java/org/infinispan/graalvm/NativeMetadataProvider.java
  server/resp/src/main/java/org/infinispan/server/resp/RespServer.java
  server/resp/src/test/java/org/infinispan/server/resp/BaseMultipleRespTest.java
  server/resp/src/test/java/org/infinispan/server/resp/SingleNodeRespBaseTest.java
Labels: Changes Required

#11109 [14.0] ISPN-15036 Never use search#hitCount() without check if it is exact
  query/src/main/java/org/infinispan/query/clustered/DistributedIndexedQueryImpl.java
  query/src/main/java/org/infinispan/query/clustered/NodeTopDocs.java
  query/src/main/java/org/infinispan/query/clustered/QueryResponse.java
  query/src/main/java/org/infinispan/query/clustered/commandworkers/CQCreateEagerQuery.java
  query/src/test/java/org/infinispan/query/maxresult/DistributedHitCountAccuracyTest.java
  query/src/test/java/org/infinispan/query/maxresult/HitCountAccuracyTest.java
  query/src/test/java/org/infinispan/query/maxresult/LocalHitCountAccuracyTest.java
Labels: Image Required

#11115 Docs broken links fix
  documentation/src/main/asciidoc/topics/proc_configuring_server_fips.adoc
  documentation/src/main/asciidoc/topics/streams.adoc
Labels: Trivial :-), Documentation

#11116 [14.0.x] Docs broken links fix
  documentation/src/main/asciidoc/topics/proc_configuring_server_fips.adoc
  documentation/src/main/asciidoc/topics/streams.adoc
Labels: Trivial :-), Backport, Documentation

#11117 [13.0.x] Docs broken links fix
  documentation/src/main/asciidoc/topics/proc_configuring_server_fips.adoc
  documentation/src/main/asciidoc/topics/streams.adoc
Labels: Trivial :-), Backport, Documentation

#11125 Add missing closing tag in the schema
  core/src/main/resources/schema/infinispan-config-15.0.xsd
Labels: Trivial :-), Documentation

#11124 ISPN-15059 Support different ways to handle unclean shutdowns
  core/src/main/java/org/infinispan/configuration/global/GlobalStateConfiguration.java
  core/src/main/java/org/infinispan/configuration/global/GlobalStateConfigurationBuilder.java
  core/src/main/java/org/infinispan/configuration/global/UncleanShutdownAction.java
  core/src/main/java/org/infinispan/configuration/parsing/Attribute.java
  core/src/main/java/org/infinispan/configuration/parsing/Parser.java
  core/src/main/java/org/infinispan/configuration/serializing/CoreConfigurationSerializer.java
  core/src/main/java/org/infinispan/globalstate/impl/GlobalStateManagerImpl.java
  core/src/main/java/org/infinispan/util/logging/Log.java
  core/src/main/resources/schema/infinispan-config-15.0.xsd
  core/src/test/java/org/infinispan/globalstate/GlobalStateTest.java
  core/src/test/resources/configs/all/15.0.xml
  documentation/src/main/asciidoc/topics/con_global_persistent_location.adoc
  documentation/src/main/asciidoc/topics/upgrading.adoc
  server/tests/src/test/resources/configuration/PersistenceTest.xml
  server/tests/src/test/resources/configuration/cache-container/clustered-ignore-unclean.xml
Labels: Docs Updated

#11129 [14.0] ISPN-15062 Customizing JGroups stack example xml is invalid
  documentation/src/main/asciidoc/topics/xml/jgroups_stack_extends.xml
Labels: Trivial :-), Backport, Documentation, Docs Updated

#10733 ISPN-14418 CLI/REST command to recover an incomplete cluster if it ca…
  cli/src/main/java/org/infinispan/cli/commands/Batch.java
  cli/src/main/java/org/infinispan/cli/commands/CLI.java
  cli/src/main/java/org/infinispan/cli/commands/rest/Topology.java
  client/rest-client/src/main/java/org/infinispan/client/rest/RestCacheClient.java
  client/rest-client/src/main/java/org/infinispan/client/rest/impl/okhttp/RestCacheClientOkHttp.java
  core/src/main/java/org/infinispan/commands/topology/TopologyUpdateStableCommand.java
  core/src/main/java/org/infinispan/distribution/ch/ConsistentHash.java
  core/src/main/java/org/infinispan/distribution/ch/impl/AbstractConsistentHash.java
  core/src/main/java/org/infinispan/distribution/ch/impl/DefaultConsistentHash.java
  core/src/main/java/org/infinispan/topology/CacheTopology.java
  core/src/main/java/org/infinispan/topology/ClusterCacheStatus.java
  core/src/main/java/org/infinispan/topology/ClusterTopologyManager.java
  core/src/main/java/org/infinispan/topology/ClusterTopologyManagerImpl.java
  core/src/main/java/org/infinispan/topology/LocalTopologyManagerImpl.java
  core/src/main/java/org/infinispan/util/logging/Log.java
  core/src/test/java/org/infinispan/globalstate/ThreeNodeTopologyReinstallTest.java
  documentation/src/main/asciidoc/stories/assembly_cli_cache_operations.adoc
  documentation/src/main/asciidoc/topics/con_restarting_clusters.adoc
  documentation/src/main/asciidoc/topics/proc_cli_set_topology_caches.adoc
  documentation/src/main/asciidoc/topics/ref_rest_caches.adoc
  server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
Labels: Docs Updated

#11112 ISPN-14987 SIGSEGV and memory corruption with persistent cache backed…
  persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/RocksDBStore.java
Labels: Changes Required, Image Required

#11134 [14.0.x] ISPN-14987 SIGSEGV and memory corruption with persistent cache backed…
  persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/RocksDBStore.java
Labels: Backport

#11133 [14.0] ISPN-15042 Do not collect clustered stats in some conditions
  core/src/main/java/org/infinispan/stats/impl/AbstractClusterStats.java
  core/src/main/java/org/infinispan/stats/impl/ClusterCacheStatsImpl.java
  core/src/main/java/org/infinispan/stats/impl/ClusterContainerStatsImpl.java
Labels: Backport

#11145 fix server readme link
  documentation/src/main/asciidoc/topics/con_server_directory_structure.adoc
  documentation/src/main/asciidoc/topics/proc_downloading_server.adoc
Labels: Trivial :-), Documentation

#11144 [14.0.x]fix server readme link
  documentation/src/main/asciidoc/topics/con_server_directory_structure.adoc
  documentation/src/main/asciidoc/topics/proc_downloading_server.adoc
Labels: Trivial :-), Documentation

#11143 [13.0.x]fix server readme link
  documentation/src/main/asciidoc/topics/con_server_directory_structure.adoc
  documentation/src/main/asciidoc/topics/proc_downloading_server.adoc
Labels: Trivial :-), Documentation

#11142 [11.0.x]fix server readme link
  documentation/src/main/asciidoc/topics/con_server_directory_structure.adoc
  documentation/src/main/asciidoc/topics/proc_downloading_server.adoc
Labels: Trivial :-), Documentation

#11147 [14.0.x] Docs review Query hit count efficiency
  core/src/main/resources/schema/infinispan-config-14.0.xsd
  documentation/src/main/asciidoc/topics/con_performance_indexing_querying.adoc
  documentation/src/main/asciidoc/topics/ref_query_ickle.adoc
  documentation/src/main/asciidoc/topics/ref_rest_caches_query.adoc
Labels: Backport, Documentation

#11146 Docs review Query hit count accuracy
  core/src/main/resources/schema/infinispan-config-15.0.xsd
  documentation/src/main/asciidoc/topics/con_performance_indexing_querying.adoc
  documentation/src/main/asciidoc/topics/hotrod_protocol.adoc
  documentation/src/main/asciidoc/topics/ref_query_ickle.adoc
  documentation/src/main/asciidoc/topics/ref_rest_caches_query.adoc
Labels: Documentation

#11157 ISPN-14744 docs follow up
  documentation/src/main/asciidoc/topics/con_declarative_cache_configuration.adoc
  documentation/src/main/asciidoc/topics/ref_infinispan_caches.adoc
Labels: Trivial :-), Documentation

#11160 ISPN-14643 writeArrayPrefix compilation error
  server/resp/src/main/java/org/infinispan/server/resp/Resp3Handler.java
Labels: Urgent!, Trivial :-)

#11158 [14.x]ISPN-14744-14
  documentation/src/main/asciidoc/topics/con_declarative_cache_configuration.adoc
  documentation/src/main/asciidoc/topics/ref_infinispan_caches.adoc
Labels: Backport, Documentation

#11159 Revert "ISPN-14484 mark opentelementry as community only in ispn 14
  documentation/src/main/asciidoc/stories/assembly_hotrod_client_configuration.adoc
  documentation/src/main/asciidoc/stories/assembly_rest_api.adoc
Labels: Documentation

#11169 ISPN-15009 docs update mask secured caches by role
  documentation/src/main/asciidoc/topics/ref_rest_cache_managers.adoc
Labels: Trivial :-), Documentation
