Repository infinispan/infinispan, pull requests merged in 2024-05, with the labels that each got.

#12345 Fix getting started guide to mention the minimum version of JDK 17
  documentation/src/main/asciidoc/topics/ref_quick_start.adoc
Labels: Trivial :-), Documentation

#12346 Parameterize the JDK version in the docs
  documentation/pom.xml
  documentation/src/main/asciidoc/stories/assembly_functional_map_api.adoc
  documentation/src/main/asciidoc/topics/code_examples/RestHttpClient.java
  documentation/src/main/asciidoc/topics/contributing/basics.adoc
  documentation/src/main/asciidoc/topics/contributing/building.adoc
  documentation/src/main/asciidoc/topics/execute_grid.adoc
  documentation/src/main/asciidoc/topics/functional_api.adoc
  documentation/src/main/asciidoc/topics/proc_adding_hotrod_client_dependencies.adoc
  documentation/src/main/asciidoc/topics/proc_using_mvn_archetypes.adoc
  documentation/src/main/asciidoc/topics/ref_quick_start.adoc
  documentation/src/main/asciidoc/topics/ref_server_requirements.adoc
Labels: Trivial :-), Documentation

#12334 ISPN-16034 Cache REST release resource is blocking
  server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
Labels: Trivial :-), 14.0.x

#12354 ISPN-16050 Tracing: NullPointerException checking for permission
  core/src/main/java/org/infinispan/security/audit/LoggingAuditLogger.java
Labels: Trivial :-)

#12353 ISPN-16049 Tracing: add node name to the spans
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/xsite/TracingXSiteTest.java
  core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
  core/src/main/java/org/infinispan/telemetry/InfinispanTelemetry.java
  core/src/main/java/org/infinispan/telemetry/impl/DisabledInfinispanTelemetry.java
  server/core/src/main/java/org/infinispan/server/core/telemetry/OpenTelemetryService.java
Labels: Trivial :-)

#12290 Amend resp/memcached connector docs
  documentation/src/main/asciidoc/stories/assembly_memcached.adoc
  documentation/src/main/asciidoc/stories/assembly_resp_endpoint.adoc
  documentation/src/main/asciidoc/topics/proc_server_configuring_resp.adoc
Labels: Documentation

#12371 ISPN-16066 Convert max-size to bytes before comparing
  core/src/main/java/org/infinispan/configuration/cache/MemoryConfiguration.java
  core/src/test/java/org/infinispan/configuration/cache/MemoryConfigurationTest.java
Labels: Trivial :-), 14.0.x

#12384 ISPN-16084 Fix TracingSecurityTest flaky test
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/tracing/TracingSecurityTest.java
Labels: Trivial :-)

#12385 ISPN-16085 Updates Console to 15.0.3.Final
  build/configuration/pom.xml
Labels: Trivial :-)

#12379 Change SCRAM-SHA-512 -> SCRAM-SHA-256
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/AuthenticationConfigurationBuilder.java
Labels: Image Required

#12393 ISPN-16085 Adjust FootprintIT for smaller console size
  server/tests/src/test/java/org/infinispan/server/footprint/FootprintIT.java
Labels: Trivial :-), Test fix

#12403 ISPN-16099 Align computeIfAbsent javadoc with Map#computeIfAbsent
  core/src/main/java/org/infinispan/Cache.java
Labels: Trivial :-)

#12386 ISPN-16087 Concrete config is validated before applying template conf…
  core/src/main/java/org/infinispan/configuration/parsing/ConfigurationBuilderHolder.java
  core/src/test/java/org/infinispan/configuration/XSiteParsingTest.java
  core/src/test/java/org/infinispan/configuration/parsing/ConfigurationBuilderHolderTest.java
Labels: 14.0.x

#12408 ISPN-16080 Use ProtoStream's ProtoLock
  client/hotrod/pom.xml
  server/hotrod/pom.xml
  server/memcached/pom.xml
  server/resp/pom.xml
Labels: Trivial :-)

#12410 ISPN-16103 CrossSite: Wait for prepare command in case of local failure
  core/src/main/java/org/infinispan/interceptors/xsite/OptimisticBackupInterceptor.java
  core/src/test/java/org/infinispan/xsite/RollbackNoPrepareOptimisticTest.java
  core/src/test/java/org/infinispan/xsite/RollbackNoPreparePessimisticTest.java
  core/src/test/java/org/infinispan/xsite/irac/ManualIracManager.java
Labels: 14.0.x, 15.0.x

#12413 [15.0.x] ISPN-16103 CrossSite: Wait for prepare command in case of local failure
  core/src/main/java/org/infinispan/interceptors/xsite/OptimisticBackupInterceptor.java
  core/src/test/java/org/infinispan/xsite/RollbackNoPrepareOptimisticTest.java
  core/src/test/java/org/infinispan/xsite/RollbackNoPreparePessimisticTest.java
  core/src/test/java/org/infinispan/xsite/irac/ManualIracManager.java
Labels: Backport

#12412 [DOC] ISPN-16092 Documenting RESP cache
  documentation/src/main/asciidoc/stories/assembly_resp_endpoint.adoc
  documentation/src/main/asciidoc/titles/resp/resp-endpoint.asciidoc
  documentation/src/main/asciidoc/topics/proc_server_configuring_resp.adoc
Labels: Documentation, 15.0.x

#12414 [14.0.x] ISPN-16103 CrossSite: Wait for prepare command in case of local failure
  core/src/main/java/org/infinispan/interceptors/xsite/OptimisticBackupInterceptor.java
  core/src/test/java/org/infinispan/xsite/RollbackNoPrepareOptimisticTest.java
  core/src/test/java/org/infinispan/xsite/RollbackNoPreparePessimisticTest.java
  core/src/test/java/org/infinispan/xsite/irac/ManualIracManager.java
Labels: Backport

#12415 ISPN-16107 RocksDBStore: wait for batch to complete before writing
  persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/RocksDBStore.java
Labels: Trivial :-), 15.0.x

#12447 Updated Third-party server tests configuration for MariaDB106 and EAP8.
  integrationtests/server-integration/third-party-server/pom.xml
  integrationtests/server-integration/third-party-server/src/test/resources/mariadb.properties
  integrationtests/server-integration/third-party-server/src/test/resources/wildfly/standalone-test.xml
Labels: 15.0.x

#12453 ISPN-16143 HotRodQueryIT fix
  integrationtests/server-integration/server-integration-commons/src/test/java/org/infinispan/test/integration/remote/AbstractHotRodQueryIT.java
Labels: Trivial :-), Test fix, 14.0.x, 15.0.x
