Repository infinispan/infinispan, pull requests merged in 2024-12, with the labels that each got.

#13241 Updates to Console 15.1.4.Final
  build/configuration/pom.xml
Labels: pr/trivial 😀, area/server

#13218 Fix LicenseTest.testLicense. Fixes #13217
  server/runtime/pom.xml
Labels: pr/trivial 😀, target/15.1.x

#13198 Update Resp connector documentation
  documentation/src/main/asciidoc/stories/assembly_resp_endpoint.adoc
  documentation/src/main/asciidoc/topics/proc_server_configuring_resp.adoc
  documentation/src/main/asciidoc/topics/proc_server_resp_differences.adoc
  documentation/src/main/asciidoc/topics/ref_redis_commands.adoc
Labels: pr/documentation, backport/15.0.x, target/15.1.x

#13193 [15.0.x] ISPN-16826 PerformConcurrently with collector
  commons/all/src/main/java/org/infinispan/commons/util/concurrent/CompletionStages.java
  query/src/main/java/org/infinispan/query/clustered/commandworkers/CQDelete.java
Labels: pr/changes required, target/15.0.x, release/15.0.12

#12931 Explain how to connect to the server with the CLI running in a container
  documentation/src/main/asciidoc/stories/assembly_cli_starting.adoc
  documentation/src/main/asciidoc/topics/proc_cli_connecting_container.adoc
Labels: pr/trivial 😀, backport/15.0.x, target/15.1.x

#13221 Renamed label to `pr/Image Required`. Fixes #13220
  .github/workflows/on_build_do_publish_image.yml
  Jenkinsfile
Labels: pr/trivial 😀, github_actions, target/15.1.x

#13206 New VersionGenerator for the Hot Rod protocol
  client/hotrod-client-legacy/src/test/java/org/infinispan/client/hotrod/HotRodIntegrationTest.java
  client/hotrod-client-test/src/test/java/org/infinispan/client/hotrod/CacheEntryAssertions.java
  client/hotrod-client-test/src/test/java/org/infinispan/client/hotrod/HotRodAsyncCacheTest.java
  client/hotrod-client-test/src/test/java/org/infinispan/client/hotrod/HotRodMutinyCacheTest.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/HotRodIntegrationTest.java
  core/src/main/java/org/infinispan/container/versioning/RandomVersionGenerator.java
  core/src/main/java/org/infinispan/factories/VersionGeneratorFactory.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodServer.java
Labels: backport/15.0.x, target/15.1.x

#13312 Paginate gh get labels call. Fixes #13311
  .github/workflows/pull_request_open.yml
Labels: pr/trivial 😀, backport/14.0.x, backport/15.0.x

#13211 Fix REST client parsing for gzip content
  cli/src/main/java/org/infinispan/cli/connection/rest/RestConnection.java
  client/rest-client/src/main/java/org/infinispan/client/rest/impl/jdk/RestRawClientJDK.java
  client/rest-client/src/main/java/org/infinispan/client/rest/impl/jdk/RestServerClientJDK.java
  commons/all/src/main/java/org/infinispan/commons/dataconversion/MediaType.java
  server/rest/src/main/java/org/infinispan/rest/resources/ServerResource.java
  server/runtime/src/main/server/bin/report.sh
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/TestSystemPropertyNames.java
  server/tests/pom.xml
  server/tests/src/test/java/org/infinispan/server/security/authorization/RESTAuthorizationTest.java
Labels: kind/bug, area/cli, area/client/rest, target/15.1.x

#13318 [#13317] Auto merge Dependabot PRs
  .github/workflows/dependabot_pull_request.yml
Labels: backport/14.0.x, backport/15.0.x

#13049 ISPN-16759 Do not enable memcached text protocol implicitly without s…
  server/runtime/src/main/java/org/infinispan/server/configuration/ServerConfigurationParser.java
  server/tests/src/test/java/org/infinispan/server/functional/BackupManagerIT.java
  server/tests/src/test/java/org/infinispan/server/functional/RequestTracingIT.java
  server/tests/src/test/java/org/infinispan/server/functional/memcached/MemcachedOperations.java
  server/tests/src/test/java/org/infinispan/server/functional/rest/RestServerResource.java
  server/tests/src/test/resources/configuration/BasicServerTest.xml
  server/tests/src/test/resources/configuration/TracingServerTest.xml
  server/tests/src/test/resources/configuration/endpoints/noauth.xml
Labels: pr/changes required, backport/15.0.x, target/15.1.x

#13315 [14.0.x][backport] Paginate gh get labels call.
  .github/workflows/pull_request_open.yml
Labels: pr/trivial 😀, github_actions, target/14.0.x

#13314 [15.0.x][backport] Paginate gh get labels call.
  .github/workflows/pull_request_open.yml
Labels: pr/trivial 😀, github_actions, target/15.0.x

#13245 Create issue on GH instead of Jira for flaky tests. Fixes #13238
  .github/workflows/on_test_update_gh_flaky_test.yml
  Jenkinsfile
  bin/gh/common.sh
  bin/gh/track_flaky_tests.sh
  bin/jira/track_flaky_tests.sh
Labels: github_actions

#13334 [#13318] Auto merge Dependabot utilise PR URL
  .github/workflows/dependabot_pull_request.yml
Labels: backport/14.0.x, backport/15.0.x

#13335 [14.0.x] [#13318] Auto merge Dependabot utilise PR URL
  .github/workflows/dependabot_pull_request.yml
Labels: target/14.0.x

#13336 [15.0.x] [#13318] Auto merge Dependabot utilise PR URL
  .github/workflows/dependabot_pull_request.yml
Labels: target/15.0.x

#13384 New flaky test label. Closes #13383
  bin/gh/track_flaky_tests.sh
Labels: pr/trivial 😀, github_actions

#13240 [15.0] Upgrades to Console 15.0.11.Final
  .github/workflows/supported_jdks.yaml
Labels: pr/trivial 😀, area/server, release/15.0.12

#13250 [15.0.x] Update Resp connector documentation
  documentation/src/main/asciidoc/stories/assembly_resp_endpoint.adoc
  documentation/src/main/asciidoc/topics/proc_server_configuring_resp.adoc
  documentation/src/main/asciidoc/topics/proc_server_resp_differences.adoc
  documentation/src/main/asciidoc/topics/ref_redis_commands.adoc
Labels: pr/backport, pr/documentation

#13200 [15.0.x] ISPN-16852: Vector Search is not supported feature
  documentation/src/main/asciidoc/stories/assembly_query_creating_ickle_queries.adoc
Labels: target/15.0.x, release/15.0.12

#13225 Updates to Quarkus 3.15 Closes #13223
  build/configuration/pom.xml
  core/src/main/java/org/infinispan/metrics/config/MicrometerMeterRegisterConfigurationBuilder.java
  core/src/main/java/org/infinispan/metrics/impl/MetricsRegistryImpl.java
  pom.xml
  quarkus/embedded/runtime/src/main/java/org/infinispan/quarkus/embedded/runtime/InfinispanEmbeddedProducer.java
  quarkus/embedded/runtime/src/main/java/org/infinispan/quarkus/embedded/runtime/InfinispanEmbeddedRuntimeConfig.java
  quarkus/embedded/runtime/src/main/java/org/infinispan/quarkus/embedded/runtime/SubstituteMicrometerMetrics.java
  quarkus/embedded/runtime/src/main/resources/META-INF/quarkus-extension.yaml
  quarkus/integration-tests/embedded/src/main/resources/import.sql
  quarkus/server/deployment/src/main/java/org/infinispan/quarkus/server/deployment/InfinispanServerProcessor.java
  quarkus/server/runtime/src/main/java/org/infinispan/quarkus/server/runtime/graal/SubstituteIndexClasses.java
  server/core/pom.xml
  server/rest/pom.xml
  server/rest/src/main/java/org/infinispan/rest/resources/MetricsResource.java
  server/runtime/pom.xml
  server/tests/src/test/java/org/infinispan/server/footprint/FootprintIT.java
  server/tests/src/test/java/org/infinispan/server/functional/hotrod/HotRodClientMetrics.java
  server/tests/src/test/java/org/infinispan/server/functional/rest/RestMetricsResourceIT.java
  spring/spring-boot-3/pom.xml
Labels: pr/changes required, area/integrations/quarkus, target/15.1.x, dependencies

#13406 [#13405] - nested queries improvements - proper handling of OR predicates
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/nested/ParentJoinNestedRemoteTest.java
  object-filter/src/main/java/org/infinispan/objectfilter/impl/syntax/parser/ExpressionBuilder.java
  query/src/test/java/org/infinispan/query/nested/ParentJoinNestedTest.java
Labels: Image Required

#13375 [#13272] Collect remote cache configuration to concurrent map
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/Configuration.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationBuilder.java
Labels: pr/trivial 😀, backport/15.0.x, area/client/hotrod

#13393 Negative metrics raise exceptions in micrometer+prometheus Closes #13235
  .gitignore
  spring/spring-boot-3/embedded/pom.xml
  spring/spring-boot-3/embedded/src/main/java/org/infinispan/spring/starter/embedded/actuator/InfinispanCacheMeterBinder.java
  spring/spring-boot-3/it-tests/embedded-tests/pom.xml
  spring/spring-boot-3/it-tests/embedded-tests/src/test/java/test/infinispan/integration/embedded/SimpleApp.java
  spring/spring-boot-3/it-tests/embedded-tests/src/test/java/test/infinispan/integration/embedded/SimpleApplicationTests.java
  spring/spring-boot-3/it-tests/embedded-tests/src/test/resources/application.properties
  spring/spring-boot-3/it-tests/session-tests/pom.xml
  spring/spring-boot-3/it-tests/session-tests/src/test/java/test/infinispan/autoconfigure/CacheDisabledTest.java
  spring/spring-boot-3/it-tests/session-tests/src/test/java/test/infinispan/autoconfigure/CacheManagerTest.java
  spring/spring-boot-3/it-tests/session-tests/src/test/java/test/infinispan/integration/AbstractSpringSessionTCK.java
  spring/spring-boot-3/it-tests/session-tests/src/test/java/test/infinispan/integration/InfinispanSessionListener.java
  spring/spring-boot-3/it-tests/session-tests/src/test/java/test/infinispan/integration/SecurityConfig.java
  spring/spring-boot-3/it-tests/session-tests/src/test/java/test/infinispan/integration/TestRESTController.java
  spring/spring-boot-3/it-tests/session-tests/src/test/java/test/infinispan/integration/embedded/EmbeddedSessionApp.java
  spring/spring-boot-3/it-tests/session-tests/src/test/java/test/infinispan/integration/embedded/EmbeddedSpringSessionTest.java
  spring/spring-boot-3/it-tests/session-tests/src/test/java/test/infinispan/integration/remote/RemoteSessionApp.java
  spring/spring-boot-3/it-tests/session-tests/src/test/java/test/infinispan/integration/remote/RemoteSpringSessionTest.java
  spring/spring-boot-3/pom.xml
Labels: backport/15.0.x, kind/bug, area/integrations/spring

#13434 [15.0.x] [#13272] Collect remote cache configuration to concurrent map
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/Configuration.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/configuration/ConfigurationBuilder.java
Labels: pr/trivial 😀, pr/backport, area/client/hotrod, target/15.0.x

#13454 Propagate run-name, through whole CI pipeline. Closes #13449
  .github/workflows/on_build_do_publish_image.yml
  .github/workflows/on_build_do_test.yml
  .github/workflows/on_test_publish_surefire_report.yml
  .github/workflows/on_test_update_gh_flaky_test.yml
Labels: pr/trivial 😀, github_actions

#13202 [15.0] ISPN-16827 Set fixed ports in the UDP stack
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/test/MultiHotRodServersTest.java
  core/src/main/resources/default-configs/default-jgroups-udp.xml
  core/src/test/java/org/infinispan/test/MultipleCacheManagersTest.java
  core/src/test/java/org/infinispan/test/fwk/JGroupsConfigBuilder.java
  core/src/test/java/org/infinispan/test/fwk/TransportFlags.java
  documentation/src/main/asciidoc/topics/ref_jgroups_ports.adoc
  server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodMultiNodeTest.java
  server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodStatsClusterTest.java
  server/hotrod/src/test/java/org/infinispan/server/hotrod/event/AbstractHotRodClusterEventsTest.java
Labels: pr/backport, target/15.0.x

#13488 [#13487] Native Mac CLI release incorrectly states amd64 when it shou…
  .github/workflows/pull_request_native_cli.yml
  .github/workflows/release.yml
Labels: pr/trivial 😀, backport/15.0.x, backport/15.1.x

#13491 [15.1.x] [#13487] Native Mac CLI release incorrectly states amd64 when it shou…
  .github/workflows/pull_request_native_cli.yml
  .github/workflows/release.yml
Labels: target/15.1.x

#13498 [15.1.x][#13449] Propagate run-name, through whole CI pipeline.
  .github/workflows/on_build_do_publish_image.yml
  .github/workflows/on_build_do_test.yml
  .github/workflows/on_test_publish_surefire_report.yml
  .github/workflows/on_test_update_gh_flaky_test.yml
Labels: pr/trivial 😀, github_actions, target/15.1.x

#13520 [#13519] Parse invalidation-cache fragments
  core/src/main/java/org/infinispan/configuration/parsing/CacheParser.java
  core/src/test/java/org/infinispan/configuration/parsing/XmlFileParsingTest.java
Labels: backport/14.0.x, backport/15.0.x, kind/bug, backport/15.1.x

#13492 [#13403] Flaky test: org.infinispan.client.hotrod.retry.DistributionR…
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/retry/DistributionRetryTest.java
Labels: pr/test fix, kind/flaky test

#13532 [15.1.x] [#13519] Parse invalidation-cache fragments
  core/src/main/java/org/infinispan/configuration/parsing/CacheParser.java
  core/src/test/java/org/infinispan/configuration/parsing/XmlFileParsingTest.java
Labels: target/15.1.x

#13531 [15.0.x] [#13519] Parse invalidation-cache fragments
  core/src/main/java/org/infinispan/configuration/parsing/CacheParser.java
  core/src/test/java/org/infinispan/configuration/parsing/XmlFileParsingTest.java
Labels: target/15.0.x

#13530 [14.0.x] [#13519] Parse invalidation-cache fragments
  core/src/main/java/org/infinispan/configuration/parsing/CacheParser.java
  core/src/test/java/org/infinispan/configuration/parsing/XmlFileParsingTest.java
Labels: target/14.0.x

#13514 [#13489] Add opentelemetry api incubator
  build/configuration/pom.xml
  pom.xml
  server/core/pom.xml
  server/tests/src/test/java/org/infinispan/server/functional/RequestTracingIT.java
Labels: Image Required, backport/15.1.x

#13559 [15.1.x] [#13489] Add opentelemetry api incubator
  build/configuration/pom.xml
  pom.xml
  server/core/pom.xml
  server/tests/src/test/java/org/infinispan/server/functional/RequestTracingIT.java
Labels: target/15.1.x
