Repository infinispan/infinispan, pull requests merged in 2024-07, with the labels that each got.

#12573 ISPN-16235: Doc edits for topology set-stable command
  documentation/src/main/asciidoc/topics/proc_cli_set_topology_caches.adoc
  documentation/src/main/asciidoc/topics/ref_rest_caches.adoc
Labels: 15.0.x

#12587 ISPN-16251: [doc] Add information how to set JVM options for the server
  documentation/src/main/asciidoc/stories/assembly_server_getting_started.adoc
  documentation/src/main/asciidoc/topics/con_jvm-settings-for-server.adoc
Labels: 15.0.x

#12586 ISPN-16250 [RESP] Fixes HINCRBY and HINCRBYFLOAT
  server/resp/src/main/java/org/infinispan/server/resp/ByteBufferUtils.java
  server/resp/src/main/java/org/infinispan/server/resp/commands/ArgumentUtils.java
  server/resp/src/main/java/org/infinispan/server/resp/commands/hash/HINCRBY.java
  server/resp/src/main/java/org/infinispan/server/resp/commands/hash/HINCRBYFLOAT.java
  server/resp/src/test/java/org/infinispan/server/resp/HashOperationsTest.java
  server/resp/src/test/java/org/infinispan/server/resp/util/ArgumentUtilsTest.java
  server/resp/src/test/java/org/infinispan/server/resp/util/ByteBufferUtilsTest.java
Labels: 15.0.x

#12584 ISPN-16247: Add more info about pessimistic transactions locking mode
  documentation/src/main/asciidoc/topics/ref_hotrod_client_transactions.adoc
Labels: 15.0.x

#12578 ISPN-16241 [RESP] "HRANDFIELD key count withvalues" should return map
  server/resp/src/main/java/org/infinispan/server/resp/commands/hash/HRANDFIELD.java
  server/resp/src/test/java/org/infinispan/server/resp/HashOperationsTest.java
Labels: 15.0.x

#12491 ISPN-16172 Exclude META-INF directory from unpacked console
  server/runtime/build.xml
Labels: Question

#12601 ISPN-16239: Add missing RESP commands to documentation
  documentation/src/main/asciidoc/topics/ref_redis_commands.adoc
Labels: 15.0.x

#12604 ISPN-16265 Updates Console to 15.1.0.Final
  build/configuration/pom.xml
Labels: Trivial :-)

#12610 ISPN-16270 Non indexed delete statement fails with MarshallingException
  query-core/src/main/java/org/infinispan/query/core/impl/EmbeddedQuery.java
  server/tests/src/test/java/org/infinispan/server/functional/hotrod/HotRodCacheQueries.java
Labels: 15.0.x

#12617 ISPN-16276 set ttl with xx
  server/resp/src/main/java/org/infinispan/server/resp/operation/SetOperation.java
  server/resp/src/test/java/org/infinispan/server/resp/StringCommandsTest.java
Labels: 15.0.x

#12568 [DOC] ISPN-16229 Added docs for explicit resp cache config
  documentation/src/main/asciidoc/topics/json/resp_cache.json
  documentation/src/main/asciidoc/topics/proc_server_configuring_resp.adoc
  documentation/src/main/asciidoc/topics/xml/resp_cache.xml
  documentation/src/main/asciidoc/topics/yaml/resp_cache.yaml
Labels: 15.0.x

#12612 ISPN-16272 [RESP] GETRANGE can't handle huge ranges
  server/resp/src/main/java/org/infinispan/server/resp/commands/string/GETRANGE.java
  server/resp/src/test/java/org/infinispan/server/resp/StringCommandsTest.java
Labels: 15.0.x

#12611 ISPN-14653 LCS
  server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java
  server/resp/src/main/java/org/infinispan/server/resp/commands/string/LCS.java
  server/resp/src/main/java/org/infinispan/server/resp/commands/string/STRALGO.java
  server/resp/src/main/java/org/infinispan/server/resp/operation/LCSOperation.java
  server/resp/src/test/java/org/infinispan/server/resp/CustomStringCommands.java
  server/resp/src/test/java/org/infinispan/server/resp/StringCommandsTest.java
Labels: 15.0.x

#12625 ISPN-16283 Remove set if empty after operation
  multimap/src/main/java/org/infinispan/multimap/impl/function/set/SPopFunction.java
  multimap/src/main/java/org/infinispan/multimap/impl/function/set/SSetFunction.java
  server/resp/src/test/java/org/infinispan/server/resp/RespSetCommandsTest.java
Labels: 15.0.x

#12621 ISPN-16278 [RESP] Fix msetnx behavior with same key
  server/resp/src/main/java/org/infinispan/server/resp/commands/string/MSETNX.java
  server/resp/src/test/java/org/infinispan/server/resp/CustomStringCommands.java
  server/resp/src/test/java/org/infinispan/server/resp/StringCommandsTest.java
Labels: 15.0.x

#12628 ISPN-16286 RESP `KEYS *` hangs with persistence enabled
  server/core/src/main/java/org/infinispan/server/iteration/IterationManager.java
  server/resp/src/main/java/org/infinispan/server/resp/Resp3Handler.java
  server/resp/src/main/java/org/infinispan/server/resp/commands/iteration/BaseIterationCommand.java
  server/resp/src/test/java/org/infinispan/server/resp/AbstractRespTest.java
  server/resp/src/test/java/org/infinispan/server/resp/persistent/ClusteredPersistentStringCommandTest.java
  server/resp/src/test/java/org/infinispan/server/resp/persistent/PersistentStringCommandTest.java
Labels: 15.0.x

#12607 ISPN-16235: Doc edits for topology set-stable command review
  documentation/src/main/asciidoc/topics/proc_cli_set_topology_caches.adoc
Labels: 15.0.x

#12634 ISPN-16294 Don't force the server port in the code
  server/runtime/src/main/java/org/infinispan/server/Server.java
Labels: Trivial :-), 15.0.x

#12641 ISPN-16296 [RESP] KEYS may cause server to get stuck
  commons/all/src/main/java/org/infinispan/commons/util/GlobMatcher.java
  commons/all/src/test/java/org/infinispan/commons/util/GlobMatcherTest.java
  server/resp/src/main/java/org/infinispan/server/resp/commands/pubsub/CHANNELS.java
  server/resp/src/main/java/org/infinispan/server/resp/filter/GlobMatchFilterConverter.java
  server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java
Labels: 15.0.x

#12585 [15.0.x] ISPN-16240 ServerConfigurationSerializer should include the RESP endpoint
  server/runtime/src/main/java/org/infinispan/server/configuration/ServerConfigurationSerializer.java
  server/runtime/src/main/java/org/infinispan/server/configuration/endpoint/EndpointConfiguration.java
  server/runtime/src/main/java/org/infinispan/server/configuration/endpoint/EndpointConfigurationBuilder.java
  server/runtime/src/test/java/org/infinispan/server/configuration/ServerConfigurationSerializerTest.java
  server/runtime/src/test/resources/configuration/versions/15.0.xml
Labels: Backport

#12650 ISPN-16302 Fails to read cache files inside cache folder in Infinispa…
  commons/all/src/main/java/org/infinispan/commons/util/concurrent/FileSystemLock.java
  core/src/test/java/org/infinispan/globalstate/GlobalStateTest.java
Labels: 14.0.x, 15.0.x

#12655 ISPN-16308 Auto-detect RESP when SELECT is the first command
  server/resp/src/main/java/org/infinispan/server/resp/RespDetector.java
Labels: 15.0.x

#12645 ISPN-16233 Fix Netty buffer leaks
  commons-test/src/main/java/org/infinispan/commons/test/ThreadLeakChecker.java
  pom.xml
  server/rest/src/main/java/org/infinispan/rest/resources/BackupManagerResource.java
  server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
  server/rest/src/test/java/org/infinispan/rest/resources/AbstractRestResourceTest.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/NettyLeakDetectionLoggingConsumer.java
Labels: 15.0.x

#12659 ISPN-16311 [RESP] Inconsistent error type
  server/resp/src/main/java/org/infinispan/server/resp/RespErrorUtil.java
  server/resp/src/test/java/org/infinispan/server/resp/TransactionOperationsTest.java
  server/resp/src/test/java/org/infinispan/server/resp/test/RespTestingUtil.java
  server/tests/src/test/java/org/infinispan/server/functional/resp/RespHashTest.java
  server/tests/src/test/java/org/infinispan/server/functional/resp/RespListTest.java
  server/tests/src/test/java/org/infinispan/server/functional/resp/RespSetTest.java
  server/tests/src/test/java/org/infinispan/server/functional/resp/RespSortedSetTest.java
  server/tests/src/test/java/org/infinispan/server/functional/resp/RespTransactionTest.java
  server/tests/src/test/java/org/infinispan/server/security/authorization/RESPAuthorizationTest.java
Labels: Trivial :-), 15.0.x

#12654 ISPN-16307 Fix parsing of multi-value attributes
  core/src/main/java/org/infinispan/configuration/parsing/CacheParser.java
  core/src/main/java/org/infinispan/configuration/parsing/ParseUtils.java
  core/src/main/java/org/infinispan/configuration/parsing/Parser.java
  core/src/test/java/org/infinispan/configuration/parsing/JsonParsingTest.java
  core/src/test/java/org/infinispan/configuration/serializer/AbstractConfigurationSerializerTest.java
  core/src/test/resources/configs/aliases-test.json
  server/runtime/src/main/java/org/infinispan/server/configuration/ServerConfigurationParser.java
Labels: 15.0.x

#12658 ISPN-16310 Handle Memcached touch with 0 expiration
  server/memcached/src/main/java/org/infinispan/server/memcached/MemcachedBaseDecoder.java
  server/memcached/src/test/java/org/infinispan/server/memcached/test/MemcachedFunctionalTest.java
Labels: 15.0.x

#12660 ISPN-16306 EmbeddedTransactionManager hide exceptions for asynchronou…
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/retry/ReceiveTransactionExceptionTest.java
  core/src/main/java/org/infinispan/cache/impl/InvocationHelper.java
  core/src/test/java/org/infinispan/tx/EmbeddedTransactionManagerRollbackTest.java
Labels: 15.0.x

#12678 ISPN-16322 [RESP] Null Value should use RESP 3 null instead of RESP 2…
  server/resp/src/main/java/org/infinispan/server/resp/ByteBufferUtils.java
  server/resp/src/main/java/org/infinispan/server/resp/Consumers.java
  server/resp/src/main/java/org/infinispan/server/resp/Resp3Handler.java
  server/resp/src/main/java/org/infinispan/server/resp/RespConstants.java
  server/resp/src/main/java/org/infinispan/server/resp/commands/cluster/SHARDS.java
  server/resp/src/main/java/org/infinispan/server/resp/commands/cluster/SLOTS.java
  server/resp/src/main/java/org/infinispan/server/resp/commands/hash/HRANDFIELD.java
  server/resp/src/main/java/org/infinispan/server/resp/commands/string/MGET.java
Labels: 15.0.x

#12665 [14.0.x] ISPN-16302 Fails to read cache files inside cache folder in Infinispa…
  commons/all/src/main/java/org/infinispan/commons/util/concurrent/FileSystemLock.java
  commons/all/src/test/java/org/infinispan/commons/util/FileSystemLockTest.java
Labels: Backport
