Repository infinispan/infinispan, pull requests merged in 2024-01, with the labels that each got.

#11615 ISPN-15400 Support collection parameter serialization
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/vector/VectorSearchRemoteTest.java
  core/src/main/java/org/infinispan/marshall/protostream/impl/SerializationContextRegistryImpl.java
  graalvm/client-hotrod/src/test/resources/resource-config.json
  query/src/test/java/org/infinispan/query/vector/VectorSearchBroadcastTest.java
  server/rest/src/test/java/org/infinispan/rest/search/RestVectorSearchTest.java
  server/tests/src/test/java/org/infinispan/server/functional/hotrod/HotRodCacheQueries.java
  test-support/proto-sample-domain-implementation/pom.xml
  test-support/proto-sample-domain-implementation/src/main/java/org/infinispan/protostream/sampledomain/Image.java
  test-support/proto-sample-domain-implementation/src/main/java/org/infinispan/protostream/sampledomain/marshallers/MarshallerRegistration.java
Labels: Question

#11618 ISPN-15352 NullPointerException in case of failover brings to HR Clie…
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelPool.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelRecord.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelCloseAndInactiveTest.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/impl/transport/netty/CrashMidOperationTest.java
Labels: Question, 14.0.x

#11617 ISPN-15405 Add archetype for custom Infinispan module
  archetypes/custom-module/pom.xml
  archetypes/custom-module/src/main/resources/META-INF/maven/archetype-metadata.xml
  archetypes/custom-module/src/main/resources/archetype-resources/pom.xml
  archetypes/custom-module/src/main/resources/archetype-resources/src/main/java/Attribute.java
  archetypes/custom-module/src/main/resources/archetype-resources/src/main/java/CustomModule.java
  archetypes/custom-module/src/main/resources/archetype-resources/src/main/java/CustomModuleConfiguration.java
  archetypes/custom-module/src/main/resources/archetype-resources/src/main/java/CustomModuleConfigurationBuilder.java
  archetypes/custom-module/src/main/resources/archetype-resources/src/main/java/CustomModuleParser.java
  archetypes/custom-module/src/main/resources/archetype-resources/src/main/java/CustomModuleSerializer.java
  archetypes/custom-module/src/main/resources/archetype-resources/src/main/java/Element.java
  archetypes/custom-module/src/test/resources/projects/test/archetype.properties
  archetypes/custom-module/src/test/resources/projects/test/goal.txt
  archetypes/pom.xml
  documentation/src/main/asciidoc/topics/contributing/building.adoc
Labels: 14.0.x

#11678 ISPN-15455 Spring Session and Lettuce update
  build/configuration/pom.xml
Labels: 14.0.x

#11684 [14.0.x] ISPN-15456 PreferConsistencyRestartTest.testCrashBeforeRecover random…
  core/src/test/java/org/infinispan/partitionhandling/PreferConsistencyRestartTest.java
Labels: Backport, Test fix

#11736 ISPN-15501 Add options to configure JGroups bundler and TCP SO_LINGER
  core/src/main/resources/default-configs/default-jgroups-azure.xml
  core/src/main/resources/default-configs/default-jgroups-ec2.xml
  core/src/main/resources/default-configs/default-jgroups-google.xml
  core/src/main/resources/default-configs/default-jgroups-kubernetes.xml
  core/src/main/resources/default-configs/default-jgroups-tcp.xml
  core/src/main/resources/default-configs/default-jgroups-udp.xml
Labels: Trivial :-), 14.0.x

#11635 ISPN-15425 TopologyChangeFunctionalTest random failures
  core/src/main/java/org/infinispan/util/concurrent/locks/impl/InfinispanLock.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/LifecycleCallbacks.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/PrepareCoordinator.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/operation/BaseCompleteTransactionOperation.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/operation/CommitTransactionOperation.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/operation/RollbackTransactionOperation.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/table/TxState.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/table/functions/ConditionalMarkAsRollbackFunction.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/table/functions/CreateStateFunction.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/table/functions/PreparingDecisionFunction.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/table/functions/SetCompletedTransactionFunction.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/table/functions/SetDecisionFunction.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/table/functions/SetPreparedFunction.java
  server/hotrod/src/test/java/org/infinispan/server/hotrod/ServerHotRodTestBlockHoundIntegration.java
  server/hotrod/src/test/java/org/infinispan/server/hotrod/tx/TopologyChangeFunctionalTest.java
Labels: 14.0.x

#11634 ISPN-15427 Upgrade JGroups to 5.3.1.Final
  build/configuration/pom.xml
  quarkus/embedded/deployment/src/main/java/org/infinispan/quarkus/embedded/deployment/InfinispanEmbeddedProcessor.java
  quarkus/pom.xml
  quarkus/server/deployment/src/main/java/org/infinispan/quarkus/server/deployment/InfinispanServerProcessor.java
  server/tests/src/test/java/org/infinispan/server/footprint/FootprintIT.java
Labels: Trivial :-), Changes Required

#11727 ISPN-15494 Near cache with invalidation fails to start in Spring Boot
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/InvalidatedNearRemoteCache.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/logging/Log.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/ClusterNearCacheMarshallingTest.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/near/NearCacheMarshallingTest.java
Labels: 14.0.x

#11745 ISPN-15507 Make log4j xml parser more robust
  commons/all/src/main/java/org/infinispan/commons/logging/log4j/XmlConfiguration.java
Labels: 14.0.x

#11805 ISPN-13969 Fix SoftIndexFileStoreRestartTest#testStatsUponRestart test
  core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreRestartTest.java
Labels: Test fix, 14.0.x

#11847 [14.0x] ISPN-15425 TopologyChangeFunctionalTest random failures
  server/hotrod/src/main/java/org/infinispan/server/hotrod/LifecycleCallbacks.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/PrepareCoordinator.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/operation/BaseCompleteTransactionOperation.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/operation/CommitTransactionOperation.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/operation/RollbackTransactionOperation.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/table/TxState.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/table/functions/ConditionalMarkAsRollbackFunction.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/table/functions/CreateStateFunction.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/table/functions/PreparingDecisionFunction.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/table/functions/SetCompletedTransactionFunction.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/table/functions/SetDecisionFunction.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/tx/table/functions/SetPreparedFunction.java
  server/hotrod/src/test/java/org/infinispan/server/hotrod/ServerHotRodTestBlockHoundIntegration.java
  server/hotrod/src/test/java/org/infinispan/server/hotrod/tx/TopologyChangeFunctionalTest.java
Labels: Backport

#11845 ISPN-15571 Enable by default Insights profile
  build/configuration/pom.xml
  server/insights/src/main/java/org/infinispan/server/insights/InsightsService.java
  server/insights/src/main/java/org/infinispan/server/insights/report/InfinispanSubReportSerializer.java
  server/insights/src/main/java/org/infinispan/server/insights/report/InfinispanSubreport.java
  server/insights/src/main/java/org/infinispan/server/insights/report/InfinispanTopReport.java
  server/insights/src/test/java/org/infinispan/server/insights/BasicInsightsTest.java
  server/insights/src/test/java/org/infinispan/server/insights/InsightsActivationTest.java
Labels: 14.0.x

#11846 [14.x] ISPN-15428 Upgrade JGroups to 5.2.21.Final
  build/configuration/pom.xml
Labels: Trivial :-)

#11672 ISPN-15432 Make stable topology recovery more robust
  core/src/main/java/org/infinispan/statetransfer/InboundTransferTask.java
  core/src/main/java/org/infinispan/topology/LocalTopologyManagerImpl.java
  core/src/test/java/org/infinispan/globalstate/AbstractGlobalStateRestartTest.java
  core/src/test/java/org/infinispan/globalstate/ThreeNodeTopologyReinstallTest.java
Labels: 14.0.x

#11870 ISPN-15555 Update com.github.ben-manes.caffeine:caffeine to 3.1.8
  core/src/main/java/org/infinispan/util/concurrent/DataOperationOrderer.java
  core/src/test/java/org/infinispan/stats/SingleStatsTest.java
  server/tests/src/test/java/org/infinispan/server/persistence/JdbcStringBasedCacheStorePassivation.java
Labels: Test fix

#11869 ISPN-15606 Prevent leaking MBean for the HotRodClient
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/RemoteCacheManager.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheImpl.java
Labels: 14.0.x
