Repository infinispan/infinispan, pull requests merged in 2024-08, with the labels that each got.

#12687 ISPN-16337 ISPN004116 warn message always thrown when utising script …
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheImpl.java
Labels: 15.0.x

#12696 ISPN-16341 LocalCacheStream toList/toArray are empty when using sorte…
  core/src/main/java/org/infinispan/stream/impl/IntermediateCacheStream.java
  core/src/test/java/org/infinispan/stream/BaseStreamTest.java
Labels: Trivial :-), 15.0.x

#12697 ISPN-16284 PersistenceManagerImpl.acquireKeyFromContext(...) throws N…
  core/src/main/java/org/infinispan/interceptors/impl/PassivationWriterInterceptor.java
  core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java
Labels: 14.0.x

#12656 ISPN-16309 Throw a descriptive exception if user properties are malfo…
  server/runtime/src/main/java/org/infinispan/server/logging/Log.java
  server/runtime/src/main/java/org/infinispan/server/security/realm/EncryptedPropertiesSecurityRealm.java
Labels: 15.0.x

#12714 [15.0.x] ISPN-16347 Bump JGroups to 5.3.10.Final
  build/component-processor/src/main/java/org/infinispan/component/processor/external/JGroupsComponentProcessor.java
  build/configuration/pom.xml
  server/tests/src/test/resources/jgroups_metrics.txt
Labels: Backport

#12699 ISPN-16319 NPE thrown when attempting to remove entry with xsite.
  core/src/main/java/org/infinispan/configuration/cache/PersistenceConfiguration.java
  core/src/main/java/org/infinispan/factories/InterceptorChainFactory.java
  core/src/main/java/org/infinispan/interceptors/impl/CacheWriterInterceptor.java
  core/src/main/java/org/infinispan/interceptors/impl/DistCacheWriterInterceptor.java
  core/src/main/java/org/infinispan/interceptors/impl/IsMarshallableInterceptor.java
  core/src/test/java/org/infinispan/xsite/irac/persistence/IracAsyncStoreTest.java
Labels: 15.0.x

#12682 ISPN-16328 [RESP] HRANDFIELD against non-existing hash with count sho…
  server/resp/src/main/java/org/infinispan/server/resp/commands/hash/HRANDFIELD.java
Labels: 15.0.x

#12723 ISPN-16365 infinispan-commons contains unnecessary dependency on wild…
  commons/all/pom.xml
Labels: 15.0.x

#12751 [15.0] ISPN-16413 Upgrade Console 15.0.7.Final
  build/configuration/pom.xml
Labels: Trivial :-)

#12695 ISPN-16339 User properties format documentation
  documentation/src/main/asciidoc/topics/properties/server_users_structure.properties
  documentation/src/main/asciidoc/topics/ref_server_realm_property.adoc
Labels: Documentation, 15.0.x

#12690 ISPN-16120 LDAP SSL
  pom.xml
  server/runtime/src/main/java/org/infinispan/server/configuration/ServerConfigurationParser.java
  server/runtime/src/main/java/org/infinispan/server/configuration/security/LdapRealmConfigurationBuilder.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/AbstractInfinispanServerDriver.java
  server/tests/pom.xml
  server/tests/src/test/java/org/infinispan/server/security/AuthenticationLDAPSIT.java
  server/tests/src/test/java/org/infinispan/server/test/core/ldap/ApacheLdapServer.java
  server/tests/src/test/resources/configuration/AuthenticationLDAPSTest.xml
  server/tests/src/test/resources/configuration/security/ldap-ssl.xml
Labels: 15.0.x

#12762 ISPN-16416 ZADD catch proper validation error for incopatible options
  multimap/src/main/java/org/infinispan/multimap/impl/SortedSetAddArgs.java
  server/resp/src/test/java/org/infinispan/server/resp/SortedSetCommandsTest.java
Labels: 15.0.x

#12771 Ignore JVMCI-native CompilerThread[0-9] leaks
  commons-test/src/main/java/org/infinispan/commons/test/ThreadLeakChecker.java
Labels: 15.0.x

#12773 ISPN-16425 Setrange should not create empty entries
  server/resp/src/main/java/org/infinispan/server/resp/commands/string/SETRANGE.java
  server/resp/src/test/java/org/infinispan/server/resp/StringCommandsTest.java
Labels: 15.0.x

#12768 ISPN-16424 GETRANGE single character
  server/resp/src/main/java/org/infinispan/server/resp/commands/string/GETRANGE.java
  server/resp/src/test/java/org/infinispan/server/resp/StringCommandsTest.java
Labels: 15.0.x

#12765 ISPN-16419 Fixes LMPOP and WITHSCORES case sensitive
  server/resp/src/main/java/org/infinispan/server/resp/commands/list/LMPOP.java
  server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/ZRANK.java
  server/resp/src/main/java/org/infinispan/server/resp/commands/sortedset/ZSetCommonUtils.java
  server/resp/src/test/java/org/infinispan/server/resp/RespListCommandsTest.java
  server/resp/src/test/java/org/infinispan/server/resp/commands/sortedset/ZSetCommonUtilsTest.java
Labels: 15.0.x

#12763 ISPN-16418 Fixes Sorted Set XX option with LT or GT option
  multimap/src/main/java/org/infinispan/multimap/impl/SortedSetBucket.java
  server/resp/src/test/java/org/infinispan/server/resp/SortedSetCommandsTest.java
Labels: 15.0.x

#12772 ISPN-16383 SQL store numeric precision throwing in acceptable values
  core/src/test/java/org/infinispan/test/data/Numerics.java
  persistence/sql/src/main/java/org/infinispan/persistence/sql/AbstractSchemaJdbcStore.java
  persistence/sql/src/test/java/org/infinispan/persistence/sql/AbstractSQLStoreFunctionalTest.java
  persistence/sql/src/test/java/org/infinispan/persistence/sql/QueriesJdbcStoreFunctionalTest.java
Labels: 15.0.x

#12766 ISPN-16417 Fix maxOccurs in XSD schema for index-sharding
  core/src/main/resources/schema/infinispan-config-15.1.xsd
Labels: 15.0.x

#12730 [14.0.x] ISPN-16233 REST compare API has buffer leak issue because of not call…
  commons-test/src/main/java/org/infinispan/commons/test/ThreadLeakChecker.java
  pom.xml
  server/rest/src/main/java/org/infinispan/rest/resources/BackupManagerResource.java
  server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
  server/rest/src/test/java/org/infinispan/rest/resources/AbstractRestResourceTest.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/NettyLeakDetectionLoggingConsumer.java
Labels: Backport

#12783 ISPN-16416 Assert IllegalArgumentException
  multimap/src/test/java/org/infinispan/multimap/impl/EmbeddedMultimapSortedSetCacheTest.java
Labels: Trivial :-), Test fix

#12767 ISPN-16419 LMPOP Raise syntax error with extra args
  server/resp/src/main/java/org/infinispan/server/resp/commands/list/LMPOP.java
  server/resp/src/test/java/org/infinispan/server/resp/RespListCommandsTest.java
Labels: 15.0.x

#12788 ISPN-16442 Set JGroups bind address to localhost for Wildfly servers …
  integrationtests/server-integration/third-party-server/src/test/resources/arquillian.xml
Labels: 15.0.x

#12789 ISPN-16360 Flaky test: org.infinispan.commons.util.GlobMatcherTest#te…
  commons/all/src/main/java/org/infinispan/commons/util/GlobMatcher.java
  commons/all/src/test/java/org/infinispan/commons/util/GlobMatcherTest.java
Labels: 15.0.x

#12797 ISPN-16451 [RESP] SMOVE doesn't detect WRONGTYPE when member isn't pr…
  documentation/src/main/asciidoc/topics/ref_redis_commands.adoc
  multimap/src/main/java/org/infinispan/multimap/impl/EmbeddedSetCache.java
  server/resp/src/main/java/org/infinispan/server/resp/commands/set/SMOVE.java
  server/resp/src/test/java/org/infinispan/server/resp/RespSetCommandsTest.java
Labels: 15.0.x

#12798 ISPN-16452 [RESP] *INCRBY[FLOAT] calls leading to NaN should result i…
  multimap/src/main/java/org/infinispan/multimap/impl/SortedSetBucket.java
  server/resp/src/main/java/org/infinispan/server/resp/Resp3Handler.java
  server/resp/src/main/java/org/infinispan/server/resp/RespErrorUtil.java
  server/resp/src/main/java/org/infinispan/server/resp/commands/ArgumentUtils.java
  server/resp/src/main/java/org/infinispan/server/resp/commands/hash/HINCRBYFLOAT.java
  server/resp/src/main/java/org/infinispan/server/resp/commands/string/CounterIncOrDec.java
  server/resp/src/main/java/org/infinispan/server/resp/commands/string/INCRBYFLOAT.java
  server/resp/src/test/java/org/infinispan/server/resp/HashOperationsTest.java
  server/resp/src/test/java/org/infinispan/server/resp/SortedSetCommandsTest.java
  server/resp/src/test/java/org/infinispan/server/resp/StringCommandsTest.java
Labels: 15.0.x

#12719 ISPN-15776 Flaky test: IracAlwaysRemoveConflictTest#testRemove
  core/src/main/java/org/infinispan/interceptors/impl/AbstractIracLocalSiteInterceptor.java
  core/src/main/java/org/infinispan/interceptors/impl/NonTxIracLocalSiteInterceptor.java
  core/src/main/java/org/infinispan/interceptors/impl/OptimisticTxIracLocalSiteInterceptor.java
  core/src/main/java/org/infinispan/interceptors/impl/PessimisticTxIracLocalInterceptor.java
Labels: Test fix, 15.0.x

#12811 ISPN-16473 Skip indexing of map fields
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/annotation/model/Message.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/map/MapStringTest.java
  remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/indexing/IndexingTagHandler.java
Labels: 15.0.x
