Repository infinispan/infinispan, pull requests merged in 2024-04, with the labels that each got.

#12218 ISPN-15930 SoftIndexFileStore locking inconsistent on clear and publi…
  core/src/main/java/org/infinispan/persistence/sifs/Compactor.java
  core/src/main/java/org/infinispan/persistence/sifs/Index.java
  core/src/main/java/org/infinispan/persistence/sifs/Log.java
  core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreStressTest.java
Labels: 14.0.x

#12228 ISPN-15938 Integration tests for databases fail to find image
  server/tests/src/test/resources/database/mysql.properties
  server/tests/src/test/resources/database/postgres.properties
Labels: Trivial :-), Test fix

#12121 ISPN-15857 Allow to configure DNS record type for DNS_PING with a Java property
  core/src/main/resources/default-configs/default-jgroups-kubernetes.xml
  documentation/src/main/asciidoc/topics/ref_jgroups_extras_properties.adoc
Labels: 14.0.x

#12194 [14.0.x] ISPN-15539 commons-io:commons-io 2.15.1
  pom.xml
Labels: dependencies, java

#12238 ISPN-15943 SIFS during stop may not index puts that don't error
  core/src/main/java/org/infinispan/persistence/sifs/LogAppender.java
  core/src/main/java/org/infinispan/persistence/sifs/NonBlockingSoftIndexFileStore.java
  core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreTest.java
Labels: 14.0.x

#12224 ISPN-15923 More detailed metrics in CacheMgmtInterceptor
  commons/all/src/main/java/org/infinispan/commons/stat/CounterTracker.java
  commons/all/src/main/java/org/infinispan/commons/stat/FunctionTimerMetricInfo.java
  commons/all/src/main/java/org/infinispan/commons/stat/TimerTracker.java
  core/src/main/java/org/infinispan/factories/InterceptorChainFactory.java
  core/src/main/java/org/infinispan/factories/InternalCacheFactory.java
  core/src/main/java/org/infinispan/interceptors/impl/CacheMgmtInterceptor.java
  core/src/main/java/org/infinispan/interceptors/impl/TxInterceptor.java
  core/src/main/java/org/infinispan/metrics/impl/FunctionTimerTrackerImpl.java
  core/src/main/java/org/infinispan/metrics/impl/MetricUtils.java
  core/src/main/java/org/infinispan/metrics/impl/MetricsRegistryImpl.java
  core/src/main/java/org/infinispan/metrics/impl/TimerTrackerImpl.java
  core/src/main/java/org/infinispan/metrics/impl/helper/KeyMetrics.java
  core/src/main/java/org/infinispan/remoting/rpc/RpcManagerImpl.java
  core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsMetricsManagerImpl.java
  server/tests/src/test/java/org/infinispan/server/functional/rest/RestMetricsResourceIT.java
Labels: 14.0.x

#12217 ISPN-15895 Cross-site: 2PC transaction does not acquire locks
  commons/all/src/main/java/org/infinispan/commons/tx/TransactionImpl.java
  core/src/main/java/org/infinispan/factories/EmptyConstructorNamedCacheFactory.java
  core/src/main/java/org/infinispan/interceptors/xsite/OptimisticBackupInterceptor.java
  core/src/main/java/org/infinispan/interceptors/xsite/PessimisticBackupInterceptor.java
  core/src/main/java/org/infinispan/xsite/BackupSenderImpl.java
  core/src/main/java/org/infinispan/xsite/ClusteredCacheBackupReceiver.java
  core/src/test/java/org/infinispan/xsite/backupfailure/tx/BackupCustomFailurePolicyTxFailureTest.java
  core/src/test/java/org/infinispan/xsite/backupfailure/tx/BackupTxFailureTest.java
  core/src/test/java/org/infinispan/xsite/backupfailure/tx/BaseBackupTxFailureTest.java
  core/src/test/java/org/infinispan/xsite/backupfailure/tx/BaseLocalClusterTxFailureTest.java
  core/src/test/java/org/infinispan/xsite/backupfailure/tx/CustomFailurePolicyTxTest.java
  core/src/test/java/org/infinispan/xsite/backupfailure/tx/DistBackupTxFailureTest.java
  core/src/test/java/org/infinispan/xsite/backupfailure/tx/DistLocalClusterFailureTest.java
  core/src/test/java/org/infinispan/xsite/backupfailure/tx/DistLocalClusterTxBackupFailureTest.java
  core/src/test/java/org/infinispan/xsite/backupfailure/tx/ReplBackupTxFailureTest.java
  core/src/test/java/org/infinispan/xsite/backupfailure/tx/ReplLocalClusterFailureTest.java
  core/src/test/java/org/infinispan/xsite/backupfailure/tx/SinglePhaseCommitFailureTest.java
  server/tests/src/test/java/org/infinispan/server/functional/hotrod/XSiteHotRodCacheOperations.java
Labels: 14.0.x

#12244 ISPN-15942 Add JGroups probe and gossip router scripts
  server/runtime/src/main/server/bin/gossip-router.sh
  server/runtime/src/main/server/bin/gossiprouter.log4j2.xml
  server/runtime/src/main/server/bin/probe.sh
Labels: Trivial :-), 14.0.x

#12236 ISPN-15940 Avoid indexes creation on purge and stop/close
  query/src/main/java/org/infinispan/query/backend/QueryInterceptor.java
  query/src/main/java/org/infinispan/query/backend/SegmentListener.java
  query/src/main/java/org/infinispan/query/logging/Log.java
  query/src/main/java/org/infinispan/search/mapper/mapping/SearchMapping.java
  query/src/main/java/org/infinispan/search/mapper/mapping/impl/InfinispanMapping.java
  remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/LazySearchMapping.java
  remote-query/remote-query-server/src/test/java/org/infinispan/query/remote/impl/indexing/NoSchemaTest.java
  server/rest/src/test/java/org/infinispan/rest/ServerRestTestBlockHoundIntegration.java
Labels: 14.0.x

#12229 ISPN-15937 Protobuf metadata cache should ignore zero-capacity config…
  cli/src/main/java/org/infinispan/cli/connection/rest/RestConnection.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/ExecTest.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/ExecTypedTest.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/JsonScriptTest.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/ProtobufJsonScriptTest.java
  commons/all/src/main/java/org/infinispan/commons/internal/InternalCacheNames.java
  core/src/main/java/org/infinispan/globalstate/GlobalConfigurationManager.java
  core/src/main/java/org/infinispan/globalstate/impl/GlobalConfigurationManagerImpl.java
  core/src/main/java/org/infinispan/statetransfer/StateTransferManagerImpl.java
  core/src/test/java/org/infinispan/distribution/ZeroCapacityAdministrationTest.java
  core/src/test/java/org/infinispan/manager/CacheDependencyTest.java
  counter/src/main/java/org/infinispan/counter/impl/manager/CounterConfigurationManager.java
  counter/src/test/java/org/infinispan/counter/jmx/CounterJmxTest.java
  remote-query/remote-query-client/src/main/java/org/infinispan/query/remote/client/ProtobufMetadataManagerConstants.java
  remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/ProtobufMetadataManager.java
  remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/LifecycleManager.java
  remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/ProtobufMetadataManagerImpl.java
  remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/ProtobufMetadataManagerInterceptor.java
  remote-query/remote-query-server/src/test/java/org/infinispan/query/remote/impl/ZeroCapacityNodeProtobufMetadataTest.java
  server/core/src/main/java/org/infinispan/server/core/BaseServerManagement.java
  server/core/src/main/java/org/infinispan/server/core/backup/resources/InternalCacheResource.java
  server/hotrod/src/test/java/org/infinispan/server/hotrod/counter/impl/CounterManagerImplTestStrategy.java
  server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
  server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
  server/rest/src/test/java/org/infinispan/rest/resources/ContainerResourceTest.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/TestClient.java
  server/tests/src/test/java/org/infinispan/server/cli/CliIT.java
  server/tests/src/test/java/org/infinispan/server/cli/XSiteCliOperations.java
  server/tests/src/test/java/org/infinispan/server/functional/BackupManagerIT.java
  tasks/scripting/src/main/java/org/infinispan/scripting/ScriptingManager.java
  tasks/scripting/src/main/java/org/infinispan/scripting/impl/LifecycleCallbacks.java
  tasks/scripting/src/main/java/org/infinispan/scripting/impl/ScriptingManagerImpl.java
  tasks/scripting/src/test/java/org/infinispan/scripting/ScriptCachePreserveStateAcrossRestartsTest.java
  tasks/scripting/src/test/java/org/infinispan/scripting/ScriptingTest.java
  tasks/scripting/src/test/java/org/infinispan/scripting/SecureScriptingTaskManagerTest.java
  tasks/scripting/src/test/java/org/infinispan/scripting/SecureScriptingTest.java
Labels: 14.0.x

#12272 ISPN-15963 Protostream 5.0.2.Final
  commons/all/src/main/java/org/infinispan/commons/marshall/ProtoStreamTypeIds.java
Labels: Trivial :-)

#12283 ISPN-15976 WildFly Elytron 2.4.0.Final
  build/configuration/pom.xml
Labels: CVE

#12209 ISPN-15921 Add Server Hinting unit test
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/ServerHintingTest.java
Labels: Test fix, 14.0.x

#12284 ISPN-15977 Record fails to compile on ComponentAnnotationProcessor
  build/component-processor/src/main/java/org/infinispan/component/processor/ComponentAnnotationProcessor.java
Labels: Trivial :-)

#12289 ISPN-15981 Wrap ScriptEngine init in blocking call
  tasks/scripting/src/main/java/org/infinispan/scripting/impl/ScriptingInterceptor.java
  tasks/scripting/src/main/java/org/infinispan/scripting/impl/ScriptingManagerImpl.java
Labels: Test fix, 14.0.x

#12292 ISPN-15984 OutdatedTopologyException is not properly marshalled
  core/src/main/java/org/infinispan/marshall/exts/ThrowableExternalizer.java
Labels: Trivial :-), 14.0.x

#12262 [14.0.x] ISPN-15895 Cross-site: 2PC transaction does not acquire locks
  commons/all/src/main/java/org/infinispan/commons/tx/TransactionImpl.java
  core/src/main/java/org/infinispan/factories/EmptyConstructorNamedCacheFactory.java
  core/src/main/java/org/infinispan/interceptors/xsite/OptimisticBackupInterceptor.java
  core/src/main/java/org/infinispan/interceptors/xsite/PessimisticBackupInterceptor.java
  core/src/main/java/org/infinispan/xsite/BackupSenderImpl.java
  core/src/main/java/org/infinispan/xsite/ClusteredCacheBackupReceiver.java
  core/src/test/java/org/infinispan/xsite/backupfailure/tx/BackupCustomFailurePolicyTxFailureTest.java
  core/src/test/java/org/infinispan/xsite/backupfailure/tx/BackupTxFailureTest.java
  core/src/test/java/org/infinispan/xsite/backupfailure/tx/BaseBackupTxFailureTest.java
  core/src/test/java/org/infinispan/xsite/backupfailure/tx/BaseLocalClusterTxFailureTest.java
  core/src/test/java/org/infinispan/xsite/backupfailure/tx/CustomFailurePolicyTxTest.java
  core/src/test/java/org/infinispan/xsite/backupfailure/tx/DistBackupTxFailureTest.java
  core/src/test/java/org/infinispan/xsite/backupfailure/tx/DistLocalClusterFailureTest.java
  core/src/test/java/org/infinispan/xsite/backupfailure/tx/DistLocalClusterTxBackupFailureTest.java
  core/src/test/java/org/infinispan/xsite/backupfailure/tx/ReplBackupTxFailureTest.java
  core/src/test/java/org/infinispan/xsite/backupfailure/tx/ReplLocalClusterFailureTest.java
  core/src/test/java/org/infinispan/xsite/backupfailure/tx/SinglePhaseCommitFailureTest.java
  server/tests/src/test/java/org/infinispan/server/functional/hotrod/XSiteHotRodCacheOperations.java
Labels: Backport, Image Required

#12234 [14.0.x] ISPN-15872 View change during a cache join can lead to not replicatin…
  core/src/main/java/org/infinispan/commands/topology/CacheJoinCommand.java
  core/src/main/java/org/infinispan/topology/LocalTopologyManagerImpl.java
  core/src/test/java/org/infinispan/commands/CommandIdUniquenessTest.java
  core/src/test/java/org/infinispan/test/Mocks.java
  core/src/test/java/org/infinispan/topology/ClusterTopologyViewChangesTest.java
  core/src/test/java/org/infinispan/topology/TopologyUnorderedJoinTest.java
Labels: Backport

#12328 [14.0.x] ISPN-16025 Disable CloudEventsIntegrationIT in 14.0.x branch
  server/tests/src/test/java/org/infinispan/server/functional/CloudEventsIntegrationIT.java
Labels: Trivial :-), Test fix
