Repository infinispan/infinispan, pull requests merged in 2024-02, with the labels that each got.

#11871 [14.0] ISPN-15555 Update com.github.ben-manes.caffeine:caffeine to 3.1.8
  build/configuration/pom.xml
  core/src/main/java/org/infinispan/util/concurrent/DataOperationOrderer.java
  core/src/test/java/org/infinispan/stats/SingleStatsTest.java
  server/tests/src/test/java/org/infinispan/server/persistence/JdbcStringBasedCacheStorePassivation.java
Labels: Backport

#11905 ISPN-15636 Fix RESP command case-insensitive handling
  server/resp/src/main/java/org/infinispan/server/resp/Util.java
Labels: Trivial :-)

#11933 Revert "Disable Jenkins image creation until cekit issues resolved"
  Jenkinsfile
Labels: Image Required

#11929 ISPN-15658 Do no fail build if snapshot deployment fails
  Jenkinsfile
Labels: 14.0.x

#11944 ISPN-15658 Do no fail build if snapshot deployment fails
  Jenkinsfile
Labels: Trivial :-)

#11942 ISPN-15665 SSLContext ignored by RemoteStore
  persistence/remote/src/main/java/org/infinispan/persistence/remote/RemoteStore.java
  persistence/remote/src/main/java/org/infinispan/persistence/remote/configuration/SslConfiguration.java
Labels: Trivial :-), 14.0.x

#11928 ISPN-15657 NullPointerException in MBeans without getters
  commons/all/src/main/java/org/infinispan/commons/stat/TimerTracker.java
  core/src/main/java/org/infinispan/interceptors/impl/CacheMgmtInterceptor.java
  core/src/main/java/org/infinispan/jmx/ResourceDMBean.java
  core/src/main/java/org/infinispan/metrics/impl/AbstractMetricsRegistration.java
  core/src/main/java/org/infinispan/metrics/impl/CustomMetricsSupplier.java
  core/src/main/java/org/infinispan/persistence/manager/PersistenceManagerImpl.java
  core/src/main/java/org/infinispan/remoting/rpc/RpcManagerImpl.java
  core/src/main/java/org/infinispan/xsite/XSiteAdminOperations.java
  core/src/main/java/org/infinispan/xsite/status/DefaultTakeOfflineManager.java
  core/src/main/java/org/infinispan/xsite/status/TakeOfflineManager.java
Labels: 14.0.x

#11953 ISPN-15675 ExpirationFileStoreDistListenerFunctionalTest doesn't clea…
  core/src/test/java/org/infinispan/expiration/impl/ExpirationFileStoreDistListenerFunctionalTest.java
  core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreFileStatsTest.java
Labels: Test fix, 14.0.x

#11951 ISPN-15674 Undeprecate JBoss Marshalling
  core/src/main/java/org/infinispan/util/logging/Log.java
  documentation/src/main/asciidoc/topics/proc_using_jboss_marshaller.adoc
  jboss-marshalling/src/main/java/org/infinispan/jboss/marshalling/JbossMarshallingModule.java
  jboss-marshalling/src/main/java/org/infinispan/jboss/marshalling/commons/AbstractJBossMarshaller.java
  jboss-marshalling/src/main/java/org/infinispan/jboss/marshalling/commons/CheckedClassResolver.java
  jboss-marshalling/src/main/java/org/infinispan/jboss/marshalling/commons/DefaultContextClassResolver.java
  jboss-marshalling/src/main/java/org/infinispan/jboss/marshalling/commons/ExtendedRiverMarshaller.java
  jboss-marshalling/src/main/java/org/infinispan/jboss/marshalling/commons/ExtendedRiverUnmarshaller.java
  jboss-marshalling/src/main/java/org/infinispan/jboss/marshalling/commons/JBossExternalizerAdapter.java
  jboss-marshalling/src/main/java/org/infinispan/jboss/marshalling/commons/JBossMarshallerFactory.java
  jboss-marshalling/src/main/java/org/infinispan/jboss/marshalling/commons/RiverCloseListener.java
  jboss-marshalling/src/main/java/org/infinispan/jboss/marshalling/commons/SerializeWithExtFactory.java
  jboss-marshalling/src/main/java/org/infinispan/jboss/marshalling/core/JBossMarshaller.java
  jboss-marshalling/src/main/java/org/infinispan/jboss/marshalling/core/JBossUserMarshaller.java
Labels: 14.0.x

#11930 [14.0.x] ISPN-15659 Hot Rod Client RemoteCache#computeAsync() can lose the res…
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/RemoteCacheImpl.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/protocol/HeaderParams.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/HotRodIntegrationTest.java
Labels: Backport

#11996 Fixes FootprintIT test
  server/tests/src/test/java/org/infinispan/server/footprint/FootprintIT.java
Labels: Trivial :-), Test fix

#12006 ISPN-15719 Remove JGroups AWS and Azure
  core/src/main/resources/default-configs/default-jgroups-ec2.xml
  distribution/pom.xml
  documentation/src/main/asciidoc/topics/ref_discovery_cloud.adoc
  pom.xml
Labels: Trivial :-)

#12007 ISPN-15720 Drop cloudevents module
  build/bom/pom.xml
  cloudevents-integration/pom.xml
  cloudevents-integration/src/main/java/org/infinispan/cloudevents/CloudEventsModule.java
  cloudevents-integration/src/main/java/org/infinispan/cloudevents/README.md
  cloudevents-integration/src/main/java/org/infinispan/cloudevents/configuration/Attribute.java
  cloudevents-integration/src/main/java/org/infinispan/cloudevents/configuration/CloudEventsConfiguration.java
  cloudevents-integration/src/main/java/org/infinispan/cloudevents/configuration/CloudEventsConfigurationBuilder.java
  cloudevents-integration/src/main/java/org/infinispan/cloudevents/configuration/CloudEventsConfigurationParser.java
  cloudevents-integration/src/main/java/org/infinispan/cloudevents/configuration/CloudEventsConfigurationSerializer.java
  cloudevents-integration/src/main/java/org/infinispan/cloudevents/configuration/CloudEventsGlobalConfiguration.java
  cloudevents-integration/src/main/java/org/infinispan/cloudevents/configuration/CloudEventsGlobalConfigurationBuilder.java
  cloudevents-integration/src/main/java/org/infinispan/cloudevents/configuration/CloudEventsGlobalConfigurationSerializer.java
  cloudevents-integration/src/main/java/org/infinispan/cloudevents/configuration/Element.java
  cloudevents-integration/src/main/java/org/infinispan/cloudevents/impl/EntryEventListener.java
  cloudevents-integration/src/main/java/org/infinispan/cloudevents/impl/KafkaEventSender.java
  cloudevents-integration/src/main/java/org/infinispan/cloudevents/impl/KafkaEventSenderFactory.java
  cloudevents-integration/src/main/java/org/infinispan/cloudevents/impl/KafkaEventSenderImpl.java
  cloudevents-integration/src/main/java/org/infinispan/cloudevents/impl/Log.java
  cloudevents-integration/src/main/java/org/infinispan/cloudevents/impl/StructuredEventBuilder.java
  cloudevents-integration/src/main/resources/schema/infinispan-cloudevents-config-15.0.xsd
  cloudevents-integration/src/test/java/org/infinispan/cloudevents/CacheEntryCloudEventsTest.java
  cloudevents-integration/src/test/java/org/infinispan/cloudevents/CloudEventsConfigurationSerializerTest.java
  cloudevents-integration/src/test/java/org/infinispan/cloudevents/MockKafkaEventSender.java
  cloudevents-integration/src/test/resources/configs/all/cloudevents.xml
  cloudevents-integration/src/test/resources/configs/cloudevents-missing-bootstrap-servers.xml
  core/src/test/java/org/infinispan/commands/module/TestModuleLifecycle.java
  documentation/src/main/asciidoc/stories/assembly_cloud_events.adoc
  documentation/src/main/asciidoc/topics/cloudevents_integration.adoc
  pom.xml
  quarkus/server/runtime/pom.xml
  server/runtime/pom.xml
  server/tests/pom.xml
  server/tests/src/test/java/org/infinispan/server/functional/CloudEventsIntegrationIT.java
  server/tests/src/test/resources/configuration/CloudEventsIntegration.xml
  server/tests/src/test/resources/configuration/cache-container/clustered-cloudevents.xml
Labels: Trivial :-)

#12004 ISPN-15717: Fix proto schema, cache configuration in SQL store config
  documentation/src/main/asciidoc/topics/code_examples/PersistenceSqlQuery.java
  documentation/src/main/asciidoc/topics/json/persistence_sql_query.json
  documentation/src/main/asciidoc/topics/protobuf/address-db-table.proto
  documentation/src/main/asciidoc/topics/protobuf/person-db-table.proto
  documentation/src/main/asciidoc/topics/ref_sql_store_query_configuration.adoc
  documentation/src/main/asciidoc/topics/xml/persistence_sql_query.xml
  documentation/src/main/asciidoc/topics/yaml/persistence_sql_query.yaml
Labels: 14.0.x

#12015 ISPN-15725 TracingConfiguration categories always serialized
  core/src/main/java/org/infinispan/configuration/cache/TracingConfiguration.java
  core/src/test/java/org/infinispan/configuration/ConfigurationConversionTest.java
Labels: Image Required

#12028 ISPN-15736 Log broadcast queries and loading
  query/src/main/java/org/infinispan/query/clustered/ClusteredQueryInvoker.java
  query/src/main/java/org/infinispan/query/clustered/DistributedIndexedQueryImpl.java
Labels: 14.0.x

#11995 [14.0] ISPN-15202 Mask Hot Rod and database credentials when serializing con…
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/HotRodURI.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/configuration/ConfigurationTest.java
  client/hotrod/src/main/java/org/infinispan/hotrod/impl/HotRodURI.java
  commons/all/src/main/java/org/infinispan/commons/configuration/BasicConfiguration.java
  commons/all/src/main/java/org/infinispan/commons/configuration/StringConfiguration.java
  commons/all/src/main/java/org/infinispan/commons/configuration/attributes/AttributeSerializer.java
  core/src/main/java/org/infinispan/configuration/cache/Configuration.java
  core/src/main/java/org/infinispan/globalstate/impl/GlobalConfigurationManagerImpl.java
  persistence/jdbc-common/src/main/java/org/infinispan/persistence/jdbc/common/configuration/AbstractJdbcStoreConfigurationSerializer.java
  persistence/jdbc-common/src/main/java/org/infinispan/persistence/jdbc/common/configuration/AbstractUnmanagedConnectionFactoryConfiguration.java
  persistence/jdbc-common/src/main/java/org/infinispan/persistence/jdbc/common/configuration/ConnectionFactoryConfiguration.java
  persistence/jdbc/src/test/java/org/infinispan/persistence/jdbc/configuration/ConfigurationSerializerTest.java
  persistence/remote/src/main/java/org/infinispan/persistence/remote/configuration/KeyStoreConfiguration.java
  persistence/remote/src/main/java/org/infinispan/persistence/remote/configuration/MechanismConfiguration.java
  persistence/remote/src/main/java/org/infinispan/persistence/remote/configuration/RemoteStoreConfiguration.java
  persistence/remote/src/main/java/org/infinispan/persistence/remote/configuration/SslConfiguration.java
  persistence/remote/src/main/java/org/infinispan/persistence/remote/configuration/TrustStoreConfiguration.java
  persistence/remote/src/main/java/org/infinispan/persistence/remote/upgrade/SerializationUtils.java
  persistence/sql/src/test/java/org/infinispan/persistence/sql/configuration/ConfigurationSerializerTest.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/AbstractInfinispanServerDriver.java
  server/tests/src/test/java/org/infinispan/server/persistence/JdbcConfigurationUtil.java
  server/tests/src/test/java/org/infinispan/server/persistence/JdbcStringBasedCacheStorePassivation.java
Labels: Backport, CVE

#12027 [14.0] ISPN-15685 Fix projection names with Rest client
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/projection/RemoteProjectionTest.java
  remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/impl/JsonQuerySerializer.java
  remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/json/EntityProjection.java
  remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/json/Hit.java
  remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/json/JsonProjection.java
  remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/json/JsonQueryResponse.java
  remote-query/remote-query-server/src/main/java/org/infinispan/query/remote/json/ProjectedJsonResult.java
  server/rest/src/test/java/org/infinispan/rest/search/projection/RestProjectionTest.java
  server/rest/src/test/java/org/infinispan/rest/search/vector/RestVectorSearchTest.java
Labels: Backport

#11919 ISPN-15626 Hot Rod client tries to schedule operation twice
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelPool.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/impl/transport/netty/AcquireChannelOperation.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/impl/transport/netty/CloseBeforeEnqueuingTest.java
Labels: 14.0.x

#12055 fix ascii syntax to prevent renderring issues
  documentation/src/main/asciidoc/topics/ref_redis_commands.adoc
Labels: Documentation

#12054 ISPN-15755 Add WebSphere Liberty TransactionManager
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/transaction/lookup/GenericTransactionManagerLookup.java
  client/hotrod/src/main/java/org/infinispan/hotrod/transaction/lookup/GenericTransactionManagerLookup.java
  commons/all/src/main/java/org/infinispan/commons/logging/Log.java
  commons/all/src/main/java/org/infinispan/commons/tx/lookup/LookupNames.java
  core/src/main/java/org/infinispan/transaction/lookup/GenericTransactionManagerLookup.java
Labels: 14.0.x

#12036 ISPN-15744 Remove metric data from the overview report
  core/src/main/java/org/infinispan/manager/CacheManagerInfo.java
  core/src/main/java/org/infinispan/metrics/impl/BaseOperatingSystemAdditionalMetrics.java
  server/core/src/main/java/org/infinispan/server/core/BaseServerManagement.java
  server/rest/src/test/java/org/infinispan/rest/resources/OverviewReportResourceTest.java
Labels: Question, 14.0.x

#12058 ISPN-15758 Publisher should fetch data from remote nodes
  commons/all/src/main/java/org/infinispan/commons/util/EnumUtil.java
  core/src/main/java/org/infinispan/reactive/publisher/impl/ClusterPublisherManagerImpl.java
  core/src/test/java/org/infinispan/persistence/SharedStoreTest.java
Labels: 14.0.x
