Repository infinispan/infinispan, pull requests merged in 2024-03, with the labels that each got.

#12072 ISPN-15769 Response time between nodes is not correctly computed
  core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsMetricsManagerImpl.java
  server/tests/src/test/java/org/infinispan/server/functional/rest/RestMetricsResourceIT.java
Labels: Trivial :-), 14.0.x

#12070 [14.0.x] ISPN-15712 org.apache.commons:commons-compress 1.26.0
  build/configuration/pom.xml
  cli-jakarta/pom.xml
  cli/pom.xml
  pom.xml
  server/testdriver/core/pom.xml
Labels: Backport

#12073 ISPN-15772 Allow report file writing on cert exception
  server/insights/src/main/java/org/infinispan/server/insights/InfinispanInsightsConfiguration.java
  server/insights/src/main/java/org/infinispan/server/insights/InsightsService.java
  server/insights/src/main/java/org/infinispan/server/insights/logging/Log.java
  server/insights/src/test/java/org/infinispan/server/insights/InsightsActivationTest.java
Labels: 14.0.x

#12092 [14.0.x] ISPN-15735 Report flaky infinispan tests to Jira
  Jenkinsfile
  bin/jira/add_comment.sh
  bin/jira/add_fix_version.sh
  bin/jira/add_pull_request.sh
  bin/jira/assign_issue.sh
  bin/jira/common.sh
  bin/jira/track_flaky_tests.sh
  bin/jira/transition.sh
  bin/jira/upsert.sh
Labels: Backport

#12096 [14.0] ISPN-15757 Fix JMH annotation processor
  cli/pom.xml
Labels: Trivial :-), Backport, Test fix

#12103 ISPN-8652 - Updated test.
  jcache/commons/src/test/java/org/infinispan/jcache/AbstractTwoCachesBasicOpsTest.java
Labels: 14.0.x

#12107 [14.0.x] ISPN-15838 Add realm to tls-endpoint for Insights
  server/runtime/src/main/java/org/infinispan/server/Server.java
  server/runtime/src/main/java/org/infinispan/server/configuration/endpoint/EndpointConfiguration.java
  server/tests/src/test/java/org/infinispan/server/security/AuthenticationCertIT.java
  server/tests/src/test/java/org/infinispan/server/security/TLSWithoutAuthenticationIT.java
Labels: Backport

#12120 ISPN-15489 ProtoStream 5.0.1.Final
  build/configuration/pom.xml
Labels: Image Required

#12144 ISPN-15866 SimpleCache compute with same value doesn't notify or retu…
  core/src/main/java/org/infinispan/cache/impl/SimpleCacheImpl.java
  core/src/test/java/org/infinispan/api/SimpleCacheTest.java
Labels: 14.0.x

#12141 [14.0] ISPN-15865 Avoid to stop the server in case of Insights error
  server/insights/src/main/java/org/infinispan/server/insights/InsightsModule.java
  server/insights/src/main/java/org/infinispan/server/insights/InsightsService.java
  server/insights/src/main/java/org/infinispan/server/insights/logging/Log.java
  server/insights/src/test/java/org/infinispan/server/insights/BasicInsightsTest.java
  server/insights/src/test/java/org/infinispan/server/insights/InsightsActivationTest.java
Labels: Backport

#12157 [14.0] ISPN-15881 Check null service at cache manager stopping
  server/insights/src/main/java/org/infinispan/server/insights/InsightsModule.java
Labels: Backport

#12133 ISPN-15861 SIFS doc omitted that purge on startup is for clustered ca…
  documentation/src/main/asciidoc/topics/con_file_based_cache_stores.adoc
Labels: Trivial :-), Documentation, 14.0.x

#12142 ISPN-15782 Flaky test: org.infinispan.expiration.impl.ExpirationFileS…
  core/src/main/java/org/infinispan/expiration/impl/ExpirationManagerImpl.java
  core/src/main/java/org/infinispan/persistence/sifs/Compactor.java
Labels: 14.0.x

#12169 ISPN-15894 SoftIndexFileStore clear during a write can cause index to…
  core/src/main/java/org/infinispan/persistence/sifs/LogAppender.java
Labels: 14.0.x

#12171 ISPN-15896 Do not autostart authorization components when disabled
  core/src/main/java/org/infinispan/factories/EmptyConstructorFactory.java
  core/src/test/java/org/infinispan/manager/CacheDependencyTest.java
Labels: 14.0.x

#12130 ISPN-15717: [Follow-up] Fix proto schema, cache configuration in SQL
  documentation/src/main/asciidoc/topics/code_examples/PersistenceSqlQuery.java
  documentation/src/main/asciidoc/topics/json/persistence_sql_query.json
  documentation/src/main/asciidoc/topics/protobuf/person-db-table.proto
  documentation/src/main/asciidoc/topics/xml/persistence_sql_query.xml
  documentation/src/main/asciidoc/topics/yaml/persistence_sql_query.yaml
Labels: 14.0.x

#12175 ISPN-15898 QueryEngine logs a DEBUG message for every query executed
  query-core/src/main/java/org/infinispan/query/core/impl/QueryEngine.java
  query/src/main/java/org/infinispan/query/dsl/embedded/impl/QueryEngine.java
Labels: Trivial :-), 14.0.x

#12140 ISPN-15860 Exception with async store when not segmented
  core/src/main/java/org/infinispan/persistence/async/AsyncNonBlockingStore.java
  core/src/test/java/org/infinispan/persistence/dummy/DummyInMemoryStore.java
  core/src/test/java/org/infinispan/persistence/dummy/DummyInMemoryStoreConfiguration.java
  core/src/test/java/org/infinispan/persistence/dummy/DummyInMemoryStoreConfigurationBuilder.java
  core/src/test/java/org/infinispan/persistence/support/AsyncStoreTest.java
Labels: 14.0.x

#12201 Quiet jenkins warning plugin
  Jenkinsfile
Labels: 14.0.x

#12193 ISPN-15778 Flaky test: org.infinispan.client.hotrod.HotRodIntegration…
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/HotRodIntegrationTest.java
Labels: Test fix, 14.0.x

#12199 ISPN-15915 Fix configdocs
  core/src/main/resources/schema/infinispan-config-15.0.xsd
  tools/src/main/resources/xsd/xsdoc.xslt
Labels: Trivial :-)

#12202 ISPN-15817 Flaky test: org.infinispan.globalstate.ThreeNodeReplGlobal…
  core/src/main/java/org/infinispan/topology/LocalTopologyManagerImpl.java
Labels: 14.0.x

#12158 ISPN-15872 View change during a cache join can lead to not replicatin…
  core/src/main/java/org/infinispan/commands/topology/CacheJoinCommand.java
  core/src/main/java/org/infinispan/topology/LocalTopologyManagerImpl.java
  core/src/test/java/org/infinispan/commands/CommandIdUniquenessTest.java
  core/src/test/java/org/infinispan/test/Mocks.java
  core/src/test/java/org/infinispan/topology/ClusterTopologyViewChangesTest.java
  core/src/test/java/org/infinispan/topology/TopologyUnorderedJoinTest.java
Labels: 14.0.x
