Repository infinispan/infinispan, pull requests merged in 2025-05, with the labels that each got.

#14689 [15.0.x] [#14662] Return fixed id in case of shutdown
  server/insights/src/main/java/org/infinispan/server/insights/InfinispanInsightsConfiguration.java
Labels: target/15.0.x

#14715 [15.0.x] [#14630] Break cycle between local and cluster topology manager
  core/src/main/java/org/infinispan/commands/topology/CacheStatusRequestCommand.java
  core/src/main/java/org/infinispan/commands/topology/TopologyUpdateCommand.java
  core/src/main/java/org/infinispan/commands/topology/TopologyUpdateStableCommand.java
  core/src/main/java/org/infinispan/factories/GlobalComponentRegistry.java
  core/src/main/java/org/infinispan/topology/ClusterTopologyManagerImpl.java
  core/src/main/java/org/infinispan/topology/LocalTopologyManagerImpl.java
  core/src/test/java/org/infinispan/topology/AbstractStatefulCluster.java
  core/src/test/java/org/infinispan/topology/ClusterTopologyStatefulTest.java
Labels: pr/backport, area/core, target/15.0.x

#14714 [15.2.x] [#14630] Break cycle between local and cluster topology manager
  core/src/main/java/org/infinispan/commands/topology/CacheStatusRequestCommand.java
  core/src/main/java/org/infinispan/commands/topology/TopologyUpdateCommand.java
  core/src/main/java/org/infinispan/commands/topology/TopologyUpdateStableCommand.java
  core/src/main/java/org/infinispan/factories/GlobalComponentRegistry.java
  core/src/main/java/org/infinispan/topology/ClusterTopologyManagerImpl.java
  core/src/main/java/org/infinispan/topology/LocalTopologyManagerImpl.java
  core/src/test/java/org/infinispan/topology/AbstractStatefulCluster.java
  core/src/test/java/org/infinispan/topology/ClusterTopologyStatefulTest.java
Labels: pr/backport, area/core, target/15.2.x

#14713 [#14712] Disable op upgrade test on main
  .github/workflows/operator_upgrade.yaml
Labels: pr/trivial 😀, github_actions

#14726 [#14725] Add port_range back to the default stacks
  core/src/main/resources/default-configs/default-jgroups-azure.xml
  core/src/main/resources/default-configs/default-jgroups-ec2.xml
  core/src/main/resources/default-configs/default-jgroups-google.xml
  core/src/main/resources/default-configs/default-jgroups-kubernetes.xml
  core/src/main/resources/default-configs/default-jgroups-tcp.xml
  core/src/main/resources/default-configs/default-jgroups-tunnel.xml
  core/src/main/resources/default-configs/default-jgroups-udp.xml
Labels: pr/trivial 😀, backport/15.0.x, area/clustering, backport/15.2.x

#14703 [15.2.x] [#14700] Move custom testcontainers.properties out of the server test…
  server/tests/src/test/resources/testcontainers.properties
Labels: target/15.2.x

#14728 [15.0.x] [#14725] Add port_range back to the default stacks
  core/src/main/resources/default-configs/default-jgroups-azure.xml
  core/src/main/resources/default-configs/default-jgroups-ec2.xml
  core/src/main/resources/default-configs/default-jgroups-google.xml
  core/src/main/resources/default-configs/default-jgroups-kubernetes.xml
  core/src/main/resources/default-configs/default-jgroups-tcp.xml
  core/src/main/resources/default-configs/default-jgroups-tunnel.xml
  core/src/main/resources/default-configs/default-jgroups-udp.xml
Labels: target/15.0.x

#14690 [15.2.x] [#14662] Return fixed id in case of shutdown
  server/insights/src/main/java/org/infinispan/server/insights/InfinispanInsightsConfiguration.java
Labels: target/15.2.x

#14754 [#14753] upgrade graalvm to 24.0.1
  build/configuration/pom.xml
Labels: backport/15.0.x

#14760 [#14759] CommonNameRoleMapper support for bare names
  core/src/main/java/org/infinispan/security/mappers/CommonNameRoleMapper.java
  core/src/test/java/org/infinispan/security/RoleMapperTest.java
Labels: backport/15.0.x

#14787 [15.0.x] [#14759] CommonNameRoleMapper support for bare names
  core/src/main/java/org/infinispan/security/mappers/CommonNameRoleMapper.java
  core/src/test/java/org/infinispan/security/RoleMapperTest.java
Labels: target/15.0.x

#14761 [15.0.x] [#14753] upgrade graalvm to 24.0.1
  build/configuration/pom.xml
Labels: target/15.0.x

#14780 [#14777] Intermittent Indexing incorrectly states Hibernate Search qu…
  query/src/main/java/org/infinispan/search/mapper/work/impl/SearchIndexerImpl.java
Labels: backport/15.0.x, backport/15.2.x

#14793 Revert "[#14575] Close stale 'kind/flaky test' issue"
  .github/workflows/cron-close-stale-issues.yaml
  bin/gh/track_flaky_tests.sh
Labels: github_actions

#14807 [15.2] [#14796] SoftIndexFileStore should proactively purge and not rely upo…
  core/src/main/java/org/infinispan/persistence/InitializationContextImpl.java
  core/src/main/java/org/infinispan/persistence/sifs/NonBlockingSoftIndexFileStore.java
  core/src/main/java/org/infinispan/persistence/spi/InitializationContext.java
Labels: area/core, target/15.2.x

#14808 [15.0] [#14796] SoftIndexFileStore should proactively purge and not rely upo…
  core/src/main/java/org/infinispan/persistence/InitializationContextImpl.java
  core/src/main/java/org/infinispan/persistence/sifs/NonBlockingSoftIndexFileStore.java
  core/src/main/java/org/infinispan/persistence/spi/InitializationContext.java
Labels: target/15.0.x

#14816 [#14815] RESP documentation page fix
  documentation/src/main/asciidoc/stories/assembly_resp_endpoint.adoc
Labels: pr/trivial 😀, backport/15.0.x, backport/15.1.x, backport/15.2.x

#14826 [15.0.x] [#14815] RESP documentation page fix
  documentation/src/main/asciidoc/stories/assembly_resp_endpoint.adoc
Labels: target/15.0.x

#14828 [15.2.x] [#14815] RESP documentation page fix
  documentation/src/main/asciidoc/stories/assembly_resp_endpoint.adoc
Labels: target/15.2.x

#14843 [15.0.x] [#14821] Soft Index File Store calculates the highest sequence id at …
  core/src/main/java/org/infinispan/persistence/sifs/Index.java
  core/src/main/java/org/infinispan/persistence/sifs/LogAppender.java
  core/src/main/java/org/infinispan/persistence/sifs/NonBlockingSoftIndexFileStore.java
Labels: target/15.0.x

#14823 [#14820] Size method with a local cache and store is not optimized
  core/src/main/java/org/infinispan/interceptors/impl/CacheLoaderInterceptor.java
  core/src/main/java/org/infinispan/persistence/sifs/Index.java
  core/src/test/java/org/infinispan/expiration/impl/ExpirationFunctionalTest.java
  core/src/test/java/org/infinispan/expiration/impl/ExpirationStoreFunctionalTest.java
  core/src/test/java/org/infinispan/persistence/dummy/DummyInMemoryStore.java
Labels: pr/changes required, backport/15.0.x, backport/15.2.x

#14851 [15.0.x] [#14820] Size method with a local cache and store is not optimized
  core/src/main/java/org/infinispan/interceptors/impl/CacheLoaderInterceptor.java
  core/src/main/java/org/infinispan/persistence/sifs/Index.java
  core/src/test/java/org/infinispan/expiration/impl/ExpirationFunctionalTest.java
  core/src/test/java/org/infinispan/expiration/impl/ExpirationStoreFunctionalTest.java
  core/src/test/java/org/infinispan/persistence/dummy/DummyInMemoryStore.java
Labels: target/15.0.x

#14681 [#14680] Align 15.0.x GH workflow with main
  .github/actions/build-infinispan/action.yml
  .github/actions/extract-maven-artifacts/action.yml
  .github/workflows/on_propen_push_do_build.yml
  .github/workflows/on_propen_push_do_test.yml
Labels: target/15.0.x

#14669 [#14663] On main docs go to dev
  .github/workflows/sync_docs.yml
Labels: github_actions, area/documentation

#14825 [#14802] Add resource for health check
  client/rest-client/src/main/java/org/infinispan/client/rest/RestServerClient.java
  client/rest-client/src/main/java/org/infinispan/client/rest/impl/jdk/RestServerClientJDK.java
  core/src/main/java/org/infinispan/manager/CacheManagerInfo.java
  server/rest/src/main/java/org/infinispan/rest/RestServer.java
  server/rest/src/main/java/org/infinispan/rest/resources/ContainerResource.java
  server/rest/src/main/java/org/infinispan/rest/resources/HealthCheckResource.java
  server/rest/src/test/java/org/infinispan/rest/resources/AbstractRestResourceTest.java
  server/rest/src/test/java/org/infinispan/rest/resources/HealthCheckResourceTest.java
Labels: pr/Image Required, area/server/rest, area/client/rest

#14852 [15.2.x] [#14820] Size method with a local cache and store is not optimized
  core/src/main/java/org/infinispan/interceptors/impl/CacheLoaderInterceptor.java
  core/src/main/java/org/infinispan/persistence/sifs/Index.java
  core/src/test/java/org/infinispan/expiration/impl/ExpirationFunctionalTest.java
  core/src/test/java/org/infinispan/expiration/impl/ExpirationStoreFunctionalTest.java
  core/src/test/java/org/infinispan/persistence/dummy/DummyInMemoryStore.java
Labels: target/15.2.x

#14856 [15.2.x] Add resource for health check
  client/rest-client/src/main/java/org/infinispan/client/rest/RestServerClient.java
  client/rest-client/src/main/java/org/infinispan/client/rest/impl/jdk/RestServerClientJDK.java
  core/src/main/java/org/infinispan/manager/CacheManagerInfo.java
  server/rest/src/main/java/org/infinispan/rest/RestServer.java
  server/rest/src/main/java/org/infinispan/rest/resources/HealthCheckResource.java
  server/rest/src/test/java/org/infinispan/rest/resources/AbstractRestResourceTest.java
  server/rest/src/test/java/org/infinispan/rest/resources/HealthCheckResourceTest.java
Labels: target/15.2.x

#14864 [15.0.x] [#14863] infinispan-server-integration tests missing file cause GH Action CI to fail
  integrationtests/server-integration/pom.xml
  integrationtests/server-integration/server-integration-commons/pom.xml
  integrationtests/server-integration/third-party-server/pom.xml
Labels: target/15.0.x

#14839 [15.2] [#14709] Replace synchronized block with lock in SoftIndexFileStore
  core/src/main/java/org/infinispan/persistence/sifs/IndexNode.java
Labels: pr/backport, target/15.2.x

#14840 [15.0] [#14709] Replace synchronized block with lock in SoftIndexFileStore
  core/src/main/java/org/infinispan/persistence/sifs/IndexNode.java
Labels: pr/backport, target/15.0.x

#14857 [15.0.x] Add resource for health check
  client/rest-client/src/main/java/org/infinispan/client/rest/RestServerClient.java
  client/rest-client/src/main/java/org/infinispan/client/rest/impl/jdk/RestServerClientJDK.java
  core/src/main/java/org/infinispan/manager/CacheManagerInfo.java
  server/rest/src/main/java/org/infinispan/rest/RestServer.java
  server/rest/src/main/java/org/infinispan/rest/resources/HealthCheckResource.java
  server/rest/src/test/java/org/infinispan/rest/resources/AbstractRestResourceTest.java
  server/rest/src/test/java/org/infinispan/rest/resources/HealthCheckResourceTest.java
Labels: pr/Image Required, target/15.0.x

#14869 [#14802] Recovering caches marked as ready
  core/src/main/java/org/infinispan/manager/CacheManagerInfo.java
  core/src/main/java/org/infinispan/topology/LocalTopologyManager.java
  core/src/main/java/org/infinispan/topology/LocalTopologyManagerImpl.java
  server/tests/src/test/java/org/infinispan/server/resilience/GracefulShutdownRestartIT.java
Labels: backport/15.0.x, backport/15.2.x

#14871 [15.2.x] [#14802] Recovering caches marked as ready
  core/src/main/java/org/infinispan/manager/CacheManagerInfo.java
  core/src/main/java/org/infinispan/topology/LocalTopologyManager.java
  core/src/main/java/org/infinispan/topology/LocalTopologyManagerImpl.java
  server/tests/src/test/java/org/infinispan/server/resilience/GracefulShutdownRestartIT.java
Labels: target/15.2.x

#14687 [15.2] [#14556] Workaround network interface test failures on GitHub Actions
  .github/workflows/on_build_do_test.yml
  commons-test/src/main/java/org/infinispan/commons/test/skip/SkipTestNG.java
  server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodMultiHomedAddressTest.java
  server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodSingleClusteredNonLoopbackTest.java
Labels: pr/test fix, backport/15.0.x, target/15.2.x

#14853 [15.0] [#14556] Workaround network interface test failures on GitHub Actions
  commons-test/src/main/java/org/infinispan/commons/test/skip/SkipTestNG.java
  server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodMultiHomedAddressTest.java
  server/hotrod/src/test/java/org/infinispan/server/hotrod/HotRodSingleClusteredNonLoopbackTest.java
Labels: target/15.0.x

#14881 [15.0] Revert "[#14802] Add resource for health check"
  client/rest-client/src/main/java/org/infinispan/client/rest/RestServerClient.java
  client/rest-client/src/main/java/org/infinispan/client/rest/impl/jdk/RestServerClientJDK.java
  core/src/main/java/org/infinispan/manager/CacheManagerInfo.java
  server/rest/src/main/java/org/infinispan/rest/RestServer.java
  server/rest/src/main/java/org/infinispan/rest/resources/HealthCheckResource.java
  server/rest/src/test/java/org/infinispan/rest/resources/AbstractRestResourceTest.java
  server/rest/src/test/java/org/infinispan/rest/resources/HealthCheckResourceTest.java
Labels: target/15.0.x

#14889 [#14888] Wait for Maven Central publish completion
  build/configuration/pom.xml
Labels: backport/15.0.x, backport/15.2.x

#14887 [15.2] [#14499] UnsafeMemoryAddressOffHeapMemory throws CNFE with widfly
  commons/jdk22/src/main/java/org/infinispan/commons/jdk22/logging/Jdk22Log.java
  commons/jdk22/src/main/java/org/infinispan/commons/jdk22/logging/Jdk22LogFactory.java
  commons/jdk22/src/main/java/org/infinispan/commons/jdkspecific/OffHeapMemory.java
  commons/jdk22/src/main/java/org/infinispan/commons/jdkspecific/UnsafeMemoryAddressOffHeapMemory.java
Labels: target/15.2.x

#14886 [15.0.x] [#14132] Report jacoco coverage using GitHub actions
  pom.xml
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/AbstractInfinispanServerDriver.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/InfinispanGenericContainer.java
  server/tests/pom.xml
Labels: target/15.0.x

#14891 [15.2.x] [#14888] Wait for Maven Central publish completion
  build/configuration/pom.xml
Labels: target/15.2.x

#14909 [15.2.x] [#14900] Update exception handling
  core/src/main/java/org/infinispan/manager/DefaultCacheManager.java
  core/src/main/java/org/infinispan/persistence/sifs/Index.java
  core/src/main/java/org/infinispan/persistence/sifs/NonBlockingSoftIndexFileStore.java
  core/src/main/java/org/infinispan/util/logging/Log.java
Labels: target/15.2.x

#14923 [#14922] Log method commandNotYeySupportedByAllClusterMembers is missing an id attribute
  core/src/main/java/org/infinispan/util/logging/Log.java
Labels: pr/trivial 😀

#14791 [#14790] Add correct label on closed issue for main
  .github/scripts/pr-label-issues.sh
  .github/workflows/label.yml
Labels: pr/trivial 😀, github_actions

#14915 [15.2.x] [#14892] CacheEntrySet encoder swaps arguments causing ClassCastExcep…
  core/src/main/java/org/infinispan/cache/impl/EncoderCache.java
  core/src/test/java/org/infinispan/stream/BaseStreamIteratorTest.java
Labels: target/15.2.x

#14904 [15.2.x] [#14865] NullPointerException while expiring entry with cross-site
  core/src/main/java/org/infinispan/xsite/irac/DefaultIracManager.java
  core/src/test/java/org/infinispan/xsite/irac/IracMaxIdleTest.java
  core/src/test/java/org/infinispan/xsite/irac/ManualIracManager.java
Labels: target/15.2.x

#14907 [15.0] [#14486] Handle reflection exceptions in ThreadLeakChecker
  commons-test/src/main/java/org/infinispan/commons/test/ThreadLeakChecker.java
Labels: target/15.0.x

#14729 [15.2.x] [#14725] Add port_range back to the default stacks
  core/src/main/resources/default-configs/default-jgroups-azure.xml
  core/src/main/resources/default-configs/default-jgroups-ec2.xml
  core/src/main/resources/default-configs/default-jgroups-google.xml
  core/src/main/resources/default-configs/default-jgroups-kubernetes.xml
  core/src/main/resources/default-configs/default-jgroups-tcp.xml
  core/src/main/resources/default-configs/default-jgroups-tunnel.xml
  core/src/main/resources/default-configs/default-jgroups-udp.xml
Labels: target/15.2.x

#14964 [#14963] SIFS may encounter negative size exception on restart
  core/src/main/java/org/infinispan/persistence/sifs/Index.java
Labels: backport/15.0.x, backport/15.2.x
