Repository infinispan/infinispan, pull requests merged in 2025-01, with the labels that each got.

#13607 [#13604] Only test server upgrades on CI with the latest Operator release
  .github/workflows/operator_upgrade.yaml
Labels: backport/14.0.x, backport/15.0.x, backport/15.1.x

#13518 [#13515] Automatic release labels
  .github/scripts/pr-find-issues.sh
  .github/scripts/pr-label-issues.sh
  .github/workflows/label.yml
Labels: backport/15.1.x

#13610 [#13609] Reduce virtual thread pinned events
  commons/all/src/main/java/org/infinispan/commons/jdkspecific/ThreadCreator.java
  commons/all/src/main/java/org/infinispan/commons/tx/TransactionImpl.java
  commons/jdk21/src/main/java/org/infinispan/commons/jdk21/ThreadCreatorImpl.java
  commons/spi/src/main/java/org/infinispan/commons/spi/ThreadCreator.java
  core/src/main/java/org/infinispan/factories/NamedExecutorsFactory.java
  core/src/main/java/org/infinispan/factories/threads/NonBlockingThreadPoolExecutorFactory.java
  core/src/main/java/org/infinispan/notifications/cachelistener/cluster/ClusterListenerReplicateCallable.java
  core/src/main/java/org/infinispan/remoting/transport/jgroups/StaggeredRequest.java
  core/src/test/java/org/infinispan/expiration/impl/ExpirationThreadCountTest.java
  core/src/test/java/org/infinispan/test/fwk/JGroupsConfigBuilder.java
  core/src/test/resources/configs/xsite/bridge.xml
  core/src/test/resources/stacks/tcp.xml
  core/src/test/resources/stacks/udp.xml
  server/runtime/src/test/java/org/infinispan/server/task/ServerTaskEngineBlockingTest.java
Labels: backport/15.0.x, backport/15.1.x

#13618 [15.1.x] [#13604] Only test server upgrades on CI with the latest Operator release
  .github/workflows/operator_upgrade.yaml
Labels: backport/14.0.x, backport/15.0.x, target/15.1.x

#13674 [#13673] Archive log files as artefact
  .github/workflows/on_build_do_test.yml
Labels: pr/trivial 😀, github_actions

#13665 [#13644] Fix run id in flaky test issue link
  .github/workflows/on_test_update_gh_flaky_test.yml
Labels: pr/trivial 😀, github_actions

#13647 [15.1.x] [#13609] Reduce virtual thread pinned events
  commons/all/src/main/java/org/infinispan/commons/jdkspecific/ThreadCreator.java
  commons/all/src/main/java/org/infinispan/commons/tx/TransactionImpl.java
  commons/jdk21/src/main/java/org/infinispan/commons/jdk21/ThreadCreatorImpl.java
  commons/spi/src/main/java/org/infinispan/commons/spi/ThreadCreator.java
  core/src/main/java/org/infinispan/factories/NamedExecutorsFactory.java
  core/src/main/java/org/infinispan/factories/threads/NonBlockingThreadPoolExecutorFactory.java
  core/src/main/java/org/infinispan/notifications/cachelistener/cluster/ClusterListenerReplicateCallable.java
  core/src/main/java/org/infinispan/remoting/transport/jgroups/StaggeredRequest.java
  core/src/test/java/org/infinispan/expiration/impl/ExpirationThreadCountTest.java
  core/src/test/java/org/infinispan/test/fwk/JGroupsConfigBuilder.java
  core/src/test/resources/configs/xsite/bridge.xml
  core/src/test/resources/stacks/tcp.xml
  core/src/test/resources/stacks/udp.xml
  server/runtime/src/test/java/org/infinispan/server/task/ServerTaskEngineBlockingTest.java
Labels: target/15.1.x

#13646 [15.0.x] [#13609] Reduce virtual thread pinned events
  commons/all/src/main/java/org/infinispan/commons/jdkspecific/ThreadCreator.java
  commons/all/src/main/java/org/infinispan/commons/tx/TransactionImpl.java
  commons/jdk21/src/main/java/org/infinispan/commons/jdk21/ThreadCreatorImpl.java
  commons/spi/src/main/java/org/infinispan/commons/spi/ThreadCreator.java
  core/src/main/java/org/infinispan/factories/NamedExecutorsFactory.java
  core/src/main/java/org/infinispan/factories/threads/NonBlockingThreadPoolExecutorFactory.java
  core/src/main/java/org/infinispan/notifications/cachelistener/cluster/ClusterListenerReplicateCallable.java
  core/src/main/java/org/infinispan/remoting/transport/jgroups/StaggeredRequest.java
  core/src/test/java/org/infinispan/expiration/impl/ExpirationThreadCountTest.java
  core/src/test/java/org/infinispan/test/fwk/JGroupsConfigBuilder.java
  core/src/test/resources/configs/xsite/bridge.xml
  core/src/test/resources/stacks/tcp.xml
  core/src/test/resources/stacks/udp.xml
  server/runtime/src/test/java/org/infinispan/server/task/ServerTaskEngineBlockingTest.java
Labels: target/15.0.x

#13642 [15.1.x] [#13515] Automatic release labels
  .github/scripts/pr-find-issues.sh
  .github/scripts/pr-label-issues.sh
  .github/workflows/label.yml
Labels: target/15.1.x

#13668 [14.0.x] Operand upgrade test fixes
  .github/workflows/operator_upgrade.yaml
Labels: target/14.0.x

#13667 [15.0.x] Operand upgrade test fixes
  .github/workflows/operator_upgrade.yaml
Labels: target/15.0.x

#13718 [#13717] JDK Compatibility Tests not executed on 15.1.x branch
  .github/workflows/supported_jdks.yaml
Labels: backport/15.1.x

#13716 [#13715] Do not cancel concurrent jobs on push
  .github/workflows/on_build_do_publish_image.yml
  .github/workflows/on_build_do_test.yml
  .github/workflows/on_propen_push_do_build.yml
  .github/workflows/operator_upgrade.yaml
  .github/workflows/pull_request_native_cli.yml
  .github/workflows/supported_jdks.yaml
Labels: pr/trivial 😀, github_actions

#13337 Expand troubleshooting documentation
  cli/src/main/resources/help/benchmark.adoc
  documentation/src/main/asciidoc/stories/assembly_server_troubleshooting.adoc
  documentation/src/main/asciidoc/topics/proc_cli_benchmark.adoc
  documentation/src/main/asciidoc/topics/proc_cli_getting_server_reports.adoc
  documentation/src/main/asciidoc/topics/proc_cli_logging.adoc
Labels: pr/documentation

#13649 [#13648] Retry operations submitted to closing channel
  client/hotrod-client-legacy/src/main/java/org/infinispan/client/hotrod/impl/operations/RetryOnFailureOperation.java
  client/hotrod-client-legacy/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelFactory.java
  client/hotrod-client-legacy/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelPool.java
  client/hotrod-client-legacy/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/HeaderDecoder.java
  client/hotrod-client-legacy/src/test/java/org/infinispan/client/hotrod/impl/transport/netty/CloseBeforeEnqueuingTest.java
Labels: area/client/hotrod

#13735 [#13734] Client topology installed during authentication can cause
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/HeaderDecoder.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/OperationChannel.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/AuthenticationTest.java
Labels: target/15.1.x, target/15.2.x, backport/15.1.x

#13190 Support custom properties in script metadata
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/test/HotRodClientTestingUtil.java
  tasks/scripting/pom.xml
  tasks/scripting/src/main/java/org/infinispan/scripting/ScriptingManager.java
  tasks/scripting/src/main/java/org/infinispan/scripting/impl/PersistenceContextInitializer.java
  tasks/scripting/src/main/java/org/infinispan/scripting/impl/ScriptMetadata.java
  tasks/scripting/src/main/java/org/infinispan/scripting/impl/ScriptMetadataParser.java
  tasks/scripting/src/main/java/org/infinispan/scripting/impl/ScriptWithMetadata.java
  tasks/scripting/src/main/java/org/infinispan/scripting/impl/ScriptingInterceptor.java
  tasks/scripting/src/main/java/org/infinispan/scripting/impl/ScriptingManagerImpl.java
  tasks/scripting/src/main/java/org/infinispan/scripting/logging/Log.java
  tasks/scripting/src/test/java/org/infinispan/scripting/ClusteredScriptingTest.java
  tasks/scripting/src/test/java/org/infinispan/scripting/ScriptMetadataTest.java
  tasks/scripting/src/test/java/org/infinispan/scripting/ScriptingTest.java
  tasks/scripting/src/test/java/org/infinispan/scripting/utils/ScriptingUtils.java
Labels: pr/question ❓, target/15.2.x

#13620 [#13619] BlockingManager blockingPublisher doesn't cancel on the bloc…
  core/src/main/java/org/infinispan/util/concurrent/BlockingManagerImpl.java
  core/src/test/java/org/infinispan/util/concurrent/BlockingManagerTest.java
Labels: backport/15.0.x, backport/15.1.x

#13743 [15.1.x] [#13734] Client topology installed during authentication can cause
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/HeaderDecoder.java
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/OperationChannel.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/AuthenticationTest.java
Labels: target/15.1.x

#13744 [15.0.x] [#13619] BlockingManager blockingPublisher doesn't cancel on the bloc…
  core/src/main/java/org/infinispan/util/concurrent/BlockingManagerImpl.java
  core/src/test/java/org/infinispan/util/concurrent/BlockingManagerTest.java
Labels: target/15.0.x

#13745 [15.1.x] [#13619] BlockingManager blockingPublisher doesn't cancel on the bloc…
  core/src/main/java/org/infinispan/util/concurrent/BlockingManagerImpl.java
  core/src/test/java/org/infinispan/util/concurrent/BlockingManagerTest.java
Labels: target/15.1.x

#13749 [15.1] Limit reindexing concurrency pressure to 100
  query/src/main/java/org/infinispan/query/impl/massindex/IndexWorker.java
Labels: target/15.1.x

#13748 [15.0] Limit reindexing concurrency pressure to 100
  query/src/main/java/org/infinispan/query/impl/massindex/IndexWorker.java
Labels: target/15.0.x

#13451 [15.0.x] Negative metrics raise exceptions in micrometer+prometheus Closes #13235
  .gitignore
  spring/spring-boot-3/embedded/pom.xml
  spring/spring-boot-3/embedded/src/main/java/org/infinispan/spring/starter/embedded/actuator/InfinispanCacheMeterBinder.java
  spring/spring-boot-3/it-tests/embedded-tests/pom.xml
  spring/spring-boot-3/it-tests/embedded-tests/src/test/java/test/infinispan/integration/embedded/SimpleApp.java
  spring/spring-boot-3/it-tests/embedded-tests/src/test/java/test/infinispan/integration/embedded/SimpleApplicationTests.java
  spring/spring-boot-3/it-tests/embedded-tests/src/test/resources/application.properties
  spring/spring-boot-3/it-tests/session-tests/pom.xml
  spring/spring-boot-3/it-tests/session-tests/src/test/java/test/infinispan/autoconfigure/CacheDisabledTest.java
  spring/spring-boot-3/it-tests/session-tests/src/test/java/test/infinispan/autoconfigure/CacheManagerTest.java
  spring/spring-boot-3/it-tests/session-tests/src/test/java/test/infinispan/integration/AbstractSpringSessionTCK.java
  spring/spring-boot-3/it-tests/session-tests/src/test/java/test/infinispan/integration/InfinispanSessionListener.java
  spring/spring-boot-3/it-tests/session-tests/src/test/java/test/infinispan/integration/SecurityConfig.java
  spring/spring-boot-3/it-tests/session-tests/src/test/java/test/infinispan/integration/TestRESTController.java
  spring/spring-boot-3/it-tests/session-tests/src/test/java/test/infinispan/integration/embedded/EmbeddedSessionApp.java
  spring/spring-boot-3/it-tests/session-tests/src/test/java/test/infinispan/integration/embedded/EmbeddedSpringSessionTest.java
  spring/spring-boot-3/it-tests/session-tests/src/test/java/test/infinispan/integration/remote/RemoteSessionApp.java
  spring/spring-boot-3/it-tests/session-tests/src/test/java/test/infinispan/integration/remote/RemoteSpringSessionTest.java
  spring/spring-boot-3/pom.xml
  spring/spring-boot-3/remote/src/main/java/org/infinispan/spring/starter/remote/actuator/RemoteInfinispanCacheMeterBinder.java
Labels: pr/changes required, kind/bug, area/integrations/spring, target/15.0.x

#13755 [15.1.x] [#13648] Retry operations submitted to closing channel
  client/hotrod-client-legacy/src/main/java/org/infinispan/client/hotrod/impl/operations/RetryOnFailureOperation.java
  client/hotrod-client-legacy/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelFactory.java
  client/hotrod-client-legacy/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/ChannelPool.java
  client/hotrod-client-legacy/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/HeaderDecoder.java
  client/hotrod-client-legacy/src/test/java/org/infinispan/client/hotrod/impl/transport/netty/CloseBeforeEnqueuingTest.java
Labels: pr/backport, area/client/hotrod, target/15.1.x

#13769 [#13768] Publish DBs test report
  .github/workflows/on_build_do_test.yml
  .github/workflows/on_test_publish_surefire_report.yml
Labels: github_actions, backport/15.1.x

#13784 [#13783] Set maven-javadoc-plugin output directory
  javadoc/pom.xml
Labels: pr/trivial 😀

#13776 [#13775][15.0] Upgrade Quarkus 3.8.6
  build/configuration/pom.xml
Labels: target/15.0.x

#13837 [#13836] Fix concurrency group for push
  .github/workflows/on_propen_push_do_build.yml
  .github/workflows/operator_upgrade.yaml
  .github/workflows/pull_request_native_cli.yml
  .github/workflows/supported_jdks.yaml
Labels: pr/trivial 😀, github_actions, backport/15.1.x

#13838 [#13834] Install client topology only after a channel is fully connected
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/HeaderDecoder.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/PingOnStartupTest.java
Labels: area/client/hotrod, target/15.2.x, backport/15.1.x

#13842 [15.1.x] [#13834] Install client topology only after a channel is fully connected
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/HeaderDecoder.java
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/PingOnStartupTest.java
Labels: target/15.1.x

#13830 [#13829] Don't include protocol stack in transport exceptions
  core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
Labels: backport/14.0.x, backport/15.0.x, area/security, backport/15.1.x

#13833 [#13832] Update Server with PT6 Console
  build/configuration/pom.xml
  server/tests/src/test/java/org/infinispan/server/footprint/FootprintIT.java
Labels: area/server

#13816 [#13814] Add token auth URL to Content-Security-Policy header
  server/core/src/main/java/org/infinispan/server/core/ServerManagement.java
  server/rest/src/main/java/org/infinispan/rest/InvocationHelper.java
  server/runtime/src/main/java/org/infinispan/server/Server.java
Labels: pr/urgent ⚠️, backport/15.0.x, area/server/rest, backport/15.1.x

#13713 [15.0.x] Bump io.lettuce:lettuce-core from 6.3.2.RELEASE to 6.5.2.RELEASE
  build/configuration/pom.xml
  server/resp/src/test/java/org/infinispan/server/resp/RespSingleNodeTest.java
Labels: pr/trivial 😀, pr/question ❓, java, target/15.0.x, dependencies

#13281 [15.0.x] ISPN-16840 [RESP] LPUSH + DEL + SET fails with unable to aquire a lock
  core/src/main/java/org/infinispan/cache/impl/DecoratedCache.java
  server/resp/src/main/java/org/infinispan/server/resp/commands/tx/TransactionDecorator.java
  server/resp/src/test/java/org/infinispan/server/resp/TransactionOperationsTest.java
  server/resp/src/test/java/org/infinispan/server/resp/dist/TransactionClusteredTest.java
Labels: pr/backport, area/server/resp, target/15.0.x

#13858 [15.1.x] [#13829] Don't include protocol stack in transport exceptions
  core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
Labels: area/security, target/15.1.x

#13857 [15.0.x] [#13829] Don't include protocol stack in transport exceptions
  core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
Labels: area/security, target/15.0.x

#13856 [14.0.x] [#13829] Don't include protocol stack in transport exceptions
  core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
Labels: area/security, target/14.0.x

#13266 ISPN-16801: Follow-up to JDBC_PING doc updates for some fixes
  documentation/src/main/asciidoc/topics/xml/jdbc_ping.xml
  documentation/src/main/asciidoc/topics/xml/server-transport-datasource.xml
Labels: pr/changes required, backport/15.0.x

#13886 [15.0.x] ISPN-16801: Follow-up to JDBC_PING doc updates for some fixes
  documentation/src/main/asciidoc/topics/xml/jdbc_ping.xml
  documentation/src/main/asciidoc/topics/xml/server-transport-datasource.xml
Labels: target/15.0.x

#13870 [15.0.x] [#13814] Add token auth URL to Content-Security-Policy header
  server/core/src/main/java/org/infinispan/server/core/ServerManagement.java
  server/rest/src/main/java/org/infinispan/rest/InvocationHelper.java
  server/runtime/src/main/java/org/infinispan/server/Server.java
Labels: area/security, target/15.0.x

#13871 [15.1.x] [#13814] Add token auth URL to Content-Security-Policy header
  server/core/src/main/java/org/infinispan/server/core/ServerManagement.java
  server/rest/src/main/java/org/infinispan/rest/InvocationHelper.java
  server/runtime/src/main/java/org/infinispan/server/Server.java
Labels: area/security, target/15.1.x

#13879 [#13872] Remap removeAsync future to boolean
  query/src/main/java/org/infinispan/query/clustered/commandworkers/CQDelete.java
Labels: backport/15.0.x, backport/15.1.x

#13791 [#13790] Sync JGroups properties in 15.0.x branch
  core/src/main/resources/default-configs/default-jgroups-azure.xml
  core/src/main/resources/default-configs/default-jgroups-ec2.xml
  core/src/main/resources/default-configs/default-jgroups-google.xml
  core/src/main/resources/default-configs/default-jgroups-kubernetes.xml
  core/src/main/resources/default-configs/default-jgroups-tcp.xml
  core/src/main/resources/default-configs/default-jgroups-tunnel.xml
  core/src/main/resources/default-configs/default-jgroups-udp.xml
  core/src/test/resources/configs/all/12.0.xml
  core/src/test/resources/configs/all/12.1.xml
  core/src/test/resources/configs/all/13.0.xml
  core/src/test/resources/configs/all/14.0.xml
  core/src/test/resources/configs/all/15.0.xml
  core/src/test/resources/configs/config-with-jgroups-stack.xml
  core/src/test/resources/configs/xsite/bridge.xml
  core/src/test/resources/configs/xsite/xsite-inline-test.xml
  core/src/test/resources/stacks/broken-tcp.xml
  core/src/test/resources/stacks/tcp.xml
  core/src/test/resources/stacks/tcp_mping/tcp1.xml
  core/src/test/resources/stacks/tcp_mping/tcp2.xml
  core/src/test/resources/stacks/udp.xml
  documentation/src/main/asciidoc/topics/ref_jgroups_system_properties.adoc
  hibernate/cache-commons/src/test/resources/2lc-test-tcp.xml
  quarkus/integration-tests/embedded/src/main/resources/embedded.xml
  quarkus/integration-tests/embedded/src/main/resources/stacks/broken-tcp.xml
  quarkus/integration-tests/embedded/src/main/resources/stacks/tcp.xml
  quarkus/integration-tests/embedded/src/main/resources/stacks/tcp_mping/tcp1.xml
  quarkus/integration-tests/embedded/src/main/resources/stacks/tcp_mping/tcp2.xml
  quarkus/integration-tests/embedded/src/main/resources/stacks/udp.xml
  server/testdriver/junit5/src/test/resources/jgroups/xsite-stacks.xml
  server/tests/src/test/resources/configuration/jgroups/xsite-stacks-single-site-master.xml
  server/tests/src/test/resources/configuration/jgroups/xsite-stacks.xml
  tools/src/test/resources/udp.xml
Labels: target/15.0.x

#13869 [#13864] Correctly report removed/ignored attributes when parsing
  core/src/main/java/org/infinispan/configuration/parsing/CacheParser.java
  core/src/main/java/org/infinispan/configuration/parsing/ParseUtils.java
  core/src/main/java/org/infinispan/configuration/parsing/Parser.java
  core/src/main/java/org/infinispan/util/logging/Log.java
  core/src/test/java/org/infinispan/configuration/parsing/XmlFileParsingTest.java
  core/src/test/java/org/infinispan/persistence/dummy/DummyInMemoryStoreConfigurationParser.java
  persistence/jdbc/src/main/java/org/infinispan/persistence/jdbc/configuration/JdbcStoreConfigurationParser.java
  persistence/rocksdb/src/main/java/org/infinispan/persistence/rocksdb/configuration/RocksDBStoreConfigurationParser.java
  server/runtime/src/main/java/org/infinispan/server/configuration/ServerConfigurationParser.java
Labels: area/core

#13883 [#13882] Documentation code highlighting
  documentation/pom.xml
Labels: area/documentation

#13907 [#13864] Fix XmlFileParsingTest.testRemovedAttribute failure
  core/src/test/java/org/infinispan/configuration/parsing/XmlFileParsingTest.java
Labels: pr/trivial 😀

#13893 [15.1.x] [#13872] Remap removeAsync future to boolean
  query/src/main/java/org/infinispan/query/clustered/commandworkers/CQDelete.java
Labels: target/15.1.x

#13892 [15.0.x] [#13872] Remap removeAsync future to boolean
  query/src/main/java/org/infinispan/query/clustered/commandworkers/CQDelete.java
Labels: target/15.0.x

#13936 [#13935] Disable Jenkins Warnings for JavaDocs
  Jenkinsfile
Labels: backport/14.0.x, backport/15.0.x, backport/15.1.x
