Repository infinispan/infinispan, pull requests merged in 2025-07, with the labels that each got.

#15124 [15.0.x] [#15070] Do not install outdated JGroups views
  core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
  core/src/main/java/org/infinispan/util/logging/Log.java
  core/src/test/java/org/infinispan/remoting/transport/jgroups/JGroupsTransportTest.java
Labels: target/15.0.x

#14845 [#14803] Decouple server and cache manager start
  integrationtests/endpoints-interop-it/src/test/java/org/infinispan/it/endpoints/BaseJsonTest.java
  integrationtests/endpoints-interop-it/src/test/java/org/infinispan/it/endpoints/EndpointInteroperabilityTest.java
  integrationtests/endpoints-interop-it/src/test/java/org/infinispan/it/endpoints/EndpointsCacheFactory.java
  persistence/remote/src/test/java/org/infinispan/persistence/remote/RemoteStoreSSLTest.java
  server/core/src/main/java/org/infinispan/server/core/AbstractProtocolServer.java
  server/core/src/main/java/org/infinispan/server/core/backup/BackupManagerImpl.java
  server/core/src/main/java/org/infinispan/server/core/logging/Log.java
  server/core/src/test/java/org/infinispan/server/core/backup/BackupManagerImplTest.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/BaseDecoder.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/CounterRequestProcessor.java
  server/hotrod/src/main/java/org/infinispan/server/hotrod/HotRodServer.java
  server/hotrod/src/main/resources/hotrod.gr
  server/memcached/src/main/java/org/infinispan/server/memcached/MemcachedBaseDecoder.java
  server/memcached/src/main/java/org/infinispan/server/memcached/MemcachedServer.java
  server/memcached/src/main/resources/memcache-binary-op.gr
  server/memcached/src/main/resources/memcache-text-op.gr
  server/memcached/src/test/java/org/infinispan/server/memcached/test/MemcachedFunctionalTest.java
  server/memcached/src/test/java/org/infinispan/server/memcached/test/MemcachedMultiNodeTest.java
  server/memcached/src/test/java/org/infinispan/server/memcached/test/MemcachedSingleNodeTest.java
  server/memcached/src/test/java/org/infinispan/server/memcached/text/MemcachedServerTest.java
  server/resp/src/main/java/org/infinispan/server/resp/CacheRespRequestHandler.java
  server/resp/src/main/java/org/infinispan/server/resp/Resp3AuthHandler.java
  server/resp/src/main/java/org/infinispan/server/resp/Resp3Handler.java
  server/resp/src/main/java/org/infinispan/server/resp/RespChannelInitializer.java
  server/resp/src/main/java/org/infinispan/server/resp/RespHandler.java
  server/resp/src/main/java/org/infinispan/server/resp/RespServer.java
  server/resp/src/main/java/org/infinispan/server/resp/SubscriberHandler.java
  server/resp/src/main/java/org/infinispan/server/resp/tx/RespTransactionHandler.java
  server/resp/src/test/java/org/infinispan/server/resp/RespDecoderTest.java
  server/resp/src/test/java/org/infinispan/server/resp/RespServerTest.java
  server/resp/src/test/java/org/infinispan/server/resp/test/RespTestingUtil.java
  server/rest/src/main/java/org/infinispan/rest/InvocationHelper.java
  server/rest/src/main/java/org/infinispan/rest/RestServer.java
  server/rest/src/test/java/org/infinispan/rest/helper/RestServerHelper.java
  server/router/src/main/java/org/infinispan/server/router/router/impl/singleport/SinglePortEndpointRouter.java
  server/router/src/test/java/org/infinispan/server/router/integration/SinglePortTest.java
  server/router/src/test/java/org/infinispan/server/router/utils/RestTestingUtil.java
  server/runtime/src/main/java/org/infinispan/server/Server.java
  server/runtime/src/main/java/org/infinispan/server/state/ServerStateManagerImpl.java
  server/runtime/src/main/java/org/infinispan/server/tasks/admin/CacheGetOrCreateTask.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/EmbeddedInfinispanServerDriver.java
  server/tests/src/test/java/org/infinispan/server/functional/rest/RestReinitializeCacheIT.java
  spring/spring-boot-3/it-tests/session-tests/src/test/java/test/infinispan/integration/remote/RemoteSpringSessionTest.java
Labels: area/server

#15228 [#15227] CVE-2025-5731 Fix potential credential leakage in CLI
  cli/src/main/java/org/infinispan/cli/impl/CliRuntimeRunner.java
Labels: CVE, backport/15.0.x, backport/15.2.x

#15213 [#15190] Remove old assigned alias
  core/src/main/java/org/infinispan/manager/DefaultCacheManagerAdmin.java
  core/src/test/java/org/infinispan/globalstate/GlobalStateTest.java
Labels: area/core, backport/15.2.x

#14302 [#13427] JSON.DEBUG command
  commons/all/src/main/java/org/infinispan/commons/marshall/ProtoStreamTypeIds.java
  server/resp/src/main/java/org/infinispan/server/resp/GlobalContextInitializer.java
  server/resp/src/main/java/org/infinispan/server/resp/commands/Commands.java
  server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONCommandArgumentReader.java
  server/resp/src/main/java/org/infinispan/server/resp/commands/json/JSONDEBUG.java
  server/resp/src/main/java/org/infinispan/server/resp/json/EmbeddedJsonCache.java
  server/resp/src/main/java/org/infinispan/server/resp/json/JsonDebugMemoryFunction.java
  server/resp/src/test/java/org/infinispan/server/resp/JsonCommandsTest.java
Labels: area/server/resp

#15243 [#15242] Log creation can be flagged as blocking which can cause test…
  commons/all/src/main/java/org/infinispan/commons/internal/CommonsBlockHoundIntegration.java
Labels: pr/trivial 😀, pr/test fix

#15241 [15.2.x][#14390] Avoid file clash in surefire-reports
  anchored-keys/pom.xml
  cdi/embedded/pom.xml
  cdi/remote/pom.xml
  client/hotrod-client/pom.xml
  core/pom.xml
  counter/pom.xml
  gridfs/pom.xml
  integrationtests/cdi-weld-se-it/pom.xml
  integrationtests/endpoints-interop-it/pom.xml
  integrationtests/jboss-marshalling-it/pom.xml
  jcache/embedded/pom.xml
  jcache/remote/pom.xml
  lock/pom.xml
  multimap/pom.xml
  persistence/remote/pom.xml
  persistence/rocksdb/pom.xml
  query-core/pom.xml
  query/pom.xml
  remote-query/remote-query-server/pom.xml
  server/core/pom.xml
  server/hotrod/pom.xml
  server/memcached/pom.xml
  server/resp/pom.xml
  server/rest/pom.xml
  spring/spring6/spring6-embedded/pom.xml
  spring/spring6/spring6-remote/pom.xml
  tasks/manager/pom.xml
  tasks/scripting/pom.xml
  tools/pom.xml
Labels: target/15.2.x

#15194 [#15192] Fix non-tx issue with Invalidation
  core/src/main/java/org/infinispan/factories/InterceptorChainFactory.java
  core/src/main/java/org/infinispan/interceptors/impl/CacheLoaderInterceptor.java
  core/src/main/java/org/infinispan/interceptors/impl/InvalidationCacheLoaderInterceptor.java
  core/src/main/java/org/infinispan/interceptors/impl/InvalidationCacheWriterInterceptor.java
  core/src/test/java/org/infinispan/distribution/BaseDistStoreTest.java
  core/src/test/java/org/infinispan/invalidation/InvalidationPersistenceTest.java
Labels: backport/15.0.x, backport/15.2.x

#15284 [15.2.x] [#15192] Fix non-tx issue with Invalidation
  core/src/main/java/org/infinispan/factories/InterceptorChainFactory.java
  core/src/main/java/org/infinispan/interceptors/impl/CacheLoaderInterceptor.java
  core/src/main/java/org/infinispan/interceptors/impl/InvalidationCacheLoaderInterceptor.java
  core/src/main/java/org/infinispan/interceptors/impl/InvalidationCacheWriterInterceptor.java
  core/src/test/java/org/infinispan/distribution/BaseDistStoreTest.java
  core/src/test/java/org/infinispan/invalidation/InvalidationPersistenceTest.java
Labels: target/15.2.x

#15233 [15.0.x] [#15227] CVE-2025-5731 Fix potential credential leakage in CLI
  cli/src/main/java/org/infinispan/cli/impl/CliRuntimeRunner.java
Labels: target/15.0.x

#15245 [#15224] Update query cache CLI doc
  documentation/src/main/asciidoc/topics/proc_query_querying_console_cli.adoc
Labels: pr/trivial 😀, pr/documentation

#15254 [#15253] Update readiness probe
  core/src/main/java/org/infinispan/manager/CacheManagerInfo.java
  server/rest/src/main/java/org/infinispan/rest/resources/HealthCheckResource.java
  server/rest/src/test/java/org/infinispan/rest/RestServerLifecycleTest.java
  server/rest/src/test/java/org/infinispan/rest/resources/HealthCheckResourceTest.java
Labels: area/server/rest

#15296 [#15295] Change server status after post start
  server/runtime/src/main/java/org/infinispan/server/Server.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/EmbeddedInfinispanServerDriver.java
Labels: pr/trivial 😀, area/server

#15308 [#15304] Server Extension gets NPE if afterAll fails with a specific …
  server/testdriver/junit5/src/main/java/org/infinispan/server/test/junit5/AbstractServerExtension.java
Labels: pr/trivial 😀, pr/test fix

#15140 [#15139] Fixes 500 REST endpoint with local server
  server/rest/src/main/java/org/infinispan/rest/resources/ClusterResource.java
  server/rest/src/test/java/org/infinispan/rest/resources/LocalClusterResourceTest.java
  server/runtime/src/main/java/org/infinispan/server/state/ServerStateManagerImpl.java
Labels: area/server/rest, release/16.0.0

#15235 [15.2.x] [#15190] Remove old assigned alias
  core/src/main/java/org/infinispan/manager/DefaultCacheManagerAdmin.java
  core/src/test/java/org/infinispan/globalstate/GlobalStateTest.java
Labels: target/15.2.x

#15322 [#15321] No timeout for cdi test with expectedException
  commons-test/src/main/java/org/infinispan/commons/test/TestNGTestListener.java
Labels: pr/test fix

#15343 [15.2.x] [#15193] Invalidation mode anomalies in transactional cache
  core/src/main/java/org/infinispan/container/entries/AbstractInternalCacheEntry.java
  core/src/main/java/org/infinispan/container/entries/CacheEntry.java
  core/src/main/java/org/infinispan/container/entries/ClearCacheEntry.java
  core/src/main/java/org/infinispan/container/entries/ForwardingCacheEntry.java
  core/src/main/java/org/infinispan/container/entries/NullCacheEntry.java
  core/src/main/java/org/infinispan/container/entries/ReadCommittedEntry.java
  core/src/main/java/org/infinispan/interceptors/impl/CallInterceptor.java
  core/src/main/java/org/infinispan/interceptors/impl/InvalidationInterceptor.java
  core/src/main/java/org/infinispan/interceptors/locking/ClusteringDependentLogic.java
  core/src/main/java/org/infinispan/notifications/cachelistener/NotifyHelper.java
  core/src/main/java/org/infinispan/util/CoreImmutables.java
  core/src/test/java/org/infinispan/invalidation/InvalidationPersistenceTest.java
  core/src/test/java/org/infinispan/test/fwk/CacheEntryDelegator.java
Labels: target/15.2.x

#15342 [15.0.x] [#15193] Invalidation mode anomalies in transactional cache
  core/src/main/java/org/infinispan/container/entries/AbstractInternalCacheEntry.java
  core/src/main/java/org/infinispan/container/entries/CacheEntry.java
  core/src/main/java/org/infinispan/container/entries/ClearCacheEntry.java
  core/src/main/java/org/infinispan/container/entries/ForwardingCacheEntry.java
  core/src/main/java/org/infinispan/container/entries/NullCacheEntry.java
  core/src/main/java/org/infinispan/container/entries/ReadCommittedEntry.java
  core/src/main/java/org/infinispan/interceptors/impl/CallInterceptor.java
  core/src/main/java/org/infinispan/interceptors/impl/InvalidationInterceptor.java
  core/src/main/java/org/infinispan/interceptors/locking/ClusteringDependentLogic.java
  core/src/main/java/org/infinispan/notifications/cachelistener/NotifyHelper.java
  core/src/main/java/org/infinispan/util/CoreImmutables.java
  core/src/test/java/org/infinispan/invalidation/InvalidationPersistenceTest.java
  core/src/test/java/org/infinispan/test/fwk/CacheEntryDelegator.java
Labels: target/15.0.x

#15363 Support "latest" images
  .github/workflows/release.yml
Labels: pr/trivial 😀

#15349 [#15348] Include IT suffix to test classes
  server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/DefaultRollingUpgradeTestIT.java
  server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/RollingUpgradePersistenceTestIT.java
  server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/RollingUpgradeTaskTestIT.java
  server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/RollingUpgradeXSiteIT.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeConfigurationBuilder.java
  server/testdriver/junit5/src/main/java/org/infinispan/server/test/junit5/RollingUpgradeHandlerXSiteExtension.java
Labels: pr/test fix
