Repository infinispan/infinispan, pull requests merged in 2025-09, with the labels that each got.

#14948 [15.2] [#14878] Adjust FootprintIT limits to account for coverage and insights
  .gitignore
  pom.xml
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java
  server/tests/pom.xml
  server/tests/src/test/java/org/infinispan/server/footprint/FootprintIT.java
Labels: pr/test fix, target/15.2.x

#14946 [15.0] [#14878] Adjust FootprintIT limits to account for coverage and insights
  .gitignore
  pom.xml
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java
  server/tests/pom.xml
  server/tests/src/test/java/org/infinispan/server/footprint/FootprintIT.java
Labels: target/15.0.x

#15533 [15.2] [#15531] Netty 4.1.124.Final
  build/configuration/pom.xml
  server/tests/src/test/java/org/infinispan/server/functional/resp/AbstractRespTest.java
Labels: CVE, target/15.2.x

#15552 [15.0] Blockhound 1.0.13
  build/configuration/pom.xml
Labels: target/15.0.x

#15534 [15.0] [#15531] Netty 4.1.124.Final
  build/configuration/pom.xml
  server/tests/src/test/java/org/infinispan/server/functional/resp/AbstractRespTest.java
Labels: CVE, target/15.0.x

#15576 [#15544] Upgrade to JGroups 5.3.21.Final
  build/configuration/pom.xml
Labels: target/15.0.x

#15551 [15.2] Blockhound 1.0.13
  build/configuration/pom.xml
Labels: target/15.2.x

#15619 [#15617] Cache stats check cache running
  core/src/main/java/org/infinispan/stats/impl/ClusterCacheStatsImpl.java
Labels: pr/trivial 😀

#15487 [#15075] Use indexed queries for all aggregations
  build/configuration/pom.xml
  client/hotrod-client/src/test/java/org/infinispan/client/hotrod/query/aggregation/RemoteQueryAggregationCountTest.java
  query/src/main/java/org/infinispan/query/dsl/embedded/impl/QueryAnalyzer.java
  query/src/main/java/org/infinispan/query/dsl/embedded/impl/SearchQueryMaker.java
  query/src/test/java/org/infinispan/query/aggregation/QueryAggregationBroadcastTest.java
  query/src/test/java/org/infinispan/query/aggregation/QueryAggregationCountTest.java
  query/src/test/java/org/infinispan/query/aggregation/QueryAggregationsSimpleTest.java
  query/src/test/java/org/infinispan/query/model/IndexedPlayer.java
  query/src/test/java/org/infinispan/query/model/Sale.java
  server/rest/src/test/java/org/infinispan/rest/search/aggregation/RestQueryAggregationCountTest.java
  server/tests/src/test/java/org/infinispan/server/functional/extensions/RemoteQueryAccessIT.java
  server/tests/src/test/java/org/infinispan/server/functional/hotrod/HotRodCacheContinuousQueries.java
  server/tests/src/test/java/org/infinispan/server/functional/hotrod/HotRodCacheEvents.java
  server/tests/src/test/java/org/infinispan/server/functional/hotrod/HotRodCacheQueries.java
  server/tests/src/test/java/org/infinispan/server/functional/hotrod/HotRodFlagCacheOperations.java
  server/tests/src/test/java/org/infinispan/server/functional/hotrod/HotRodListenerWithDslFilter.java
  server/tests/src/test/java/org/infinispan/server/test/core/Common.java
Labels: area/query, release/16.0.0

#15660 [15.0.x] [#15657] State transfer progress tracker 30s interval
  core/src/main/java/org/infinispan/statetransfer/StateConsumerImpl.java
Labels: target/15.0.x

#15663 [#15662] Client can hang on shutdown
  client/hotrod-client/src/main/java/org/infinispan/client/hotrod/impl/transport/netty/OperationChannel.java
Labels: kind/bug, area/client/hotrod, backport/15.2.x

#15650 [#15649] Make await-initial-transfer mutable
  core/src/main/java/org/infinispan/configuration/cache/StateTransferConfiguration.java
  core/src/test/java/org/infinispan/globalstate/GlobalStateTest.java
  server/rest/src/test/java/org/infinispan/rest/resources/CacheResourceV2Test.java
Labels: pr/changes required, backport/15.0.x, area/core

#15727 [#15628] Updates to Quarkus 3.27
  build/configuration/pom.xml
Labels: area/integrations/quarkus

#15731 [#15730] IsRebalancingEnabled blocking call
  server/rest/src/main/java/org/infinispan/rest/resources/ContainerResource.java
Labels: area/server/rest
