Repository infinispan/infinispan, pull requests merged in 2025-08, with the labels that each got.

#15288 [#15287] Make traces current while communication runs against JGroups
  core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java
Labels: backport/15.2.x

#15387 [#15386] Rolling upgrade tests accept JGroups stack
  server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/DefaultRollingUpgradeTestIT.java
  server/rollingupgradetests/src/test/java/org/infinispan/server/rollingupgrade/RollingUpgradePersistenceTestIT.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/rollingupgrade/RollingUpgradeConfigurationBuilder.java
Labels: pr/trivial 😀, pr/test fix

#15377 [#15394] Fixes ProgrammaticSearchMappingProvider use case
  query/src/main/java/org/infinispan/search/mapper/impl/InfinispanMappingInitiator.java
  query/src/test/java/org/infinispan/query/mapper/ProgrammaticSearchMappingProviderTest.java
Labels: area/query, target/15.2.x

#15416 [#15415] Build clean up
  commons/all/src/test/resources/log4j2-test.xml
  pom.xml
  query/src/test/java/org/infinispan/query/config/CacheModeTest.java
  query/src/test/java/org/infinispan/query/config/EngineConfigTest.java
Labels: pr/trivial 😀

#15417 [#15371] SIFS can hang on various methods when a non owned segment is…
  core/src/main/java/org/infinispan/persistence/sifs/Index.java
  core/src/test/java/org/infinispan/persistence/BaseNonBlockingStoreTest.java
  core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreDistFourNodeTest.java
  core/src/test/java/org/infinispan/persistence/support/WaitNonBlockingStore.java
Labels: backport/15.0.x, backport/15.2.x

#15452 [15.2.x] [#15371] SIFS can hang on various methods when a non owned segment is…
  core/src/main/java/org/infinispan/persistence/sifs/Index.java
  core/src/test/java/org/infinispan/persistence/BaseNonBlockingStoreTest.java
  core/src/test/java/org/infinispan/persistence/sifs/SoftIndexFileStoreDistFourNodeTest.java
  core/src/test/java/org/infinispan/persistence/support/WaitNonBlockingStore.java
Labels: target/15.2.x

#15450 [#15110] Use weld-servlet-core instead of weld-servlet-shaded
  integrationtests/server-integration/third-party-server/pom.xml
  integrationtests/server-integration/third-party-server/src/test/java/org/infinispan/test/integration/thirdparty/DeploymentHelper.java
Labels: backport/15.0.x, backport/15.2.x

#15490 [15.0] [#15489] Use correct activation range for JDK 21+
  commons/all/pom.xml
  commons/pom.xml
Labels: target/15.0.x

#15446 [#15445] Rise required tests num
  .github/workflows/on_test_publish_surefire_report.yml
Labels: pr/trivial 😀, github_actions

#15393 [#15381] Jacoco Report Fix for MultiModule project.
  .github/scripts/merge-jacoco-files.sh
  .github/workflows/on_build_do_test.yml
  .gitignore
  documentation/src/main/asciidoc/topics/contributing/tests.adoc
  jacoco-report-aggregator/pom.xml
  pom.xml
  server/rollingupgradetests/pom.xml
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/TestSystemPropertyNames.java
  server/testdriver/junit4/pom.xml
  server/testdriver/junit5/pom.xml
  server/tests/pom.xml
Labels: github_actions

#15431 Cross compatibility test workflow for 14.0.x
  .github/workflows/test_client_with_new_server.yml
  server/rest/src/main/java/org/infinispan/rest/resources/CacheResourceV2.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/api/HotRodTestClientDriver.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/ContainerInfinispanServerDriver.java
  server/testdriver/core/src/main/java/org/infinispan/server/test/core/TestSystemPropertyNames.java
  server/tests/src/test/java/org/infinispan/server/cli/CliIT.java
  server/tests/src/test/java/org/infinispan/server/functional/AbstractMultiClusterIT.java
  server/tests/src/test/java/org/infinispan/server/functional/AnchoredKeysIT.java
  server/tests/src/test/java/org/infinispan/server/functional/CloudEventsIntegrationIT.java
  server/tests/src/test/java/org/infinispan/server/functional/ConcurrentShutdownRestIT.java
  server/tests/src/test/java/org/infinispan/server/functional/HotRodCompCacheOperationsIT.java
  server/tests/src/test/java/org/infinispan/server/functional/JCacheOperations.java
  server/tests/src/test/java/org/infinispan/server/functional/ProtocolManagementIT.java
  server/tests/src/test/java/org/infinispan/server/functional/ShutdownRestIT.java
  server/tests/src/test/java/org/infinispan/server/functional/StartupFailureIT.java
  server/tests/src/test/java/org/infinispan/server/functional/hotrod/HotRodCacheEvents.java
  server/tests/src/test/java/org/infinispan/server/functional/hotrod/HotRodCacheQueries.java
  server/tests/src/test/java/org/infinispan/server/functional/overview/OverviewReportIT.java
  server/tests/src/test/java/org/infinispan/server/functional/rest/RestOperations.java
  server/tests/src/test/java/org/infinispan/server/functional/rest/RestServerResource.java
  server/tests/src/test/java/org/infinispan/server/persistence/ManagedConnectionOperations.java
  server/tests/src/test/java/org/infinispan/server/resilience/ResilienceMaxRetryIT.java
  server/tests/src/test/java/org/infinispan/server/security/AuthenticationCertIT.java
  server/tests/src/test/java/org/infinispan/server/security/AuthenticationImplicitIT.java
  server/tests/src/test/java/org/infinispan/server/security/AuthenticationKerberosIT.java
  server/tests/src/test/java/org/infinispan/server/security/AuthenticationKeyCloakIT.java
  server/tests/src/test/java/org/infinispan/server/security/AuthenticationKeyCloakSSLIT.java
  server/tests/src/test/java/org/infinispan/server/security/AuthenticationLDAPIT.java
  server/tests/src/test/java/org/infinispan/server/security/AuthenticationMultiEndpointIT.java
  server/tests/src/test/java/org/infinispan/server/security/AuthenticationMultiRealmIT.java
  server/tests/src/test/java/org/infinispan/server/security/AuthenticationTLSIT.java
  server/tests/src/test/java/org/infinispan/server/security/CertWithoutAuthenticationIT.java
  server/tests/src/test/java/org/infinispan/server/security/TLSWithoutAuthenticationIT.java
  server/tests/src/test/java/org/infinispan/server/security/TransportTLSIT.java
  server/tests/src/test/java/org/infinispan/server/security/authorization/AbstractAuthorization.java
  server/tests/src/test/java/org/infinispan/server/security/authorization/AuthorizationKerberosIT.java
  server/tests/src/test/resources/data/templates.xml
Labels: target/14.0.x

#15318 [#15317] Upgrade commons-lang3 to version 3.18.0
  pom.xml
Labels: pr/changes required, target/15.0.x

#15176 [infinispan#15175] remove DelayedExpansion from windows scripts
  server/runtime/src/main/server/bin/cli.bat
  server/runtime/src/main/server/bin/server.bat
Labels: pr/changes required
